### ISSUE TITLE
PRs are created based off old commit and not latest HEAD

### ISSUE THREAD

**Issue by ashkulz** [dependabot/dependabot-core#2969] opened 2021-01-12 10:12 UTC
**Package manager/ecosystem**
ruby:bundler

**Manifest contents prior to update**
n/a

**Updated dependency**
n/a

**What you expected to see, versus what you actually saw**

I've been merging Dependabot PRs today, and newly created PRs do not take into account the latest `master`. Is there some sort of caching going on?

**Images of the diff or a link to the PR, issue or logs**
```
$ git log --graph --oneline master origin/dependabot/bundler/aws-sdk-s3-1.87.0 origin/dependabot/bundler/numbers_in_words-1.0.1 
* c5a242d78 (origin/dependabot/bundler/aws-sdk-s3-1.87.0) Bump aws-sdk-s3 from 1.86.0 to 1.87.0
| * efe235228 (origin/dependabot/bundler/numbers_in_words-1.0.1) Bump numbers_in_words from 0.4.0 to 1.0.1
|/  
| * da386baf5 (HEAD -> master, origin/master) bump factory_bot_rails from 5.1.0 to 5.2.0
| * 66c690fa4 bump brakeman from 4.10.0 to 4.10.1
| * 48f2fe059 bump ruby-prof from 1.0.0 to 1.4.2
| * ec3d539b6 <redacted>
| * f9fd1a01e <redacted>
| * e1cad3cfe bump byebug from 11.0.1 to 11.1.3
| * 69bfc8346 bump public_suffix from 4.0.2 to 4.0.6
|/  
* 4ca8e083c <redacted>
```
At least 4 hours have passed since I merged in the earlier PRs.

**Comment by jeffwidman** [comment] 2022-08-11 07:09
There's some races internally where a job may fire and then take a long time... we could certainly handle this better, both reducing the race latency and also just before the PR double-checking to see if the lockfile changed. That said, we have made incremental improvements and will continue to chip away at this over time... there's a bunch of different causes for it, so it's not one single issue unfortunately. So I'm going to close this for now as it's a year and a half old. If you see this happen again, please file another issue and we'll try to investigate the specific root cause of why it happened.

**Closed by jeffwidman** 2022-08-11 07:09 UTC
Labels: T: bug 🐞
