### ISSUE TITLE
Support conditional sections in csproj

### ISSUE THREAD

**Issue by leastprivilege** [dependabot/dependabot-core#2107] opened 2019-09-25 06:36 UTC
Dependabot wants to update the netstandard2.0 section - but that would be wrong.

https://github.com/IdentityModel/IdentityModel.AspNetCore/pull/18/files

**Comment by infin8x** [comment] 2020-07-20 15:22
Duplicate of #1303

**Closed by infin8x** 2020-07-20 15:22 UTC
