### ISSUE TITLE
Request to link `@sentry` & `@opentelemetry` dependencies in Node/Yarn ecosystems

### ISSUE THREAD

**Issue by lizthegrey** [dependabot/dependabot-core#6008] opened 2022-11-01 00:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

`@sentry/*` should be all combined into one update. e.g. updating `@sentry/tracing` should also update `@sentry/node` and `@sentry/browser`, otherwise you wind up with two or three updates that fail to type check separately but will work fine if combined:

https://github.com/eve-val/eve-roster/pull/1421
https://github.com/eve-val/eve-roster/pull/1418
https://github.com/eve-val/eve-roster/pull/1415

This is similar to the case you currently support of associating `@types/*` to the respective `*`.

Similarly, begging a favour on behalf of OTel, all OTel versions should be bundled coupled together -- e.g. these all have a common versioning scheme

```
    "@opentelemetry/core": "^1.7.0",
    "@opentelemetry/sdk-trace-base": "^1.7.0",
    "@opentelemetry/sdk-trace-node": "^1.7.0",
```

as do these

```
    "@opentelemetry/exporter-trace-otlp-grpc": "^0.33.0",
    "@opentelemetry/instrumentation": "^0.33.0",
    "@opentelemetry/instrumentation-http": "^0.33.0",
```

**Comment by lizthegrey** [comment] 2022-11-01 00:15
A rough heuristic I'd propose is that if packages share the same prefix either `@foo/*` or or `foo` or `foo-*` and are being update from: and to: the same version numbers, they should be tried aggregated together.

**Comment by jeffwidman** [comment] 2022-11-01 00:48
Yeah, I hear what you're saying.  That is annoying.

There's a couple of ways to tackle this:
* Have a pre-configured internal lists of packages that bump together... this is non-scalable across the number of ecosystems we support so we'd rather avoid that pain.
* Allow users to configure their own lists of packages that they want bumped together... this is an interesting idea, not sure what it'd take to built it out. It wouldn't allow for shared lists, but it'd be better than nothing, and it's the only one that would solve some innersource use cases.
* Allow libraries to specify groups of deps they want to be bumped together with. This inverts ☝️, and might be interesting, but has some weird pretty much unresolvable edge cases. Such as what happens if a library stops maintaining their list?
* Use a heuristic like what you suggested above. It'd generally work, except when it doesn't. 😀 
* Support grouped updates in general... ie, if we assemble a single PR of your outdated deps, then as long as upstream releases everything together, we'd pickup all those bumps in one shot. Unfortunately you might get other deps shoehorned into that PR, but that's a separate problem.
* Allow users to dynamically specify PR's they want grouped together using comment ops, like `@dependabot group #1, #2, #3`... a little tedious, but gives the users the most control.

Anyway, we're still in the very exploratory phases (example https://github.com/dependabot/dependabot-core/pull/5867), no promises of what route we'll eventually go, nor the ETA. But it is definitely on our radar as something we'd like to provide some solutions for.

**Comment by Mr0grog** [comment] 2023-01-10 19:24
I’d been subscribed to #1296 for this issue, and just saw this more specific version of it.

@jurre I didn’t think Dependabot would update `package.json` (not just the lockfile) in the peer dependency case, which I think you’d want to see in this situation. Do I have that wrong? If so, cool! I don’t think I’ve ever seen that happen, and It doesn’t seem like this works for me with `@aws-sdk/lib-storage` and `@aws-sdk/client-s3` (`/lib-storage` has a peer dependency on `/client-s3`). That said, now that I look at the actual `package.json` files, their peer dependency listings are inaccurately broad. That inaccurate broadness seems to be the case in most of the other similar groups I occasionally have to manually update together. 😕 (While that means maintainers could make it better, it also seems like a signal that keeping those listings correctly versioned may be tough in practical cases.)

I’m also not sure maintainers *can* always provide a meaningful peer dependency list. For example, I think part of the reason `@sentry/tracing` does not list `@sentry/node` and `@sentry/browser` as peer dependencies is because it works with *either,* but you should never have both installed, and they would not want to cause NPM warnings or errors by listing both (both could be listed as optional in `peerDependenciesMeta`, but then you don’t get a warning if neither is installed; they may also be worried about compatibility with older NPM versions or other package managers that don’t support that field).

As a user of Dependabot, I’d really love to see a way to configure grouping certain dependencies together in `dependabot.yml`, since the overall problem is not really NPM/JavaScript-specific. That said, just grouping together all `@xyz/*` packages as @lizthegrey proposed (*if* they have identical latest version numbers) would be a huge improvement for me; in JS repositories I maintain, it would solve the vast majority of my failed Dependabot PRs. I don’t know of any obvious cases where it be likely to cause problems, but as noted above, there will probably be some exception to that somewhere. My guess is that it’s extremely rare (especially with the criteria of identical latest version numbers). Maybe it could be an opt-in feature during some testing period to gather feedback or telemetry. 🤷

(“Allow libraries to specify groups of deps they want to be bumped together” would also be neat, but strikes me as really tough, since it would have to be solved differently for every dependency management ecosystem.)

**Comment by jeffwidman** [comment] 2023-02-04 01:24
This is definitely a duplicate of #1296, let's continue the discussion there.

**Closed by jeffwidman** 2023-02-04 01:24 UTC
Labels: T: feature-request, L: javascript:npm, L: javascript:yarn
