### ISSUE TITLE
Add ability to use shorter commit messages (i.e. without body)

### ISSUE THREAD

**Issue by tjanez** [dependabot/dependabot-core#2633] opened 2020-10-13 10:25 UTC
I like Dependabot's pull request description which is lengthy and informative.

On the other hand, I would prefer to be able to configure short and simple commit messages.

For example, instead of this commit message:
```
ci: bump actions/setup-python from v1 to v2.1.3

Bumps [actions/setup-python](https://github.com/actions/setup-python) from v1 to v2.1.3.
- [Release notes](https://github.com/actions/setup-python/releases)
- [Commits](actions/setup-python@v1...c181ffa)

Signed-off-by: dependabot[bot] <support@github.com>
```

I would prefer an option to shorten it to:
```
ci: bump actions/setup-python from v1 to v2.1.3

Signed-off-by: dependabot[bot] <support@github.com>
```
---

An additional bonus side-effect of this is that if a project uses [gitlint](https://github.com/jorisroovers/gitlint) (or a similar git commit messages linter), the shorter commit message would also avoid gitlint errors due to lines exceeding maximum length of 80 characters.

**Comment by jeffwidman** [comment] 2023-02-06 00:20
Duplicate of:
* https://github.com/dependabot/dependabot-core/issues/1460

**Closed** 2023-02-06 00:20 UTC
Labels: T: feature-request, F: pull-requests
