### ISSUE TITLE
no implicit conversion of nil into String (TypeError) when generating commit message for npm_and_yarn

### ISSUE THREAD

**Issue by jgv115** [dependabot/dependabot-core#3560] opened 2021-04-26 07:17 UTC
**Package ecosystem**
npm
**Package manager version**
yarn v1.22.10

**Manifest location and content prior to update**

**dependabot.yml content**

**Updated dependency**
eslint 7.21.0

I'm running dependabot-script on top of dependabot-core and I'm coming across this stack track:

```
Updating eslint (from 7.21.0)…
/usr/lib/ruby/2.6.0/time.rb:372:in `_parse': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/2.6.0/time.rb:372:in `parse'
	from /home/dependabot/.bundle/gems/dependabot-npm_and_yarn-0.143.3/lib/dependabot/npm_and_yarn/metadata_finder.rb:65:in `block in previous_releasers'
	from /home/dependabot/.bundle/gems/dependabot-npm_and_yarn-0.143.3/lib/dependabot/npm_and_yarn/metadata_finder.rb:65:in `reject'
	from /home/dependabot/.bundle/gems/dependabot-npm_and_yarn-0.143.3/lib/dependabot/npm_and_yarn/metadata_finder.rb:65:in `previous_releasers'
	from /home/dependabot/.bundle/gems/dependabot-npm_and_yarn-0.143.3/lib/dependabot/npm_and_yarn/metadata_finder.rb:26:in `maintainer_changes'
	from /usr/lib/ruby/2.6.0/forwardable.rb:230:in `maintainer_changes'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:139:in `maintainer_changes_cascade'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:42:in `to_s'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator/message_builder.rb:323:in `metadata_cascades_for_dep'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator/message_builder.rb:299:in `metadata_cascades'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator/message_builder.rb:50:in `pr_message'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator.rb:133:in `github_creator'
	from /home/dependabot/.bundle/gems/dependabot-common-0.143.3/lib/dependabot/pull_request_creator.rb:102:in `create'
	from /opt/project/generic-update-script.rb:163:in `block in <main>'
	from /opt/project/generic-update-script.rb:102:in `each'
	from /opt/project/generic-update-script.rb:102:in `<main>'
```

Based on this line: https://github.com/dependabot/dependabot-core/blob/2f0db3e851ba2cc43d0b6dcd70da5e69d5b63eb6/npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb#L65

From a quick glance, it seems like what's happening is that the times fetched from the npm listing on line 54 does not include the time fetched from `all_versions_listings` which is derived from the versions in the npm listing.

This is crashing this block of code in my script:

```
  pr_creator = Dependabot::PullRequestCreator.new(
    source: source,
    base_commit: commit,
    dependencies: updated_deps,
    files: updated_files,
    credentials: credentials,
    assignees: assignees,
    author_details: { name: "Dependabot", email: "no-reply@github.com" },
    label_language: true,
  )
  pull_request = pr_creator.create
```

Does anyone have any idea on how to prevent this error?

**Comment by jeffwidman** [comment] 2022-08-25 08:34
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid / reproducible issue?

**Comment by jeffwidman** [comment] 2023-02-02 23:13
Closing due to a lack of user response.

**Closed by jeffwidman** 2023-02-02 23:13 UTC
Labels: T: bug 🐞, L: javascript:yarn
