### ISSUE TITLE
Add authentication support for Composer (private librairies)

### ISSUE THREAD

**Issue by benoitchantre** [dependabot/dependabot-core#3092] opened 2021-02-08 10:09 UTC
At the moment, Dependabot fails to create pull requests when some dependencies come from a composer library requiring an authentication.

Could you add a way to set the required configuration for Composer that would work with the _Secrets_?

**Comment by rdohms** [comment] 2021-02-09 10:53
Duplicate of #2545
Relates to ##2778

In case anyone is looking for more updated information.

**Comment by thepwagner** [comment] 2021-02-11 18:04
Closing as duplicate of https://github.com/dependabot/dependabot-core/issues/2545

The best issue to follow is https://github.com/github/roadmap/issues/67

**Closed by thepwagner** 2021-02-11 18:04 UTC
Labels: T: feature-request
