### ISSUE TITLE
Docker: ARG support fails

### ISSUE THREAD

**Issue by hfhbd** [dependabot/dependabot-core#4725] opened 2022-02-09 18:50 UTC
Sorry, the new docker ARG support https://github.com/dependabot/dependabot-core/pull/4598 still fails, because I forgot to update the file-updater...
The outdated docker version is parsed correctly, and the new version is found, but the file_updater is not able to update the new format: eg `FROM $HUB/docker:20.10.7-dind` to `FROM $HUB/docker:20.10.12-dind`

https://github.com/dependabot/dependabot-core/blob/main/docker/lib/dependabot/docker/file_updater.rb

```stacktrace
/home/dependabot/dependabot-script/.bundle/ruby/2.7.0/gems/dependabot-docker-0.172.1/lib/dependabot/docker/file_updater.rb:57:in `updated_dockerfile_content': Expected content to change! (RuntimeError)
from /home/dependabot/dependabot-script/.bundle/ruby/2.7.0/gems/dependabot-docker-0.172.1/lib/dependabot/docker/file_updater.rb:25:in `block in updated_dependency_files'
from /home/dependabot/dependabot-script/.bundle/ruby/2.7.0/gems/dependabot-docker-0.172.1/lib/dependabot/docker/file_updater.rb:19:in `each'
from /home/dependabot/dependabot-script/.bundle/ruby/2.7.0/gems/dependabot-docker-0.172.1/lib/dependabot/docker/file_updater.rb:19:in `updated_dependency_files'
from ./generic-update-script.rb:232:in `block in <main>'
from ./generic-update-script.rb:192:in `each'
from ./generic-update-script.rb:192:in `<main>'
```

**Comment by jeffwidman** [comment] 2022-09-15 09:24
Closing as a dupe of #2057 since we had to revert the whole thing for now, and the fix (including the bit about updating the File updater) is re-staged in https://github.com/dependabot/dependabot-core/pull/4837.

**Closed by jeffwidman** 2022-09-15 09:24 UTC
Labels: T: bug 🐞, L: docker
