### ISSUE TITLE
Remove these hacks once we've deprecated npm 6 support as it no longer

### ISSUE THREAD

**Issue by lilsunny243** [dependabot/dependabot-core#6806] opened 2023-03-08 19:44 UTC
https://github.com/lilsunny243/dependabot-core/blob/30f9e404c832253c2da6f61d73f6c51a6d96984e/updater/config/.npmrc#L1

**Comment by jeffwidman** [comment] 2023-03-08 21:19
Duplicate of #6805

**Closed** 2023-03-08 21:18 UTC
