### ISSUE TITLE
Ability to have duplicate updates - but different allow types

### ISSUE THREAD

**Issue by kbrashears5** [dependabot/dependabot-core#2390] opened 2020-07-30 22:11 UTC
Ability to have duplicate updates in the same dependabot

Would like the ability to do something like this:
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "production"
        
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    allow:
      - dependency-type: "development"
```

This lets me define that daily, look for dependencies, and weekly look for dev dependencies.

How I have this setup now, I get an error saying 
> The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'

**Comment by volovyk-s** [comment] 2021-08-10 13:50
Any plans on this feature?

**Comment by mwaddell** [comment] 2022-01-29 20:06
Duplicate of #1778

**Comment by jeffwidman** [comment] 2023-02-05 22:41
Thanks @mwaddell ❤️ , closing as a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/1778

**Closed by jeffwidman** 2023-02-05 22:41 UTC
Labels: T: feature-request, F: noise
