### ISSUE TITLE
Dependabot Not working For Javascript in Azure Repos

### ISSUE THREAD

**Issue by Alec321** [dependabot/dependabot-core#2647] opened 2020-10-15 18:19 UTC
Message is empty and get weird type of exception

org => project=> Repo => npm_and_yarn => Dependabot configuration { directory: /WebGui, ignore: [], automerged: ["dependabot/dependabot-core"] }
org => project => Repo  => npm_and_yarn => Fetching dependency files...
org => project => Repo  => npm_and_yarn => Parsing dependencies information..
org => project => Repo  => npm_and_yarn => @angular/animations (10.1.5) => Checking for updates..
org => project =>Repo => npm_and_yarn => @angular/animations (10.1.5 -> 10.1.6) => Generating file updates...
org => project => Repo  => Failed processing: Message =  Type = Dependabot::SharedHelpers::HelperSubprocessFailed

**Package manager/ecosystem**
Javascript NPM
**Manifest contents prior to update**
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/WebApiCore"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "dependabot/dependabot-core"
  - package_manager: "javascript"
    directory: "/WebGui"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "dependabot/dependabot-core"
**Updated dependency**
@angular/animations (10.1.5 -> 10.1.6)
**What you expected to see, versus what you actually saw**
Create a PR like it does for our .Net app. Instead have an exception with no message on why?

**Comment by yotamshapira** [comment] 2020-10-15 20:25
Seems like a duplicate of #2621

**Comment by Alec321** [comment] 2020-10-15 20:31
@yotamshapira could be I didn't know if it being in Azure DevOps and a DevOps repo was enough of a difference? This is also only happening with Javascript not Nuget

**Comment by yotamshapira** [comment] 2020-10-15 20:34
Yes, I'm experiencing similar behaviour where NPM-based repos are slow to update (it takes a day or 2 to "bump")

**Comment by jeffwidman** [comment] 2022-08-11 07:47
There's been a _lot_ of code + infra backend changes since this ticket was filed two years ago.

I'm going to close as I doubt we can repro the issue, but if you're still seeing problems, please file a new issue so that we can figure out what is going wrong in your specific case.

**Closed by jeffwidman** 2022-08-11 07:47 UTC
Labels: T: bug 🐞
