### ISSUE TITLE
Dependabot updates caddy:2.4.5-alpine to caddy:2.4.6-builder instead of caddy:2.4.6-alpine

### ISSUE THREAD

**Issue by kwypchlo** [dependabot/dependabot-core#4391] opened 2021-11-09 11:43 UTC
**Package ecosystem**
docker
**Package manager version**

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**
https://github.com/SkynetLabs/skynet-webportal/blob/master/.github/dependabot.yml#L27-L30
**Updated dependency**
https://hub.docker.com/_/caddy
**What you expected to see, versus what you actually saw**
One Dockerfile contains 2 image dependencies: caddy:2.4.5-builder and caddy:2.4.6-alpine.
caddy:2.4.5-builder got updated to caddy:2.4.6-builder => correct
caddy:2.4.6-alpine for updated to caddy:2.4.6-builder => **incorrect**, should be caddy:2.4.6-alpine
**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**
https://github.com/SkynetLabs/skynet-webportal/pull/1366/commits/c25618cd7607b18002306b74aa6a54daf25464fa
**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment] 2022-08-25 05:01
I'm pretty sure this is a dupe of #5538 which was recently resolved in https://github.com/dependabot/dependabot-core/pull/5560.

**Closed by jeffwidman** 2022-08-25 05:01 UTC
Labels: T: bug 🐞, L: docker
