### ISSUE TITLE
Conda Environment Support

### ISSUE THREAD

**Issue by joshowen** [dependabot/dependabot-core#1249] opened 2019-07-10 20:34 UTC
It would be very helpful if this supported Conda Environment files for Python environments.  Conda is used widely in the Python ecosystem: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

Example Environment File:
https://github.com/enigmampc/catalyst/blob/master/etc/python3.6-environment.yml

I don't know much Ruby, but I'm happy to help however I can.

**Comment by rickard-von-essen-iz** [comment] 2019-10-23 10:45
Still very much needed

**Comment by rebelagentm** [comment] 2019-10-23 16:35
Sorry for the confusion!  We installed Stale to help manage our backlog and some issues got closed before I had the chance to triage them.

**Comment by Zethson** [comment] 2020-03-25 09:24
Is there any progress on this issue?

**Comment by alexvicegrab** [comment] 2020-05-05 21:26
Yes, this would be useful indeed

**Comment by ajschmidt8** [comment] 2020-05-13 17:10
also think this would be a great addition

**Comment by RoyTrudell** [comment] 2020-06-23 21:31
yes, this would help in my workflow also.

**Comment by infin8x** [comment] 2020-07-02 16:31
Duplicate of #2227

**Closed by infin8x** 2020-07-02 16:31 UTC
Labels: L: python:pip, T: feature-request
