### ISSUE TITLE
Large files in the repo (and git history)

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#7053] opened 2023-04-11 19:34 UTC
### Code improvement description

I noticed that the repo is considerable larger than expected (80+MB) that make it very slow for first time clone (and possibly CI) 

Is there any way we can store these in a different location? 

Possibly using [Git LFS](https://git-lfs.com/)

Some examples : 

> 
> 2431aca2d8af  1.0MiB npm_and_yarn/helpers/test/npm/fixtures/subdependency-version-resolver/v2-lockfile/package-lock.json
> 00c7145c746b  1.1MiB npm_and_yarn/spec/fixtures/npm_responses/react-apollo.json
> 57f3ae3c8bdf  1.1MiB npm_and_yarn/spec/fixtures/npm_responses/vue.json
> aa623040e938  1.6MiB common/spec/fixtures/git/upload_packs/gatsby
> 243478fffda4  1.7MiB bin/cli/github_graphql_schema.json
> e44722e933f8  1.8MiB helpers/php/composer.phar
> 322e0ff37482  1.8MiB helpers/php/composer.phar
> af0feb3adc2a  1.8MiB helpers/php/composer.phar
> 96fa2df7bdbe  1.8MiB helpers/php/composer.phar
> 47f24f66e01a  2.1MiB npm_and_yarn/spec/fixtures/projects/yarn_berry/simple_node_modules/.yarn/releases/yarn-3.3.0.cjs
> 8329dc721f16  2.7MiB helpers/terraform/json2hcl.darwin
> 831eb76813f3  2.8MiB helpers/terraform/json2hcl.linux
> e2011b9b012d  2.8MiB helpers/go/updater/updater.darwin64
> 394b53713ab4  2.8MiB helpers/go/updater/updater.linux64
> f7c6c1cc8ad4  4.0MiB composer/spec/fixtures/packagist_responses/illuminate--console.json
> 2c3953262175  4.1MiB composer/spec/fixtures/packagist_responses/illuminate--support.json
> 3f402a01cc97  4.2MiB omnibus/vendor/solargraph-0.40.4.gem
> 8af8d1f84bd2  4.3MiB omnibus/vendor/debase-ruby_core_source-0.10.12.gem
> 3ae82e79875a  6.0MiB omnibus/vendor/nokogiri-1.11.2-x86_64-darwin.gem
> bf3fc168a3c3  7.6MiB npm_and_yarn/spec/fixtures/vcr_cassettes/Dependabot_NpmAndYarn_UpdateChecker/_up_to_date_/with_no_lockfile/returns_false_when_there_is_a_newer_version_available.yml
> 43b45556c8fc  8.8MiB omnibus/vendor/gpgme-2.0.20.gem
> e83bfea0b6f5   14MiB bundler/spec/fixtures/rubygems_responses/index

I extracted them running : 

```shell

git rev-list --objects --all |
  git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
  sed -n 's/^blob //p' |
  sort --numeric-sort --key=2 |
  cut -c 1-12,41- |
  $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest

```

From https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history

**Comment by jeffwidman** [comment] 2023-04-17 22:28
Yeah, it's annoying, although 80 MB isn't horrific TBH, my last employer had a git monorepo that was closing in on 3 GB! 😢 🤣 

The problem is removing these from a git repo will require not only moving them from the file system, but also rewriting the entire git history to drop all references to the file. It's probably been close to a decade since I did a deep dive into this problem, but my understanding is this results in breaking everyone's references to the git repo, causing a lot of pain for everyone to re-create branches, PR's etc. I'm not aware of an easy way to do this without impacting everyone.

So at this point, a few extra megs probably isn't that big of a price to pay compared to the cost of getting everyone in-sync.

If this crept up to half a gig or a gig, or if those files were only committed in the last few commits where most of the older references to the repo wouldn't be broken then we'd be open to this for sure.

I'm going to close as "wontfix", but if you find a way to do this w/o causing a lot of pain to developer / CI workflows, then would love to do it.

**Closed by jeffwidman** 2023-04-17 22:28 UTC
Labels: core 🍏, T: tech-debt ⚙️, build 🛠
