### ISSUE TITLE
No auto-rebase after `@dependabot merge` command

### ISSUE THREAD

**Issue by Maxim-Mazurok** [dependabot/dependabot-core#3132] opened 2021-02-14 03:38 UTC
Related to: https://github.com/dependabot/feedback/issues/365

**Package manager/ecosystem**
javascript, npm

**Manifest contents prior to update**
https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/dependabot.yml

**What you expected to see, versus what you actually saw**
Every week, dependabot open a couple of PRs.
I have [auto-merge action](https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/workflows/auto-merge-dependabot.yml), which adds "@dependabot merge" comment to all minor update PRs automatically. The problem is that only the first one gets merged. Other ones need to be rebased, but they never do it automatically. I have to manually comment "@dependabot rebase" on every PR, which defeats the purpose.
I want dependabot to automatically rebase my PRs even if I have commented "@dependabot merge".
I believe that this was implemented as part of https://github.com/dependabot/feedback/issues/365 and now it doesn't work, so this may be a regression.

**Images of the diff or a link to the PR, issue or logs**

All 4 got opened yesterday:
This one got merged: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/443
These 3 are stuck unless I manually comment `"@dependabot rebase"`
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/441
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/442
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/444

**Comment by Maxim-Mazurok** [comment] 2021-02-20 07:41
@greysteil do you know anything about this, by chance?

**Comment by greysteil** [comment] 2021-02-21 17:43
Afraid not - I haven't worked on Dependabot for the last couple of years! It's in the safe hands of @hmarr and @asciimike now, and this looks like a very clear bug report for them and the team to dig into.

**Comment by jurre** [comment] 2021-04-12 09:28
Hi @Maxim-Mazurok, this has been open for a while, apologies for that.

The PRs you linked to have since been rebased and merged, so it's a little hard to dive into what happened.

> I want dependabot to automatically rebase my PRs even if I have commented "@dependabot merge".

It's good to know that dependabot will only rebase if there are any merge conflicts, but not when the ref is out of date. Do you happen to know if this was the case? Has this happened since?

**Comment by Maxim-Mazurok** [comment] 2021-04-12 10:08
@jurre thank you for picking up this one.
Unfortunately, this was very frustrating for me, so instead of relying on `@dependabot merge` command, I started using [Kodiak merge.automerge_dependencies](https://kodiakhq.com/docs/config-reference#mergeautomerge_dependenciesversions). Here's the commit in which I switched: https://github.com/Maxim-Mazurok/google-api-typings-generator/commit/40d393bdb1e41d72599250c5366c1e83b8eac5ce

Now it works as expected.

As you can see, dependabot opened two PRs last Saturday: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/478 and https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/479

First, I have approved https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/478#pullrequestreview-632887234
Then I approved https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/479#pullrequestreview-632887257

Kodiak merged the first one: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/478#event-4577066254
Then, Kodiak rebased the second one: [Maxim-Mazurok/google-api-typings-generator@`429318c` (#479)](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/479/commits/429318c87ba7199fd87b9c289b99c3024220eb3b)
And Kodiak merged it: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/478#event-4577066254

This is precisely what I wanted Dependabot, paired with [ahmadnassri/action-dependabot-auto-merge)](https://github.com/ahmadnassri/action-dependabot-auto-merge) to do.

That being said, I'll try to create reproduction in the new repo.

**Comment by Maxim-Mazurok** [comment] 2021-04-12 10:30
I forgot to mention my repo settings:

```
  Protect matching branches
   [x] Require pull request reviews before merging: 
    Required approving reviews: 1
    [x] Dismiss stale pull request approvals when new commits are pushed
   [x] Require status checks to pass before merging
    [x] Require branches to be up to date before merging
    Status checks found in the last week for this repository: 
     [x] test
```

These options are checked. Everything else is disabled.

**Comment by Maxim-Mazurok** [comment] 2021-04-12 11:39
I tried to reproduce it here: https://github.com/Maxim-Mazurok/dependabot-3132-repro but I couldn't.

Because of the https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60 issue, I had to change from `on: pull_request` to `on: pull_request_target`.

Everything works as expected:
1. 3 PRs opened: https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/8 and https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/9 and https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/10
2. https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/8 got merged
3. https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/9 and https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/10 rebased
4. https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/9 got merged
5. https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/10 rebased
6. https://github.com/Maxim-Mazurok/dependabot-3132-repro/pull/10 got merged

And all of that even without the need to manually approve PRs, perfect! (even though not very secure)

I'm going to try this approach on my main repo and will let you know how it goes after the weekend. I do updates on it every Saturday.

**Comment by jurre** [comment] 2021-04-16 08:25
I'm expecting this to have been resolved, I'm going to close the issue out for now, but please reopen if you run into things @Maxim-Mazurok!

**Comment by Maxim-Mazurok** [comment] 2021-04-16 08:26
It's only Friday here in Sydney, so I haven't confirmed if it works. Will reopen in case if it doesn't.

**Comment by Maxim-Mazurok** [comment] 2021-04-17 03:00
Unfortunately, this week I received only one dependency update (https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/481) so couldn't verify rebasing functionality. Will have to wait for the next Saturday.

**Comment by Maxim-Mazurok** [comment] 2021-05-08 00:59
Finally, this week I received 4 PRs:
- [#487 (merged)](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/487)
- [#488 (stuck)](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/488)
- [#489 (stuck)](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/489)
- [#490 (merged)](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/490)

As you can see, two of them are "stuck" with `@dependabot merge` comment :(

**Comment by Maxim-Mazurok** [comment] 2021-05-21 00:39
@jurre any ETA on when I could manually merge stuck PRs? Don't want to do that before your investigation.

**Comment by Maxim-Mazurok** [comment] 2021-05-29 03:13
@jurre following up, as the issue has been reopened 19 days ago and now I have 4 PRs stuck. Take a look, please, before I manually merge these PRs. Thanks!

**Comment by Maxim-Mazurok** [comment] 2021-06-07 03:45
@jurre bumping this, since 3 PRs are still stuck, see https://github.com/Maxim-Mazurok/google-api-typings-generator/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aapp%2Fdependabot

**Comment by Maxim-Mazurok** [comment] 2021-06-25 10:29
> unsure if related, but on a private repo we see that dependabot doesn't work the whole day - we merge a pr and than it takes hours before dependabot rebase the others.

I wish it was the case with my repo. PRs never get rebased for me :(

@jurre can you please confirm that this issue is not abandoned? I really want to help you by not rebasing PRs manually, but if this issue is abandoned - I'll have to look for alternative solutions. Cheers!

**Comment by Maxim-Mazurok** [comment] 2021-07-03 03:46
@jurre, unfortunately, I haven't heard back from you in a while, but I see from your GitHub profile that you're active. So I'm assuming that this issue is abandoned and I will be reverting back to using https://github.com/chdsbd/kodiak to auto-merge dependabot PRs

**Comment by BriceTossim** [comment] 2021-07-09 12:11
@dependabot help

**Comment by bdo** [comment] 2021-12-29 10:21
We're also getting the same issue in some of our private Discovery repos!

In one of these projects, I ended up using a solution described at the bottom of this community post: [How can I stop babysitting Dependabot?](https://github.community/t/how-can-i-stop-babysitting-dependabot/178664/3)

It would be great if someone from Github could assist debugging the problem. It is sad to see that @Maxim-Mazurok's efforts to reproduce the problem have been done in vain.

**Comment by Maxim-Mazurok** [comment] 2021-12-29 10:37
https://github.com/marketplace/actions/gha-auto-dependabot-rebase seems like a pretty nice hack, thanks for sharing!

I've been using Kodiak for a while now and it worked flawlessly for me. Almost every Saturday I get a couple of dependencies auto-updated, rebased, and merged.

My configs: https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/dependabot.yml and https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.kodiak.toml

The only weird issue is that dependabot refuse to add "automerge-kodiak" label to PRs... And for whatever reason that doesn't stop Kodiak from auto-merging them anyway :D So somehow it works...

**Comment by Maxim-Mazurok** [comment] 2022-02-22 03:14
Actually, in [this PR](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/593) I somehow had some conflicts that kodiak wasn't able to resolve using rebase. But dependabot isn't just doing git rebase, as far as I understand, it's doing npm update from master discarding original PR changes.

So I will be adding [gha-auto-dependabot-rebase](https://github.com/marketplace/actions/gha-auto-dependabot-rebase) into the mix to handle rebasing.

**Comment by abdulapopoola** [comment] 2024-03-04 21:27
Closing out as stale

**Closed by abdulapopoola** 2024-03-04 21:27 UTC
Labels: T: bug 🐞, F: pull-requests, service 💁
