### ISSUE TITLE
[Grouped Updates] single dependency in group cannot be ignored

### ISSUE THREAD

**Issue by huehnerlady** [dependabot/dependabot-core#7518] opened 2023-07-05 07:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

GRadle

### Package manager version

8.1.1

### Language version

Kotlin

### What you expected to see, versus what you actually saw

I got a first grouped Pull Request, but there in the dependabot comments there is no possibility to ignore one or many dependencies.

I expected to see:
![image](https://github.com/dependabot/dependabot-core/assets/12533979/5fde9f7c-4573-46ee-bdec-af46c1735b12)

But I get:
![image](https://github.com/dependabot/dependabot-core/assets/12533979/e182170b-c033-4619-8ed8-d724ba0ef79c)

I expect to have the possibility to ignore one version / minor version / major version and then dependabot to recreate the grouped pull request for all but this version.

As a bonus feature request it would be nice to be able to potentially mention multiple dependencies

**Comment by Nishnha** [comment] 2023-07-05 17:41
Hi we don't currently support ignoring dependencies in grouped updates. We do plan on adding support in the future.

For now I am closing this issue as a duplicate of https://github.com/dependabot/dependabot-core/issues/7461

**Closed by Nishnha** 2023-07-05 17:41 UTC
Labels: T: bug 🐞
