### ISSUE TITLE
dependabot doesn't remove old version of package from go.sum when updating

### ISSUE THREAD

**Issue by echarrod** [dependabot/dependabot-core#1707] opened 2020-02-27 10:01 UTC
dependabot correctly updates the go.mod, and adds the new version to go.sum. But it doesn't remove the old version from go.sum.

See https://github.com/getyoti/yoti-go-sdk/pull/111/ for initial commit by dependabot, I then manually added a fix in a separate commit

**Comment by echarrod** [comment] 2020-03-17 08:32
Happened again - https://github.com/getyoti/yoti-go-sdk/pull/112/files

**Comment by hmarr** [comment] 2020-05-13 11:20
Looks like this is a duplicate of https://github.com/dependabot/feedback/issues/909, so let's track this there.

**Closed by hmarr** 2020-05-13 11:20 UTC
