### ISSUE TITLE
Dependabot doesn't create PR

### ISSUE THREAD

**Issue by monaka** [dependabot/dependabot-core#7542] opened 2023-07-10 07:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### Manifest location and content before the Dependabot update

https://github.com/pizzafactory-contorno/piatto/blob/main/debian-10.1/Dockerfile

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: docker
  directory: /alpine-3.10
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.10"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.15.0
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.15.0"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.16
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.16"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.17
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.17"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.18
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.18"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-10
  ignore:
  - dependency-name: debian
    versions:
    - "!= 10.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-10.1
  ignore:
  - dependency-name: debian
    versions:
    - "!= 10.1.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-10.2
  ignore:
  - dependency-name: debian
    versions:
    - "!= 10.2.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-11.1
  ignore:
  - dependency-name: debian
    versions:
    - "!= 11.1.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-9.11
  ignore:
  - dependency-name: debian
    versions:
    - "!= 9.11.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-16.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 16.04"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-18.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 18.04"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-20.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 20.04"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-22.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 22.04"
  schedule:
    interval: daily
```

### Updated dependency

Update logs in Dependency-graph

```
updater | 2023/07/08 10:38:14 INFO <job_690289655> Finished job processing
updater | 2023/07/08 10:38:14 INFO Results:
updater | +--------------------------------------------------+
updater | |       Changes to Dependabot Pull Requests        |
updater | +---------+----------------------------------------+
updater | | created | debian ( from `a893719` to `1125379` ) |
updater | +---------+----------------------------------------+
updater | time="2023-07-08T10:38:15Z" level=info msg="task complete" container_id=job-690289655-updater exit_code=0 job_id=690289655 step=updater
```

### What you expected to see, versus what you actually saw

I expect a pull request is created.
I see no pull requests.

**Comment by monaka** [comment] 2023-07-10 07:45
Additional info:

Dependabot creates some PRs for another Dockerfile in the same repository. e.g. https://github.com/pizzafactory-contorno/piatto/pull/59

I guess Dependabot fails to create PR if the image tag contains `-`.

* `FROM ubuntu:22.04@sha256:...` is acceptable.
* `FROM debian:10.1-slim@sha256:...` may not be acceptable.

**Comment by Didel** [comment] 2023-08-03 18:25
I think I am experiencing the same issue. In my case, I am using the npm environment.

The result of the logs indicate that it should create a PR:

```
updater | 2023/08/03 15:50:19 INFO Results:
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | @storybook/addon-essentials ( from 7.1.1 to 7.2.1 ), @storybook/addon-interactions ( from 7.1.1 to 7.2.1 ), @storyboo... |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | time="2023-08-03T15:50:19Z" level=info msg="task complete" container_id=job-704710861-updater exit_code=0 job_id=704710861 step=updater
```

However, no PR is actually created.

Interestingly, in my case the name of the package to update also contains a dash (`-`). I am using the experimental Groups feature, but it has been working fine for this same group less than a week ago.

The relevan

**Comment by arununzer** [comment] 2023-08-08 07:13
The issue which i had was with the schedule.time: "16:17"... after setting it to 09:00 it worked.. not sure what is the time format it supports.. 12 or 24 hours ?

**Comment by larouxn** [comment] 2023-08-13 22:16
> I think I am experiencing the same issue. In my case, I am using the npm environment.
> 
> The result of the logs indicate that it should create a PR:
> 
> ```
> updater | 2023/08/03 15:50:19 INFO Results:
> updater | +------------------------------------------------------------------------------------------------------------------------------------+
> updater | |                                                Changes to Dependabot Pull Requests                                                 |
> updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
> updater | | created | @storybook/addon-essentials ( from 7.1.1 to 7.2.1 ), @storybook/addon-interactions ( from 7.1.1 to 7.2.1 ), @storyboo... |
> updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
> updater | time="2023-08-03T15:50:19Z" level=info msg="task complete" container_id=job-704710861-updater exit_code=0 job_id=704710861 step=updater
> ```
> 
> However, no PR is actually created.

Whatever issue was causing this might have been fixed. Finally received a grouped Storybook bump yesterday.

**Comment by Didel** [comment] 2023-08-16 05:57
It does seem to work for me again as well... might have been a hickup, but certainly not something caused by misconfiguration.

**Comment by deivid-rodriguez** [comment] 2023-08-16 06:59
Not sure what fixed this, but let's close this since it seems indeed fixed! :)

**Closed by deivid-rodriguez** 2023-08-16 06:59 UTC
Labels: T: bug 🐞
