### ISSUE TITLE
Ability to update only to major versions

### ISSUE THREAD

**Issue by limonte** [dependabot/dependabot-core#2646] opened 2020-10-15 12:17 UTC
It'd be great to decrease the amount of noise dependabot creates by creating pull requests only for updating to a new major releases.

Greenkeeper was working that way and it was exactly what I need, dependabot isn't configurable at all regarding to the semver level.

**Comment by feelepxyz** [comment] 2021-04-09 09:46
Closing as a duplicate of #2219

**Closed by feelepxyz** 2021-04-09 09:46 UTC
Labels: F: noise, T: feature-request
