### ISSUE TITLE
Dependabot cannot update two top-level bundler dependencies with an equality version constraint between them

### ISSUE THREAD

**Issue by Bo98** [dependabot/dependabot-core#5569] opened 2022-08-22 18:26 UTC
**Package ecosystem**
Bundler
**Package manager version**
Both v1 and v2
**Manifest location and content before the Dependabot update**
Gemfile: https://github.com/Bo98/dependabot-sorbet-test/blob/main/Gemfile

```rb
source "https://rubygems.org"

gem "sorbet-runtime"

group :development, optional: true do
  gem "sorbet-static-and-runtime"
end
```

Gemfile.lock: https://github.com/Bo98/dependabot-sorbet-test/blob/main/Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.10175)
      sorbet-static (= 0.5.10175)
    sorbet-runtime (0.5.10175)
    sorbet-static (0.5.10175-universal-darwin-14)
    sorbet-static-and-runtime (0.5.10175)
      sorbet (= 0.5.10175)
      sorbet-runtime (= 0.5.10175)

PLATFORMS
  ruby

DEPENDENCIES
  sorbet-runtime
  sorbet-static-and-runtime
```

**dependabot.yml content**
https://github.com/Bo98/dependabot-sorbet-test/blob/main/.github/dependabot.yml
**Updated dependency**
sorbet-runtime and sorbet-static-and-runtime to latest (0.5.10346 at time of writing)
**What you expected to see, versus what you actually saw**
Expected: Both sorbet-runtime and sorbet-static-and-runtime is updated.
Actual: Neither is updated.
**Native package manager behavior**
Bundler v1 has an odd warning but otherwise works (nothing was removed like it claims):

```
$ bundle update sorbet-runtime sorbet-static-and-runtime --conservative
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies........
Using bundler 1.17.3
Using sorbet-runtime 0.5.10346 (was 0.5.10175)
Bundler attempted to update sorbet-static-and-runtime but it was removed from the bundle
Bundle updated!
```

Bundler v2 only works without `--conservative`:

```
$ bundle update sorbet-runtime sorbet-static-and-runtime --conservative
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.11
Using sorbet-runtime 0.5.10175
Bundler attempted to update sorbet-runtime but its version stayed the same
Bundle updated!

$ bundle update sorbet-runtime sorbet-static-and-runtime
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.3.11
Using sorbet-runtime 0.5.10346 (was 0.5.10175)
Bundle updated!
```

---

I suspect the answer here is that this scenario is unsupported, given each top-level dependency has its own policies such as version ignore ranges which probably complicates trying to support scenarios like this. Though given this pattern will start to gain popularity (`sorbet-static-and-runtime` did not exist a few months ago), I thought it's worth at least documenting in an issue.

**Comment by deivid-rodriguez** [comment] 2022-08-24 18:00
Thanks for the report @Bo98!

We have confirmed the issue and identified that it's related to the `lockfile-only` versioning strategy. We'll be working on fixing this, but you may be able to workaround the issue by removing that configuration, although of course, that might get you updates that you don't want 😅.

**Comment by Bo98** [comment] 2022-08-30 16:34
Thanks! A brief local test of that PR seems to indicate that it works!

**Comment by deivid-rodriguez** [comment] 2022-08-31 08:57
Nice, thanks for checking @Bo98! ❤️ 

#5581 by itself won't fix the issue, we need a few other changes to our internal infrastructure too, but I'll let you know once the fix is out!

**Comment by deivid-rodriguez** [comment] 2022-10-17 12:17
I had to revert the fix because it was created problems worse than this bug. Will retry it, hopefully soon.

**Comment by Bo98** [comment] 2022-10-17 12:18
No worries, thanks for the work you've done so far!

**Closed** 2023-05-05 18:07 UTC
Labels: T: bug 🐞, L: ruby:bundler
