### ISSUE TITLE
Swift Package Manager Support?

### ISSUE THREAD

**Issue by satishbabariya** [dependabot/dependabot-core#1245] opened 2019-07-04 14:31 UTC
Is there any plans for spm support?, some of the following details may help

1. use `Package.swift` in `file_fetcher`
2. use `.package(url: "https://github.com/abc/abc.git", from: "1.0.0)` for dependency in `file_parser`

Listing Dependency using Command Line (exec)

```
swift package dump-package --type json
```

For Package Metadata

```
swift package describe --type json
```

3. use git tag for checking new version update

I don't know much ruby, but I can help in creating specific dependency updater for package file.

**Comment by greysteil** [comment] 2019-07-04 23:02
We'd love to add spm support. Are there any docs and/or example `Package.swift` files you can link to?

**Comment by satishbabariya** [comment] 2019-07-05 08:20
here is the documentation on spm [https://github.com/apple/swift-package-manager/tree/master/Documentation](https://github.com/apple/swift-package-manager/tree/master/Documentation)

and here is the example of package file [https://github.com/vapor/vapor/blob/master/Package.swift](https://github.com/vapor/vapor/blob/master/Package.swift)

**Comment by satishbabariya** [comment] 2019-07-05 08:26
also here is the dockerfile in case
```dockerfile
FROM ubuntu:18.04

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
    apt-get -q install -y \
    libatomic1 \
    libbsd0 \
    libcurl4 \
    libxml2 \
    tzdata \
    && rm -r /var/lib/apt/lists/*

ARG SWIFT_PLATFORM=ubuntu18.04
ARG SWIFT_BRANCH=swift-5.0.1-release
ARG SWIFT_VERSION=swift-5.0.1-RELEASE

ENV SWIFT_PLATFORM=$SWIFT_PLATFORM \
    SWIFT_BRANCH=$SWIFT_BRANCH \
    SWIFT_VERSION=$SWIFT_VERSION

RUN SWIFT_URL=https://swift.org/builds/$SWIFT_BRANCH/$(echo "$SWIFT_PLATFORM" | tr -d .)/$SWIFT_VERSION/$SWIFT_VERSION-$SWIFT_PLATFORM.tar.gz \
    && curl -fSsL $SWIFT_URL -o swift.tar.gz \
    && export GNUPGHOME="$(mktemp -d)" \
    && tar -xzf swift.tar.gz --directory / --strip-components=1 \
    && rm -r "$GNUPGHOME" swift.tar.gz \
    && chmod -R o+r /usr/lib/swift

# Print Installed Swift Version
RUN swift --version
```

**Comment by orj** [comment] 2020-10-15 01:29
Gonna add my voice to those calling for Swift Package Manager support in Dependabot.

**Comment by lyzkov** [comment] 2021-02-21 02:33
Where is SPM hook for pushing updatedeps commit to git repo? Where is a bot here? Or dependabot is little bit more advanced yet powerful?

**Comment by apps4everyone** [comment] 2021-03-01 17:46
Any progress here? Would be great to have SPM soon....

**Comment by greysteil** [comment] 2021-03-02 02:53
Cc @feelepxyz and @asciimike for awareness. I know the Dependabot team are heads down on some other features and not planning to expand to new ecosystems imminently - they'll have the latest, though.

**Comment by Kurgol** [comment] 2021-05-24 15:28
Just a note to say that [ZD1133745](https://github.com/dependabot/dependabot-core/issues/1245) customer is also requesting swift support. Abbot Labs 👍

**Comment by asciimike** [comment] 2021-05-25 22:53
Xref https://github.com/dependabot/dependabot-core/pull/3772

**Comment by loganblevins** [comment] 2022-05-20 21:07
Bumping for SPM vote

**Comment by ryandrewery** [comment] 2022-07-13 11:36
Hello all, 

I was following up to see if there has been any movement in the road map to add swift support to Dependabot? KBC bank have requested support. Are there any updates that could be shared? Thanks cc @sam-rowe

**Comment by Panajev** [comment] 2022-09-06 08:45
Is there any update or any roadmap on this? Speaking as a GitHub Enteprise customer that will get this months behind the .com version so the delay in announcing anything for the regular versions are even more painful :/.

**Comment by jeffwidman** [comment] 2022-09-12 18:43
Related: https://github.com/dependabot/dependabot-core/pull/5562

We are starting to get a little more caught up on our backlog / infra tasks as a team, so I expect in the not _too_ distant future we'll start looking at adding ecosystems again. But I'm afraid we don't have anything specific to share just yet.

In the meantime, if Swift support is important to you, please 👍 the original issue... it helps us gauge the popularity of different ecosystems that are requested. No need to add a comment, that just spams the folks following this issue for updates.

**Comment by 0xTim** [comment] 2023-02-01 22:18
@jeffwidman any news to share here - we're looking at picking this up to get the support over the line so interested to know if it's worth spending the effort on

**Comment by afern247** [comment] 2023-03-16 23:11
Any update on this?

**Comment by baptistedajon** [comment] 2023-03-17 10:58
Interested to have updates too :)

**Comment by jacobhzen** [comment] 2023-04-04 19:23
Very interested

**Comment by daytime-em** [comment] 2023-04-08 14:55
Putting myself down as interested in SwiftPM support!

**Comment by brennobemoura** [comment] 2023-04-15 16:22
I'm waiting for it! 🔎

**Comment by afern247** [comment] 2023-04-15 19:58
Same, can we add support please

**Comment by deivid-rodriguez** [comment] 2023-04-17 12:18
Please, if your comment is just a reaction to show support for this feature, do use reactions! See https://github.com/dependabot/dependabot-core#no-1-comments.

**Comment by deivid-rodriguez** [comment] 2023-06-21 18:17
Hei!

Just some heads up that we're actively working on this and plan to ship Swift support during this quarter.

**Comment by loganblevins** [comment] 2023-06-21 18:20
@deivid-rodriguez Thank you! Wonderful news.

**Comment by caiofbpa** [comment] 2023-07-11 22:07
@deivid-rodriguez please note that there's a difference in the way Swift Libraries/Executables and Swift Apps deal with SwiftPM:

Swift Libraries/Executables (Libraries, Command Line Tools, Server-side Swift)
- Have a `Package.swift` file defining dependency version rules
- Have a `Package.resolved` file with the "pins" for specific package versions actually used
- Interactions are mostly editing `Package.swift` and running `swift package resolve` or `swift package update`

Swift Apps (iOS, macOS)
- Have a `*.xcodeproj/project.pbxproj` file defining dependency version rules (among other project stuff)
- Have a `*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` file with the "pins" for specific package versions actually used
- Interactions are mostly through Xcode manually editing version rules and clicking at `Update to Latest Package Versions`

Adding support to Swift Libraries/Executables should be trivial, but supporting Swift Apps doesn't look easy to automate. If you could confirm what kind of support is being worked on, that could help some of us to set our expectations in terms of use cases.

**Comment by deivid-rodriguez** [comment] 2023-07-12 07:30
Yes, we're only working in the first case as of now.

**Comment by pyrtsa** [comment] 2023-07-12 07:39
> * Interactions are mostly through Xcode manually editing version rules and clicking at `Update to Latest Package Versions`

I think you can automate this part as well by using the `xcodebuild -resolvePackageDependencies` command with some further options.

**Comment by deivid-rodriguez** [comment] 2023-07-25 21:02
Hello!

We have enabled beta testing for Swift Package Manager version updates. To opt-in to it, you need to specify the `enable-beta-ecosystems: true` top level configuration, and `swift` as the package ecosystem. Like this

```yaml
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
```

Feel free to try it out and report any issues you find.

Note that there's [a known issue](https://github.com/dependabot/dependabot-core/pull/7525#issuecomment-1633969938) with a specific Swift dependency where we end up adding some unnecessary changes to the `Package.resolved` file. Swift should deal with it just fine but I can see how it could be annoying. No need to report that one issue if you find it since we already know about it :)

Thanks!

**Comment by redfearnk** [comment] 2023-07-25 21:29
Have you completed the Xcode project file version or only the Package.swift version as outlined above?

**Comment by deivid-rodriguez** [comment] 2023-07-26 09:11
Only through `Package.swift` for now. Will open a separate issue for Xcode projects once we close this one and release the initial version supporting SwiftPM.

**Comment by 0xTim** [comment] 2023-07-26 09:30
Supporting Xcode apps is going to be hard, if not impossible. There's a resolved file, but the location of it is liable to move on any Xcode update. The manifest itself is stored in a the `project.pbxproj` in a custom format. That format (and location) is not defined anywhere authoritative and can change at any point (and has done so in the past)

**Comment by redfearnk** [comment] 2023-07-26 16:06
Hopefully Apple will make the Xcode version better in the future. I don't see any reason why they can't just use a Package.swift

**Comment by pyrtsa** [comment] 2023-07-26 17:12
I can't recommend this, but as a potential workaround, it seems to me `swift package` commands do the right thing in an Xcode project if you just create a symlink next to the package file pointing to your project's `*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`.

**Comment by timdawborn** [comment] 2023-07-28 04:56
@deivid-rodriguez Where would you like bug reports for this beta release — here, or in another issue? We've been struggling to get this to run without crashing on our iOS app. The stacktrace from Dependabot is currently:

```
pdater | 2023/07/28 04:22:26 ERROR <job_701761721> error: 'repo': Source files for target OurDependencies should be located under 'Sources/OurDependencies', or a custom sources path can be set with the 'path' property in Package.swift
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/shared_helpers.rb:345:in `run_shell_command'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:37:in `formatted_deps'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:23:in `block (2 levels) in parse'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/shared_helpers.rb:187:in `with_git_configured'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:22:in `block in parse'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `block in in_a_temporary_repo_directory'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `chdir'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `in_a_temporary_repo_directory'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:19:in `parse'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/update_checker/version_resolver.rb:40:in `fetch_latest_resolvable_version'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/update_checker/version_resolver.rb:20:in `latest_resolvable_version'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/update_checker.rb:66:in `fetch_latest_resolvable_version'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/swift/lib/dependabot/swift/update_checker.rb:21:in `latest_resolvable_version'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:75:in `preferred_resolvable_version'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:263:in `preferred_version_resolvable_with_unlock?'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:255:in `numeric_version_can_update?'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:205:in `version_can_update?'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:45:in `can_update?'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:204:in `requirements_to_unlock'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:88:in `check_and_create_pull_request'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `check_and_create_pr_with_error_handling'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:63:in `run'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/07/28 04:22:26 ERROR <job_701761721> bin/update_files.rb:23:in `<main>'
```

In our repo, there is indeed a `OurDependencies/Sources/OurDependencies.swift` file, so this error was initially rather confusing. The stacktrace shows that it's coming from running `swift package show-dependencies --format json` from inside the `OurDependencies` folder (which is what is set as the `path` in our `swift` entry in `.github/dependabot.yml`). The error itself [looks to be coming from SPM](https://github.com/apple/swift-package-manager/blob/7b23fa795d3bc1fa26f9fbf20e067a38bd1f3bf2/Sources/PackageLoading/Diagnostics.swift#L17-L24). [This logic here in Dependabot](https://github.com/dependabot/dependabot-core/blob/c9e14c9c7158181e8e2ed41df10e248988295931/swift/lib/dependabot/swift/file_parser/dependency_parser.rb#L30-L34) appears to only be writing the dependency files, which I'm guessing might only be the `Package.*` files?

Locally, going into `OurDependencies` and removing the `Sources` folder entirely, I can reproduce this error message from SPM.

Is this expected behaviour?

**Comment by deivid-rodriguez** [comment] 2023-07-28 12:09
Hi @timdawborn, thanks for digging into this!

I think a new issue is better, can you copy this to a new issue? If you can also create a small public repository that reproduces it, it would be perfect. In principle, it seems unexpected because the full clone of the repo should be present at `repo_contents_path`, we only rewrite manifest changes on top of it to figure out updates.

**Comment by caiofbpa** [comment] 2023-07-29 04:41
I'm trying @pyrtsa approach, it sort of works but I need to manually edit every Dependabot PR to make sure both Package.swift and .xcodeproj files point to the same version, every time.

I found this ruby gem that can read and write .xcodeproj bundles, this could help Dependabot deal with the Xcode projects.

Gem: https://github.com/CocoaPods/Xcodeproj
Specific class that deals with SwiftPM dependencies and versions: https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/XCRemoteSwiftPackageReference

Hopefully this helps the implementation to cater for a wider user base!

**Comment by deivid-rodriguez** [comment] 2023-08-01 14:32
@timdawborn I ended up being able to reproduce your issue and has been fixed at https://github.com/dependabot/dependabot-core/pull/7674. Try again and hopefully should just work now.

For everyone else, we've just released [Swift support for Version & Security Updates](https://github.blog/changelog/2023-08-01-swift-support-for-dependabot-updates/), so let me close this ticket since this has been implemented 🎉.

I'll make sure to open separate feature requests for the things that we left out of this release, and please do report any issues you find.

Cheers!

**Closed by deivid-rodriguez** 2023-08-01 14:32 UTC
Labels: T: new-ecosystem

**Comment by timdawborn** [comment] 2023-08-02 06:54
@deivid-rodriguez Thanks! It's now working like a charm for us 🎉 

<img width="974" alt="Screenshot 2023-08-02 at 16 53 07" src="https://github.com/dependabot/dependabot-core/assets/812019/01fdeaa8-1159-405d-a0b8-b6c2b9620e92">

**Comment by deivid-rodriguez** [comment] 2023-08-02 07:06
Glad to hear that! 🎉

**Comment by caiofbpa** [comment] 2023-08-02 07:38
@deivid-rodriguez could you link here the additional issues you created for things left out of this release? Especially the support for using `.xcodeproj` project bundles are source for version definitions instead of `Package.swift`?

**Comment by macfanatic** [comment] 2023-08-18 13:53
Is there any special configuration needed to use updates to internal private packages published on Github via SPM?

We have several libraries that depend upon other smaller internal libraries, just as private repos in our organization.  These are specified via HTTPS URLs in our `Package.swift` file.

Eagerly awaiting support for the app project file itself as well in #7694 :)

**Comment by deivid-rodriguez** [comment] 2023-08-18 13:55
I guess configure [a git registry](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#git).
