### ISSUE TITLE
Dependabot doesn't raise PR for updates where complex image tag is used

### ISSUE THREAD

**Issue by lcooper01** [dependabot/dependabot-core#5728] opened 2022-09-14 13:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

### Updated dependency

```eclipse-temurin``` from ```11.0.14.1_1-jre-alpine``` to  ```11.0.16.1_1-jre-alpine```

### What you expected to see, versus what you actually saw

I expected to see dependabot create a PR for the newer version of 11.0

It seems that the complex tag stops this from happening as I tested using a centos image with a simple tag that followed semantic versioning

I have also tried to use the sha256 digest for eclipse and centos to see if dependabot would pick up the dependency update but sadly this didn't work for either image.

### Images of the diff or a link to the PR, issue, or logs

```
  proxy | time="2022-09-14T13:50:36Z" level=info msg="proxy starting" commit=b031647dc5f52d8120800fc16337727989cb9be0
  proxy | 2022/09/14 13:50:36 Listening (:1080)
updater | 2022-09-14T13:50:36.757878927 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-09-14T13:50:36.777553574 [458863050:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-09-14T13:50:38Z" level=info msg="guest starting" commit=d97478b458e198f9b9a6cb546d902ee2e6651286
updater | time="2022-09-14T13:50:38Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=458863050 updater_timeout=45m0s updater_version=8b7894be54c6b357e90d1be860cf1bbfbe3d4ea5
updater | I, [2022-09-14T13:50:39.833934 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_458863050> Starting job processing
  proxy | 2022/09/14 13:50:42 [002] GET https://api.github.com:443/repos/elcoops99/test-dependabot
  proxy | 2022/09/14 13:50:42 [002] * authenticating github api request
  proxy | 2022/09/14 13:50:42 [002] 200 https://api.github.com:443/repos/elcoops99/test-dependabot
  proxy | 2022/09/14 13:50:42 [004] GET https://api.github.com:443/repos/elcoops99/test-dependabot/git/refs/heads/main
  proxy | 2022/09/14 13:50:42 [004] * authenticating github api request
  proxy | 2022/09/14 13:50:42 [004] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/git/refs/heads/main
  proxy | 2022/09/14 13:50:42 [006] GET https://api.github.com:443/repos/elcoops99/test-dependabot/contents/?ref=9829ea254d95242bfe1ebafa8197107311336c0b
  proxy | 2022/09/14 13:50:42 [006] * authenticating github api request
  proxy | 2022/09/14 13:50:42 [006] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/contents/?ref=9829ea254d95242bfe1ebafa8197107311336c0b
  proxy | 2022/09/14 13:50:42 [008] GET https://api.github.com:443/repos/elcoops99/test-dependabot/contents/Dockerfile?ref=9829ea254d95242bfe1ebafa8197107311336c0b
  proxy | 2022/09/14 13:50:42 [008] * authenticating github api request
  proxy | 2022/09/14 13:50:42 [008] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/contents/Dockerfile?ref=9829ea254d95242bfe1ebafa8197107311336c0b
updater | INFO <job_458863050> Finished job processing
updater | time="2022-09-14T13:50:42Z" level=info msg="task complete" container_id=job-458863050-file-fetcher exit_code=0 job_id=458863050 step=fetcher
updater | I, [2022-09-14T13:50:43.851226 #6]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_458863050> Starting job processing
updater | INFO <job_458863050> Starting update job for elcoops99/test-dependabot
updater | INFO <job_458863050> Checking if eclipse-temurin 11.0.14.1_1-jre-alpine needs updating
updater | INFO <job_458863050> Latest version is 11.0.14.1_1-jre-alpine
updater | INFO <job_458863050> No update needed for eclipse-temurin 11.0.14.1_1-jre-alpine
updater | INFO <job_458863050> Finished job processing
updater | time="2022-09-14T13:50:45Z" level=info msg="task complete" container_id=job-458863050-updater exit_code=0 job_id=458863050 step=updater
```

### Smallest manifest that reproduces the issue

Has huge log and doesn't do any comparions
```
FROM eclipse-temurin@sha256:8b432d7aed1ae6d87a568842a04e4a7bfc11b880ce7b1a98cb9a252d864ead93 as java-11
```

Small log but fails to find any updates
```
FROM eclipse-temurin:11.0.14.1_1-jre-alpine as java11
```

Testing centos simple tagged image (works perfectly and creates pr for version 8.x.x)
```
FROM centos:7.6.1810 as centos
```

Testing centos using sha for centos:7.6.1810 (using sha doesn't work)
```
FROM centos@sha256:747b2de199b6197a26eb1a24d69740d25483995842b2d2f75824095e9d1d19eb as centos
```

**Comment by jeffwidman** [comment] 2022-09-14 21:09
Pretty sure this is a dupe of https://github.com/dependabot/dependabot-core/issues/5728, so closing.

Pretty sure that one is also a dupe of a prior report, but I haven't taken the time to poke through the issue backlog yet as there's multiple related but not quite identical reports.

If for some reason you think it's not a dupe, comment and we can re-open.

**Comment by lcooper01** [comment] 2022-09-15 08:50
@jeffwidman #5708 is a very similar issue. The difference is for mine there's not multiple versions in the tag, but rather a version with an extension of the alpine name.

**Comment by deivid-rodriguez** [comment] 2022-09-15 11:02
I confirmed both issues:

```
FROM eclipse-temurin@sha256:8b432d7aed1ae6d87a568842a04e4a7bfc11b880ce7b1a98cb9a252d864ead93 as java-11
```

takes a really long time and does not do anything. Not sure why.

```
FROM eclipse-temurin:11.0.14.1_1-jre-alpine as java11
```

does not find any updates, because we currently don't accept `_` in Docker version tags.

**Comment by jeffwidman** [comment] 2022-09-15 20:08
Related:
* https://github.com/dependabot/dependabot-core/pull/4801

**Comment by deivid-rodriguez** [comment] 2022-09-15 20:17
Oh shit, I was just about to open a PR for the underscores! Will have a look at that PR.

**Closed** 2022-09-17 07:49 UTC
Labels: T: bug 🐞, L: docker

**Comment by lcooper01** [comment] 2022-09-20 08:29
@jeffwidman @deivid-rodriguez 

Can you confirm the issue is resolved please ?  I've retested and it seems to be still saying no update needed.

```
  proxy | time="2022-09-20T08:24:34Z" level=info msg="proxy starting" commit=b031647dc5f52d8120800fc16337727989cb9be0
  proxy | 2022/09/20 08:24:34 Listening (:1080)
updater | 2022-09-20T08:24:34.766737554 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-09-20T08:24:34.838657993 [465429355:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-09-20T08:24:39Z" level=info msg="guest starting" commit=d97478b458e198f9b9a6cb546d902ee2e6651286
updater | time="2022-09-20T08:24:39Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=465429355 updater_timeout=45m0s updater_version=8b7894be54c6b357e90d1be860cf1bbfbe3d4ea5
updater | I, [2022-09-20T08:24:44.724562 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_465429355> Starting job processing
  proxy | 2022/09/20 08:24:54 [002] GET https://api.github.com:443/repos/elcoops99/test-dependabot
  proxy | 2022/09/20 08:24:54 [002] * authenticating github api request
  proxy | 2022/09/20 08:24:54 [002] 200 https://api.github.com:443/repos/elcoops99/test-dependabot
  proxy | 2022/09/20 08:24:54 [004] GET https://api.github.com:443/repos/elcoops99/test-dependabot/git/refs/heads/main
  proxy | 2022/09/20 08:24:54 [004] * authenticating github api request
  proxy | 2022/09/20 08:24:54 [004] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/git/refs/heads/main
  proxy | 2022/09/20 08:24:54 [006] GET https://api.github.com:443/repos/elcoops99/test-dependabot/contents/?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
  proxy | 2022/09/20 08:24:54 [006] * authenticating github api request
  proxy | 2022/09/20 08:24:54 [006] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/contents/?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
  proxy | 2022/09/20 08:24:54 [008] GET https://api.github.com:443/repos/elcoops99/test-dependabot/contents/Dockerfile?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
  proxy | 2022/09/20 08:24:54 [008] * authenticating github api request
  proxy | 2022/09/20 08:24:54 [008] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/contents/Dockerfile?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
updater | INFO <job_465429355> Finished job processing
updater | time="2022-09-20T08:24:55Z" level=info msg="task complete" container_id=job-465429355-file-fetcher exit_code=0 job_id=465429355 step=fetcher
updater | I, [2022-09-20T08:24:59.791714 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_465429355> Starting job processing
updater | INFO <job_465429355> Starting update job for elcoops99/test-dependabot
updater | INFO <job_465429355> Checking if eclipse-temurin 11.0.14.1_1-jre-alpine needs updating
updater | INFO <job_465429355> Latest version is 11.0.14.1_1-jre-alpine
updater | INFO <job_465429355> No update needed for eclipse-temurin 11.0.14.1_1-jre-alpine
updater | INFO <job_465429355> Finished job processing
updater | time="2022-09-20T08:25:06Z" level=info msg="task complete" container_id=job-465429355-updater exit_code=0 job_id=465429355 step=updater
```

**Comment by lcooper01** [comment] 2022-09-20 15:01
@jeffwidman @deivid-rodriguez 

I've ran the check for updates this afternoon and its now ran successfully and found and update.

However my expectation was to find updates for version 11 and get the latest.

What I see is it finding version 17.x.

This is probably normal behaviour for other versioned packages but 11 / 17 relates to the Java version so we would never want a bump from 11 to 17 since we maintain both Java versions separately.

Should I raise another issue for this or is this expected behaviour and nothing can be done about it ?


```
  proxy | time="2022-09-20T14:57:35Z" level=info msg="proxy starting" commit=b031647dc5f52d8120800fc16337727989cb9be0
  proxy | 2022/09/20 14:57:35 Listening (:1080)
updater | 2022-09-20T14:57:35.534235973 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-09-20T14:57:35.571741869 [465669678:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-09-20T14:57:37Z" level=info msg="guest starting" commit=d97478b458e198f9b9a6cb546d902ee2e6651286
updater | time="2022-09-20T14:57:37Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=465669678 updater_timeout=45m0s updater_version=fa633193af60954e1f92662c83038f62d29365a2
updater | I, [2022-09-20T14:57:38.775810 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_465669678> Starting job processing
  proxy | 2022/09/20 14:57:40 [002] GET https://api.github.com:443/repos/elcoops99/test-dependabot
  proxy | 2022/09/20 14:57:40 [002] * authenticating github api request
  proxy | 2022/09/20 14:57:41 [002] 200 https://api.github.com:443/repos/elcoops99/test-dependabot
  proxy | 2022/09/20 14:57:41 [004] GET https://api.github.com:443/repos/elcoops99/test-dependabot/git/refs/heads/main
  proxy | 2022/09/20 14:57:41 [004] * authenticating github api request
  proxy | 2022/09/20 14:57:41 [004] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/git/refs/heads/main
  proxy | 2022/09/20 14:57:41 [006] GET https://api.github.com:443/repos/elcoops99/test-dependabot/contents/?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
  proxy | 2022/09/20 14:57:41 [006] * authenticating github api request
  proxy | 2022/09/20 14:57:41 [006] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/contents/?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
  proxy | 2022/09/20 14:57:41 [008] GET https://api.github.com:443/repos/elcoops99/test-dependabot/contents/Dockerfile?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
  proxy | 2022/09/20 14:57:41 [008] * authenticating github api request
  proxy | 2022/09/20 14:57:41 [008] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/contents/Dockerfile?ref=31865055254d7d9f022e42c1e7c0718e1a699f4c
updater | INFO <job_465669678> Finished job processing
updater | time="2022-09-20T14:57:41Z" level=info msg="task complete" container_id=job-465669678-file-fetcher exit_code=0 job_id=465669678 step=fetcher
updater | I, [2022-09-20T14:57:42.474121 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_465669678> Starting job processing
updater | INFO <job_465669678> Starting update job for elcoops99/test-dependabot
updater | INFO <job_465669678> Checking if eclipse-temurin 11.0.14.1_1-jre-alpine needs updating
  proxy | 2022/09/20 14:57:44 [012] GET https://registry.hub.docker.com:443/v2/library/eclipse-temurin/tags/list
  proxy | 2022/09/20 14:57:44 [012] 401 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/tags/list
  proxy | 2022/09/20 14:57:44 [014] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:44 [014] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:44 [016] GET https://registry.hub.docker.com:443/v2/library/eclipse-temurin/tags/list
  proxy | 2022/09/20 14:57:45 [016] 200 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/tags/list
  proxy | 2022/09/20 14:57:45 [018] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/latest
  proxy | 2022/09/20 14:57:45 [018] 401 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/latest
  proxy | 2022/09/20 14:57:45 [020] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [020] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [022] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/latest
  proxy | 2022/09/20 14:57:45 [022] 200 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/latest
  proxy | 2022/09/20 14:57:45 [024] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/18
  proxy | 2022/09/20 14:57:45 [024] 401 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/18
  proxy | 2022/09/20 14:57:45 [026] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [026] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [028] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/18
  proxy | 2022/09/20 14:57:45 [028] 200 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/18
updater | INFO <job_465669678> Latest version is 17.0.4_8-jre-alpine
  proxy | 2022/09/20 14:57:45 [030] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/11.0.14.1_1-jre-alpine
  proxy | 2022/09/20 14:57:45 [030] 401 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/11.0.14.1_1-jre-alpine
  proxy | 2022/09/20 14:57:45 [032] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [032] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [034] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/11.0.14.1_1-jre-alpine
  proxy | 2022/09/20 14:57:45 [034] 200 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/11.0.14.1_1-jre-alpine
  proxy | 2022/09/20 14:57:45 [036] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/17.0.4_8-jre-alpine
  proxy | 2022/09/20 14:57:45 [036] 401 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/17.0.4_8-jre-alpine
  proxy | 2022/09/20 14:57:45 [038] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [038] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Feclipse-temurin%3Apull
  proxy | 2022/09/20 14:57:45 [040] HEAD https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/17.0.4_8-jre-alpine
  proxy | 2022/09/20 14:57:45 [040] 200 https://registry.hub.docker.com:443/v2/library/eclipse-temurin/manifests/17.0.4_8-jre-alpine
updater | INFO <job_465669678> Requirements to unlock own
updater | INFO <job_465669678> Requirements update strategy 
updater | INFO <job_465669678> Updating eclipse-temurin from 11.0.14.1_1-jre-alpine to 17.0.4_8-jre-alpine
  proxy | 2022/09/20 14:57:45 [042] GET https://api.github.com:443/repos/elcoops99/test-dependabot/commits?per_page=100
  proxy | 2022/09/20 14:57:45 [042] * authenticating github api request
  proxy | 2022/09/20 14:57:46 [042] 200 https://api.github.com:443/repos/elcoops99/test-dependabot/commits?per_page=100
updater | INFO <job_465669678> Submitting eclipse-temurin pull request for creation
updater | INFO <job_465669678> Finished job processing
updater | INFO Results:
updater | +----------------------------------------------------------------------------------+
updater | |                       Changes to Dependabot Pull Requests                        |
updater | +---------+------------------------------------------------------------------------+
updater | | created | eclipse-temurin ( from 11.0.14.1_1-jre-alpine to 17.0.4_8-jre-alpine ) |
updater | +---------+------------------------------------------------------------------------+
updater | time="2022-09-20T14:57:46Z" level=info msg="task complete" container_id=job-465669678-updater exit_code=0 job_id=465669678 step=updater
```

**Comment by lcooper01** [comment] 2022-09-20 15:25
I've added the required ignore config to dependabot.yaml and still the same

I'll raise a new issue
