### ISSUE TITLE
Dependabot updating SHA to short semver

### ISSUE THREAD

**Issue by wolf99** [dependabot/dependabot-core#4781] opened 2022-03-01 22:18 UTC
**Package ecosystem**
GitHub actions, actions/checkout
**Package manager version**
actions/checkout@v3

**dependabot.yml content**
https://github.com/exercism/probby/blob/main/.github/dependabot.yml

**What you expected to see, versus what you actually saw**
Expected to see `actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f` change to `actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846`

Instead it changed to `actions/checkout@v3`

**Images of the diff or a link to the PR, issue or logs**
See diff: https://github.com/exercism/probby/pull/15/files

**🕹 Bonus points: Smallest manifest that reproduces the issue**
How's 8 LoC ? 
Same content as the above link 😉 

```yml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

**Comment by SaschaMann** [comment] 2022-03-03 13:54
I think this is caused by `- uses: actions/checkout@v2` in L15 of `.github/workflows/general-ci.yml` using the tag-based versioning. While I can't find them right now (sorry!), I've seen similar behaviour in other PRs where some affected workflows used tags and others used SHAs for the same action that is being updated by Dependabot.

**Comment by dfarrell07** [comment] 2022-03-23 15:39
Does Dependabot support SHA-based version bumps at all (I wish it did)? From the original press release, I see:

> Dependabot creates pull requests that update the action to the latest released tag (e.g., v2), regardless of if you’re currently on a release tag, a pre-release tag, or a specific hash.

https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/

**Comment by deivid-rodriguez** [comment] 2023-02-10 16:19
I think this issue is fixed now, so I'm closing this, but feel free to reopen if I'm mistaken and this is still happening!

**Closed by deivid-rodriguez** 2023-02-10 16:19 UTC
Labels: T: bug 🐞, L: github:actions
