### ISSUE TITLE
Provide an official JSON Schema for the config file

### ISSUE THREAD

**Issue by jonasbb** [dependabot/dependabot-core#2113] opened 2019-08-26 21:17 UTC
It would be great if dependabot could release an official JSON Schema for the config file format.
Ideally this would also be added to [schemastore](https://github.com/schemastore/schemastore/) such that editors can pick up the new file automatically.
Publishing the schema allows users to benefit from auto completion in their editors, for example with [VS Code](https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas).

It seems that the config validator on the dependabot website already uses a JSON schema, so it might be enough to simply publish that one.

**Comment by thepwagner** [comment] 2021-04-19 15:46
This is a duplicate of https://github.com/dependabot/dependabot-core/issues/1927

**Closed by thepwagner** 2021-04-19 15:46 UTC
Labels: F: version-updates ⬆️, T: feature-request
