### ISSUE TITLE
Grouping of updates and binary searching upon failure to build

### ISSUE THREAD

**Issue by sampsakuronen** [dependabot/dependabot-core#1875] opened 2020-05-21 09:12 UTC
I failed to find this exact feature request/proposal. There are multiple requests for a feature where you can group updates based on some attribute (e.g. sharing a part of the package name).

My suggestion is to have a more universal approach to the underlying need behind the grouping. We rely heavily on tests and merge after a successful test run. My pet peeves:

- Having spammy levels of pull requests (easily 50 each week)
- Building each of those (build & test times in our project are around 5 min)
- Merge spam

**Proposal:** 

1. Group all updates to a batch. 
2. Try to build and if the build fails, split the updates to two batches. 
3. Continue until the failing update is found while accepting the passing ones. 

The basic idea is to use binary search here.

**Comment by jeffwidman** [comment] 2022-11-24 11:34
Closing for now as a duplicate of https://github.com/dependabot/dependabot-core/issues/1190. I realize this suggests a specific implementation, so I'll cross-link it from that issue as well.

**Closed by jeffwidman** 2022-11-24 11:34 UTC
Labels: T: feature-request
