### ISSUE TITLE
[berry] ENOENT: no such file or directory when repacking branch build

### ISSUE THREAD

**Issue by lizthegrey** [dependabot/dependabot-core#6003] opened 2022-10-31 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn berry

### Package manager version

4.0.0-rc.27

### Language version

16.18

### Manifest location and content before the Dependabot update

https://github.com/eve-val/eve-roster/blob/main/package.json

### dependabot.yml content

https://github.com/eve-val/eve-roster/blob/main/.github/dependabot.yml

### Updated dependency

any dependency that needs update, PLUS `webpack-hot-middleware` also in file (version staying same: `webpack-contrib/webpack-hot-middleware#webpack5`)

### What you expected to see, versus what you actually saw

Unpacking from git and rebundling should proceed smoothly.

### Native package manager behavior

Unpacking fails with ENOENT error

### Images of the diff or a link to the PR, issue, or logs

Excerpts from https://github.com/eve-val/eve-roster/network/updates/496008292

```
  proxy | 2022/10/31 16:49:25 [246] GET https://github.com:443/webpack-contrib/webpack-hot-middleware.git/info/refs?service=git-upload-pack
  proxy | 2022/10/31 16:49:25 [246] * authenticating git server request (host: github.com)
  proxy | 2022/10/31 16:49:25 [246] 200 https://github.com:443/webpack-contrib/webpack-hot-middleware.git/info/refs?service=git-upload-pack
  proxy | 2022/10/31 16:49:25 [248] POST https://github.com:443/webpack-contrib/webpack-hot-middleware.git/git-upload-pack
  proxy | 2022/10/31 16:49:25 [248] * authenticating git server request (host: github.com)
  proxy | 2022/10/31 16:49:25 [248] 200 https://github.com:443/webpack-contrib/webpack-hot-middleware.git/git-upload-pack
updater | I, [2022-10-31T16:49:36.419067 #7]  INFO -- sentry: ** [Raven] Sending event b67e88ed0d204e4e916d2dd1974f57b7 to Sentry
  proxy | 2022/10/31 16:49:36 [250] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/10/31 16:49:36 [250] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_496008292> Error processing @sentry/tracing (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_496008292> ➤ YN0000: ┌ Resolution step
updater | <job_496008292> ➤ YN0002: │ @types/css-minimizer-webpack-plugin@npm:3.2.1 doesn't provide webpack (pf9118), requested by css-minimizer-webpack-plugin
updater | <job_496008292> ➤ YN0002: │ @types/mini-css-extract-plugin@npm:2.5.1 doesn't provide webpack (p375d7), requested by mini-css-extract-plugin
updater | <job_496008292> ➤ YN0002: │ @types/webpack-dev-middleware@npm:5.3.0 doesn't provide webpack (p6c425), requested by webpack-dev-middleware
updater | <job_496008292> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
updater | <job_496008292> ➤ YN0000: └ Completed in 2s 409ms
updater | <job_496008292> ➤ YN0000: ┌ Fetch step
updater | <job_496008292> ➤ YN0013: │ @ampproject/remapping@npm:2.2.0 can't be found in the cache and will be fetched from the remote registry
[...]
updater | <job_496008292> ➤ YN0013: │ zenscroll@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
updater | <job_496008292> ➤ YN0013: │ webpack-hot-middleware@https://github.com/webpack-contrib/webpack-hot-middleware.git#commit=2cf576f86b7b9e18ee10bfd954fffde4e7e17a22 can't be found in the cache and will be fetched from the remote repository
updater | <job_496008292> ➤ YN0001: │ Error: webpack-hot-middleware@https://github.com/webpack-contrib/webpack-hot-middleware.git#commit=2cf576f86b7b9e18ee10bfd954fffde4e7e17a22: ENOENT: no such file or directory, rename '/tmp/xfs-b8ab09a2/webpack-hot-middleware-2.25.0.tgz' -> '/tmp/xfs-b8ab09a2/package.tgz'
updater | <job_496008292> ➤ YN0000: └ Completed in 3m 34s
updater | <job_496008292> ➤ YN0000: Failed with errors in 3m 36s
updater | ERROR <job_496008292> /home/dependabot/common/lib/dependabot/shared_helpers.rb:314:in `run_shell_command'
```

```
  proxy | 2022/10/31 17:20:18 [228] GET https://github.com:443/webpack-contrib/webpack-hot-middleware.git/info/refs?service=git-upload-pack
  proxy | 2022/10/31 17:20:18 [228] * authenticating git server request (host: github.com)
  proxy | 2022/10/31 17:20:18 [228] 200 https://github.com:443/webpack-contrib/webpack-hot-middleware.git/info/refs?service=git-upload-pack
  proxy | 2022/10/31 17:20:18 [230] POST https://github.com:443/webpack-contrib/webpack-hot-middleware.git/git-upload-pack
  proxy | 2022/10/31 17:20:18 [230] * authenticating git server request (host: github.com)
  proxy | 2022/10/31 17:20:18 [230] 200 https://github.com:443/webpack-contrib/webpack-hot-middleware.git/git-upload-pack
updater | I, [2022-10-31T17:20:25.230696 #7]  INFO -- sentry: ** [Raven] Sending event 188ab8f7eed148a88c3d23d127c396e7 to Sentry
  proxy | 2022/10/31 17:20:25 [232] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/10/31 17:20:25 [232] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_496008292> Error processing typescript (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_496008292> ➤ YN0000: ┌ Resolution step
updater | <job_496008292> ➤ YN0002: │ @types/css-minimizer-webpack-plugin@npm:3.2.1 doesn't provide webpack (pf9118), requested by css-minimizer-webpack-plugin
updater | <job_496008292> ➤ YN0002: │ @types/mini-css-extract-plugin@npm:2.5.1 doesn't provide webpack (p375d7), requested by mini-css-extract-plugin
updater | <job_496008292> ➤ YN0002: │ @types/webpack-dev-middleware@npm:5.3.0 doesn't provide webpack (p6c425), requested by webpack-dev-middleware
updater | <job_496008292> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
updater | <job_496008292> ➤ YN0000: └ Completed in 4s 385ms
updater | <job_496008292> ➤ YN0000: ┌ Fetch step
updater | <job_496008292> ➤ YN0013: │ typescript@npm:4.8.4 can't be found in the cache and will be fetched from the remote registry
updater | <job_496008292> ➤ YN0013: │ typescript@patch:typescript@npm%3A4.8.4#optional!builtin<compat/typescript>::version=4.8.4&hash=0102e9 can't be found in the cache and will be fetched from the disk
updater | <job_496008292> ➤ YN0013: │ webpack-hot-middleware@https://github.com/webpack-contrib/webpack-hot-middleware.git#commit=2cf576f86b7b9e18ee10bfd954fffde4e7e17a22 can't be found in the cache and will be fetched from GitHub
updater | <job_496008292> ➤ YN0013: │ typescript@npm:4.8.4 can't be found in the cache and will be fetched from the remote registry
updater | <job_496008292> ➤ YN0013: │ webpack-hot-middleware@https://github.com/webpack-contrib/webpack-hot-middleware.git#commit=2cf576f86b7b9e18ee10bfd954fffde4e7e17a22 can't be found in the cache and will be fetched from the remote repository
updater | <job_496008292> ➤ YN0001: │ Error: webpack-hot-middleware@https://github.com/webpack-contrib/webpack-hot-middleware.git#commit=2cf576f86b7b9e18ee10bfd954fffde4e7e17a22: ENOENT: no such file or directory, rename '/tmp/xfs-887e85cc/webpack-hot-middleware-2.25.0.tgz' -> '/tmp/xfs-887e85cc/package.tgz'
updater | <job_496008292> ➤ YN0000: └ Completed in 35s 971ms
updater | <job_496008292> ➤ YN0000: Failed with errors in 40s 361ms
```

### Smallest manifest that reproduces the issue

Something like this should do the trick, basically anything with `webpack-hot-middleware#webpack5`, plus something that needs an update (e.g. typescript from `^4.8.2` to `^4.8.4`).
```
  "devDependencies": {
    "typescript": "^4.8.2",
    "webpack-hot-middleware": "webpack-contrib/webpack-hot-middleware#webpack5"
  }
```

**Comment by lizthegrey** [comment] 2022-10-31 18:13
Workaround: checking in the zip file in .yarn/cache works and prevents the need to re-bundle on the fly.

https://github.com/eve-val/eve-roster/pull/1411 did fix the next dependabot run (at a cost, namely that my downstream heroku buildpack then sees at least one file in cache and then does not merge with its own cache)

**Comment by pavera** [comment] 2022-10-31 19:24
@lizthegrey Thanks for the report! I'm setting up to test. I wonder if it might be because we removed `--mode=update-lockfile` in an attempt to support zero-install repos, but for users without cache checked in, this might be causing issues. At any rate, I'll be investigating and will let you know.

**Comment by anero** [comment] 2023-02-10 18:50
@pavera We're seeing what appears to be the same issue, except that for us dependabot ends up timing out:

```
updater | ERROR <job_598617214> Error processing postcss-import (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_598617214> ➤ YN0000: ┌ Resolution step
updater | <job_598617214> ➤ YN0002: │ @geostarters/mapbox-gl-draw-rectangle-assisted-mode@npm:3.0.4 doesn't provide @babel/core (pf1d8d), requested by @babel/plugin-transform-modules-commonjs
updater | <job_598617214> ➤ YN0002: │ agra@workspace:. doesn't provide @vue/compiler-sfc (p57825), requested by vue-loader
updater | <job_598617214> ➤ YN0002: │ agra@workspace:. doesn't provide mapbox-gl (p7e11e), requested by @mapbox/mapbox-gl-language
updater | <job_598617214> ➤ YN0002: │ agra@workspace:. doesn't provide mapbox-gl (p6ed39), requested by vue-mapbox
updater | <job_598617214> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
updater | <job_598617214> ➤ YN0000: └ Completed in 0s 564ms
updater | <job_598617214> ➤ YN0000: ┌ Fetch step
updater | <job_598617214> ➤ YN0013: │ postcss-import@npm:15.1.0 can't be found in the cache and will be fetched from the remote registry
updater | <job_598617214> ➤ YN0013: │ vue-mapbox@https://github.com/soal/vue-mapbox.git#commit=e0edd17bde5fe8d1db7f44029e0e3399e2bf35ea can't be found in the cache and will be fetched from GitHub
updater | <job_598617214> ➤ YN0013: │ vue-mapbox@https://github.com/soal/vue-mapbox.git#commit=e0edd17bde5fe8d1db7f44029e0e3399e2bf35ea can't be found in the cache and will be fetched from the remote repository
updater | <job_598617214> ➤ YN0001: │ Error: vue-mapbox@https://github.com/soal/vue-mapbox.git#commit=e0edd17bde5fe8d1db7f44029e0e3399e2bf35ea: ENOENT: no such file or directory, rename '/tmp/xfs-b0fe6768/vue-mapbox-0.5.0.tgz' -> '/tmp/xfs-b0fe6768/package.tgz'
updater | <job_598617214> ➤ YN0000: └ Completed in 30s 692ms
updater | <job_598617214> ➤ YN0000: Failed with errors in 31s 261ms
updater | ERROR <job_598617214> /home/dependabot/common/lib/dependabot/shared_helpers.rb:316:in `run_shell_command'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb:94:in `run_yarn_command'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:153:in `run_yarn_berry_top_level_updater'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:110:in `block (2 levels) in run_yarn_updater'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `chdir'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `block in run_yarn_updater'
updater | ERROR <job_598617214> /home/dependabot/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:106:in `run_yarn_updater'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:79:in `run_current_yarn_update'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:60:in `block in updated_yarn_lock'
updater | ERROR <job_598617214> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
updater | ERROR <job_598617214> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
updater | ERROR <job_598617214> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:56:in `updated_yarn_lock'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:32:in `updated_yarn_lock_content'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:218:in `updated_yarn_lock_content'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:162:in `yarn_lock_changed?'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:186:in `block in updated_lockfiles'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:185:in `each'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:185:in `updated_lockfiles'
updater | ERROR <job_598617214> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:40:in `updated_dependency_files'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:747:in `generate_dependency_files_for'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:311:in `check_and_create_pull_request'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_598617214> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
```

The `vue-mapbox` dependency is declared as follows in `yarn.lock`:
```
agra@workspace:.":
  version: 0.0.0-use.local
  resolution: "agra@workspace:."
  dependencies:
    ....
    vue-mapbox: "soal/vue-mapbox#development"
    ....

....

"vue-mapbox@soal/vue-mapbox#development":
  version: 0.5.0
  resolution: "vue-mapbox@https://github.com/soal/vue-mapbox.git#commit=e0edd17bde5fe8d1db7f44029e0e3399e2bf35ea"
  dependencies:
    map-promisified: latest
  peerDependencies:
    mapbox-gl: ^1.12.0
    vue: ^2.6.7
  checksum: dfae7debd1bb247e126da8ef542dc97892aa3f6949adfc24007f55f96bf36541c061e09942179cbe364759636b27124eb00c3f299726d473f8527c2fbb238071
  languageName: node
  linkType: hard
```

**Comment by jeffwidman** [comment] 2023-02-10 19:45
@anero do you have a public repo where this can be reproduced by others? Generally folks take their private repos and strip out the private bits.

TBH, we're a little buried right now, but the great thing is this is all open source so if it's a blocker the fastest thing you can do is pop it open in docker and run our `dry-run.rb` script against it using [these instructions](https://github.com/dependabot/dependabot-core#running-with-docker) together with some `debugger` / `puts` statements to identify what's happening. Since it's likely that the problem is related to the flags we pass to `yarn`, this may also be useful: https://github.com/dependabot/dependabot-core#debugging-native-helpers

**Comment by deivid-rodriguez** [comment] 2023-02-13 21:03
Just tried you reproduction case and #6516 seems to fix it! 💃

**Closed** 2023-02-14 13:05 UTC
Labels: T: bug 🐞, L: javascript:yarn

**Comment by deivid-rodriguez** [comment] 2023-02-14 16:08
The fix is live now, let me know if it worked as expected!
