### ISSUE TITLE
Option to delay pull request creation after a new release

### ISSUE THREAD

**Issue by jwgmeligmeyling** [dependabot/dependabot-core#4338] opened 2021-10-21 22:41 UTC
I've seen delay features only requested with regard to auto-merge of PR's, not the creation of PR's itself.

In the Maven ecosystem, it is quite common that it takes up to a day for new releases to be propagated through common public repositories.

Dependabot seems to get faster and faster with creating new pull requests right after dependencies have released a new version. For my projects this causes a lot of issues because 80% of the pull requests Dependabot creates get failing CI builds. This then requires manual action in triggering all the CI builds for all pull requests again, greatly increasing the time it takes to process all dependency updates. It also eats through CI minutes.

It would be nice to be able to configure a delay after which a PR can be made for a new dependency release. Alternatively it would be nice if dependabot just withdraws PRs with failing builds.

**Comment by chasefinch** [comment] 2021-11-15 16:31
+1 for the delay, not for the auto-withdrawal of PRs.

**Comment by PatMyron** [comment] 2022-01-10 00:32
previous discussions:
https://github.com/dependabot/dependabot-core/issues/2208
https://github.com/dependabot/dependabot-core/issues/2243

**Comment by mwaddell** [comment] 2022-01-29 17:58
Could this be combined with #4545 and configured as an "initial snooze"?

**Comment by mwaddell** [comment] 2022-01-29 22:06
also related to #2151

**Comment by nipunn1313** [comment] 2022-02-01 17:00
I’d like a feature like this to delay picking up new dependencies until they’ve been out for a few days, in order to avoid being the guinea pig.

Renovatebot has stabilityDays for example
https://docs.renovatebot.com/configuration-options/#stabilitydays

**Comment by jeffwidman** [comment] 2022-08-24 20:36
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/3651

This is an interesting idea for sure, so let's continue the discussion over there.

**Closed by jeffwidman** 2022-08-24 20:36 UTC
Labels: T: feature-request
