### ISSUE TITLE
Open an accompanying issue (to the automated PR)

### ISSUE THREAD

**Issue by mykaul** [dependabot/dependabot-core#6832] opened 2023-03-14 15:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It's great that dependabot automatically opens a PR, but it'd be great if it can also have an issue, and link them with 'Fixes #xxxx' or so.

**Comment by jeffwidman** [comment] 2023-03-14 19:37
This is mostly a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2242

I realize the requested behavior here includes opening the PR, but there's enough overlap I'm going to close as a duplicate to keep the product feedback limited to one thread. Do you mind taking a gander at that issue and if it's not capturing your use case leaving a comment on it explaining what you're trying to solve for and why you want both PR and issue, not just one or the other?

**Closed by jeffwidman** 2023-03-14 19:37 UTC
Labels: T: feature-request
