### ISSUE TITLE
Prioritize dependencies based on likelyhood that CI run will succeed

### ISSUE THREAD

**Issue by thomaseizinger** [dependabot/dependabot-core#2114] opened 2019-08-23 11:50 UTC
With the compatiblity score, dependabot already has an idea of how likely it is that a CI run will succeed.

It would be good if this information were used to open those PRs first.
This would result in a smoother dependabot experience because it would take care of the dependencies that don't cause any issues and delay the ones that likely cause problems.

If not enough data is available for a compatiblity score, the version number information could be used. Patch versions are more likely to succeed than minor ones, followed by major version bumps.

We run dependabot on the weekend. This often leaves us with several PRs that need attention on a Monday morning, causing noise on our board and slightly slowing us down.
Together with the proposal I made in https://github.com/dependabot/dependabot-core/issues/2115, dependabot could be even more of a killer application than it already is! :)

I imagine a situation where I can start my work week with a freshly updated project where only one or two dependencies need manual action and the rest was done by dependabot on the weekend :)

**Comment by jeffwidman** [comment] 2023-02-07 20:43
To clarify, this isn't something that would happen here in the open source `dependabot-core`, since it has zero visibility into CI results. 

Only the native GitHub service for Dependabot has access to that data... potentially it could do this, but it gets tricky quickly because even if though it knows what PR's are likely to succeed, different users will want to do different things as a result. Some will want all the PR's opened immediately, just first most likely to last most likely. Others will want them the PR's to slowly trickle in, but the rate will vary... some will want them spread out by a few minutes, others an hour, and some even won't want a new PR until the last one was merged.

While I personally empathize with the problem, I think there are better ways to tackle this, varying from grouped updates that includes multiple deps in a single PR to setting custom schedules such that certain dependencies are checked daily and others checked weekly/monthly to having auto-merge enabled so that as PR's are put up, if they're mergable they can just merge. Part of the problem is that some users are optimizing for minimizing CI minutes, and others are optimizing for minimizing human engineering minutes, and at times those will be in opposition to each other.

**Closed** 2023-02-11 02:01 UTC
Labels: T: feature-request, F: version-updates ⬆️, F: noise, service 💁
