### ISSUE TITLE
Dependabot is not enabled when importing repositories with existing v2 config (and broken "create config file" flow)

### ISSUE THREAD

**Issue by cjolowicz** [dependabot/dependabot-core#2306] opened 2020-07-10 15:29 UTC
After uploading a project with a Dependabot v2 configuration file to GitHub, the Dependabot dashboard at *Insights > Dependency graph > Dependabot (Beta)* shows a message that Dependabot version updates aren't configured yet, and a button **Create config file**. Pressing the button opens a web editor with a sample config file, even though the config file is already present in the repository. Attempting to commit the config file to master from that dialog fails because the file already exists.

This happens only with a fresh test account, like in [this repository](https://github.com/cjolowicz-test/hypermodern-python/). Dependabot appears to work fine when importing from my real account, like in [this repository](https://github.com/cjolowicz/test), which recently upgraded from dependabot-preview.

**Package manage/ecosystem**
n/a
**Manifest contents prior to update**
n/a
**Updated dependency**
n/a
**What you expected to see, versus what you actually saw**
Dependabot starts working immediately when a repository with an existing Dependabot config is imported.

Instead, Dependabot is disabled. The normal flow to create a config file does not and cannot work, but is proposed nonetheless.
**Images of the diff or a link to the PR, issue or logs**

<img width="936" alt="Screenshot 2020-07-10 at 17 06 06" src="https://user-images.githubusercontent.com/653941/87171493-0d955580-c2d3-11ea-9c24-63678093069f.png">

**Comment by feelepxyz** [comment] 2020-07-10 15:42
@cjolowicz thanks for reporting. Did you add the repo by importing from here https://github.com/new/import?

You should be able to work around it by editing the config file but will look into handling this case better.

**Comment by cjolowicz** [comment] 2020-07-10 15:48
Thanks for the reply.

> Did you add the repo by importing from here https://github.com/new/import?

No, sorry for the misuse of terminology. The repository was uploaded to GitHub using git from the command line:

```sh
git remote add origin 'https://github.com/cjolowicz-test/hypermodern-python.git'
git push -u origin master
```

The repository contains a single commit, including the Dependabot config.

This is quite a common use case for me, as I'm developing [a Cookiecutter template for Python projects](https://github.com/cookiecutter-hypermodern-python). Projects generated from the template typically include the Dependabot config in the initial commit.

**Comment by cjolowicz** [comment] 2020-07-10 15:52
> You should be able to work around it by editing the config file 

Sure, I don't mind doing that for my personal projects. Unfortunately, for the users of my template this is not a good flow.

> but will look into handling this case better.

I would love that, thanks!

**Comment by brechin** [comment] 2021-02-11 19:41
Just to add some additional evidence here... I'm having this issue with an organization repo. Monday I had Dependabot PRs waiting. Starting Tuesday, Dependabot appears to think it isn't configured and presents like the Issue describes.

**Comment by davidwessman** [comment] 2021-02-15 06:29
> Just to add some additional evidence here... I'm having this issue with an organization repo. Monday I had Dependabot PRs waiting. Starting Tuesday, Dependabot appears to think it isn't configured and presents like the Issue describes.

Same here, disappeared during the week.

**Comment by feelepxyz** [comment] 2021-02-15 09:50
@brechin @davidwessman could you email the org/repo to github support asking them to forward it to the dependabot team? (assuming the repo's are private?) https://support.github.com/contact

**Comment by davidwessman** [comment] 2021-02-15 10:13
@feelepxyz Done! 🙂 Updating our configuration helped as well.

**Comment by davidwessman** [comment] 2021-02-15 10:20
Updating our configuration did however remove history of all skipped updates and such :/

**Comment by feelepxyz** [comment] 2021-02-15 10:28
@davidwessman ah sorry about that, I'm looking into the cause of this. It seems to be caused by upstream issues with the github api that make dependabot think a repo is no longer accessible.

**Comment by brechin** [comment] 2021-02-15 16:12
@feelepxyz I did contact support through that form. I've also pushed an update to our dependabot config and it is now working again, finding updates as expected.

**Comment by smirnoffs** [comment] 2021-03-04 10:50
I had the same, was fixed by pushing changes into `dependabot.yaml`

**Comment by sfkpmr** [comment] 2021-12-12 17:59
Revived an old project and got stuck on this error as well. Created .github/dependabot.yml multiple times on Github and though git. It was finally recognized after 16 commits.

**Comment by yashash1511** [comment] 2022-04-22 05:27
still having this problem

**Comment by radio-rogal** [comment] 2022-05-22 16:39
I have met this issue after I transfered my own project to my organisation.

**Comment by jeffwidman** [comment] 2022-09-18 06:02
I _think_ we've solved this internally for the known root causes, so I'm going to close this as it's become a catch-all issue... Unfortunately catch-call issues aren't really helpful because while the symptoms may be similar, the root cause may be entirely different.

If you _do_ continue to see this, please file a support ticket and be sure to include a link to your repo.

Normally I'd say file a new issue, but given that the problem will not be in `dependabot-core` library, but rather GitHub internal infra, a support ticket will be the best way for it to get routed to the right engineering team internally.

**Closed by jeffwidman** 2022-09-18 06:02 UTC
Labels: E: api-support, F: github-ui, F: infrastructure, 💁 service
