### ISSUE TITLE
Dependabot updates private npm lib with public npm registry

### ISSUE THREAD

**Issue by nindzyago** [dependabot/dependabot-core#5812] opened 2022-09-29 12:47 UTC
Have a config like:

```
registries:
  my-company-npm:
    type: npm-registry
    url: https://my-company-012345678.d.codeartifact.us-east-1.amazonaws.com/npm/my-company-npm
    token: ${{secrets.NPM_AUTH_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: "/iam-tools"
    registries:
      - my-company-npm
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 7
    allow:
      - dependency-name: '@my-company/*'
```

and it seems like it found updates for my lib:

```
updater | INFO <job_471907512> Checking if @my-company/tenant-config 0.1.100 needs updating
  proxy | 2022/09/29 11:34:18 [136] GET https://my-company-863233358811.d.codeartifact.us-east-1.amazonaws.com:443/npm/my-company-npm/@my-company%2Ftenant-config
...
  proxy | 2022/09/29 11:34:19 [140] 200 https://my-company-863233358811.d.codeartifact.us-east-1.amazonaws.com:443/npm/my-company-npm/@my-company%2Ftenant-config/0.1.197
updater | INFO <job_471907512> Latest version is 0.1.197
```

but then for some reason it tries to update it with default npm registry:

```
  proxy | 2022/09/29 11:34:24 [142] GET https://registry.npmjs.org:443/@my-company%2ftenant-config
  proxy | 2022/09/29 11:34:24 [142] 404 https://registry.npmjs.org:443/@my-company%2ftenant-config
```

I've read a lot of topics and issues, tried different formats for url field in config etc but without success

_Originally posted by @nindzyago in https://github.com/dependabot/dependabot-core/issues/3305#issuecomment-1262223248_

**Comment by jeffwidman** [comment] 2022-10-01 04:42
Is this a duplicate of https://github.com/dependabot/dependabot-core/issues/4669 ?

**Comment by dsemarketer** [comment] 2022-10-27 19:17
Ive got the same behavior with yarn and codeartifact in #5441

**Comment by jeffwidman** [comment] 2023-02-01 01:02
Closing due to lack of user response. I suspect https://github.com/dependabot/dependabot-core/issues/5441#issuecomment-1411052920 is what was missing here. The `replaces-base` may not be required, depends on what specifically you're trying to accomplish, but AFAIK specifying the private registry in the `.npmrc` config is generally recommended. (to be clear: I'm not an npm expert, so would have to check with other team members / read a bunch of source to come up to speed on that ecosystem for finer details on it)

**Closed by jeffwidman** 2023-02-01 01:02 UTC
Labels: L: javascript:npm, F: private-registries 💂‍♂️
