### ISSUE TITLE
Improvement Proposal: Configurable Pull Requests

### ISSUE THREAD

**Issue by ChrisCates** [dependabot/dependabot-core#2672] opened 2020-10-24 21:21 UTC
## Summary

Dependabot provides several pull requests all for the same repository. These diffs in the repository are pretty trivial and generally involve changes only relating to package managers. Pull Requests needs to be configurable from a `dependabot.yml` file.

### Commit Structure

Currently, commits are structured for only a single version change.

```
@dependabot
Bump elliptic from 6.5.0 to 6.5.3 …
00dff40
Bumps [elliptic](https://github.com/indutny/elliptic) from 6.5.0 to 6.5.3.
- [Release notes](https://github.com/indutny/elliptic/releases)
- [Commits](indutny/elliptic@v6.5.0...v6.5.3)
```

Instead, add all changes to a single commit and have it structured something like this.

```
@dependabot - Version Updates

Bump elliptic from 6.5.0 to 6.5.3 … 00dff40
Bumps [elliptic](https://github.com/indutny/elliptic) from 6.5.0 to 6.5.3.
- [Release notes](https://github.com/indutny/elliptic/releases)
- [Commits](indutny/elliptic@v6.5.0...v6.5.3)

Bump lodash from 4.17.15 to 4.17.20 ... 0e4a060
Bumps [lodash](https://github.com/lodash/lodash) from 4.17.15 to 4.17.20.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](lodash/lodash@4.17.15...4.17.20)
```

### Configuration with `dependabot.yml`

For complete and full granular control of how @dependabot configures pull requests. A `dependabot.yml` file seems most ideal.

**Example Configuration:**

```yml
ignore:
  - list
  - packages
  - here

group:
  - list
  - packages
  - here

group:
  - multiple
  - iterations
```

**Example Configuration Group All:**

```yml
group:
  - *
```

**Example Configuration Grouping Based on organization deps:**

```yml
group
  - @org/*
```

#### `ignore`

The ignore key in the `.yml` file ignores all the packages

#### `group`

The group key in the `.yml` file groups all packages into the same pr.

**Both keys can be iterated multiple times in the `.yml` file.**

#### Project Structure

If the project is running on a monorepo. You can have multiple `.yml` files in each respective folder. @dependabot will walk through each folder to find the `.yml` file.

**Comment by fkirc** [comment] 2020-10-29 17:59
I would prefer to list not only individual packages, but to also have the ability to list entire organizations.
For example, organizations like `@types` or `@symfony` could be good candidates for an organization-wide grouping.
Please see https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-718919532 for further details.

Listing individual packages is fine in some cases, but there are also cases where an organization-wide grouping is easier to maintain than individual packages.

**Comment by ChrisCates** [comment] 2020-10-29 19:39
@fkirc, would love to be able to do something like this.

```yml
group:
  - @symfony/*
  - @laravel/*
...
```

I agree with that!

**Comment by Jacob-Morgan** [comment] 2020-10-30 02:21
This might be useful as a real world example, we had similar issues using a custom variant of the [Dependabot script](https://github.com/pharos/dependabot-script/tree/pharos-giltlab) with our self-hosted gitlab server, developers complained about the number of Merge Requests that where being generated. To fix this we extended the dependabot configuration with `group_updates` which has similar traits with  `ignored_updates` and `allowed_updates`, where by you state package names that should be grouped.

```
version: 1
update_configs:
  - package_manager: dotnet:nuget
    directory: /Source
    update_schedule: daily
    ...
    group_updates:
      - match:
          dependency_name:*
```

The result of including all packages into a single, so not only do the developers get bothered less with merge messages, the number of auto-merge fails due to conflicts requiring a rebase has been almost reduced to zero.
![Grouped Packages Updates](https://user-images.githubusercontent.com/1430195/97652402-23699900-1ac3-11eb-9afb-9e8e129a0ccc.png)

**Comment by h-no** [comment] 2020-11-02 08:49
I have a monorepo and even though it is not very large at the moment I expect the sheer volume of PR's will be difficult to handle as the repo grows. I'd love to be able to configure dependabot like this. Great idea!

> @fkirc, would love to be able to do something like this.
> 
> ```yaml
> group:
>   - @symfony/*
>   - @laravel/*
> ...
> ```
> 
> I agree with that!

That looks like a good idea for handling grouped dependencies, @ChrisCates why not update your proposal with these changes?

**Comment by ChrisCates** [comment] 2020-11-02 19:39
@Jacob-Morgan, thanks for the reference to that fork. It's actually very relevant.

@h-no, agreed, going to add that!

**Comment by DavidSpek** [comment] 2021-01-26 23:29
I am currently looking at the adoption of dependabot for the Kubeflow project, and as many others the amount of PRs that will be created for a given repository (and the resulting load on the AWS testing infra) are the man reasons for concern. The ability to group dependency updates together seems to be the most effective way to combat this issue, along with the problem that some dependencies need to be updated together to be functional. To me it seems the solution provided in https://github.com/dependabot/dependabot-core/issues/2672#issuecomment-719130140 is a good way forwards. What would be required to start getting this integrated into dependabot?

**Comment by halter73** [comment] 2021-06-03 20:42
This would also help us out in the https://github.com/dotnet/aspnetcore repo.

**Comment by mwaddell** [comment] 2022-01-29 19:37
Solving this is a more general way is a bit beyond dependabot's scope.  However, you should be able to solve this with a [custom github workflow](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#common-dependabot-automations).  You would create an action that runs whenever a new PR is created by dependabot and it uses [github-script](https://github.com/actions/github-script) to locate instances of PRs for related dependencies across your repo and then merges the changes from the new PR into the existing one and closes this new PR with a comment referring to the other PR.

Related to #3856 #1296 and #1190

**Comment by spenserblack** [comment] 2022-06-20 23:53
Sorry for commenting on an issue that hasn't had activity for a while, but I think having wildcards could also be useful. For example, Vue CLI dependencies are released together all at once (https://github.com/vuejs/vue-cli/commit/ef08a08c41b028a2484f262414a8c91d151febc7), so it's useful to have one PR for them all.

Something like this, for example:
```yaml
group:
  - @vue/cli*
```

I realize this is already very similar to the concept of "grouping all" and "grouping organizations", but I think those concepts can be combined into a more generalized pattern-matching for grouping/ignoring.

If you agree, maybe the proposal can be updated to specify that `*` is a pattern-matching wildcard in general, and not just for combining all deps or organization deps?

**Comment by pauleustice** [comment] 2022-08-04 12:38
Hello everyone! We at Legal and General have just open sourced [Dependabot Batcher](https://github.com/marketplace/actions/dependabot-batcher?version=v1.0.0), a GitHub Action that we've been trialling internally for some time. When run on a schedule (or ad-hoc, if you prefer), it will combine all open Dependabot PR changes into one.

The PR provides links to the original PRs, while closing them down. This can save a lot of CI time as well uncluttering your Pull Requests page.

Here's what the generated PR looks like:

![](https://github.com/Legal-and-General/dependabot-batcher/raw/v1.0.0/images/batch-pr-example.png)

We hope that someone finds this useful as we do, and look forward to hearing any feedback you might have!

**Comment by jurre** [comment] 2022-08-04 17:42
Interesting @pauleustice, can you share a little about how this deals with conflicts?

**Comment by pauleustice** [comment] 2022-08-05 08:19
@jurre Sure. Here's what we have in the readme:

> ℹ️ When the Action is unable to merge a Dependabot PR, it will keep the original PR open. This usually happens when there are updates for consecutive dependency entries in your package.json file, which cause merge conflicts. Merging the batched PR will mean it gets picked up on the next run.
> 
> You will see the branches that could not be combined in the logs, for example:
> 
> 🚫 These branches could not be combined:
> dependabot/npm_and_yarn/nrwl/linter-14.5.1
> dependabot/npm_and_yarn/nrwl/eslint-plugin-nx-14.5.1

Of course, you can manually add any merge conflicts to the combined PR if you wish. In our team we just merge the batched PR and then they get picked up on the next run.

**Comment by spenserblack** [comment] 2023-01-26 20:26
:tada: https://github.com/github/combine-prs

**Comment by jeffwidman** [comment] 2023-02-04 01:46
Thanks @spenserblack I hadn't seen that. :grin

Hopefully it's a helpful workaround until we get a chance to actually get this solved upstream here in :dependabot:.

Looking through the comments, this is pretty clearly a duplicate of a combination of:
* #1296
* #1190

**Closed by jeffwidman** 2023-02-04 01:46 UTC
Labels: T: feature-request, Workaround :repeat:, F: grouped-updates 🧑‍🤝‍🧑
