### ISSUE TITLE
NPM latest version finder not working with Artifactory (?)

### ISSUE THREAD

**Issue by lenntt** [dependabot/dependabot-core#945] opened 2019-01-21 17:23 UTC
(I hacked around #943, by ignoring the portnumber in a comparison.)

My upgradable dependency doesn't get updated. the `@yanked` check gets resolved to `true`, because it tries to retrieve an 'invalid url (404).
The check it does, doesn't seem right, it tries whether: `dependency_url + "/#{version}"` exists.

Enterprise npm repositories, like Artifactory, might return a 404 - the urls dont follow this convention. Instead, in my case, the `npm_details["versions"]` contains objects with the url to each version.

**Comment by lenntt** [comment] 2019-01-22 09:17
Authentication/generated urls aren't working correctly for me.
When skipping the yanked check, it gets one step further, by failing at updating the lock file. :/

```
         9: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:26:in `updated_dependency_files'
         8: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:97:in `updated_lockfiles'
         7: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:97:in `each'
         6: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:98:in `block in updated_lockfiles'
         5: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:69:in `package_lock_changed?'
         4: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:132:in `updated_package_lock_content'
         3: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:24:in `updated_lockfile_content'
         2: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:44:in `rescue in updated_lockfile_content'
         1: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:208:in `handle_npm_updater_error'
<myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:257:in `handle_missing_package': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): <mynpmreg-withouthttps> (Dependabot::PrivateSourceAuthenticationFailure)
```

**Comment by greysteil** [comment] 2019-01-22 09:22
Hmmm, I think you mentioned you're using artifactory for your private registry - is that JFrog? The permissions required for JFrog are really surprisingly - unless you're using a token that has `deploy` access it will fail at the lockfile step or before because it won't be able to fetch uncached artifacts. Could it be that?

**Comment by greysteil** [comment] 2019-01-22 10:04
OK, given #943 my first guess on this is that it's going to be related to the token permission. Can you take a look at that? If not, I'll dig deeper on our side, but I *think* that the `/{version}` URL is a required part of the `npm` registry spec.

**Comment by greysteil** [comment] 2019-01-22 10:06
And as an aside, I'm sorry about these issues. The Dependabot app has lots of validations that make it hard to enter invalid credentials, and serializes the errors Dependabot generates with suggestions (like the above one for JFrog). That logic doesn't like in `dependabot-core`, so this library is trickier to use than it should be with private credentials.

I'll see what I can do about improving that once we've got everything working here.

**Comment by lenntt** [comment] 2019-01-22 10:31
With your help, I've outputted the `npmrc_content`. 
With that same content, I seem to be able to update one of my packages in my project repository, which updates the package and lockfile. So I guess authentication should be working fine 
(?).


To make it a bit more concrete (perhaps I simply misinterpret things (would be a first time :)):
My package json + lock has my package at `2.1.9`.

The `npm_details["dist-tags"]["latest"]` is `2.1.11`, which seems to be read well.
in `wants_latest_dist_tag?` the last check is `yanked(ver)`, which returns true (because `version_not_found`, resulting in trying other versions, that also fail, and eventually a `:update_not_possible`.
So digging into `yanked`:
```
version_endpoint_working? # => true
```

Think I'm onto something, in `yanked?`:
```
dependency_url  # => JFROG RESPONDS url, consist out of "<repo>/<scope>%2F<package>
dependency_url + "/#{version}" # => JFROG says no. However, replacing %2F with /, works!
```
I think it relates with using `%2F` instead of `/`

**Comment by greysteil** [comment] 2019-01-22 12:08
Ah, interesting! I mean, that is unexpected behaviour from JFrog, but if it's consistent then we should be able to work around it. I'll take a look.

**Comment by greysteil** [comment] 2019-01-22 12:14
I'm really surprised that https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb#L192-L212 is returning `true` in this case. Does JFrog make an exception for `"<repo>/<scope>%2F<package>/latest"`?

**Comment by lenntt** [comment] 2019-01-22 14:05
> Does JFrog make an exception for `"<repo>/<scope>%2F<package>/latest"`?
Whoa, /latest seems to work with the `%2F` separator.

**Comment by greysteil** [comment] 2019-01-22 14:06
Haha, those guys are jokers! OK, will get Dependabot Core fixed up to try using slashes if %2F fails this evening / tomorrow morning. Have another big thing on my plate right now and the context switching is killing me! 🙂

**Comment by lenntt** [comment] 2019-01-23 09:10
No rush, thanks for all your help so far.

I've ran a single green thread, by hardcoded patches locally, 
I believe only this issue and #951 are in my way to set up a reproducable environment.

**Comment by greysteil** [comment] 2019-01-23 09:11
Awesome - we'll get there. Apologies for being a bit slow yesterday (and probably today).

**Comment by greysteil** [comment] 2019-02-11 16:01
Fixed by https://github.com/dependabot/dependabot-core/commit/06868cf8a2d05ccaee7b4619cb44168f1f31b58c.

**Closed by greysteil** 2019-02-11 16:01 UTC
