### ISSUE TITLE
Support multiple directories to bump the same package across dependency files

### ISSUE THREAD

**Issue by foolip** [dependabot/dependabot-core#3856] opened 2021-06-07 08:43 UTC
In https://github.com/web-platform-tests/wpt we track Python dependencies with a number of files named requirements_*.txt across directories, since the project is used in a number of different contexts (mostly browser engines like Chromium, Gecko and WebKit) where only a subset of the dependencies are needed.

We switched from pyup to Dependabot in https://github.com/web-platform-tests/wpt/pull/29161, and quickly found that Dependabot is creating separate pull requests for the same dependency across files, for example https://github.com/web-platform-tests/wpt/pull/29223 + https://github.com/web-platform-tests/wpt/pull/29227 or https://github.com/web-platform-tests/wpt/pull/29219 + https://github.com/web-platform-tests/wpt/pull/29224 + https://github.com/web-platform-tests/wpt/pull/29225.

We want those dependencies to stay in sync, so it would be much better if they were updated together. Unfortunately, there doesn't seem to be a way to specify multiple directories. This was the state of our config when the PRs were created:
https://github.com/web-platform-tests/wpt/blob/f44fd9953ebdbe8ef90ddf3bae8daaaa0173a92c/.github/dependabot.yml

Note that this is *not* the same request as https://github.com/dependabot/dependabot-core/issues/2178, wildcards would not  help us since there's no pattern that would match everything we want to update and still exclude all the things we *don't* want to touch (third party code).

**Comment by mwaddell** [comment] 2022-01-29 18:29
Solving this is a more general way is a bit beyond dependabot's scope.  However, you should be able to solve this with a [custom github workflow](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#common-dependabot-automations).  You would create an action that runs whenever a new PR is created by dependabot and it uses [github-script](https://github.com/actions/github-script) to locate instances of the same dependency in other locations across your repo and then merges the changes from the new PR into the existing one and closes this new PR with a comment referring to the other PR.

**Comment by jeffwidman** [comment] 2023-02-10 00:29
This is a monorepo specific problem, so is tricky because some users want us to bump a dep across all apps/libraries in the monorepo, and others want us to only bump in one specific place at a time.

So _if_ we added support for this, we'd need to ensure it was configurable. For now, I created the `F: monorepo` label so we can track the monorepo-related feedback together and added this to it.

**Comment by jeffwidman** [comment] 2023-02-10 07:02
Actually, this is a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/1595

So follow/upvote that for updates.

**Closed by jeffwidman** 2023-02-10 07:02 UTC
Labels: T: feature-request, Workaround :repeat:, F: grouped-updates 🧑‍🤝‍🧑, F: monorepo 📦
