### ISSUE TITLE
Problem with grouping updates

### ISSUE THREAD

**Issue by Maggus85** [dependabot/dependabot-core#10287] opened 2024-07-25 14:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

C#

### dependabot.yml content

```
version: 2
registries:
  farm-cloud:
    type: nuget-feed
    url: https://agrisolutionseu.pkgs.visualstudio.com/_packaging/FarmCloud/nuget/v3/index.json
    token: PAT:${{VSS_NUGET_ACCESSTOKEN}}
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
schedule:
  interval: "daily"
updates:
  - package-ecosystem: "nuget"
    directory: 
      - /src/API/AS.FarmCloud.Sensor.Storage/
    open-pull-requests-limit: 20
    registries:
      - farm-cloud
      - nuget
groups:
  internal-libs:
    applies-to: version-updates
    patterns:
      - "AS.Farm*
  external-libs:
    applies-to: version-updates
    patterns:
      - *
```
  

### What you expected to see, versus what you actually saw

I wanted to create one pr that updates the packages from our internal feed and a second that updates the others nugets.
For this reason, I added a section

```
groups:
  internal-libs:
    applies-to: version-updates
    patterns:
      - "AS.Farm*"
  external-libs:
    applies-to: version-updates
    patterns:
      - "*"

```
Without this section, everything works, but a lot of pr is created, which is not the expected behavior

Translated with DeepL.com (free version)

### Images of the diff or a link to the PR, issue, or logs

```
running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri\%20Solutions/_git/FarmCloud --solution-or-project /home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri\%20Solutions/_git/FarmCloud/src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj --dependency coverlet.collector --new-version 6.0.2 --previous-version 3.0.3 --result-output-path /tmp/update-result.json --verbose
  No dotnet-tools.json file found.
  No global.json file found.
Running for project file [src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj]
Updating project [/home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri%20Solutions/_git/FarmCloud/src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj]
  Running for SDK-style project
    Package [coverlet.collector] already meets the requested dependency version in [/home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri%20Solutions/_git/FarmCloud/src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj].
Update complete.
  Writing update result to [/tmp/update-result.json].
I, [2024-07-24T19:53:23.971283 #7]  INFO -- : update result: {
  "ErrorType": null,
  "ErrorDetails": null
}
Submitting coverlet.collector pull request for creation.
E, [2024-07-24T19:53:23.973486 #7] ERROR -- : Error while generating commit message: Passed `nil` into T.must
E, [2024-07-24T19:53:23.973531 #7] ERROR -- : /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/_types.rb:222:in `must'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'

```

**Comment by brettfo** [comment] 2024-07-25 17:49
@jakecoffman Could I get your help in triaging this?  I don't see anything that's specific to the NuGet updater (i.e., it doesn't do anything specific with groups that I know of.  Have you seen similar issues with other ecosystems?

**Comment by rhyskoedijk** [comment] 2024-07-26 03:28
This might be unrelated, but the stacktrace exactly matches an issue recently reported here: https://github.com/tinglesoftware/dependabot-azure-devops/issues/1232

L285: "Error while generating commit message: Passed `nil` into T.must"
https://github.com/dependabot/dependabot-core/blob/8441dbad1bb13149f897cdbe92c11d36f98c8248/common/lib/dependabot/pull_request_creator/message_builder.rb#L284-L288

`files.first` is nil, no files were updated by NuGetUpdater.Cli for the dependency.
In this case I presume the reason was "Package [coverlet.collector] already meets the requested dependency version in ...csproj."?

The issue in https://github.com/tinglesoftware/dependabot-azure-devops/issues/1232 was ultimately caused due to auth issues accessing the private nuget-feed, which is a known issue (see: https://github.com/dependabot/dependabot-core/pull/8927). However there are no auth errors are mentioned in OP's logs, so the root cause is probably different here but the output from NuGetUpdater.Cli appears to be the same; no files were changed, PR message build throws error.

**Comment by soltanmsa** [comment] 2024-07-26 05:52
Have you seen similar issues with other no

**Comment by Maggus85** [comment] 2024-08-01 08:56
I was trying to use according to [https://github.com/tinglesoftware/dependabot-azure-devops/issues/1257](url)

But it did not change anything, still same error.

My current pipeline looks like

`trigger: none

stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Private Feed Authentication'
          - task: dependabot@1
            displayName: 'Run Dependabot'
            inputs:
              packageManager: 'nuget'
              targetBranch: 'dev'
              openPullRequestsLimit: 50
              azureDevOpsAccessToken: '$(System.AccessToken)'
              dockerImageTag: '1.30.3-ci0008'
              useUpdateScriptvNext: true`

**Comment by rhyskoedijk** [comment] 2024-08-18 22:54
@Maggus85 or @brettfo are you able to close this issue? It is not an issue with dependabot-core, it is an auth issue in https://github.com/tinglesoftware/dependabot-azure-devops

**Closed** 2024-08-21 18:12 UTC
Labels: T: bug 🐞, L: ruby:bundler, L: git:submodules, L: dotnet:nuget
