### ISSUE TITLE
Missing continuation-line backslashes when updating requirements.txt

### ISSUE THREAD

**Issue by bemoody** [dependabot/dependabot-core#2689] opened 2020-10-27 22:29 UTC
Is this the place to report bugs when @dependabot creates a faulty pull request?  Sorry if it isn't.

It just sent us the following:
```
commit 6f2b121dc30c794111503fa1cb33a87735f7e3ea
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Oct 27 21:51:40 2020 +0000

    Bump cryptography from 2.7 to 3.2
    
    Bumps [cryptography](https://github.com/pyca/cryptography) from 2.7 to 3.2.
    - [Release notes](https://github.com/pyca/cryptography/releases)
    - [Changelog](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst)
    - [Commits](https://github.com/pyca/cryptography/compare/2.7...3.2)
    
    Signed-off-by: dependabot[bot] <support@github.com>

diff --git a/requirements.txt b/requirements.txt
index 286f037e..7f6f3dd5 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -133,9 +133,29 @@ cffi==1.12.3 \
  --hash=sha256:a1f0fd46eba2d71ce1589f7e50a9e2ffaeb739fb2c11e8192aa2b45d5f6cc41f
 pycparser==2.19 \
  --hash=sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
-cryptography==2.7 \
- --hash=sha256:96d8473848e984184b6728e2c9d391482008646276c3ff084a1bd89e15ff53a1\
- --hash=sha256:24b61e5fcb506424d3ec4e18bca995833839bf13c59fc43e530e488f28d46b8c
+cryptography==3.2 \
+ --hash=sha256:9a8580c9afcdcddabbd064c0a74f337af74ff4529cdf3a12fa2e9782d677a2e5
+ --hash=sha256:7ef41304bf978f33cfb6f43ca13bb0faac0c99cda33693aa20ad4f5e34e8cb8f
+ --hash=sha256:87c2fffd61e934bc0e2c927c3764c20b22d7f5f7f812ee1a477de4c89b044ca6
+ --hash=sha256:6a8f64ed096d13f92d1f601a92d9fd1f1025dc73a2ca1ced46dcf5e0d4930943
+ --hash=sha256:3e17d02941c0f169c5b877597ca8be895fca0e5e3eb882526a74aa4804380a98
+ --hash=sha256:6e8a3c7c45101a7eeee93102500e1b08f2307c717ff553fcb3c1127efc9b6917
+ --hash=sha256:52a47e60953679eea0b4d490ca3c241fb1b166a7b161847ef4667dfd49e7699d
+ --hash=sha256:d1cbc3426e6150583b22b517ef3720036d7e3152d428c864ff0f3fcad2b97591
+ --hash=sha256:22f8251f68953553af4f9c11ec5f191198bc96cff9f0ac5dd5ff94daede0ee6d
+ --hash=sha256:f2aa3f8ba9e2e3fd49bd3de743b976ab192fbf0eb0348cebde5d2a9de0090a9f
+ --hash=sha256:9a07e6d255053674506091d63ab4270a119e9fc83462c7ab1dbcb495b76307af
+ --hash=sha256:f0e3986f6cce007216b23c490f093f35ce2068f3c244051e559f647f6731b7ae
+ --hash=sha256:284e275e3c099a80831f9898fb5c9559120d27675c3521278faba54e584a7832
+ --hash=sha256:f01c9116bfb3ad2831e125a73dcd957d173d6ddca7701528eff1e7d97972872c
+ --hash=sha256:bd80bc156d3729b38cb227a5a76532aef693b7ac9e395eea8063ee50ceed46a5
+ --hash=sha256:8f0fd8b0751d75c4483c534b209e39e918f0d14232c0d8a2a76e687f64ced831
+ --hash=sha256:8a0866891326d3badb17c5fd3e02c926b635e8923fa271b4813cd4d972a57ff3
+ --hash=sha256:57b8c1ed13b8aa386cabbfde3be175d7b155682470b0e259fecfe53850967f8a
+ --hash=sha256:88069392cd9a1e68d2cfd5c3a2b0d72a44ef3b24b8977a4f7956e9e3c4c9477a
+ --hash=sha256:fb70a4cedd69dc52396ee114416a3656e011fb0311fca55eb55c7be6ed9c8aef
+ --hash=sha256:e15ac84dcdb89f92424cbaca4b0b34e211e7ce3ee7b0ec0e4f3c55cee65fae5a
+ --hash=sha256:e4789b84f8dedf190148441f7c5bfe7244782d9cbb194a36e17b91e7d3e1cca9
 
 # required by google-api-python-client 1.7.9
 uritemplate==3.0.0 \
```

This patch is incorrect, because it's missing backslashes (each of the "--hash" lines, except the last, should end with a backslash.)

@dependabot has done the right thing in the past, so I guess this is a recent change, or else something uniquely odd about the python "cryptography" package.

**Comment by tompollard** [comment] 2020-12-04 03:36
Does anyone have any insight into where this issue might stem from? (dependabot or the cryptography package itself?) I'm happy to have a go at fixing, but I'm not familiar with the codebase so any pointers would be appreciated! Thanks :)

**Comment by lseppala** [comment] 2021-11-30 23:55
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this still happening, or has this problem been resolved and can we close this issue?

This was the right place to report a bug :) We have a [bug report template](https://github.com/dependabot/dependabot-core/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) that has some questions about the issue that might help us diagnose it, if you would like to help us figure it out.

**Comment by jeffwidman** [comment] 2023-02-02 08:33
Closing due to lack of user response.

**Comment by deivid-rodriguez** [comment] 2023-02-03 16:30
This is still reproducible, I created #6585 to fix it!

**Closed** 2023-02-03 21:38 UTC
Labels: T: bug 🐞, L: python:pip, F: language-support, python, core 🍏
