### ISSUE TITLE
Ability to upgrade to Long Term Support version

### ISSUE THREAD

**Issue by chriseyre2000** [dependabot/dependabot-core#2651] opened 2020-10-16 09:47 UTC
Currently we can ignore a major, minor or patch version.

I would like to be able to specify that I only want the Long Term Supported version.

This would allow, for example, the docker image for node to upgrade to 14 only when it is in Long Term Support.

**Comment by Divlo** [comment] 2021-02-24 15:29
That could be cool, indeed! :smile: 
Because currently, when we setup a new repo with the `node` Docker image, it automatically open a PR to update to `v15` but that version is not LTS, so the current workaround for this is to close the PR, so `dependabot` don't open a PR when it's a release for `v15`.

**Comment by cristobal** [comment] 2021-03-04 15:36
Is there no way to specify the release one wants to track?

1.  Say i have project that's on the maintenance branch v12 for node, one would only like to have updates for the v12 branch.
2. Another project is one the active LTS branch, should only have updates for the current LTS branch e.g. v14 at this point.
3. While one could specify current if one wants to be on the v15 branch.

Would be nice to specify a release branch to follow, for the ones that supported the following table from the [releases](https://nodejs.org/en/about/releases/) page:


![Screenshot 2021-03-04 at 16 36 04](https://user-images.githubusercontent.com/155505/109988333-b7649f00-7d07-11eb-96e8-81a50a151451.png)

**Comment by jeffwidman** [comment] 2022-11-24 01:44
@cristobal I think the bug ☝️ has been fixed in one of the recent docker version parsing fixes... it should have only tracked `v14` branch.

As far as the broader request for LTS support another use case is only bumping `ubuntu` from one LTS release to the next... ie don't try to bump `18.04` to `20.04`, but only to `22.04`.

**Comment by jeffwidman** [comment] 2023-02-06 01:44
Closing as a duplicate of 
* https://github.com/dependabot/dependabot-core/issues/2247

**Closed by jeffwidman** 2023-02-06 01:44 UTC
Labels: T: feature-request, L: docker, F: noise, F: dependency-ignores
