### ISSUE TITLE
Increase character limit for `commit-message.prefix` to 50 characters

### ISSUE THREAD

**Issue by bogdannazarenko** [dependabot/dependabot-core#5553] opened 2022-08-18 17:00 UTC
When trying to set prefix for Dependabot's commit message to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) we always run into character limit.

Example specifying **type(scope): message** is already 24 characters. This can easily be longer as some teams need to include a JIRA ticket (e.g `deps(myawesomeservice): SEC-000`) when working on a monorepo

```yaml
- package-ecosystem: "npm"
   commit-message:
      prefix: "deps(myawesomeservice): "
```

**Comment by mustafaozhan** [comment] 2022-12-04 22:34
Not only for Conventional commits, we need this character limit increase in order to add cross organization commits between submodules.

Ie. we want to use prefix `OrganisationName/RepoName#IssueId` to link the commit messages between repos but due to this limit we are updating each PR title manually 😞 

Really looking forward to seeing this issue to be fixed. Also, as you can see from the picture below, in docs this limit is already 50.

<img width="742" alt="Screenshot 2022-12-05 at 00 32 05" src="https://user-images.githubusercontent.com/30001999/205519389-c15bad91-8eb0-4355-bf85-a352da1b535f.png">

**Comment by deivid-rodriguez** [comment] 2022-12-05 22:21
Actually I believe we should've fixed this already, and that's why you are seeing updated docs, but we just forgot to close this ticket? Are you still seeing this issue?

**Comment by mustafaozhan** [comment] 2022-12-08 10:11
@deivid-rodriguez Thank you for your answer. I just updated my repo to check it, and currently I have this error:
```
The property '#/updates/0/commit-message/prefix' was not of a maximum string length of 15
The property '#/updates/1/commit-message/prefix' was not of a maximum string length of 15
The property '#/updates/2/commit-message/prefix' was not of a maximum string length of 15
The property '#/updates/3/commit-message/prefix' was not of a maximum string length of 15
```
in https://github.com/Oztechan/CCC/network/updates

It looks like current length limit is 15

**Comment by deivid-rodriguez** [comment] 2022-12-08 12:08
Thanks for reporting that, it made me notice something that was missing in our previous fix. Can you try again now?

**Comment by mustafaozhan** [comment] 2022-12-08 12:18
Hey @deivid-rodriguez Thanks a lot I rerun the task that check Dependabot file, it passes this time 🎉 
But the [Oztechan/CCC/network/updates](https://github.com/Oztechan/CCC/network/updates) remains the same 🤔 Is there any caching ? Or something new needs to be merged, or should I wait a bit more ?

**Comment by mustafaozhan** [comment] 2022-12-08 12:32
<img width="1783" alt="Screenshot 2022-12-08 at 14 32 16" src="https://user-images.githubusercontent.com/30001999/206447040-f702d4b6-510e-4b26-a5a2-9cf6c4d7a641.png">
That button is not available, I just added the picture to given idea how it looks

**Comment by deivid-rodriguez** [comment] 2022-12-08 13:17
I think it should work in the next scheduled run of Dependabot in your repo, but let me know if it does not.

**Comment by mustafaozhan** [comment] 2022-12-08 13:33
Okay i will keep eye on that and give a feedback here, thanks a lot!

**Comment by mustafaozhan** [comment] 2022-12-09 09:45
@deivid-rodriguez I merged another PR on top of it today, but the issue still remains the same 😕

**Comment by deivid-rodriguez** [comment] 2022-12-09 11:17
🤔 Was it a PR changing dependency manifest files?

**Comment by mustafaozhan** [comment] 2022-12-09 12:25
Nope, but the one from yesterday was changing manifest already

**Comment by mustafaozhan** [comment] 2022-12-10 13:10
@deivid-rodriguez I confirm today my issue is gone 🎉 , so for me the issue is fixed!

**Comment by deivid-rodriguez** [comment] 2022-12-11 05:56
Awesome, great to hear!

**Closed by deivid-rodriguez** 2022-12-11 05:56 UTC
Labels: T: feature-request, F: pull-requests

**Comment by bogdannazarenko** [comment] 2023-01-31 16:08
@deivid-rodriguez thank you for working on this!

**Comment by deivid-rodriguez** [comment] 2023-01-31 16:13
No problem, glad it helped you!
