### ISSUE TITLE
`schedule.interval` of `fortnight` (every two weeks)

### ISSUE THREAD

**Issue by halostatue** [dependabot/dependabot-core#7490] opened 2023-06-27 17:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Dependabot version updates reporting weekly results in a noisy pull request queue; monthly reporting results in a potential backlog of version updates. It seems to me that for medium-sized projects, the right frequency would be every two weeks.

**Comment by halostatue** [comment] 2023-06-27 17:46
Post-submission, I found two issues that refer to this concept: #2038 (closed) and #6339 (cron scheduling).

**Comment by NazimHAli** [comment] 2024-11-18 22:06
+1

**Comment by abdulapopoola** [comment] 2024-12-23 23:20
Closing as a dupe of #6339 ; let's use #6339 to track

**Closed by abdulapopoola** 2024-12-23 23:20 UTC
Labels: T: feature-request
