### ISSUE TITLE
Poetry parsing error

### ISSUE THREAD

**Issue by isac322** [dependabot/dependabot-core#2715] opened 2020-11-03 09:06 UTC
**Package manager/ecosystem**
Python, poetry

**Manifest contents prior to update**
[pyproject.toml](https://github.com/Buzzvil/buzzvil-python-styleguide/blob/85f82be3b3f17ccadf5161f568e7a48b9358fbd2/pyproject.toml)

**Updated dependency**
No update

**What you expected to see, versus what you actually saw**

dependabot prints error below. `Status: processed_with_errors`

```
  proxy | time="2020-11-03T08:37:24Z" level=info msg="proxy starting" commit=29a0af936e208929f8103aac2cd8e186f78243b4
  proxy | 2020/11/03 08:37:24 Listening (:1080)
fetcher | yarn config v1.22.5
fetcher | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
fetcher | Done in 0.02s.
fetcher | I, [2020-11-03T08:37:27.110536 #71]  INFO -- sentry: ** [Raven] Raven 3.1.1 ready to catch errors
fetcher | INFO <job_53298451> Starting job processing
  proxy | 2020/11/03 08:37:28 [002] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide
  proxy | 2020/11/03 08:37:28 * authenticating github api request
  proxy | 2020/11/03 08:37:28 [002] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide
  proxy | 2020/11/03 08:37:28 [004] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/git/refs/heads/master
  proxy | 2020/11/03 08:37:28 * authenticating github api request
  proxy | 2020/11/03 08:37:28 [004] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/git/refs/heads/master
  proxy | 2020/11/03 08:37:28 [006] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:28 * authenticating github api request
  proxy | 2020/11/03 08:37:28 [006] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:28 [008] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/pyproject.toml?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:28 * authenticating github api request
  proxy | 2020/11/03 08:37:29 [008] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/pyproject.toml?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:29 [010] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/src?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:29 * authenticating github api request
  proxy | 2020/11/03 08:37:29 [010] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/src?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:29 [012] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/tests?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:29 * authenticating github api request
  proxy | 2020/11/03 08:37:29 [012] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/tests?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:29 [014] GET https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/setup.cfg?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
  proxy | 2020/11/03 08:37:29 * authenticating github api request
  proxy | 2020/11/03 08:37:29 [014] 200 https://api.github.com:443/repos/Buzzvil/buzzvil-python-styleguide/contents/setup.cfg?ref=85f82be3b3f17ccadf5161f568e7a48b9358fbd2
fetcher | INFO <job_53298451> Finished job processing
  proxy | time="2020-11-03T08:37:30Z" level=info msg="proxy starting" commit=29a0af936e208929f8103aac2cd8e186f78243b4
  proxy | 2020/11/03 08:37:30 Listening (:1080)
updater | yarn config v1.22.5
updater | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
updater | Done in 0.02s.
updater | I, [2020-11-03T08:37:33.002092 #71]  INFO -- sentry: ** [Raven] Raven 3.1.1 ready to catch errors
updater | INFO <job_53298451> Starting job processing
updater | INFO <job_53298451> Starting update job for Buzzvil/buzzvil-python-styleguide
updater | ERROR <job_53298451> no implicit conversion of String into Integer
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:98:in `check_requirements'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:45:in `block (2 levels) in pyproject_dependencies'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:41:in `each'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:41:in `block in pyproject_dependencies'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:38:in `each'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:38:in `pyproject_dependencies'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser/poetry_files_parser.rb:25:in `dependency_set'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser.rb:66:in `poetry_dependencies'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.124.6/lib/dependabot/python/file_parser.rb:42:in `parse'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:428:in `dependencies'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:52:in `run'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_53298451> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_53298451> bin/update_files.rb:21:in `<main>'
updater | I, [2020-11-03T08:37:34.138243 #71]  INFO -- sentry: ** [Raven] Sending event eaf6a3ca362d431bb257b0a753054707 to Sentry
  proxy | 2020/11/03 08:37:54 [002] POST https://sentry.io:443/api/1425239/store/
  proxy | 2020/11/03 08:37:54 [002] 200 https://sentry.io:443/api/1425239/store/
updater | INFO <job_53298451> Finished job processing
```

**Comment by chiehtu** [comment] 2021-02-11 12:54
This is caused by Dependabot does not support [Multiple constraints dependencies](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies).

Ruby will raise a TypeError when Dependabot try to access an array element using a string.

```ruby
def check_requirements(req)
  requirement = req.is_a?(String) ? req : req["version"]
```

from [dependabot-core/poetry_files_parser.rb at v0.133.2 · dependabot/dependabot-core · GitHub](https://github.com/dependabot/dependabot-core/blob/v0.133.2/python/lib/dependabot/python/file_parser/poetry_files_parser.rb#L98)

```
(rdb:1) req
[{"version"=>"^2.2.11", "python"=>"~3.5"}, {"version"=>"^3.0.4", "python"=>"^3.6"}]
(rdb:1) req.is_a?(Array)
true
(rdb:1) req["version"]
/usr/lib/ruby/2.6.0/debug.rb:291:in `eval':no implicit conversion of String into Integer
```

**Comment by jeffwidman** [comment] 2022-11-24 00:58
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/3565.

I realize this one is older, but that one has a bit more info on it.

**Closed by jeffwidman** 2022-11-24 00:58 UTC
Labels: T: bug 🐞, L: python:poetry
