### ISSUE TITLE
Template for commit messages

### ISSUE THREAD

**Issue by Milo123459** [dependabot/dependabot-core#4278] opened 2021-10-03 09:44 UTC
Something in the config file so you can do this:
```yml
template: "chore: deps: bump `{name}` from `{old_version}` to `{to}`"
```

Useful if projects have a commit message specification

**Comment by deivid-rodriguez** [comment] 2022-09-16 13:24
Hello! 👋

I totally agree with this request, I actually request it myself [a long time ago](https://github.com/dependabot/dependabot-core/issues/406#issuecomment-385024404). Hopefully we'll find some time to implement it in the future, thanks for the suggestion.

I'm going to close this particular issue though, since it's a duplicate of https://github.com/dependabot/dependabot-core/issues/1460. Feel free to subscribe to that issue for updates!

**Closed by deivid-rodriguez** 2022-09-16 13:24 UTC
Labels: T: feature-request
