### ISSUE TITLE
Add ability to always rebase PRs when out of date with the target branch

### ISSUE THREAD

**Issue by dstaley** [dependabot/dependabot-core#3782] opened 2021-05-24 16:20 UTC
Currently, with GitHub native Dependabot, dependency PRs are only rebased when there's a conflict in one of the dependency manager's files. It would be nice to have the ability to configure Dependabot to always rebase PRs when out of date with the target branch.

You can achieve this with branch protection rules; by requiring all branches to be in sync with your main branch, Dependabot will keep all PRs up to date with changes. However, branch protection rules aren't available for free private repos, and furthermore it might be undesirable to require updated branches from contributors.

I'd love to see a new `rebase-strategy`, maybe `always-rebase`, that tells Dependabot to always rebase PRs when the PR branch is behind the target branch. In previous discussions, this behavior was said to be a strain on CI resources, which is why I think making it an opt-in feature would be preferred.

**Comment by jeffwidman** [comment] 2022-11-24 09:17
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/2224. That one has more description, but this one had a more searchable title which is probably why it got a lot of upvotes compared to the other one so I retitled that one.

If you upvoted this one, please go stick your upvote on https://github.com/dependabot/dependabot-core/issues/2224 instead. Thanks!

And if for some reason I misread and this is actually a separate issue please comment and we can reopen.

**Closed by jeffwidman** 2022-11-24 09:17 UTC
Labels: T: feature-request, F: pull-requests, 💁 service
