### ISSUE TITLE
Dependabot reset base branch if changed

### ISSUE THREAD

**Issue by PythonCoderAS** [dependabot/dependabot-core#6692] opened 2023-02-17 20:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

When I changed the base branch of the PR (what branch it merged into) and it required a rebase, I issued `@dependabot rebase` but it caused dependabot to change the base branch back and the rebased output still cannot be merged into the other branch.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/flyboat-org/frontend/pull/111

**Comment by deivid-rodriguez** [comment] 2023-02-22 18:21
Hello! This is a duplicate of #2146 I'm pretty sure, please subscribe to that for updates!

**Closed by deivid-rodriguez** 2023-02-22 18:21 UTC
Labels: T: bug 🐞
