### ISSUE TITLE
i have some error for nuget package

### ISSUE THREAD

**Issue by firatoltulu** [dependabot/dependabot-core#8759] opened 2024-01-11 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

3

### Language version

net6

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 50
    allow:
      - dependency-name: "shopexpress*"
  
   ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
    schedule:
      interval: "daily"

### What you expected to see, versus what you actually saw

updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2024/01/11 09:50:09 ERROR <job_773004511> bin/update_files.rb:24:in `<main>'
updater | 2024/01/11 09:50:09 INFO <job_773004511> Checking if ShopExpress.Domain 1.0.5 needs updating
updater | 2024/01/11 09:50:09 INFO <job_773004511> Ignored versions:
updater | 2024/01/11 09:50:09 INFO <job_773004511>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2024/01/11 09:50:09 [269] GET https://api.nuget.org:443/v3/registration5-gz-semver2/shopexpress.domain/index.json
  proxy | 2024/01/11 09:50:09 [269] 404 https://api.nuget.org:443/v3/registration5-gz-semver2/shopexpress.domain/index.json
updater | 2024/01/11 09:50:09 INFO <job_773004511> Latest version is 
updater | 2024/01/11 09:50:09 INFO <job_773004511> Requirements to unlock all
updater | 2024/01/11 09:50:09 INFO <job_773004511> Requirements update strategy 
updater | Finding updated dependencies for ShopExpress.Domain.
updater | 2024/01/11 09:50:09 INFO <job_773004511> Sending event 60df7a7d67d24da3b6f65c468b0619f6 to Sentry
  proxy | 2024/01/11 09:50:09 [274] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/11 09:50:09 [274] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/11 09:50:10 ERROR <job_773004511> Error processing ShopExpress.Domain (NoMethodError)
updater | 2024/01/11 09:50:10 ERROR <job_773004511> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/11 09:50:10 ERROR <job_773004511> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'

**Comment by Kielek** [comment] 2024-01-11 12:07
Similar issue occuers in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation repository.

Please let me know if you need more details.

```log
updater | 2024/01/11 11:46:39 INFO <job_773050515> Checking if OpenTelemetry.ResourceDetectors.Container  needs updating
updater | 2024/01/11 11:46:39 INFO <job_773050515> Latest version is 
updater | 2024/01/11 11:46:39 INFO <job_773050515> Sending event 2fb0505d157542c7bf8a85e04ee1d846 to Sentry
  proxy | 2024/01/11 11:46:39 [758] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/11 11:46:40 [758] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/11 11:46:40 ERROR <job_773050515> Error processing OpenTelemetry.ResourceDetectors.Container (NoMethodError)
updater | 2024/01/11 11:46:40 ERROR <job_773050515> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:298:in `changed_requirements'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:284:in `requirements_up_to_date?'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:37:in `up_to_date?'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:62:in `up_to_date?'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:81:in `check_and_create_pull_request'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2024/01/11 11:46:40 ERROR <job_773050515> bin/update_files.rb:24:in `<main>'
```

**Comment by firatoltulu** [comment] 2024-01-15 11:30
any one fixed this issues ?

**Comment by vojtech-jakubec-deltatre** [comment] 2024-01-15 11:36
The same issue started appearing 5 days ago for all NuGet packages hosted on our private organization GutHub NuGet repository. Public NuGet packages do not seem to be affected. From logs it seems that DependaBot lost track of which NuGet repository to use for which package. This is currently blocking DependaBot execution on .NET projects in our organization.

Current failing run is attempting to fetch data for private packages from public NuGet
```
updater | 2024/01/12 14:21:51 INFO <job_773638892> Checking if Scale.Common.Messaging 0.4.0 needs updating
updater | 2024/01/12 14:21:51 INFO <job_773638892> Ignored versions:
updater | 2024/01/12 14:21:51 INFO <job_773638892>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2024/01/12 14:21:51 [687] GET https://api.nuget.org:443/v3/registration5-gz-semver2/scale.common.messaging/index.json
  proxy | 2024/01/12 14:21:51 [687] 404 https://api.nuget.org:443/v3/registration5-gz-semver2/scale.common.messaging/index.json
updater | 2024/01/12 14:21:51 INFO <job_773638892> Latest version is 
updater | 2024/01/12 14:21:51 INFO <job_773638892> Requirements to unlock all
updater | 2024/01/12 14:21:51 INFO <job_773638892> Requirements update strategy 
updater | Finding updated dependencies for Scale.Common.Messaging.
updater | 2024/01/12 14:21:51 INFO <job_773638892> Sending event 3fed48702cdf4ca9b75b33df89610a61 to Sentry
  proxy | 2024/01/12 14:21:51 [689] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/12 14:21:51 [689] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/12 14:21:52 ERROR <job_773638892> Error processing Scale.Common.Messaging (NoMethodError)
updater | 2024/01/12 14:21:52 ERROR <job_773638892> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
```

Two weeks old run shows package data was fetched from private GitHub NuGet feed where the package actually lives
```
updater | 2024/01/08 14:37:52 INFO <job_771156007> Checking if Scale.Subscription.Common 0.46.0 needs updating
updater | 2024/01/08 14:37:52 INFO <job_771156007> Ignored versions:
updater | 2024/01/08 14:37:52 INFO <job_771156007>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2024/01/08 14:37:52 [668] GET https://nuget.pkg.github.com:443/deltatre-vxp/index.json
  proxy | 2024/01/08 14:37:52 [668] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/08 14:37:52 [668] 200 https://nuget.pkg.github.com:443/deltatre-vxp/index.json
  proxy | 2024/01/08 14:37:52 [670] GET https://nuget.pkg.github.com:443/deltatre-vxp/query?q=scale.subscription.common&prerelease=true&semVerLevel=2.0.0
  proxy | 2024/01/08 14:37:52 [670] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/08 14:37:52 [670] 200 https://nuget.pkg.github.com:443/deltatre-vxp/query?q=scale.subscription.common&prerelease=true&semVerLevel=2.0.0
  proxy | 2024/01/08 14:37:52 [672] GET https://azuresearch-usnc.nuget.org:443/query?q=scale.subscription.common&prerelease=true&semVerLevel=2.0.0
  proxy | 2024/01/08 14:37:52 [672] 200 https://azuresearch-usnc.nuget.org:443/query?q=scale.subscription.common&prerelease=true&semVerLevel=2.0.0
  proxy | 2024/01/08 14:37:52 [674] GET https://nuget.pkg.github.com:443/deltatre-vxp-flatcontainer/scale.subscription.common/0.46.0/scale.subscription.common.nuspec
  proxy | 2024/01/08 14:37:52 [674] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/08 14:37:52 [674] 404 https://nuget.pkg.github.com:443/deltatre-vxp-flatcontainer/scale.subscription.common/0.46.0/scale.subscription.common.nuspec
  proxy | 2024/01/08 14:37:52 [676] GET https://api.nuget.org:443/v3-flatcontainer/scale.subscription.common/0.46.0/scale.subscription.common.nuspec
  proxy | 2024/01/08 14:37:52 [676] 404 https://api.nuget.org:443/v3-flatcontainer/scale.subscription.common/0.46.0/scale.subscription.common.nuspec
updater | 2024/01/08 14:37:52 INFO <job_771156007> Latest version is 0.46.0
updater | 2024/01/08 14:37:52 INFO <job_771156007> No update needed for Scale.Subscription.Common 0.46.0
```

**Comment by firatoltulu** [comment] 2024-01-15 12:41
I started getting this error 5 days ago. It has nothing to do with nuget.org, the problem is entirely with private nuget(github)
All our work has stopped, we are configuring it manually. It is unclear when it will be resolved.

**Comment by delepster** [comment] 2024-01-15 21:57
same for us, unable to fetch updated packages from our private github feed

**Comment by sgoldberg16** [comment] 2024-01-16 18:26
Any updates on this? I am having the same issue:
 latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s 
 is failing for our private github feed

**Comment by WolfgangNiedental** [comment] 2024-01-17 10:50
We are also running into this error packages from our private github feed

**Comment by bfentiman-ipipeline** [comment] 2024-01-17 14:06
I'll also add that we are having this issue with private repos

**Comment by FrankRua** [comment] 2024-01-17 15:33
We are also having issues with private repos.

**Comment by Lukasz-Additiv** [comment] 2024-01-18 13:11
Any plans to fix this ? We are facing  the same issue

**Comment by JensSchadron** [comment] 2024-01-18 15:54
Just linking for the sake of completeness, but this seems related to https://github.com/tinglesoftware/dependabot-azure-devops/issues/921, which might also be affected by the same issue (at the very least the end result is the same).

**Comment by ivanmalich** [comment] 2024-01-18 22:28
Also having the same problem for Github Nuget source. It looks like the version update job completed successfully yesterday, but failed today without any changes in the dependabot.yml file.

**Comment by abdulapopoola** [comment] 2024-01-25 00:29
Sorry about the regression; this [shipped](https://github.com/dependabot/dependabot-core/pull/8892); can you please verify that it solves the challenge?

**Comment by vojtech-jakubec-deltatre** [comment] 2024-01-25 08:54
> Sorry about the regression; this [shipped](https://github.com/dependabot/dependabot-core/pull/8892); can you please verify that it solves the challenge?

I can confirm this fixed the issue for us with private GitHub NuGet.
Thank you

**Comment by skrzysiak-ipipeline** [comment] 2024-01-25 08:57
Appears to have worked for us as well (private github feed).

**Comment by firatoltulu** [comment] 2024-01-25 09:21
Finaly!

**Comment by probitdavid** [comment] 2024-01-25 09:26
its working for us with just the .csproj updates but failing if its a combination of .csproj and packages.config

**Comment by probitdavid** [comment] 2024-01-25 09:29
@abdulapopoola would you like a new issue ?
This is log file output:
`proxy | 2024/01/25 09:08:01 proxy starting, commit: 07d59135734a484cdcd1b34f737c7bca281bcf94
  proxy | 2024/01/25 09:08:01 * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/25 09:08:01 Listening (:1080)
updater | 2024-01-25T09:08:02.583880304 [778670211:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-01-25T09:08:05Z" level=info msg="guest starting" commit=5265bc7c42825390c331713cef4ed23c69721bbb
updater | time="2024-01-25T09:08:05Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=778670211 updater_timeout=45m0s updater_version=9802e07acbab491aac0687c500c320c3a837b7cb-nuget
updater | 2024/01/25 09:08:10 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/25 09:08:13 INFO <job_778670211> Starting job processing
  proxy | 2024/01/25 09:08:13 [002] GET https://github.com:443/probit-io/aim4/info/refs?service=git-upload-pack
  proxy | 2024/01/25 09:08:13 [002] * authenticating git server request (host: github.com)
  proxy | 2024/01/25 09:08:14 [002] 200 https://github.com:443/probit-io/aim4/info/refs?service=git-upload-pack
  proxy | 2024/01/25 09:08:14 [004] POST https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/25 09:08:14 [004] * authenticating git server request (host: github.com)
  proxy | 2024/01/25 09:08:14 [004] 200 https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/25 09:08:14 [006] POST https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/25 09:08:14 [006] * authenticating git server request (host: github.com)
  proxy | 2024/01/25 09:08:14 [006] 200 https://github.com:443/probit-io/aim4/git-upload-pack
updater | 2024/01/25 09:08:17 INFO <job_778670211> Finished job processing
updater | time="2024-01-25T09:08:17Z" level=info msg="task complete" container_id=job-778670211-file-fetcher exit_code=0 job_id=778670211 step=fetcher
updater | 2024/01/25 09:08:20 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/25 09:08:23 INFO <job_778670211> Starting job processing
updater | 2024/01/25 09:08:23 INFO <job_778670211> Starting update job for probit-io/aim4
updater | 2024/01/25 09:08:23 INFO <job_778670211> Checking all dependencies for version updates...
updater | 2024/01/25 09:08:23 INFO <job_778670211> Checking if DocumentFormat.OpenXml 2.20.0 needs updating
  proxy | 2024/01/25 09:08:24 [012] GET https://nuget.pkg.github.com:443/probit-io/index.json
  proxy | 2024/01/25 09:08:24 [012] * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/25 09:08:24 [012] 200 https://nuget.pkg.github.com:443/probit-io/index.json
  proxy | 2024/01/25 09:08:24 [016] GET https://nuget.pkg.github.com:443/probit-io/documentformat.openxml/index.json
  proxy | 2024/01/25 09:08:24 [016] * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/25 09:08:24 [016] 404 https://nuget.pkg.github.com:443/probit-io/documentformat.openxml/index.json
updater | 2024/01/25 09:08:24 INFO <job_778670211> Latest version is 
updater | 2024/01/25 09:08:24 INFO <job_778670211> Requirements to unlock all
updater | 2024/01/25 09:08:24 INFO <job_778670211> Requirements update strategy 
updater | Finding updated dependencies for DocumentFormat.OpenXml.
updater | 2024/01/25 09:08:24 INFO <job_778670211> Sending event 3a60914807134d91993e36dd7228e038 to Sentry
  proxy | 2024/01/25 09:08:24 [018] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/25 09:08:24 [018] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/25 09:08:25 ERROR <job_778670211> Error processing DocumentFormat.OpenXml (NoMethodError)
updater | 2024/01/25 09:08:25 ERROR <job_778670211> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/01/25 09:08:25 ERROR <job_778670211> bin/update_files.rb:24:in `<main>'`

**Comment by abdulapopoola** [comment] 2024-01-25 17:15
@probitdavid please kindly file a new issue and tag it with the nuget tag. Closing this issue out since the original issue has been addressed.

Thanks to @brettfo for driving fixes in this space

**Closed by abdulapopoola** 2024-01-25 17:15 UTC
Labels: T: bug 🐞, L: dotnet:nuget
