### ISSUE TITLE
Option to debounce version bumps

### ISSUE THREAD

**Issue by danielpowell4** [dependabot/dependabot-core#1951] opened 2020-06-23 16:54 UTC
First off, thanks for all you do. This tool has been a game-changer for my team!

In my experience, it's fairly common for many dependencies to cut versions rather often.

This means that many times a week I am accepting PRs from dependabot to bump versions for the same project.

Sometimes, like happened with the `aws-sdk-s3` gem [on June 10/11 2020](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/CHANGELOG.md#1680-2020-06-10), versions are (rightfully) yanked. As dependabot is _so_ on top of it we ended up in no man's land as happened for others in https://github.com/dependabot/feedback/issues/961

Though the latest and greatest is a good place to be, it would be nice if I could easily wait a configurable amount of days after a release is cut to have dependabot do its magic.

By "debounce" I mean something like an option for dependabot to "wait 2 days without a new version to file a PR"

**Comment by jeffwidman** [comment] 2022-11-24 11:18
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/3651.

**Closed by jeffwidman** 2022-11-24 11:18 UTC
Labels: T: feature-request, F: version-updates ⬆️, 💁 service
