### ISSUE TITLE
Dependabot update to single (poetry-managed) package unexpectedly removes packages from lockfile

### ISSUE THREAD

**Issue by DMRobertson** [dependabot/dependabot-core#6226] opened 2022-11-28 18:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Python (poetry)

### Manifest location and content before the Dependabot update

poetry.lock --- probably easiest to see the PR diff (linked below)

### dependabot.yml content

See https://github.com/matrix-org/synapse/blob/develop/.github/dependabot.yml

### Updated dependency

types-psycopg2, from 2.9.21.1 to 2.9.21.2 

### What you expected to see, versus what you actually saw

Expected:
- don't alter the dependency metadata in `poetry.lock` forpackages other than `types-psycopg2`
- update the locked version of `types-psycopg2`

Actual:
- All references to `importlib-metadata`, `importlib-resources`, `pkgutil-resolve-name`,  `tomli`, `typed-ast`, `typing-extensions` removed from `[package.dependencies]` sections
- `importlib-resources`, `pkgutil_resolve_name` and `typed-ast` no longer included in the locked environment
- types-psycopg2 successfully updated

### Native package manager behavior

```
2022-11-28 18:14:56 ✔  $ poetry update types-psycopg2
Updating dependencies
Resolving dependencies... (1.0s)

Writing lock file

No dependencies to install or update

$ git diff
diff --git a/poetry.lock b/poetry.lock
index d9e4803a5..c09151ff4 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -1448,7 +1448,7 @@ python-versions = "*"
 
 [[package]]
 name = "types-psycopg2"
-version = "2.9.21.1"
+version = "2.9.21.2"
 description = "Typing stubs for psycopg2"
 category = "dev"
 optional = false
@@ -1790,6 +1790,7 @@ constantly = [
 cryptography = [
     {file = "cryptography-38.0.3-cp36-abi3-macosx_10_10_universal2.whl", hash = "sha256:984fe150f350a3c91e84de405fe49e688aa6092b3525f407a18b9646f6612320"},
     {file = "cryptography-38.0.3-cp36-abi3-macosx_10_10_x86_64.whl", hash = "sha256:ed7b00096790213e09eb11c97cc6e2b757f15f3d2f85833cd2d3ec3fe37c1722"},
+    {file = "cryptography-38.0.3-cp36-abi3-macosx_10_12_universal2.whl", hash = "sha256:726e3a1bfee0e919b278c8f766fdcf1fe30f8e6feea590e3f248d3636b58ffb3"},
     {file = "cryptography-38.0.3-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl", hash = "sha256:bbf203f1a814007ce24bd4d51362991d5cb90ba0c177a9c08825f2cc304d871f"},
     {file = "cryptography-38.0.3-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:554bec92ee7d1e9d10ded2f7e92a5d70c1f74ba9524947c0ba0c850c7b011828"},
     {file = "cryptography-38.0.3-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:b1b52c9e5f8aa2b802d48bd693190341fae201ea51c7a167d69fc48b60e8a959"},
@@ -2813,8 +2814,8 @@ types-pillow = [
     {file = "types_Pillow-9.3.0.1-py3-none-any.whl", hash = "sha256:79837755fe9659f29efd1016e9903ac4a500e0c73260483f07296bd6ca47668b"},
 ]
 types-psycopg2 = [
-    {file = "types-psycopg2-2.9.21.1.tar.gz", hash = "sha256:f5532cf15afdc6b5ebb1e59b7d896617217321f488fd1fbd74e7efb94decfab6"},
-    {file = "types_psycopg2-2.9.21.1-py3-none-any.whl", hash = "sha256:858838f1972f39da2a6e28274201fed8619a40a235dd86e7f66f4548ec474395"},
+    {file = "types-psycopg2-2.9.21.2.tar.gz", hash = "sha256:bff045579642ce00b4a3c8f2e401b7f96dfaa34939f10be64b0dd3b53feca57d"},
+    {file = "types_psycopg2-2.9.21.2-py3-none-any.whl", hash = "sha256:084558d6bc4b2cfa249b06be0fdd9a14a69d307bae5bb5809a2f14cfbaa7a23f"},
 ]
 types-pyopenssl = [
     {file = "types-pyOpenSSL-22.1.0.2.tar.gz", hash = "sha256:7a350e29e55bc3ee4571f996b4b1c18c4e4098947db45f7485b016eaa35b44bc"},
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/matrix-org/synapse/pull/14558

Rich diff of the delta that dependabot proposed: 
![image](https://user-images.githubusercontent.com/8614563/204351545-81dd6e1c-e9c4-421e-aef2-c32d04c90576.png)

**Comment by DMRobertson** [comment] 2022-11-28 18:26
Apologies for the lack of minimal reproduction example.

We also saw this in https://github.com/matrix-org/synapse/pull/14561, https://github.com/matrix-org/synapse/pull/14562, https://github.com/matrix-org/synapse/pull/14563,  and https://github.com/matrix-org/synapse/pull/14564.

In https://github.com/matrix-org/synapse/pull/14558#issuecomment-1329073299 I speculated that this might be related to the recent release of poetry-core---but that could just be a coincidence: I'm not sure what version of poetry and poetry-core dependabot uses behind the scenes.

**Comment by cvitan** [comment] 2022-11-28 18:47
Seeing the same issue in multiple PR's/repos, common denominator seems to be that all `[package.dependencies]` with markers `python_version` or `python_full_version` are removed.

**Comment by dimbleby** [comment] 2022-11-28 19:14
it's speculation because I don't know how dependabot works, but I'd be suspicious of https://github.com/dependabot/dependabot-core/pull/6191

what you are seeing seems to be consistent with dependabot-poetry solving with a higher python requirement than is actually in your pyproject.toml

**Comment by caugner** [comment] 2022-11-29 20:44
Same issue here: https://github.com/mdn/yari/pull/7684/commits/13a43527931e77463de3ef8643a5a46d0ec86db3

**Comment by caugner** [comment] 2022-11-29 20:46
@jeffwidman Would you have a chance to look into whether this might be a regression caused by https://github.com/dependabot/dependabot-core/pull/6191, as speculated above? 🙏

**Comment by jeffwidman** [comment] 2022-11-29 23:16
👋 Sorry for the bug... clearly affecting a lot of folks. Myself or @pavera or someone else on the team will try to dig into this tomorrow, although as y'all know could take a few days to fix... won't know til we've looked into it.

**Comment by pavera** [comment] 2022-11-30 19:50
I've now deployed the fix for this issue. I'm going to close the issue for now, but if anyone sees that this is still occurring please re-open.

**Closed by pavera** 2022-11-30 19:50 UTC
Labels: T: bug 🐞, L: python:poetry, P1

**Comment by DMRobertson** [comment] 2022-12-01 14:00
We've just asked dependabot to recreate the PR I reported in the issue and the [diff](https://github.com/matrix-org/synapse/pull/14558/commits/a4ddd8638d7736f7eab75542ff04e2456947127b) looks good to me. Just wanted to drop a quick note to confirm all looks well.

Many thanks for the quick response!
