### ISSUE TITLE
Non-deterministic behavior for environment markers in requirements.txt

### ISSUE THREAD

**Issue by adamjstewart** [dependabot/dependabot-core#5300] opened 2022-06-23 05:37 UTC
**Package ecosystem**: pip

**Package manager version**: pip 22.1.2

**Language version**: python 3.7–3.10

**Manifest location and content before the Dependabot update**: https://github.com/microsoft/torchgeo/blob/main/requirements/required.txt

**dependabot.yml content**: https://github.com/microsoft/torchgeo/blob/main/.github/dependabot.yml

**Updated dependency**: numpy from 1.22.4 to 1.23.0

**What you expected to see, versus what you actually saw**: I have a single `requirements.txt` file listing all required dependencies. Unfortunately, newer versions of many of these dependencies have dropped support for older versions of Python which I still test. To handle this, I've added environment markers such as:
```
numpy==1.22.4;python_version>='3.8'
numpy==1.21.6;python_version=='3.7'
```
When the numpy 1.23.0 release came out, I would have expected dependabot to update the first line, since 1.23.0 does not support Python 3.7. However, dependabot instead updated the second line. Interestingly, dependabot made the right decision for a different dependency in https://github.com/microsoft/torchgeo/pull/621/files. I'm unsure how dependabot is deciding which line to update, but I would like more control (either always update the first line, or actually use pip to check to see if a new version is compatible with that environment marker).

**Native package manager behavior**: N/A

**Images of the diff or a link to the PR, issue, or logs**: https://github.com/microsoft/torchgeo/pull/622

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by adamjstewart** [comment] 2022-06-23 05:42
One possible workaround would be to keep a separate `requirements.txt` for older versions of Python that dependabot would not update. Unfortunately this isn't possible due to #5299.

**Comment by jeffwidman** [comment] 2023-02-04 07:47
👋 sorry for the slow reply.

This appears to be a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/3343

**Closed** 2023-02-04 07:48 UTC
Labels: T: bug 🐞, L: python:pip
