### ISSUE TITLE
Consider rewording description for dependabot recreate command

### ISSUE THREAD

**Issue by markcellus** [dependabot/dependabot-core#3449] opened 2021-04-06 17:21 UTC
When Dependabot opens a PR to upgrade a dependency, the PR description lists a set of commands that can be posted in a comment on the PR. Among these commands is:

> `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it

The wording "will recreate this PR" makes me think that Dependabot will close the PR and create another one. But it doesn't. So it may be good to change the wording in the description.

It appears that using `@dependabot recreate` has the same effect as using `@dependabot rebase` if no edits have been made to the branch. If this evaluation is correct,  this behavior should also be noted. If this isn't correct, perhaps it should still be noted as such to minimize confusion.

**Comment by mwaddell** [comment] 2022-01-29 18:37
See also #4652

**Comment by jeffwidman** [comment] 2022-11-24 09:06
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/6204 and #4652

**Closed by jeffwidman** 2022-11-24 09:06 UTC
Labels: T: feature-request, F: pull-requests

**Comment by markcellus** [comment] 2022-11-24 09:52
@jeffwidman thank you so much for working on this. Although this doesn't look like a duplicate of those tickets. Just to clarify, regardless of what the command is renamed to, that the surrounding documentation should intuitively and accurately describe what the command does behind the scenes. Technically, those two tickets can be resolved but still be documented but still be unclear, which doesn't resolve this issue.

**Comment by jeffwidman** [comment] 2022-11-24 12:02
If we were to rename it, we'd rewrite / tweak the docs for it.
