### ISSUE TITLE
Sign the Eclipse ECA

### ISSUE THREAD

**Issue by pmlopes** [dependabot/dependabot-core#2454] opened 2020-08-17 12:22 UTC
Projects under the Eclipse Foundation Governance require that pull requests are coming from authors that have signed the Eclipse ECA https://www.eclipse.org/legal/ECA.php

This checks voids any contributions from dependabot as they are signed off, but the email address is not listed on the ECA database.

Project maintainers will in most cases, reject the PR and re-create a new one to ensure that the contract is valid.

**Comment by jeffwidman** [comment] 2022-08-13 07:41
Related: https://github.com/dependabot/dependabot-core/issues/3849

**Comment by jeffwidman** [comment] 2022-11-01 06:45
Closing as a duplicate of #3849. 

Bots generally don't need to sign CLA/ECA's... the only question is how to guarantee the commit is coming from an approved bot (which is what #3849 tracks).

**Closed by jeffwidman** 2022-11-01 06:45 UTC
Labels: T: feature-request
