### ISSUE TITLE
Dependabot not opening a PR to update to node:17.4.0-alpine3.15 (Dockerfile)

### ISSUE THREAD

**Issue by TanguyChiffoleau** [dependabot/dependabot-core#4726] opened 2022-02-10 10:21 UTC
**Package ecosystem**
docker

**Manifest location and content prior to update**
[docker/Dockerfile](https://github.com/TanguyChiffoleau/Le-bot-en-JS/blob/3cd61fb3075b402669811d17f576fec671256489/docker/Dockerfile)

**dependabot.yml content**
[.github/dependabot.yml](https://github.com/TanguyChiffoleau/Le-bot-en-JS/blob/3cd61fb3075b402669811d17f576fec671256489/.github/dependabot.yml)

**Updated dependency**
node:17.4.0-alpine3.15

**What you expected to see, versus what you actually saw**
Dependabot should open a PR to update to node:17.4.0-alpine3.15, but thinks 17.3.0-alpine3.13 does not need an update

**Images of the diff or a link to the PR, issue or logs**

```logs
updater | INFO <job_282762569> Starting job processing
updater | INFO <job_282762569> Starting update job for TanguyChiffoleau/Le-bot-en-JS
updater | INFO <job_282762569> Checking if node 17.3.0-alpine3.13 needs updating
  proxy | 2022/02/10 09:59:04 [012] GET https://registry.hub.docker.com:443/v2/library/node/tags/list
  proxy | 2022/02/10 09:59:04 [012] 401 https://registry.hub.docker.com:443/v2/library/node/tags/list
  proxy | 2022/02/10 09:59:04 [014] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fnode%3Apull
  proxy | 2022/02/10 09:59:04 [014] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fnode%3Apull
  proxy | 2022/02/10 09:59:04 [016] GET https://registry.hub.docker.com:443/v2/library/node/tags/list
  proxy | 2022/02/10 09:59:05 [016] 200 https://registry.hub.docker.com:443/v2/library/node/tags/list
  proxy | 2022/02/10 09:59:05 [018] HEAD https://registry.hub.docker.com:443/v2/library/node/manifests/latest
  proxy | 2022/02/10 09:59:05 [018] 401 https://registry.hub.docker.com:443/v2/library/node/manifests/latest
  proxy | 2022/02/10 09:59:05 [020] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fnode%3Apull
  proxy | 2022/02/10 09:59:05 [020] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fnode%3Apull
  proxy | 2022/02/10 09:59:05 [022] HEAD https://registry.hub.docker.com:443/v2/library/node/manifests/latest
  proxy | 2022/02/10 09:59:05 [022] 200 https://registry.hub.docker.com:443/v2/library/node/manifests/latest
  proxy | 2022/02/10 09:59:05 [024] HEAD https://registry.hub.docker.com:443/v2/library/node/manifests/17.4.0
  proxy | 2022/02/10 09:59:05 [024] 401 https://registry.hub.docker.com:443/v2/library/node/manifests/17.4.0
  proxy | 2022/02/10 09:59:05 [026] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fnode%3Apull
  proxy | 2022/02/10 09:59:05 [026] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fnode%3Apull
  proxy | 2022/02/10 09:59:05 [028] HEAD https://registry.hub.docker.com:443/v2/library/node/manifests/17.4.0
  proxy | 2022/02/10 09:59:05 [028] 200 https://registry.hub.docker.com:443/v2/library/node/manifests/17.4.0
updater | INFO <job_282762569> Latest version is 17.3.0-alpine3.13
updater | INFO <job_282762569> No update needed for node 17.3.0-alpine3.13
updater | INFO <job_282762569> Finished job processing
```

**Comment by DunkinDonat** [comment] 2022-04-06 06:47
Hi,

same here. When I create a tag, which looks like this: **1.20.2-alpine3.15.1**. The tag contains two versions and if for one of these versions change, I want Dependabot to open a new merge request.

```docker
FROM registry.ag/web/nginx:1.20.2-alpine3.15.1

```

But if i create a new Tag like: **1.20.2-alpine3.15.3** Dependabot says:

```
[2022-04-05 06:51:58 +0000 tid=1ect class=DependencyUpdateJob] INFO  -- start
[2022-04-05 06:51:59 +0000 tid=1ect class=DependencyUpdateJob] INFO  -- [infrastructure12/my-radar=>docker] Fetching info for web/nginx
[2022-04-05 06:51:59 +0000 tid=1ect class=DependencyUpdateJob] INFO  -- [infrastructure12/my-radar=>docker]   web/nginx: 1.20.2-alpine3.15.1 is up to date
[2022-04-05 06:51:59 +0000 tid=1ect class=DependencyUpdateJob] INFO  -- done
```

Does someone know how to handle two or more versions in one tag?

**Comment by DunkinDonat** [comment] 2022-04-06 08:18
It seams that its parsing only one version.

\[2022-04-06 06:57:56 +0000 tid=1dv1 class=DependencyUpdateJob\] INFO -- \[infrastructure12/tech-radar=>docker\] updating web/nginx: 1.20.2alpine3.15.1 => 1.20.2

**Comment by jeffwidman** [comment] 2022-08-25 06:26
Duplicate of https://github.com/dependabot/dependabot-core/issues/4329

**Closed by jeffwidman** 2022-08-25 06:26 UTC
Labels: T: bug 🐞, L: docker
