### ISSUE TITLE
Docker: Golang Alpine Image Not being Bumped

### ISSUE THREAD

**Issue by errorhandler** [dependabot/dependabot-core#1604] opened 2020-01-06 03:51 UTC
It would appear that Dependabot doesn't support updating alpine versions with (for example) the Golang docker image. For example, it considers `golang:1.13.5-alpine3.10` to be the latest version whereas `golang:1.13.5-alpine3.11` exists.

**Comment by feelepxyz** [comment] 2020-01-06 16:30
@errorhandler do you have an example repo you're seeing this in? Just the dockerfile is enough for us to debug if that's easier.

**Comment by errorhandler** [comment] 2020-01-06 21:06
@feelepxyz I've created an example Dockerfile here: https://github.com/errorhandler/dependabot-golang

**Comment by feelepxyz** [comment] 2020-01-29 16:14
@errorhandler thanks for sending that over and sorry for the slow response! This is currently expected behaviour to keep the tags compatible. Here's the code that only selects tags with the same suffix: https://github.com/dependabot/dependabot-core/blob/master/docker/lib/dependabot/docker/update_checker.rb#L141

We should probably add the ability to parse the current alpine version and select tags based on this. Will tag this a future enhancement.

**Comment by deivid-rodriguez** [comment] 2022-11-13 23:02
I think this should be handled by either https://github.com/dependabot/dependabot-core/issues/4329 or https://github.com/dependabot/dependabot-core/issues/5708.

Not sure but I guess we should keep both of the above, because while I consider #4329 a feature request ("I want to get updates for both versions"), #5708 feels more like a bug ("If a tag contains two versions, I get no updates").

This one can fit either of those, so please subscribe to them, since I'll close this one in favor of those, since they have a bit more discussion.

Thanks!

**Closed by deivid-rodriguez** 2022-11-13 23:02 UTC
Labels: T: feature-request, L: docker
