### ISSUE TITLE
Support GitHubs enable-auto-merge natively

### ISSUE THREAD

**Issue by huehnerlady** [dependabot/dependabot-core#4143] opened 2021-08-17 07:33 UTC
Hi, since February the [auto-merge](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) function is now generally available.

I have seen [here](https://github.com/dependabot/dependabot-core/issues/2268#issuecomment-854864420) that you can create some github action to set that flag in the dependabot pull requests. But why can't dependabot do that himself?

I would see it as a setting in`dependabot.yml`. There should be an option, eg. `enable-auto-merge` with `merge`, `squash`, `rebase` and `disabled` as option, `disabled` being the default.

Please add this functionality to dependabot

**Comment by lucacome** [comment] 2021-08-17 19:03
Unfortunately, that action doesn't even work with protected branches.

**Comment by asciimike** [comment] 2021-08-24 14:48
Closing as a dupe of #1973 (which has a longer discussion and history of this request).

**Closed by asciimike** 2021-08-24 14:48 UTC
Labels: T: feature-request

**Comment by huehnerlady** [comment] 2021-08-24 14:56
@asciimike I am confused, for me that is something different. the other one talks about the PRs are merged without a review (at least that is what I understand from the issue). Also as the other issue is open since mid-2020 and the auto-merge feature from Github is added early 2021, I would ask you to please reopen this issue as it is different.

This issue is about the new feature to add auto-merge, so that the PR is merged once it is approved and checks have passed. It is NOT the intention to also skip the approval process

**Comment by asciimike** [comment] 2021-08-24 15:17
Dependabot Preview's auto-merge could be set up to respect approval and respected checks as well (see [docs](https://dependabot.com/docs/config-file/#automerged_updates)), so functionally it's the same feature request, regardless of whether it's "have Dependabot enable GitHub's auto-merge" or "let Dependabot wait for checks and approval and then merge."

IMO, the functionality of "let Dependabot trigger an Action which can approve, merge, etc." is better for developers and Dependabot because it is more flexible with fairly low overhead (if you want to enable auto-merge on certain dependencies, or patch versions, or whatever, you can do that with a pretty limited amount of config, as you've already linked to; if you only want to merge on Tuesdays or when the moon is full or whatever, that's also possible, but it wouldn't be in a `dependabot.yml` implementation).

**Comment by huehnerlady** [comment] 2021-08-25 07:02
I was just thinking that with the auto-merge there is quite a bit of discussiong around the moral, and so I was hoping to detach this feature request. 

It also seems the other ones are more discussing workarounds than having a solution from dependabot, and as I am not interested in workarounds but in a solution from dependabot I was thinking maybe start small?

**Comment by zteater** [comment] 2021-08-29 15:03
@asciimike I agree with @huehnerlady's perspective, but disagree in their approach.

From my perspective, Dependabot should not be circumventing how my repository is setup. When Dependabot raises a PR, the PR should be treated as no different than if a human had raised it. If I have enabled automatic merging, then I've already accepted the risks and it should flow through just as any other PR.

**Comment by asciimike** [comment] 2021-08-30 15:09
> From my perspective, Dependabot should not be circumventing how my repository is setup. When Dependabot raises a PR, the PR should be treated as no different than if a human had raised it. If I have enabled automatic merging, then I've already accepted the risks and it should flow through just as any other PR.

I agree and don't plan to change it: if you have GitHub auto-merge enabled, Dependabot PRs will respect those settings and be merged accordingly
