### ISSUE TITLE
private_source_authentication_failure  with public PyPi

### ISSUE THREAD

**Issue by okainov** [dependabot/dependabot-core#2556] opened 2020-09-25 08:11 UTC
Python / PyPi (note it's not with private registry, but normal public pyPi)

Expected: **No error**

https://github.com/okainov/munich-scripts/issues/48

Logs:

```
fetcher | INFO <job_48723769> Finished job processing
  proxy | time="2020-09-25T08:04:45Z" level=info msg="proxy starting" commit=c5f79a43943044613474bf0c4b592cd1afbc064e
  proxy | 2020/09/25 08:04:45 Listening (:1080)
updater | yarn config v1.22.5
updater | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
updater | Done in 0.02s.
updater | I, [2020-09-25T08:04:47.394766 #72]  INFO -- sentry: ** [Raven] Raven 3.1.0 ready to catch errors
updater | INFO <job_48723769> Starting job processing
updater | INFO <job_48723769> Starting update job for okainov/munich-scripts
updater | INFO <job_48723769> Checking if elasticsearch  needs updating
  proxy | 2020/09/25 08:05:10 [004] GET https://pypi.python.org:443/simple/elasticsearch/
  proxy | 2020/09/25 08:05:10 [004] 403 https://pypi.python.org:443/simple/elasticsearch/
  proxy | 2020/09/25 08:05:10 [006] GET https://pypi.python.org:443/simple/
  proxy | 2020/09/25 08:05:10 [006] 403 https://pypi.python.org:443/simple/
updater | INFO <job_48723769> Handled error whilst updating elasticsearch: private_source_authentication_failure {:source=>"https://pypi.python.org/simple/"}
updater | INFO <job_48723769> Checking if apscheduler  needs updating
  proxy | 2020/09/25 08:05:30 [010] GET https://pypi.python.org:443/simple/apscheduler/
  proxy | 2020/09/25 08:05:30 [010] 403 https://pypi.python.org:443/simple/apscheduler/
  proxy | 2020/09/25 08:05:30 [012] GET https://pypi.python.org:443/simple/
  proxy | 2020/09/25 08:05:30 [012] 403 https://pypi.python.org:443/simple/
updater | INFO <job_48723769> Handled error whilst updating apscheduler: private_source_authentication_failure {:source=>"https://pypi.python.org/simple/"}
updater | INFO <job_48723769> Checking if python-telegram-bot 12.4.2 needs updating
  proxy | 2020/09/25 08:05:51 [016] GET https://pypi.python.org:443/simple/python-telegram-bot/
  proxy | 2020/09/25 08:05:51 [016] 403 https://pypi.python.org:443/simple/python-telegram-bot/
  proxy | 2020/09/25 08:05:51 [018] GET https://pypi.python.org:443/simple/
  proxy | 2020/09/25 08:05:51 [018] 403 https://pypi.python.org:443/simple/
updater | INFO <job_48723769> Handled error whilst updating python-telegram-bot: private_source_authentication_failure {:source=>"https://pypi.python.org/simple/"}
updater | INFO <job_48723769> Checking if cmreshandler  needs updating
  proxy | 2020/09/25 08:06:11 [022] GET https://pypi.python.org:443/simple/cmreshandler/
  proxy | 2020/09/25 08:06:11 [022] 403 https://pypi.python.org:443/simple/cmreshandler/
  proxy | 2020/09/25 08:06:11 [024] GET https://pypi.python.org:443/simple/
  proxy | 2020/09/25 08:06:11 [024] 403 https://pypi.python.org:443/simple/
updater | INFO <job_48723769> Handled error whilst updating cmreshandler: private_source_authentication_failure {:source=>"https://pypi.python.org/simple/"}
updater | INFO <job_48723769> Checking if requests  needs updating
  proxy | 2020/09/25 08:06:31 [028] GET https://pypi.python.org:443/simple/requests/
  proxy | 2020/09/25 08:06:31 [028] 403 https://pypi.python.org:443/simple/requests/
  proxy | 2020/09/25 08:06:31 [030] GET https://pypi.python.org:443/simple/
  proxy | 2020/09/25 08:06:31 [030] 403 https://pypi.python.org:443/simple/
updater | INFO <job_48723769> Handled error whilst updating requests: private_source_authentication_failure {:source=>"https://pypi.python.org/simple/"}
updater | INFO <job_48723769> Checking if sqlalchemy  needs updating
  proxy | 2020/09/25 08:06:51 [034] GET https://pypi.python.org:443/simple/sqlalchemy/
  proxy | 2020/09/25 08:06:51 [034] 403 https://pypi.python.org:443/simple/sqlalchemy/
  proxy | 2020/09/25 08:06:51 [036] GET https://pypi.python.org:443/simple/
  proxy | 2020/09/25 08:06:51 [036] 403 https://pypi.python.org:443/simple/
updater | INFO <job_48723769> Handled error whilst updating sqlalchemy: private_source_authentication_failure {:source=>"https://pypi.python.org/simple/"}
updater | INFO <job_48723769> Finished job processing
```

**Comment by jorrit-wehelp** [comment] 2020-09-25 10:42
This is duplicate of https://github.com/dependabot/dependabot-core/issues/2550

**Comment by hmarr** [comment] 2020-09-25 11:42
Thanks. Closing in favour of #2550. Please subscribe to that issue for updates.

**Closed by hmarr** 2020-09-25 11:42 UTC
Labels: T: bug 🐞
