### ISSUE TITLE
Issue with alpine specifier in Dockerfile multi-stage

### ISSUE THREAD

**Issue by edahlseng** [dependabot/dependabot-core#2059] opened 2019-12-30 19:49 UTC
We have a Dockerfile using multiple stages to build and produce an artifact:
```Dockerfile
FROM node:10.16.3 as builder

...

FROM node:10.16.2-alpine as artifact

...
```
In our most recent update from Dependabot, it looks like the alpine specifier was dropped:
```Dockerfile
FROM node:10.18.0 as builder

...

FROM node:10.18.0 as artifact

...
```
(You'll notice that originally the patch version for our builder and artifact image was slightly different. I don't know if that contributed to this bug or not. I'll manually update the versions to the same patch version today and will monitor future updates to see if those work!)

This may be related to dependabot/feedback#406.

**Comment by infin8x** [comment] 2020-07-20 16:21
Duplicate of #2179

**Closed by infin8x** 2020-07-20 16:21 UTC
