### ISSUE TITLE
checking now, hold tight!

### ISSUE THREAD

**Issue by nemchik** [dependabot/dependabot-core#1984] opened 2020-05-05 20:23 UTC
Seemingly similar issues: https://github.com/dependabot/feedback/issues/713 https://github.com/dependabot/feedback/issues/319

I have a repo https://github.com/linuxserver/docker-readme-sync which has been added to Dependabot, but the web UI just shows:

> checking now, hold tight!

**Comment by levrik** [comment] 2021-02-22 08:21
Having the same issue every Monday when I want to merge a few PRs. It's then stuck in `Checking now` and the already open PRs aren't re-based. Very annoying.

**Comment by jeffwidman** [comment] 2022-08-09 03:59
I'm going to close this, as it's been over 2 years since this issue had a useful bug report and our internal infrastructure has changed drastically since then. My apologies that we weren't able to investigate the root cause when this was originally filed. If you still encounter issues, please file a new ticket so we can investigate.

**Closed by jeffwidman** 2022-08-09 03:59 UTC
Labels: T: bug 🐞, F: pull-requests
