### ISSUE TITLE
[Python] Doesn't handle well poetry dependencies depending on Python version

### ISSUE THREAD

**Issue by alexpdp7** [dependabot/dependabot-core#2503] opened 2020-09-04 16:17 UTC
**Package manager/ecosystem**

Python Poetry.

https://github.com/alexpdp7/caw/blob/master/pyproject.toml#L14

My project supports Python 3.6, 3.7 and 3.8, hence:

```
python = ">=3.6, <3.8"
```

The project uses dataclasses, so on 3.6 I install a backport:

```
dataclasses = { version = "0.7", python = ">=3.6,<3.7" }
```

I think this worked OK, but recently Dependabot started spamming me with issues:

https://github.com/alexpdp7/caw/issues/41

, which seem to complain about this issue.

**Comment by chris48s** [comment] 2020-09-10 20:33
Dependabot has also recently started failing with 

```
[SolverProblemError]
The current project's Python requirement (^3.6) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7
```

on one of my repos too ( https://github.com/chris48s/mark-sideways ), although it is caused by effectively the same condition in one of my transitive dependencies: https://github.com/willmcgugan/rich/blob/a424fafc5654346b5d6e2db28ad19aad10040581/pyproject.toml#L27

I guess this is a manifestation of https://github.com/python-poetry/poetry/issues/2386 as opposed to a bug in dependabot itself.

Strangely, I'm unable to reproduce this locally with python 3.8/poetry 1.0.10 (although the last post in that linked issue says this is still an issue in that build, apparently)

What version of poetry does dependabot use? (I don't think the error log on my repo tells me)

**Comment by jurre** [comment] 2020-10-06 10:20
We're currently on Poetry 1.0.10, and I'm in the process of upgrading to to 1.1.1 @chris48s

**Comment by chris48s** [comment] 2020-10-07 19:43
Hopefully that upgrade will resolve it :crossed_fingers:

**Comment by chris48s** [comment] 2020-10-09 08:46
I've now had a successful dependabot run on that repo

**Comment by jurre** [comment] 2020-10-09 09:12
> I've now had a successful dependabot run on that repo

Happy to hear it! Let's keep this open for a bit longer to make sure it's really resolved, please let me know if you spot anything weird

**Comment by alexpdp7** [comment] 2020-10-09 09:21
It seems to be also working for me.

**Comment by jurre** [comment] 2020-10-09 09:24
> It seems to be also working for me.

Awesome! Alright I'm going to close this out for now, feel free to re-open if needed.

**Closed by jurre** 2020-10-09 09:24 UTC
Labels: T: bug 🐞
