### ISSUE TITLE
Dependencies listed under `<artifactItems>` are not updated 

### ISSUE THREAD

**Issue by nbauma109** [dependabot/dependabot-core#5826] opened 2022-10-02 18:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### What you expected to see, versus what you actually saw

I expect to see the dependencies updated not only under dependencies node but also artifactItems.

Dependencies updated here (as expected) :

```xml
<dependencies>
    <dependency>
        <groupId>com.eclipsesource.minimal-json</groupId>
        <artifactId>minimal-json</artifactId>
        <version>0.9.5</version>
    </dependency>
    <dependency>
        <groupId>org.ow2.asm</groupId>
        <artifactId>asm</artifactId>
        <version>9.4</version>
     </dependency>
</dependencies>
```

But versions have been left behind here, breaking the build :

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.eclipsesource.minimal-json</groupId>									 
                                    <artifactId>minimal-json</artifactId>									 
                                    <version>0.9.4</version>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>lib</outputDirectory>
                                    <destFileName>json.jar</destFileName>
                                </artifactItem>
				<artifactItem>
                                    <groupId>org.ow2.asm</groupId>
                                    <artifactId>asm</artifactId>
                                    <version>9.1</version>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>lib</outputDirectory>
				</artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
</build>
```

**Comment by deivid-rodriguez** [comment] 2022-10-03 18:13
Thanks for reporting this @nbauma109! A PR created by dependabot due to missing manifest updates seems indeed like a bug. Would you be able to share (or create) a public repository reproducing this? That would make it easier for us to have a look at what's wrong.

**Comment by nbauma109** [comment] 2022-10-03 20:00
I merged this PR but didn't notice at first that it left the other version behind https://github.com/nbauma109/ecd/pull/8

**Comment by yeikel** [comment] 2023-04-15 03:49
It is worth mentioning that if you extract these dependencies versions to a property, the problem won't happen

**Comment by nbauma109** [comment] 2023-04-15 05:55
Yes I've already put in place a dependenciesManagement to have the version at a single location (no version property needed)

**Comment by yeikel** [comment] 2023-04-15 16:05
> Yes I've already put in place a `<dependencyManagement>` to have the version at a single location (no version property needed)
> 
> https://github.com/nbauma109/ecd/blob/564da3d6f1ce256417c69d4e2c9450b2e737d7a9/pom.xml#L316
> 

You still have   org.bitbucket.mstrobel:* as two separate definitions. Are these two released independently?

**Comment by nbauma109** [comment] 2023-04-15 17:52
No, they're released simultaneously, but I purposedly didn't extract the version to a property because I have a workaround script to update versions in osgi files which are not supported by dependabots, and it will stop working if the version is in a property.

**Comment by pw-lehre** [comment] 2023-11-23 16:41
I have almost the same issue as @nbauma109. Though for me, the dependency must not be added to the classpath, so declaring it as normal dependency using a version property isn't an option.

I don't know ruby unfortunately, but is this a complicated feature? To me it seems we'd just need a new CSS selector (`artifactItems > artifactItem`) here:
https://github.com/dependabot/dependabot-core/blob/77bd32723fb202b9ec4861574347d258c446162f/maven/lib/dependabot/maven/file_parser.rb#L44-L68

**Closed** 2024-03-26 17:07 UTC
Labels: T: bug 🐞, L: java:maven, F: configuration-file
