### ISSUE TITLE
Pub package updates generate a bigger diff than needed in pubspec.lock

### ISSUE THREAD

**Issue by tsimbalar** [dependabot/dependabot-core#6929] opened 2023-03-28 16:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pub

### Package manager version

N/A

### Language version

Flutter 3.7.7 / Dart 2.19.4

### Manifest location and content before the Dependabot update

`pubspec.yaml` / `pubspec.lock` provided as gist : 
https://gist.github.com/tsimbalar/287555107604e5cf87addf0beb826e97

### dependabot.yml content

```yaml
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: koagithub-svc-account
    password: ${{secrets.DEPENDABOT_GH_TOKEN_KOA}}
updates:
  - package-ecosystem: pub
    directory: "/"
    registries:
      - github
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 20

```

### Updated dependency

Bump `webview_flutter` from 3.0.4 to 4.0.7

### What you expected to see, versus what you actually saw

**I expected :** 
minor changes in `pubspec.lock` that only updated `webview_flutter` (and possibly its dependencies)

**I actually saw**
- lots of changes on unrelated packages in `pubspec.lock`
- changes removing the `sha256` property in `pubspec.lock`
- changes to the `url` from `pub.dev` to `pub.dartlang.org`

This means the update introduces many changes that might get to Production in stealth mode and introduce breaking changes (maybe those dependency bumps required also changes in native files related to iOS or Android for instance ... but because the update happened under the hood, I didn't notice it)

![image](https://user-images.githubusercontent.com/160544/228311071-b7db3611-0848-4044-a553-8819f0e4fe1d.png)

### Native package manager behavior

if I run : 

```
flutter pub add webview_flutter
```

I get a much smaller diff
![image](https://user-images.githubusercontent.com/160544/228311528-c2c5ec92-3859-4a44-8ecd-3fd0f2622290.png)

**Comment by jeffwidman** [comment] 2023-03-28 18:32
I think updating our bundled `pub` will help with the SHA issue:
* https://github.com/dependabot/dependabot-core/pull/6454

Also related and possibly a dupe of:
* https://github.com/dependabot/dependabot-core/issues/6867

**Comment by tsimbalar** [comment] 2023-03-29 07:46
Thanks @jeffwidman for a fast reply 🙌 

Just to clarify, I think the `sha256` and `url`s would be fixed by the existing issues you mention, but I think that this wouldn't solve the part that more dependencies are updated than what we would expect.

My suspicion is that something somewhere currently does the equivalent of `flutter pub upgrade {dependency}` , but this comment updates more things than what we'd like, and the way to change the minimum amount of things seems to be `flutter pub add {dependency}`

**Closed** 2023-05-11 15:25 UTC
Labels: T: bug 🐞, L: dart:pub

**Comment by tsimbalar** [comment] 2023-05-13 19:16
thanks @jakecoffman for the fix !
Is there an estimation on when we can expect those changes to be live on GitHub ?

**Comment by tsimbalar** [comment] 2023-05-15 20:52
Just enabled it on our project, and seems to work as advertised ! 
thanks for the fix !
