### ISSUE TITLE
github-actions triggered by dependabot can't post comments.

### ISSUE THREAD

**Issue by jvesely** [dependabot/dependabot-core#3563] opened 2021-04-26 14:05 UTC
Trying to post a comment to the PR results in 403 Forbidden.
Re-running the same actions/workload completes successfully.

The attempt to post an issue comment succeeds/fails based on who the initiator of the action is.
It is strange dependabot itself can post comments/open PRs/... .

Example failure: https://github.com/PrincetonUniversity/PsyNeuLink/pull/2026/checks?check_run_id=2435632161#step:5:28
Restarted by user: https://github.com/PrincetonUniversity/PsyNeuLink/pull/2026/checks?check_run_id=2439009138#step:5:1

**Comment by asciimike** [comment] 2021-04-26 14:48
Thanks for filing! I'm going to close this as a dupe of: #3253, as it's the same core issue (`pull_request` has no secrets and a read-only token). I recommend https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-824361724 as a reasonable workaround.

As for why re-runs work, those are triggered by a human user as opposed to Dependabot, therefore they're allowed.

**Closed by asciimike** 2021-04-26 14:48 UTC
Labels: T: bug 🐞
