### ISSUE TITLE
Error: Dependabot couldn't fetch all your path-based dependencies

### ISSUE THREAD

**Issue by jlowcs** [dependabot/dependabot-core#5100] opened 2022-05-05 14:27 UTC
**Package ecosystem**
npm
**Package manager version**
npm 8.1.2
**Language version**
node 16.13.2
**Manifest location and content before the Dependabot update**
`/package.json` contains private dependencies and a path-based dependency (`config/lint-rules/index.js` does exist):
```
  "eslint-plugin-internal-rules": "file:./config/lint-rules",
```
**dependabot.yml content**
```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.ACCESS_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - npm-github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
```
**What you expected to see, versus what you actually saw**
Before recently (2 days at max), dependabot was running properly.
But then, it started failing in some of our private repositories that have private dependencies and a path-based dependency.
![image](https://user-images.githubusercontent.com/3777724/166945110-995d639f-74ec-4e90-ad6d-4cfe3a9205d4.png)

**Comment by jlowcs** [comment] 2022-05-05 14:28
might be related to https://github.com/dependabot/dependabot-core/issues/5099

**Comment by jlowcs** [comment] 2022-05-06 10:18
Apparently adding a `package.json` file to the folder fixes the issue. That was not necessary before though...

**Comment by jakecoffman** [comment] 2022-05-16 14:07
#5099 is fixed, would you mind trying to reproduce the issue again and see if that resolved it?

**Comment by jeffwidman** [comment] 2023-02-03 15:37
Closing due to lack of user response.

**Closed by jeffwidman** 2023-02-03 15:37 UTC
Labels: T: bug 🐞, L: javascript:npm

**Comment by groenroos** [comment] 2024-01-24 13:14
For anyone arriving here from Google like I did:

- If your local dependency points directly to a file (i.e. `"foo": "file:./lib/foo.js"`), Dependabot will fail to load it regardless of the format of the path (`file:lib`, `file:./lib`...) - even though these all work fine in `npm` itself
- Instead, your local dependency must be organised into its own directory, called `index.js`, and have a `package.json` next to it like so:

```
{
	"name": "foo",
	"main": "index.js"
}
```

After that, your main `package.json` must import the local dependency with a directory path (and not a file path): `"foo": "file:./lib/foo"`. These changes unblocked Dependabot updates for us.
