### ISSUE TITLE
Parse Elixir sub-dependencies

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#820] opened 2018-11-30 13:24 UTC
The work for this needs to be done in https://github.com/dependabot/dependabot-core/blob/master/hex/helpers/lib/parse_deps.exs

**Comment by jeffwidman** [comment] 2023-03-10 17:32
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/1747. I realize that one is newer, but it also has more info than this one.

**Closed by jeffwidman** 2023-03-10 17:32 UTC
Labels: T: feature-request, L: elixir:hex, F: language-support
