### ISSUE TITLE
Docker image is huge

### ISSUE THREAD

**Issue by LeoColomb** [dependabot/dependabot-core#946] opened 2019-01-22 11:33 UTC
[dependabot/dependabot-core](https://hub.docker.com/r/dependabot/dependabot-core/) image from [Dockerfile](https://github.com/dependabot/dependabot-core/blob/426fff73823cd27c6a65e1f220e936262cd07a96/Dockerfile) is amazing!

But it now exceeds [1 GB](https://hub.docker.com/r/dependabot/dependabot-core/tags), which is starting to be huge. ([why](https://developers.redhat.com/blog/2016/03/09/more-about-docker-images-size/) it [matters](https://semaphoreci.com/blog/2018/03/14/docker-image-size.html))

Some suggestions to optimize Dependabot's image (sorted by difficulty):
- [ ] Follow basic `apt` recommandations:
  * Use of `apt-get update` should be paired with `rm -rf /var/lib/apt/lists/*` in the same layer.
  * Use of `apt-get upgrade` must be avoided in a Dockerfile. ([ref](http://crosbymichael.com/dockerfile-best-practices-take-2.html)).
  * Consider using a `--no-install-recommends` when `apt-get` installing packages.
- [ ] Exclude development dependencies when distributing "production" image (#851).
  * Can be optimized easily with `build` scripts and an environment variable.
- [ ] Use [stages](https://docs.docker.com/develop/develop-images/multistage-build/) to build helpers and avoid excessive binaries distribution.
  * For example (if I'm correct) `golang` is not required to _run_ the helpers once built.
- [ ] Switch to a smaller base image for the last stage, commonly to Alpine.

**Comment by LeoColomb** [comment] 2019-01-31 15:20
Coming back to this issue (my system regularly complains this is taking too much disk space! 😱).

Actually I wonder if dividing the docker image wouldn't be even cleaner:
* Native helper isolation;
* Much (much) smaller image.

The only downside is that running all managers updaters will not be possible in the same container. (Is this a real downside? Are you used to run multiple manager-type updater in the same container?)

If interested, I can make PRs to iterate over this idea.

**Comment by greysteil** [comment] 2019-01-31 15:33
I know @hmarr has some plans for this - can you share?

**Comment by hmarr** [comment] 2019-01-31 17:07
@LeoColomb yes, we're planning exactly that! This is actually one of the main motivations for splitting up each language / package manager into independent top-level gems in dependabot-core. Once that big refactor is finished (we're super close), the next stage is to produce much leaner Docker images for each package manager, and use multi-stage builds to further trim the unnecessary fat.

If we use multi-stage builds to set up each of the native helpers, it should also be pretty trivial to re-combine them all into one big image, which would be a nice feature for people running this from home / their own servers.

**Comment by hmarr** [comment] 2019-01-31 17:19
If you're up for helping out, that'd be awesome 🙌. I'll ping you once we're ready to start splitting up the Dockerfiles.

**Comment by LeoColomb** [comment] 2019-01-31 21:50
Cool! Sure, I'm up for this! 🎉 👍

**Comment by rajivshah3** [comment] 2019-02-02 04:33
https://github.com/dependabot/dependabot-core/blob/75b5c17130b05f39f411ebcc46d3b7bd20692817/Dockerfile#L73-L80

If we can move the base image to Alpine or Debian, maybe we can also replace this with the [node image](https://hub.docker.com/_/node)?

**Comment by rajivshah3** [comment] 2019-02-02 19:21
@LeoColomb have you already started on the recommendations mentioned in https://github.com/dependabot/dependabot-core/issues/946#issue-401722030? If not I'd be happy to try it

**Comment by LeoColomb** [comment] 2019-02-02 20:38
@rajivshah3 Yes, [I have](https://github.com/LeoColomb/dependabot-core/tree/fix/docker-size), but the last two tasks in the checklist are very difficult to implement:
* Languages are sometimes cross-required (eg. npm from Node for ELM) making hard to extract entirely these requirements into stages for builds;
* More than half of the installed languages just can't be extracted since they are required to run helpers (eg. PHP);
* Moving from Ubuntu to Alpine actually require a lot of rewrites, especially because the languages compilations may require more attention (just take a look at the respective official images to get an idea).

That's why [splitting seems much more relevant](https://github.com/dependabot/dependabot-core/issues/946#issuecomment-459383019), on the one hand because using official languages docker images will be easier, on the other hand required languages will be isolated and won't pollute other Dependabot images, all of this keeping the same base for runs which can helps the cache for the docker images.

**Comment by alexanderadam** [comment] 2019-07-23 15:22
Also if there is currently the Docker refactoring going on: [it is considered good practice to switch to an unprivileged user within the Docker image](https://snyk.io/blog/10-docker-image-security-best-practices/).

**Comment by hmarr** [comment] 2019-07-25 15:36
@alexanderadam +1 on that. We use an unprivileged user internally (we just use the dependabot-core image as a base image), but I'd also like the base image to start out with the non-root user wherever possible.

**Comment by PombeirP** [comment] 2019-09-11 20:26
Has anyone considered using [Nix](https://nixos.org/nix/) to create a reproducible build environment, which also happens to be much lighter (and runs on the metal on Macs too)? I'd be up to create a PR that sets up the environment to support all languages supported by dependabot-core (and would probably get set up in less time than Docker without the need to set up tens of volumes).

FWIW, Nix has been around since 2005 and has several hundreds of PRs merged every month, so the community can be said to be quite active.

Let me know if this would be interesting or if you have any questions.

**Comment by hmarr** [comment] 2019-09-17 10:48
Hi @PombeirP! I'm a big fan of Nix's approach. That said, we aren't able to support a migration to Nix right now. It'd represent a fairly large change to our build process, and we don't the capacity to make that change on our side given all the other things we have on our plate, and I'd rather not have two separate build processes in this project. Additionally, while in some ways inferior, Docker is a much more widely used project and therefore more accessible to wider audience.

**Comment by alexanderadam** [comment] 2019-11-17 13:05
@stale this is still relevant…

**Comment by LeoColomb** [comment] 2020-01-17 09:45
Still relevant.

**Comment by robcharlwood** [comment] 2020-02-19 10:55
+1

**Comment by alexanderadam** [comment] 2020-04-19 15:54
Still relevant.

**Comment by Olegt0rr** [comment] 2021-04-12 11:50
Any news? The issue looks like abandoned :(

**Comment by jurre** [comment] 2021-04-12 12:32
Some work is being done [here](https://github.com/dependabot/dependabot-core/pull/3398#issuecomment-817680050) to improve some of the layers, but the actual solution here would be to split up the images per ecosystem. We've been wanting to do that for a long time, but unsure when we'll be able to prioritize it.

**Comment by LeoColomb** [comment] 2021-04-12 12:48
> for a long time

Very long time 😉 

@Olegt0rr I've submitted a PR a bit more than a year ago to split per ecosystem: https://github.com/dependabot/dependabot-core/pull/986
I stopped keeping it up to date (because, a year, you know), but you can use it as a base. 🙂

**Comment by PeterDaveHello** [comment] 2021-06-14 14:38
It's now 1.22GB compressed

![image](https://user-images.githubusercontent.com/3691490/121906267-890e4b00-cd5d-11eb-98dc-837fd7965923.png)

The extracted size is pretty larger > 4GB 😱 

```
$ docker images
REPOSITORY                         TAG             IMAGE ID       CREATED             SIZE
dependabot/dependabot-core         latest          aa25fd520c04   About an hour ago   4.21GB
```

Hopefully #3896 & #3897 will make it a little bit smaller ...

**Comment by mattt** [comment] 2022-05-09 12:28
I'm happy to report that my recent work in #5024 to refactor our build automation with [Earthly](https://earthly.dev) should allow us to easily split up our Docker image by ecosystem.

For example, in [this commit](https://github.com/dependabot/dependabot-core/pull/5024/commits/967e2720635aceab3bf26788693c575de4350b75) adds a `+docker` target to the `npm_and_yarn` ecosystem, which can be built independently of the core image. 

Comparing the uncompressed sizes of each, we can produce an image ~5x smaller. A corresponding Maven image, which doesn't have any system dependencies or native helpers is even smaller.

```console
$ docker image list
dependabot/dependabot-core-npm_and_yarn ... 738MB
dependabot/dependabot-core-maven        ... 541MB
dependabot/dependabot-core              ... 3.52GB
```

**Comment by jakecoffman** [comment] 2023-02-10 12:56
The Docker images are now broken out by ecosystem making them much smaller. We'll continue to work to make and keep them as small as possible.

**Closed by jakecoffman** 2023-02-10 12:56 UTC
Labels: T: feature-request, F: infrastructure
