### ISSUE TITLE
Option to make PRs for a group of dependencies

### ISSUE THREAD

**Issue by DenBond7** [dependabot/dependabot-core#6108] opened 2022-11-11 11:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello. I'm an Android Developer. In Android, we have a lot of dependencies that are grouped. It means they should be updated at the same time, not one by one like `Dependabot` does it.

For example, Please look at [these dependencies](https://developer.android.com/jetpack/androidx/releases/test#espresso-3.5.0). **Version = 3.5.0**
It would be nice to have

```gradle
androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-intents:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-web:3.5.0' //updated
```

instead of this one

```gradle
androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.4.0'
androidTestImplementation 'androidx.test.espresso:espresso-intents:3.4.0'
androidTestImplementation 'androidx.test.espresso:espresso-web:3.4.0'
```

In most cases, updating only one dependency produces compilation or runtime issues.

I read https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file but didn't find settings that can help.

Maybe we can use something similar to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

For example

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    grouped:
      - group-name: "'androidx.test.espresso"
      - group-name: "'androidx.test.*"
     
```

**Comment by TWiStErRob** [comment] 2022-11-11 11:43
Duplicate of https://github.com/dependabot/dependabot-core/issues/2203 and https://github.com/dependabot/dependabot-core/issues/1190, tracked in https://github.com/github/roadmap/issues/148

**Comment by jeffwidman** [comment] 2022-11-14 21:59
Yep, thanks @TWiStErRob !

FWIW, This is definitely on our radar, it's a common request, and hopefully one we tackle in the not-too-distant-future. No promises though.

**Closed by jeffwidman** 2022-11-14 21:59 UTC
Labels: T: feature-request

**Comment by TWiStErRob** [comment] 2022-11-15 15:46
btw, @jeffwidman, since #1190 is locked, people cannot upvote it anymore! 😞
... and https://github.com/github/roadmap/issues/148 is also restricted to collaborators.
cc @exvuma

**Comment by jeffwidman** [comment] 2022-11-15 17:13
Thanks, I unlocked https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1315623277, hopefully the conversation stays polite and we can leave it that way.

For the roadmap, well, _exvuma has moved on from GitHub and I don't have access to editing that roadmap issue either, so for now we'll just direct folks to subscribe to #1190.
