### ISSUE TITLE
Artifactory private nuget package source authentication

### ISSUE THREAD

**Issue by vadimi** [dependabot/dependabot-core#8887] opened 2024-01-24 17:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

```
registries:
  nuget-public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

  my-artifactory:
    type: nuget-feed
    url: https://xyz.jfrog.io/artifactory/api/nuget/v3/nuget-local
    username: ${{secrets.ART_USER}}
    password: ${{secrets.ART_PASS}}
```

### What you expected to see, versus what you actually saw

artifactory private nuget package source authentication is not working. I think part of the reason could be that artifactory requires username/password, but it looks like `nuget_config_credential_helpers.rb` uses hardcoded user `user` and `token` instead of password:

<img width="834" alt="image" src="https://github.com/dependabot/dependabot-core/assets/1156106/771f52fa-8ce5-4529-9e4a-da0cfb6b29f4">

is there a way to support username/password, so that artifactory authentication starts working? Otherwise none of the dependencies get updated, event the ones coming from public nuget feed.

By the way public package updates were working fine until something changed in the nuget implementation. Now none of the packages get updates in projects that also use private packages.

**Comment by abdulapopoola** [comment] 2024-01-24 18:00
Thanks @vadimi and sorry about the regression. The crew is working on fixes in this area and should hopefully have some updates

**Comment by abdulapopoola** [comment] 2024-01-25 17:17
@vadimi this [shipped](https://github.com/dependabot/dependabot-core/pull/8892); does it fix the issue?

**Comment by vadimi** [comment] 2024-01-25 21:36
unfortunately it does not, the error log I'm getting looks like this:

```
 proxy | 2024/01/25 21:15:05 [124] GET https://xyz.jfrog.io:443/artifactory/api/nuget/nuget-local/Download/MyPackage/1.2.0
  proxy | 2024/01/25 21:15:05 [124] 403 https://xyz.jfrog.io:443/artifactory/api/nuget/nuget-local/Download/MyPackage/1.2.0
  proxy | 2024/01/25 21:15:05 [124] Remote response: {
  proxy |   "errors" : [ {
  proxy |     "status" : 403,
  proxy |     "message" : "Bad credentials"
  proxy |   } ]
  proxy | }
```

it doesn't look like this PR changes anything around authentication

**Comment by abdulapopoola** [comment] 2024-01-26 15:53
Tagging @brettfo and @edgarrs ; I know there was some work done on auth improvements this week; is this scenario supported?

**Comment by brettfo** [comment] 2024-01-26 16:02
This specific scenario isn't supported, there are earlier steps that combine the username and password into a `token` field like so: `user:password`.  I'll have to explore a bit to see the best way to support this as well as the other scenarios.

**Comment by brettfo** [comment] 2024-01-26 18:12
@vadimi I'm still looking into a proper fix for this, but in the meantime you _might_ be able to make a change to your `depedabot.yml` file.  I don't yet have an Artifactory feed to test this with, but based on how we give the authentication to the NuGet feed, you might be able to pre-combine the `username` and `password` into a single `token` field like this:

``` diff
 registries:
   nuget-public:
     type: nuget-feed
     url: https://api.nuget.org/v3/index.json
 
   my-artifactory:
     type: nuget-feed
     url: https://xyz.jfrog.io/artifactory/api/nuget/v3/nuget-local
-    username: ${{secrets.ART_USER}}
-    password: ${{secrets.ART_PASS}}
+    token: "${{secrets.ART_USER}}:${{secrets.ART_PASS}}"
     # combine both username and password with a colon character ':'
```

**Comment by vadimi** [comment] 2024-01-26 19:48
thanks @brettfo just tried that, but still received:
```
  proxy | 2024/01/26 19:41:01 [287] Remote response: {
  proxy |   "errors" : [ {
  proxy |     "status" : 403,
  proxy |     "message" : "Bad credentials"
  proxy |   } ]
  proxy | }
```
I think part of the reason is that `nuget_config_credential_helpers.rb` hardcodes `Username` field in `~/.nuget/NuGet/NuGet.Config` to `user`. Artifactory requires an actual user.

**Comment by brettfo** [comment] 2024-02-07 21:11
@vadimi I'm surprised the change to `token: user:pass` didn't work and that makes me wonder what else is going on.  You included part of the  log that reported a 403, can you give the few lines of the log above that, specifically where it lists the URL it was trying to hit?  There have been reported instances of Artifactory NuGet feeds not reporting all of their supported endpoints which means we might not be able to auto-inject the authentication.

On a related note, I'd love to be able to see the raw responses from your Artifactory feed.  If you have some time I'd like to schedule a bit of a back-and-forth where we explore the responses so I can see what's going on.  I can do a video call or we could even do some back-and-forth via email, and any feed or package information I gather would be kept private.  My email address is `brettfo@microsoft.com`.

**Comment by brettfo** [comment] 2024-02-08 17:04
For anybody following along at home, I've received some logs via email and will continue my investigation of the feed.

**Comment by brettfo** [comment] 2024-02-08 23:18
Thanks again to @vadimi for providing me with some API responses.  I've distilled the information into this comment so I don't lose track of it.

The Problem
===========
NuGet feeds provided by Artifactory [don't support](https://jfrog.atlassian.net/browse/RTFACT-20469) the `PackageBaseAddress` API endpoint which we use to generate a URL to download a `.nupkg` file.  The end result was that we tried to create this URL from the base feed address, but that wasn't correct and Artifactory would just return a `404`.

The Solution
============
Artifactory _does_ support the `SearchQueryService` API endpoint which we can use to list package data by name.  The results of that query look like this:

`GET https://<SearchQueryService>?q=Some.Package&prerelease=true`

``` jsonc
{
  "totalHits": 1,
  "data": [
    {
      // these first few fields correspond to the latest package version available
      "registration": "// same value that we can calculate from the RegistrationsBaseUrl endpoint",
      "version": "1.2.3", // the latest package version available
      "description": "// not interesting",
      "authors": [
        "// not interesting"
      ],
      "totalDownloads": 123, // not interesting
      "verified": true, // not interesting
      "versions": [
        {
          "version": "1.0.0",
          "downloads": 123,
          "@id": "<SOME-URL>/some.package/1.0.0.json" // registration leaf
        },
        {
          "version": "1.2.3",
          "downloads": 123,
          "@id": "<SOME-URL>/some.package/1.2.3.json" // registration leaf
        }
      ],
      "@id": "// seems to be identical to the `registration` field above",
      "id": "Some.Package", // the package name.  This will need to be matched to the original query to protect against partial matches
    }
  ]
}
```

Once we've matched `response.data.id` to the original package name, we can then pull the [registration leaf](https://learn.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-leaf) from the `@id` field of each element of the `versions` array.  That data looks like the following:

`GET <SOME-URL>/some.package/1.2.3.json`

``` jsonc
{
  "listed": true, // n.b., if this value is missing it is considered to be `true`
  "packageContent": "<SOME-URL>/some.package.1.2.3.nupkg", // this is what we really want, the .nupkg URL
  "registration": "// same value that we can calculate from the RegistrationsBaseUrl endpoint",
  "@id": "// URL directly to a JSON file describing the package, we won't need it for this scenario"
}
```

From this, we can pull down the `response.packageContent` URL and extract the `.nuspec` from the `.nupkg` file as we currently do.

Action
======
- Modify `repository_finder.rb` to allow for a missing/`nil` `PackageBaseAddress` endpoint.
- Modify `nupkg_fetcher.rb` to use the `SearchQueryService` method described above _IFF_ the `PackageBaseAddress` endpoint is missing/`nil`.
- Modify the internal proxy to inject authentication for the `packageContent` field in the response above.
   - N.b., the original Artifactory response also lists `LegacyGallery` and `PackagePublish` endpoints that happen to match the prefix of the `packageContent` URL, so we might be able to go that route, too.

**Comment by brettfo** [comment] 2024-02-23 18:49
@vadimi I've created #9117 that fixes Artifactory feeds.

**Closed** 2024-02-26 22:25 UTC
Labels: T: bug 🐞, L: dotnet:nuget

**Comment by vadimi** [comment] 2024-02-27 01:25
thanks @brettfo , I see the PR got merged, is it ok to get it tested?

**Comment by abdulapopoola** [comment] 2024-02-27 16:23
Yes, @vadimi ; can you test it again and please let us know the outcomes?

**Comment by vadimi** [comment] 2024-02-27 19:42
tried it on a few repos - everything worked perfectly fine. thanks @brettfo and @abdulapopoola, appreciate the effort!
