### ISSUE TITLE
Add support for OCaml

### ISSUE THREAD

**Issue by smorimoto** [dependabot/dependabot-core#1534] opened 2019-11-25 12:17 UTC
https://opam.ocaml.org/doc/Packaging.html

**Comment by imbsky** [comment] 2019-11-29 07:59
https://esy.sh/docs/en/configuration.html#specify-dependencies

**Comment by imbsky** [comment] 2019-11-29 08:02
To support both, get the version from the opam repository and update esy or opam file.

**Comment by XVilka** [comment] 2019-12-24 12:57
See also https://github.com/dependabot/feedback/issues/642

**Comment by infin8x** [comment] 2020-07-20 16:01
Duplicate of #2116

**Closed by infin8x** 2020-07-20 16:01 UTC
Labels: T: feature-request
