### ISSUE TITLE
Dependabot increase to latest available

### ISSUE THREAD

**Issue by Borda** [dependabot/dependabot-core#5149] opened 2022-05-17 08:08 UTC
_tbh, not sure if this is the right place to ask as it is about the GH bot, not action._

I wonder if there is a way to make the dependency update safe/reliable and update to the latest available package version so it can be tested and not increase to a future version that is not released yet...

for example, if we have requirements such as
```
packageABC >= 0.1, <=0.8.6
```
and there is a new release `0.8.7`, so I want to increase the version to `<=0.8.7` not to `<0.9` as I can't know if eventually next `0.8.8` is also safe... see the sample PR from dependable bellow which bumped version from actual 12.x to even 13.0 which is unacceptable :(

https://github.com/PyTorchLightning/pytorch-lightning/pull/13047/files
also sked on https://github.community/t/dependabot-increase-to-latest-available/250979

**Comment by carmocca** [comment] 2022-05-18 14:35
I guess the current dependabot behaviour makes sense with the assumption that semver patch updates won't break anything. This requires a high level of trust and might not be ok for many projects.

An option to decrease the update granularity would be what the OP needs. Is this unsupported for a reason?

> Then configure Dependabot to only do patch updates
Doesn't the snippet in the linked docs ignore patch updates instead?

**Comment by Borda** [comment] 2022-05-19 03:53
I remember the case with `PyYAML` which in one minor version changed default loading and broke completely all eco-system :)
 https://github.com/PyTorchLightning/pytorch-lightning/pull/5606

**Comment by Borda** [comment] 2022-05-23 15:39
> The safest approach would be to pin to a specific version
> 
> ```
> packageABC==0.8.6
> ```

that is quite aggressive for any package user... :(
btw, have another example when a fake bug-fix release broke https://github.com/PyTorchLightning/metrics/pull/1042

**Comment by jeffwidman** [comment] 2023-02-11 06:30
Your two options are:
1. pin to a single version. This is typically a bad idea for libraries, but a good idea for apps. Dependabot will open a PR to bump the pin when a new version comes out.
2. Specify the `widen` strategy plus pin the top end of your range at the currently released version. When a new version comes out, Dependabot will continue to bump the top end of the range w/o touching the bottom end. Because this trades determinism away in favor of flexibility, this is typically a bad idea for apps, but the right choice for libraries.

For Python, we're just in the process of rolling out `widen` support. Follow this ticket for updates:
* https://github.com/dependabot/dependabot-core/issues/6630

I'm going to close as there's nothing really actionable here.

**Comment by deivid-rodriguez** [comment] 2023-02-14 20:40
I disagree with closing this. In the example PR given by the OP, Dependabot is already widening the requirement, so the `widen` strategy is already being used (since it's the default for libraries).

The problem is that Dependabot is:
* Potentially allowing more versions than the user expects.
* Changing the upper bound requirement from `<=` to `<`.

In my opinion, Dependabot should try respect user's choice of specifying dependencies, and just focus on bumping them. So just like the user suggests, when there's a new `0.8.7` release of `packageABC`, dependabot should widen the requirement to allow exactly that, with the following diff:

```diff
- packageABC >= 0.1, <=0.8.6
+ packageABC >= 0.1, <=0.8.7
```

not with the one currently provided

```diff
- packageABC >= 0.1, <=0.8.6
+ packageABC >= 0.1, <0.9
```

Let me know if this makes sense @jeffwidman and we can reopen.

**Comment by deivid-rodriguez** [comment] 2023-02-14 20:50
Reopening just so we don't lose track of this. If we end up deciding this is not worth fixing or not even an issue, we can close again.

**Closed** 2023-03-01 10:44 UTC
Labels: L: python:pip
