### ISSUE TITLE
Dependabot changing order of attributes in `poetry.lock`

### ISSUE THREAD

**Issue by natestemen** [dependabot/dependabot-core#5561] opened 2022-08-20 00:49 UTC
Dependabot seems to be opening PRs which change the ordering of attributes within the lockfile. For example [this PR](https://github.com/natestemen/mitiq/pull/61/files). I know the lockfile isn't usually meant to be read, but it's nice when dependabot PRs are small and easily check-able.

Perhaps it's also possible that the way dependabot creates new lockfiles is consistent, and my original creation differs from that. In that case, is it possible to reformat my lockfile so dependabot creates smaller PRs?

**Comment by deivid-rodriguez** [comment] 2022-08-20 09:33
I think this is a duplicate of #5530, so I will close this ticket in favor of #5530 and we can follow up in there.

**Closed by deivid-rodriguez** 2022-08-20 09:33 UTC

**Comment by natestemen** [comment] 2022-08-21 18:11
Sorry for the duplicate, and thanks for looking into it!
