### ISSUE TITLE
Scheduling for specific dependencies?

### ISSUE THREAD

**Issue by saschanaz** [dependabot/dependabot-core#3240] opened 2021-03-05 23:51 UTC
Some dependencies may directly impact the feature of the package and while others not. I want to be notified ASAP when updates happen for those important dependencies while just monthly for others.

**Comment by xlgmokha** [comment] 2021-03-05 23:53
@saschanaz Are you saying that you would like to schedule dependency intervals differently for different groups of dependencies. 

E.g. monthly for development dependencies and daily for production dependencies?

**Comment by saschanaz** [comment] 2021-03-05 23:58
Yup, exactly. Not necessarily a production dependency, though.

**Comment by asciimike** [comment] 2021-03-11 17:45
@saschanaz I think the right answer is [`allow`](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow) and have multiple updates:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "development"
    schedule:
      interval: "weekly"
```

You can also select individual dependencies to set different update frequencies on.

Closing this, but feel free to re-open if it's doesn't work in this case.

**Comment by saschanaz** [comment] 2021-03-11 18:15
Great, `allow:dependency-name` works for me 👍

**Comment by saschanaz** [comment] 2021-03-11 20:00
Oh no, that doesn't work:

> Your .github/dependabot.yml contained invalid details
> 
> Dependabot encountered the following error when parsing your .github/dependabot.yml:
> 
> The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
> 
> Please update the config file to conform with Dependabot's specification.

BTW somehow the reopen button doesn't exist here, could you reopen or update your answer?

**Comment by asciimike** [comment] 2021-05-19 15:31
Ok, I'm going to close this as a dupe of https://github.com/dependabot/dependabot-core/issues/1778, which is the feature request underpinning all of these types of requests. It's something we've been thinking through as we've been working on https://github.com/dependabot/dependabot-core/issues/2219, but we haven't scheduled work on it.

**Closed by asciimike** 2021-05-19 15:31 UTC
Labels: T: feature-request

**Comment by probablyup** [comment] 2023-09-19 19:15
> @saschanaz I think the right answer is [`allow`](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow) and have multiple updates:
> 
> ```yaml
> version: 2
> updates:
>   - package-ecosystem: "npm"
>     directory: "/"
>     allow:
>       - dependency-type: "production"
>     schedule:
>       interval: "daily"
> 
>   - package-ecosystem: "npm"
>     directory: "/"
>     allow:
>       - dependency-type: "development"
>     schedule:
>       interval: "weekly"
> ```
> 
> You can also select individual dependencies to set different update frequencies on.
> 
> Closing this, but feel free to re-open if it's doesn't work in this case.

This seems to not be valid anymore for anyone finding this in the future:

```
The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
```

**Comment by deivid-rodriguez** [comment] 2023-09-20 10:22
It was never valid, please subscribe to #1778 if you want updates about that, thanks!
