### ISSUE TITLE
How to update only root package.json in Monorepo?

### ISSUE THREAD

**Issue by gotbahn** [dependabot/dependabot-core#1513] opened 2019-11-11 16:03 UTC
In Lerna Monorepo we not quite interested in updates for all packages, rather only root one.

Is it possible to set dependabot updates only for it? I see only directory can be specified

**Comment by rebelagentm** [comment] 2019-11-12 21:44
@feelepxyz Is there a way to configure this?

**Comment by feelepxyz** [comment] 2019-11-13 12:51
@godban 👋 Do you mean to only update the root package.json/lockfile? There's currently no config for this but could use config files and set your allowed updates by name: https://dependabot.com/docs/config-file/#allowed_updates
This is definitely not ideal as you would have to keep this in sync with what's in your root package file.

This is also the first time we've heard this piece of feedback so keen to wait and see if this is a useful pattern for others before planning how we would implement.

**Comment by godban** [comment] 2019-11-13 13:00
> @godban 👋 Do you mean to only update the root package.json/lockfile? 

yes, exactly

I will try allow unique updates by name, thank you. 
But as understand it could solve issue only partially, same dependency could exist in multiple places, in root and other packages.

**Comment by feelepxyz** [comment] 2019-11-13 13:03
@godban nice one. Good point, to better understand the problem, what's the reason for only updating root packages? Or rather, why do you not want to update the packages?

**Comment by godban** [comment] 2019-11-13 13:17
difference between this two kinds in monorepos are crucial for us

**root** serves whole repo infrastructure (tests, build, etc.) it's very similar to any single package application, where we interested in latest updates.

**packages** package (sounds funny, so let's call it shared package) is responsible for our shared components, utils and lib, distributed as standalone npm packages.
Here we totally not interested in updates, unless we really want to change something. So shared package dependency never goes greater than dependency of app that gonna use it, and we assure that app and this shared package dependency can use same version that used in app.
Otherwise they gonna use each own version.

We could solve it by non-strict package versions in app, but it raises even more concerns.

**Comment by feelepxyz** [comment] 2019-11-15 17:08
@godban gotcha! That does make sense and I guess you would actually want different update strategies for the root vs the shared packages. Have you looked the  `version_requirement_updates` setting? If you set this to `widen_ranges` Dependabot will try to allow both the old and new versions in in your package.json version requirement which might be more suitable for your packages: https://dependabot.com/docs/config-file/#version_requirement_updates

**Comment by jeffwidman** [comment] 2023-02-10 06:44
Closing as a duplicate of both of the following:
* https://github.com/dependabot/dependabot-core/issues/4364
* https://github.com/dependabot/dependabot-core/issues/2883

**Closed by jeffwidman** 2023-02-10 06:44 UTC
Labels: T: feature-request, F: language-support, L: javascript:lerna, F: monorepo 📦
