### ISSUE TITLE
Gradle subprojects

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [dependabot/dependabot-core#3254] opened 2021-03-10 12:45 UTC
I am only getting updates for the root `build.gradle.kts` file, but I am seeing other projects that can get updates for all subprojects `build.gradle.kts`

Is dependabot searching in `settings.gradle.kts` file where are the subprojects? This is a problem because I can have a plugin/algorithm that auto-include all subprojects without indicating them manually with `include(":some-subproject")`.

Should be great that I can just use a wildcard pattern but it doesn't work for me:

```
version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/**/*/"
    schedule:
      interval: "daily"
```

**Comment by JavierSegoviaCordoba** [comment] 2021-03-10 12:48
I can confirm the problem is that because I added manually `include(":some-subproject")` to the settings file and it is working now.

**Comment by jeffwidman** [comment] 2022-08-24 21:38
Duplicate of https://github.com/dependabot/dependabot-core/issues/2178

**Closed by jeffwidman** 2022-08-24 21:38 UTC
Labels: T: bug 🐞, L: java:gradle
