### ISSUE TITLE
python pip-compile comment requirements.in path modified by dependabot (when pip-compile run from subdir, and requirements.in is in a nested subdir)

### ISSUE THREAD

**Issue by thomas-riccardi** [dependabot/dependabot-core#3636] opened 2021-05-04 12:45 UTC
**Package ecosystem**
python
**Package manager version**
pip-compile 5.5
**Language version**
python 3.8
**Manifest location and content prior to update**

`foo/deploy/base/build/requirements.in`

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --generate-hashes --output-file=deploy/base/build/requirements.txt deploy/base/build/requirements.in
#
algoliasearch==2.4.0 \
    --hash=sha256:525f9d50f5363c8ae6603a8e328d8c23957e825fdfe363ecbda55487a0140c76 \
    --hash=sha256:5f62155450949642fe6ae1c163d89630c9ffce9cca62901893ddc1ad3e653239
    # via -r deploy/base/build/requirements.in
```
(extract)
**dependabot.yml content**
none
**Updated dependency**
any
**What you expected to see, versus what you actually saw**
All `# via -r deploy/base/build/requirements.in` are replaced by `# via -r requirements.in`, which isn't stable with our manual usage of pip-compile.
We run pip-tools from subdirectory (`foo/`), with `pip-compile --generate-hashes --output-file=deploy/base/build/requirements.txt deploy/base/build/requirements.in`
**Native package manager behavior**
pip-compile generates (and keep stable) `# via -r deploy/base/build/requirements.in` (called from subdir `foo/`)
**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment] 2022-11-23 22:21
This appears to be a dupe of https://github.com/dependabot/dependabot-core/issues/3143.

Many thanks to @jon-betts for flagging that.

**Closed by jeffwidman** 2022-11-23 22:21 UTC
Labels: T: bug 🐞, L: python:pip
