### ISSUE TITLE
Support GitHub Actions that aren't exclusively in the `.github` directory

### ISSUE THREAD

**Issue by alexrosenfeld10** [dependabot/dependabot-core#6949] opened 2023-03-30 18:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It's a fairly common scenario where an organization might centralize workflows / actions into a common repository, to make a "private action marketplace" if you will. Referencing these actions from a separate repo would look like:

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: NPM Setup
        uses: my-org/github-actions/team-name/path-to-action/npm-setup@1.0.0
```

As you can see here, in the `my-org/github-actions` repo, the path to the composite action is not `.github/**`. Instead, it's organized into a team level basis. From the docs, it appears that dependabot exclusively updates values in `.github/**`, which means composite actions will be missed. Can we make this path more configurable?

**Comment by nschonni** [comment] 2023-03-30 18:31
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory

**Comment by alexrosenfeld10** [comment] 2023-03-30 19:38
@nschonni Thanks, I've seen that doc. It explicitly states: 
>  For GitHub Actions, set the directory to / to check for workflow files in .github/workflows.

Which is exactly the _opposite_ of what this issue is asking about.

**Comment by DaleMckeown** [comment] 2023-04-03 21:58
This is kinda related to https://github.com/dependabot/dependabot-core/issues/6894

**Comment by jeffwidman** [comment] 2023-04-05 01:59
@DaleMckeown IIUC it's actually not...  this is about the location of the actual actions files, ie, the location of the package manifests vs that's about the `dependabot.yml` config that Dependabot uses.

**Comment by jeffwidman** [comment] 2023-04-05 02:00
@alexrosenfeld10 isn't this a duplicate of https://github.com/dependabot/dependabot-core/issues/5970, which was resolved by https://github.com/dependabot/dependabot-core/pull/6189 ??

If not, can you please clarify how this is different?

**Comment by jeffwidman** [comment] 2023-04-05 18:37
I'm not sure TBH as I didn't work on that PR, but shouldn't be difficult to try both and see which one works.

**Closed** 2023-04-05 18:37 UTC
Labels: T: feature-request, L: github:actions

**Comment by alexrosenfeld10** [comment] 2023-04-05 18:53
Sure it wouldn't be difficult but it's a reasonable thing to expect documentation to be clear about something like this. I guess I'll just give it a whirl

**Comment by jeffwidman** [comment] 2023-04-05 18:58
Agreed! The great thing is this is all open source, we'd happily accept a PR if you care to pay it forward by improving the docs based on what you discover... 

You're actually the best person here because all you have to do is think "What would I have wanted in the docs that would have kept me from wasting time creating this issue?" 🙂

**Comment by alexrosenfeld10** [comment] 2023-04-05 19:03
Sure, when I'm feeling better and have time I'll get to it
