### ISSUE TITLE
Multiple docker files in one directory does not update correctly

### ISSUE THREAD

**Issue by RogierdeRuijter** [dependabot/dependabot-core#2063] opened 2019-12-24 20:48 UTC
I have a directory with multiple docker files.

**Pre update:**
 - Dockerfile.local = node:11
 - Dockerfile.production = node:11-alpine

**Post update:**
 - Dockerfile.local = node:13-alpine
 - Dockerfile.production = node:13-alpine

**Link to PR**
https://github.com/RogierdeRuijter/montepoeli/pull/288/files

**Comment by infin8x** [comment] 2020-07-20 16:17
Duplicate of #2179

**Closed by infin8x** 2020-07-20 16:17 UTC
