### ISSUE TITLE
Call out direct dependency when bumping indirect dependency

### ISSUE THREAD

**Issue by tstirrat15** [dependabot/dependabot-core#2090] opened 2019-11-06 01:49 UTC
Thank you for the awesome work you do! I'm loving Dependabot so far.

One thing that would be nice is if when an indirect dependency is bumped in a lockfile (e.g. `yarn.lock`), the direct dependency/ies that have that indirect dependency as a child are called out.

It would make impact assessment and testing easier - I'm less concerned about an update to an indirect dependency of a dev dependency than of a normal dependency.

I'm not sure exactly what it would take - it sounds like it'd be parsing the lockfile to create a dependency graph, selecting the child dependency, and then walking up the tree (DAG? what would it be in this case?) to find the direct dependency/ies at the top level. Does something like this exist in dependabot or package managers, or is there not really prior art for this?

**Comment by gabrielliwerant** [comment] 2021-07-09 21:46
I would also find this feature useful, if I understand it correctly. We have to keep on top of security updates as much as possible but updating indirect dependencies can be difficult to test in cases where it might cause breakage with the direct dependency. Part of helping to triage means tracing which direct dependencies are using the indirect dependency by searching the lock file manually, which is error prone and costly in time.

**Comment by mwaddell** [comment] 2022-02-05 04:31
I created a reusable workflow that does this:

https://github.com/pangaeatech/.github/blob/main/.github/workflows/annotate-npm-dependencies.yml

**Comment by mwaddell** [comment] 2022-02-05 04:32
Related to #2702

**Comment by jeffwidman** [comment] 2023-02-11 08:06
Closing as a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2125

**Closed by jeffwidman** 2023-02-11 08:06 UTC
Labels: T: feature-request, L: javascript:yarn, F: pull-requests
