### ISSUE TITLE
Python requirements.txt, auto PR created an empty commit

### ISSUE THREAD

**Issue by mgrandi** [dependabot/dependabot-core#3181] opened 2021-02-22 22:20 UTC
**Package manager/ecosystem**

python + pip

**Manifest contents prior to update**

https://github.com/CodeForTucson/govtracker-az/blob/master/scraping/requirements.txt

**Updated dependency**

lxml from 4.3.4 to 4.6.2

**What you expected to see, versus what you actually saw**

so it seems that Dependabot created a PR here: https://github.com/CodeForTucson/govtracker-az/pull/22

the requirements.txt file is located in ` <repo root>/scraping/requirements.txt `

dependabot created the above PR, but the commit itself (https://github.com/CodeForTucson/govtracker-az/pull/22/commits/b007c60e6ad3ede2a8ed3b1898107898eaec41d6) did not actually change anything, its a 0 line change to the requirements.txt file

**Images of the diff or a link to the PR, issue or logs**

https://github.com/CodeForTucson/govtracker-az/pull/22

https://github.com/CodeForTucson/govtracker-az/pull/22/commits/b007c60e6ad3ede2a8ed3b1898107898eaec41d6

<img width="942" alt="2021-02-22 14_19_17 - Screenshot" src="https://user-images.githubusercontent.com/802786/108777636-5bd52d00-7521-11eb-8a46-087d217ffbf4.png">

**Comment by jurre** [comment] 2021-04-12 10:20
Thanks for reporting this @mgrandi, this is 🤯. I'm not able to reproduce this, we have released some fixes to the python updater recently, could you try a `@dependabot recreate` on that PR to see if it has been resolved?

**Comment by jurre** [comment] 2021-04-16 08:24
I'm going to close this out for now as this is hopefully fixed by now, but please feel free to reopen if it happens again

**Closed by jurre** 2021-04-16 08:24 UTC
Labels: L: python:pip, T: bug 🐞

**Comment by mgrandi** [comment] 2021-04-16 08:36
hi, sorry for the delay, i did that commnad and it recreated the PR

actually, now that i look at https://github.com/CodeForTucson/govtracker-az/pull/22 , the commit is now showing that it changed stuff, but it says that the changes are binary? I still think that is a bug because the file wasn't binary to start out with

https://github.com/CodeForTucson/govtracker-az/pull/23 is the same way, you can look at https://github.com/CodeForTucson/govtracker-az/blob/master/scraping/requirements.txt fine but then if you look at the changes made here https://github.com/CodeForTucson/govtracker-az/pull/23/files , it says "binary file not shown"

however, despite that, it seems that both PR 22 and PR 23 are showing that it upgraded the lxml dependency fine, but as i showed in my screenshot, it DID show that there were no changes before, was that a github display bug or something?

![image](https://user-images.githubusercontent.com/802786/114996944-36dfa500-9e54-11eb-8f65-5c31afe61469.png)

**Comment by mgrandi** [comment] 2021-04-16 08:38
actually now that i see that screenshot, it shows `+0 -0` lines, even though if you go into the rich diff view, it shows that `lxml` is now at 4.6.3

**Comment by jurre** [comment] 2021-04-16 08:50
Ah thanks @mgrandi, so, it looks like there are some weird bytes in the requirements file:

```
cat scraping/requirements.txt
��appdirs==1.4.3
```

I think this is causing the problem here, at first I thought that maybe this was a bug in Dependabot, since we do check the mimetype in some cases, but I don't think Dependabot ends up checking it in this scenario.

However, if it does, we'd also be tripped up by those bytes:

```
file -b --mime-encoding scraping/requirements.txt
utf-16le
```

I think if those bytes are removed from the file it should all work as expected

**Comment by mgrandi** [comment] 2021-04-16 09:00
interesting, still feel like this might be a github visualization bug then where it views fine when you go to the file directly, but then viewing a PR on that file shows that its binary and can't be previewed , i'll check tomorrow on if making that file utf8 and recreating it fixes the issue

**Comment by jurre** [comment] 2021-04-16 09:22
> interesting, still feel like this might be a github visualization bug then where it views fine when you go to the file directly, but then viewing a PR on that file shows that its binary and can't be previewed , i'll check tomorrow on if making that file utf8 and recreating it fixes the issue

Right, I think it's not strictly an issue on the GitHub view side, Dependabot uses the GitHub API to push the file changes and we end up marking this file as `utf-8` rather than binary, and I think this causes the mixup.

Dependabot checks for the files mime type when [updating vendored files](https://github.com/dependabot/dependabot-core/blob/e660c7c3eeee34365c755b44a4dd570037c654be/common/lib/dependabot/file_updaters/vendor_updater.rb#L71), perhaps this is something we could do for all files, but tbh it's never come up before 🤔
