### ISSUE TITLE
Only one package is updated in a PR of grouped package version updates

### ISSUE THREAD

**Issue by steven-oriley-talogy** [dependabot/dependabot-core#8475] opened 2023-11-28 12:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### dependabot.yml content

```yaml
version: 2
registries:
  nuget-azdo-artifacts:
    type: nuget-feed
    url: https://***/nuget/v3/index.json
    username: ${{username}}
    password: ${{password}}
updates:
- package-ecosystem: nuget
  directory: "/src/"
  registries:
    - nuget-azdo-artifacts
  schedule:
    interval: weekly
    day: sunday
  groups:
    default:
      patterns:
        - "*"
      exclude-patterns:
          - "Microsoft.VisualStudio.Azure.Containers.Tools.Targets"
  open-pull-requests-limit: 10
```

### What you expected to see, versus what you actually saw

The following list of package version bumps are included in the description of the PR created by dependabot:

| Package | From | To |
| --- | --- | --- |
| [Microsoft.AspNetCore.Authentication.JwtBearer](https://github.com/dotnet/aspnetcore) | `7.0.13` | `7.0.14` |
| [Microsoft.AspNetCore.Authentication.OpenIdConnect](https://github.com/dotnet/aspnetcore) | `7.0.13` | `7.0.14` |
| [Microsoft.Extensions.Http](https://github.com/dotnet/runtime) | `7.0.0` | `8.0.0` |
| [Serilog.AspNetCore](https://github.com/serilog/serilog-aspnetcore) | `7.0.0` | `8.0.0` |
| [System.Net.Http.Json](https://github.com/dotnet/runtime) | `7.0.1` | `8.0.0` |

However, only one version bump is actually included in the code changes:

![image](https://github.com/dependabot/dependabot-core/assets/54543848/1e95113e-a6d7-40f0-9888-830ade339dd7)

In the log for the latest dependabot job, we are also seeing a recurring error that may or may not be related to this issue:

```
proxy | 2023/11/28 11:48:06 [306] 401 https://***/nuget/packages/***/versions/3.1.6/content?sourceProtocolVersion=nuget&api-version=7.0-preview
proxy | 2023/11/28 11:48:06 [306] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

### Images of the diff or a link to the PR, issue, or logs

This issue is occurring on private repositories owned by my organization. A dependabot PR was created yesterday (11/27/2023) morning that we were able to successfully merge because it did not have the issue. This PR was created as a result of the following update to dependabot.yml:

```yaml
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authentication.*"
      update-types: ["version-update:semver-major"]
```

However, PR's that were created by dependabot in the afternoon against other repositories where the same change had been merged all experienced the issue where one revision was included in the code changes despite multiple being listed in the PR description.

We have since reverted the changes to dependabot.yml that were merged before seeing this issue, but the revert was not able to fix the problem.

**Comment by thomhurst** [comment] 2023-12-05 07:40
Also experiencing this

**Comment by tj-spyro** [comment] 2023-12-06 12:16
This is affecting my organisation too and blocking our migration of repos to GitHub.

**Comment by asos-lewish** [comment] 2023-12-06 21:30
This is also affecting my organisation. Started getting the 401 error with `The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource` but have confirmed the PAT token being used is valid for accessing our private azure artifacts feed. 

Dependabot updates for nuget was working fine until just over a week ago but we had various issues since then. This is the latest one. 

Here is part of the logs:

```
proxy | 2023/12/06 21:22:38 [042] 200 https://pkgs.dev.azure.com:443/myorg/_packaging/my-feed/nuget/v3/index.json
  proxy | 2023/12/06 21:22:38 [044] GET https://pkgs.dev.azure.com:443/myorg/_packaging/cc1b0164-0367-4747-9c65-9a085ace2977/nuget/v3/query2/?q=coverlet.collector&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/06 21:22:38 [044] 401 https://pkgs.dev.azure.com:443/myorg/_packaging/cc1b0164-0367-4747-9c65-9a085ace2977/nuget/v3/query2/?q=coverlet.collector&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/06 21:22:38 [044] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
updater | 2023/12/06 21:22:38 WARN <job_759312734> Please check your configuration as there are groups where no dependencies match:
updater | - nuget
updater | 
updater | This can happen if:
updater | - the group's 'pattern' rules are mispelled
updater | - your configuration's 'allow' rules do not permit any of the dependencies that match the group
updater | - the dependencies that match the group rules have been removed from your project
updater | 
updater | 2023/12/06 21:22:39 INFO <job_759312734> Starting grouped update job for my-org/my-repo
updater | 2023/12/06 21:22:39 INFO <job_759312734> Found 1 group(s).
updater | 2023/12/06 21:22:39 WARN <job_759312734> Skipping update group for 'nuget' as it does not match any allowed dependencies.
updater | 2023/12/06 21:22:39 INFO <job_759312734> Finished job processing
updater | time="2023-12-06T21:22:39Z" level=info msg="task complete" container_id=job-759312734-updater exit_code=0 job_id=759312734 step=updater
```

**Comment by thomhurst** [comment] 2023-12-06 21:50
> This is also affecting my organisation. Started getting the 401 error with `The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource` but have confirmed the PAT token being used is valid for accessing our private azure artifacts feed.
> 
> Dependabot updates for nuget was working fine until just over a week ago but we had various issues since then. This is the latest one.
> 
> Here is part of the logs:
> 
> ```
> proxy | 2023/12/06 21:22:38 [042] 200 https://pkgs.dev.azure.com:443/myorg/_packaging/my-feed/nuget/v3/index.json
>   proxy | 2023/12/06 21:22:38 [044] GET https://pkgs.dev.azure.com:443/myorg/_packaging/cc1b0164-0367-4747-9c65-9a085ace2977/nuget/v3/query2/?q=coverlet.collector&prerelease=true&semVerLevel=2.0.0
>   proxy | 2023/12/06 21:22:38 [044] 401 https://pkgs.dev.azure.com:443/myorg/_packaging/cc1b0164-0367-4747-9c65-9a085ace2977/nuget/v3/query2/?q=coverlet.collector&prerelease=true&semVerLevel=2.0.0
>   proxy | 2023/12/06 21:22:38 [044] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
> updater | 2023/12/06 21:22:38 WARN <job_759312734> Please check your configuration as there are groups where no dependencies match:
> updater | - nuget
> updater | 
> updater | This can happen if:
> updater | - the group's 'pattern' rules are mispelled
> updater | - your configuration's 'allow' rules do not permit any of the dependencies that match the group
> updater | - the dependencies that match the group rules have been removed from your project
> updater | 
> updater | 2023/12/06 21:22:39 INFO <job_759312734> Starting grouped update job for my-org/my-repo
> updater | 2023/12/06 21:22:39 INFO <job_759312734> Found 1 group(s).
> updater | 2023/12/06 21:22:39 WARN <job_759312734> Skipping update group for 'nuget' as it does not match any allowed dependencies.
> updater | 2023/12/06 21:22:39 INFO <job_759312734> Finished job processing
> updater | time="2023-12-06T21:22:39Z" level=info msg="task complete" container_id=job-759312734-updater exit_code=0 job_id=759312734 step=updater
> ```

@asos-lewish I'm not sure what the PAT token is for, but I assume you know that builds in a dependabot context have their permissions restricted?

**Comment by ktjn** [comment] 2023-12-07 17:59
I am seeing this as well. Tried to update the PAT but no luck.

**Comment by asos-lewish** [comment] 2023-12-08 10:14
@thomhurst The PAT is used by dependabot to access a private nuget feed (artifacts).

**Comment by tom-scott** [comment] 2023-12-20 09:39
I'm also facing this issue as well. Any update on a fix?

**Comment by jevvo-trimble** [comment] 2024-01-02 07:07
Hello, any updates on this?
Have the same issue:
![image](https://github.com/dependabot/dependabot-core/assets/107613400/15e02a05-269f-4ce0-b44c-2f3a4087d09c)
![image](https://github.com/dependabot/dependabot-core/assets/107613400/51488249-62cd-4d93-8621-342945937303)
Looks like grouping is picking only last time.
I have it on multiple projects with different dependency

#8576

**Comment by ktjn** [comment] 2024-01-03 06:25
I suspect this https://github.com/dependabot/dependabot-core/commit/d33395ff5459f6b877b248bc58fa5245b7b3f2d4 broke this. Looks like the calls to index.json works and the next call somehow doesn't use the auth header.

Doing a simple curl without any auth header will give this error:
"message": "TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.",
which is very much what we see in the logs.

**Comment by TimNilimaa** [comment] 2024-01-03 18:43
+1 on this issue, also blocking our migration to GitHub. I do not agree with @ktjn however as I believe the issue to have been introduced in the batch of commits on the 27th of November 2023 https://github.com/dependabot/dependabot-core/commits/main/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb

**Comment by ktjn** [comment] 2024-01-03 19:19
Yes, I agree. It was broken even before the commit I mentioned.

**Comment by asos-bryanharveysmith** [comment] 2024-01-15 17:50
The authentication issue that I was previously seeing with Dependabot appears to be resolved. However now we're back to the issue where only one package is updated, despite the PR notes indicating that multiple updates have been applied.

**Comment by diego-oliveira6** [comment] 2024-01-28 11:29
Same problem here, the commit has many files that would be changed, but he actually updated only one row
![IMG_20240128_082812](https://github.com/dependabot/dependabot-core/assets/96154404/1d8c8a50-259f-499c-ae14-5ace45da535a)

**Comment by abdulapopoola** [comment] 2024-03-07 20:15
@sebasgomez238 just shipped this fix #9228 ; could you please confirm that this addresses the core issue?

**Comment by tom-scott** [comment] 2024-03-08 09:40
> @sebasgomez238 just shipped this fix #9228 ; could you please confirm that this addresses the core issue?

I've had this issue as well and it appears to be fixed with this PR!

**Comment by abdulapopoola** [comment] 2024-03-08 16:57
Seems this is now fixed; closing out. Please feel free to reactivate if it recurs!

**Closed by abdulapopoola** 2024-03-08 16:57 UTC
Labels: T: bug 🐞, L: dotnet:nuget, F: grouped-updates 🎳

**Comment by cclauss** [comment] 2024-03-27 21:12
pytest-dev/pytest-repeat#81 seems strange in this way.
