### ISSUE TITLE
Github Actions - allow updating major versions only

### ISSUE THREAD

**Issue by DarkWanderer** [dependabot/dependabot-core#5887] opened 2022-10-14 08:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

GitHub Actions follow docker-like tag pattern, where a new version updates 3 tags simultaneously:

- full version: v1.2.3
- minor version: v1.2
- major version: v1

A common practice then is to use a major version tag (`action@v1`) to allow automatic minor version drift, and update major versions manually (as that often implies breaking changes)

At the moment, Dependabot is not aware of this convention, and unconditionally suggests the "max" version. This leads to situation when an action updates an action v2 to v3.0.0 [example](https://github.com/DarkWanderer/ClickHouse.Client/pull/203), and that leads to a lot of extraneous PRs after (updating 3.0.0=>3.0.1, 3.0.1=>3.0.2 etc.)

Suggestion: add `versioning-strategy` value for GitHub actions (e.g. `major`) which will instruct Dependabot to exclusively use tags where only major version is specified

**Comment by DarkWanderer** [comment] 2022-10-14 08:11
Note: I am aware of `ignore: update-types:` mechanic, but this is slightly different as `ignore` will still result in dependency being updated to full version spec, i.e. `v1.2.3`

**Comment by deivid-rodriguez** [comment] 2022-10-14 12:51
Mmmm, this feels like a deja vu... I thought we had already discussed and fixed this. This is what everyone expects, Dependabot should not be proposing an upgrade that uses a different "versioning style", and instead respect what's already there.

I'll have a look at what's going on, thank for letting us now and providing a public repo as a example 🥇.

**Comment by deivid-rodriguez** [comment] 2022-10-16 16:27
Hei @DarkWanderer!

So I tried this using:

* Our [`dry-run.rb`](https://github.com/dependabot/dependabot-core/blob/2401f2bcd941bec551d9698803d3b60156b5a6c7/bin/dry-run.rb) script.
* Dependabot's [CLI](https://github.com/dependabot/cli).
* A [fork](https://github.com/deivid-rodriguez/ClickHouse.Client/pull/1) of your repo.

All three times Dependabot bumped the dependency from v2 to v3 as expected.

There's still something fishy going on here since Dependabot did open an incorrect PR on your repository, but I have no idea how that happened. This should've been working as expected 17 days ago too, since no related changes have been released since that I know of.

Anyways, I'm going to close this, if you ever get another PR by Dependabot showing this behavior, please reopen this issue as quickly as possible so we can figure out the root cause and fix it!

Thanks for your helpful report, by the way!

**Closed by deivid-rodriguez** 2022-10-16 16:27 UTC
Labels: T: feature-request, L: github:actions

**Comment by DarkWanderer** [comment] 2022-10-16 17:09
No worries. This is an excellent tool and I'll be happy if I can contribute back.

One thing I noticed is that setup-dotnet repo uses manual release scheme, and a separate action to mark 'major tag, e.g.:

- 3.0.0 version was [released manually](https://github.com/actions/setup-dotnet/releases/tag/v3.0.0) at **29 Sep 17:56** CEST
- Additional [workflow](https://github.com/actions/setup-dotnet/actions/runs/3152777369/jobs/5128427358) was triggered which ran at **30 Sep 8:28** CEST (I assume also manually).
- The [pull request](https://github.com/DarkWanderer/ClickHouse.Client/pull/203) in question was raised at **30 Sep 3:55** CEST - i.e. after creation of `v3.0.0` tag, but before `v3`. 
 
Speculatively, this time gap might explain both the bug and failure to reproduce it - as now there is a valid `v3` tag available.

I assume that in the absence of 'correct' `v3` tag, Dependabot just defaults to the highest available

P.S. And I guess my search skills could use a brush-up, there is actually a prior on this: #2304

**Comment by deivid-rodriguez** [comment] 2022-10-16 17:19
Wow, fantastic investigation! That makes total sense and I'm sure that's the cause of the issue.

Dependabot should always respect the precision chosen by the user, and it already does this in general, except for this normally very small time frame where an action has a release, but no "major tag/branch" pointing to it.

I will fix this.

**Comment by deivid-rodriguez** [comment] 2022-10-16 18:18
Ok I created https://github.com/dependabot/dependabot-core/issues/5891 to fix this. I learnt though that there's a reason for the current behavior, so it will need some team discussion to figure out whether it should be changed or not.

**Comment by rtyley** [comment] 2026-06-16 09:46
It feels like there's been a regression in this area - see this public dependabot PR, updating `actions-checkout` from `6` to `6.0.2` :

* https://github.com/guardian/gha-scala-library-release-workflow/pull/130 - opened by dependabot at `2026-06-08T04:44:06Z`

The [v6 tag,](https://github.com/actions/checkout/releases/tag/v6) as it currently stands, pointing to v6.0.3, was created at `2026-06-02T14:31:30Z` - so https://github.com/guardian/gha-scala-library-release-workflow/pull/130 was created by dependabot long after there was definitely a valid v6 tag:

<img width="1221" height="139" alt="Image" src="https://github.com/user-attachments/assets/199761ea-06c3-4fc6-8754-7e5738941578" />
