### ISSUE TITLE
Dependabot doesn't seem to pick up new docker images

### ISSUE THREAD

**Issue by oswaldquek** [dependabot/dependabot-core#6717] opened 2023-02-23 10:37 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Docker

### dependabot.yml content

https://github.com/alphagov/pay-selfservice/blob/master/.github/dependabot.yml
https://github.com/alphagov/pay-connector/blob/master/.github/dependabot.yml

### Updated dependency

From node:16.18.1-alpine3.16@sha256:868e2b6c8923d87a4bbfb157d757898061c9000aaaedf64472074fa7b62d0e72 to node:16.19.1-alpine3.17@sha256:25828d5c4ae9824273db9ca2e923da2d29bbae78f534e979f09eb99a2e812e94. I had to [manually raise a PR](https://github.com/alphagov/pay-selfservice/commit/411faa7a5447a2d3a811dc15bebe920541f2092a) for this.

From eclipse-temurin:11-jre-alpine@sha256:64674afdc275bed87f352eb94f9469842313dd2902afe9d7b0fb9508fc75cc37 to eclipse-temurin:11-jre-alpine@sha256:4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad. I had to [manually raise a PR](https://github.com/alphagov/pay-connector/commit/a250434646083fd9d55f972de6ea5efefa342401) for this.

### What you expected to see, versus what you actually saw

Expected dependabot to raise a PR, but it didn't.

**Comment by deivid-rodriguez** [comment] 2023-02-23 13:26
I think this is a duplicate of #5708, please subscribe to that other ticket for updates!

**Closed** 2023-02-23 13:26 UTC
Labels: T: bug 🐞
