### ISSUE TITLE
[C#] Dependabot not updating nuget packages in csproj's anymore.

### ISSUE THREAD

**Issue by AraHaan** [dependabot/dependabot-core#1842] opened 2020-05-06 08:35 UTC
**Package manage/ecosystem** 
nuget & C# (.NET)

**Manifest contents prior to update**
Happens to all of my C# projects that ends up also being nuget packages too.
ex: https://github.com/Elskom/zlib.managed/ the csproj file contains the information for packages.

**Updated dependency**
Any dependency I use that has updates on nuget.org, or in nuget feeds configured in my NuGet.config file for the project.

**What you expected to see, versus what you actually saw**
N/A, the issue relates to updating all of them.

**Images of the diff or a link to the PR, issue or logs**
No diff, or PR has been recently created.

**Comment by jurre** [comment] 2020-05-06 08:47
Hy @AraHaan, when I run dependabot manually (using the dry-run script in `bin/dry-run`) it does indeed not report any dependencies that need to be updated.

Which dependency would you expect to have been updated in this case? Could there be a conflict with another dependency perhaps?

FYI this does not seem related to the timeouts on a different issue that you commented on.

**Comment by AraHaan** [comment] 2020-05-06 08:52
Well I expect all of them to be updated and create a Pull request, expecially the fxcopanalyzers package that has a feed on the nuget.config. I also recently pushed a prerelease bug fixed version of AraHaan.GitInformation as well that I would like to be updated as well (The new prerelease moves everything also to github actions from appveyor).

**Comment by jurre** [comment] 2020-05-06 09:00
I see, I am not super familiar with the nuget part of the codebase but there seem to be some edge cases around prereleases that I'll need to look into, so I'll need to get back to you on this.

**Comment by jurre** [comment] 2020-05-06 09:04
Ah, I think this is because we have some logic in dependabot to only update to a prerelease version if it's related to the version that you have specified.

So we would update `1.0.2` to `1.0.2-preview-96929868`, but we would not update `1.0.1` to `1.0.2-preview-96929868`.

If you specify `1.0.2` as the version to be used, dependabot should pick it up

**Comment by AraHaan** [comment] 2020-05-06 09:09
ah I see, maybe should add an option for the ones that do however as an opt-in.

**Comment by AraHaan** [comment] 2020-05-30 00:18
@jurre question on the dependabot.yml file is it possible to increase the duration from like 1 day to like every hour or so?

**Comment by jurre** [comment] 2020-06-02 19:12
> @jurre question on the dependabot.yml file is it possible to increase the duration from like every day to like every hour or so?

Currently daily is the highest frequency that we support

**Comment by jongio** [comment] 2020-06-20 17:13
@jurre - Could you please have a look at related item #1928, as it doesn't look like the logic you mention above works.  At least not with my tests.  I also created #1926 to track the request to add "update to latest preview" as a feature.

Thank you!
Jon

**Comment by jeffwidman** [comment] 2022-08-23 22:28
Closing as this is partially "works-as-expected" and partially a dupe of #2250

**Closed by jeffwidman** 2022-08-23 22:28 UTC
Labels: T: bug 🐞
