### ISSUE TITLE
Create an issue when getting any error 

### ISSUE THREAD

**Issue by angeliski** [dependabot/dependabot-core#3626] opened 2021-05-03 15:39 UTC
I currently start the migration to the GitHub-native Dependabot and in some cases my configuration is wrong.

The problem is: I need to will check that to be sure everything is ok. 

Would be really nice if any error in the update process raises an issue to inform that for my team.

ps: I am talking about errors like `private_source_authentication_failure`

**Comment by mwaddell** [comment] 2022-01-29 18:31
Related to #3509 and #4680

**Comment by jeffwidman** [comment] 2022-11-23 21:55
I understand the request here, and the underlying problem makes sense.

That said, I'm going to close this as a duplicate of the more generic "be notified of an error" because there are other ways to do this. In particular some of our current roadmap that I'm not able to share just yet will make it much easier to observe when there's an error.
* #3509

**Closed by jeffwidman** 2022-11-23 21:55 UTC
Labels: T: feature-request
