### ISSUE TITLE
Azure now supports the `<details>` tag

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6453] opened 2023-01-17 20:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

This is no longer accurate:
https://github.com/dependabot/dependabot-core/blob/9df8aec3878641a139b9b63d94e43dbbb125c715/common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb#L148

See https://developercommunity.visualstudio.com/t/add-support-for-the-html-tag-in-markdown/609415#T-N1190213

**Comment by deivid-rodriguez** [comment] 2023-01-18 08:52
I'll close this since it seems like a duplicate of #2537, as per https://github.com/dependabot/dependabot-core/pull/6455#issuecomment-1386545528. Let me know if I got something wrong @jeffwidman 🙏.

**Closed by deivid-rodriguez** 2023-01-18 08:52 UTC
Labels: T: tech-debt ⚙️
