### ISSUE TITLE
Can it be possible to have multiple commits for the same pom.xml file in a single PR

### ISSUE THREAD

**Issue by c86amik** [dependabot/dependabot-core#3093] opened 2021-02-08 10:36 UTC
Hi Dependabot Team,
According to Dependabot-core code, a single PR consists of a single commit. I have changed the code in generic-update-script.rb, that it will raise a single PR and have all the commits clubbed as a single commit in the same PR. I did this change of code to support my organization's infrastructure. But this PR looks very clumsy as I have 10 dependencies which are outdated and all 10 dependencies's Release Notes, ChangeLogs, Commits are clubbed in the same PR. And by the way all the changes are in the same file pom.xml.
Now my requirement is that there will be a single PR, but it will have multiple commits in it. All the commits will not be clubbed rather it will show as individual commit and will not make the PR clumsy. The pain that I am facing now is that it has 10 changes and each changes when gets commit the earlier one gets overridden. As the changes are made in the same **pom.xml** file using the same **commit_id**
So can it be possible?

**Comment by jurre** [comment] 2021-02-08 11:30
It's not currently possible, we hope to add it at some point but don't have a timeline for when we'll be able to get to it.

The issue is being tracked [here](https://github.com/dependabot/dependabot-core/issues/1190), so I'm going to close this out as a duplicate.

**Closed by jurre** 2021-02-08 11:30 UTC
Labels: F: pull-requests, T: feature-request

**Comment by c86amik** [comment] 2021-02-08 15:59
Ok Thanks
