### ISSUE TITLE
Support "*" parameter in folder paths

### ISSUE THREAD

**Issue by petergrau** [dependabot/dependabot-core#1994] opened 2020-04-15 13:11 UTC
We have several plugins in one repo that all have their own `package.json`. We would like to define one directory path that catches all of them - something like: 
``` /libs/*/ ```
That should include then all `package.json` of the libs without having to define an entry for each of them following all the same ruleset.

**Comment by maneetgoyal** [comment] 2020-10-09 10:37
Will be great to have.

Using `lerna` with `yarn workspaces`. Here's my `dependabot.yml`:

```
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
```

When dependabot creates a PR for updating the dependencies that present in only the child packages `root/packages/**/abc`, `root/packages/**/def`, etc., it only updates the `yarn.lock`. Would be great if it updates the `package.json` of the child packages as well (not just the root level `package.json`).

**Comment by Abildtoft** [comment] 2020-10-09 11:53
We have a similar use case (with NX)

Thanks for an awesome tool!

**Comment by alexf101** [comment] 2020-12-10 05:59
In case it's helpful, I suggested some awful hacks to work around this for now here: https://github.com/dependabot/dependabot-core/issues/2178#issuecomment-742259742

**Comment by feelepxyz** [comment] 2020-12-10 10:14
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/2178

This isn't specific to the package manager and requires some deeper changes in the way dependabot fetches the repo contents to work. We've got some ideas around how this will also play into grouped updates.

We don't have any current plans on supporting `nx` unfortunately.

**Closed by feelepxyz** 2020-12-10 10:14 UTC
