### ISSUE TITLE
How to make dependabot to keep same version for multiple Java libraries?

### ISSUE THREAD

**Issue by IvanPizhenko** [dependabot/dependabot-core#6820] opened 2023-03-12 23:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In my build.gradle.kts I have multiple libraries that are released simultaneously with the same version and must be kept that way. How do I make Github's Dependabot to update version of all of them at once, if it has detected that version change on one of the libraries?

Example:
```kotlin
  // these all must have the same version
  kapt("io.javalin.community.openapi:openapi-annotation-processor:5.3.2")
  api("io.javalin.community.openapi:javalin-openapi-plugin:5.3.2")
  api("io.javalin.community.openapi:javalin-swagger-plugin:5.3.2")
  api("io.javalin.community.openapi:javalin-redoc-plugin:5.3.2")
```

So far I have no idea how to achieve this.
If this is completely not supported, could be a good feature to have.

**Comment by yeikel** [comment] 2023-03-13 18:06
If you extract the version as a property, then dependabot should update all of them at once

**Comment by jeffwidman** [comment] 2023-03-14 19:23
Thanks @yeikel!

This sounds like a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/1296
However, @yeikel 's workaround looks reasonable...

**Closed by jeffwidman** 2023-03-14 19:23 UTC
Labels: T: feature-request
