### ISSUE TITLE
Dependabot encountered an unknown error

### ISSUE THREAD

**Issue by PoteRii** [dependabot/dependabot-core#8597] opened 2023-12-12 06:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content
[dependabot.txt](https://github.com/dependabot/dependabot-core/files/13644280/dependabot.txt)

### What you expected to see, versus what you actually saw

instead of rising new PRs we see error in dependabot logs:

updater | Dependabot encountered '5' error(s) during execution, please check the logs for more details.
updater | +------------------------------------------------------+
updater | |            Dependencies failed to update             |
updater | +--------------------------------------+---------------+
updater | | xunit.runner.visualstudio            | unknown_error |
updater | | prometheus-net.AspNetCore            | unknown_error |
updater | | Microsoft.EntityFrameworkCore.Design | unknown_error |
updater | | xunit                                | unknown_error |
updater | | WireMock.Net                         | unknown_error |
updater | +--------------------------------------+---------------+

Full logs:
[logs.txt](https://github.com/dependabot/dependabot-core/files/13644257/logs.txt)

It started happening since last week. At around same time we started using Github Enterprise (with sso) and our own runners (but no runner has dependabot label). Nothing was changed in dependabot.yml file. We see the error for most of the repositories we have

**Comment by PoteRii** [comment] 2023-12-28 18:34
opened ticket with github support as well. issue still persists...

**Comment by brettfo** [comment] 2024-01-03 17:30
Relevant log lines:

```
updater | Running for project [/home/dependabot/dependabot-updater/repo/Space.Service.CoreApiFacade.UnitTests/Space.Service.CoreApiFacade.UnitTests.csproj]
updater |   Running for SDK-style project
updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET
updater |   Determining projects to restore...
updater | /tmp/package-dependency-resolution_R21OCk/Project.csproj : error NU1101: Unable to find package Space.Service.Common.CodeAnalyzers. No packages exist with this id in source(s): nuget.org
updater |   Failed to restore /tmp/package-dependency-resolution_R21OCk/Project.csproj (in 10.16 sec).
updater | 
updater | Build FAILED.
updater | 
updater | /tmp/package-dependency-resolution_R21OCk/Project.csproj : error NU1101: Unable to find package Space.Service.Common.CodeAnalyzers. No packages exist with this id in source(s): nuget.org
updater |     0 Warning(s)
updater |     1 Error(s)
```

Can you share any `NuGet.Config` files in the repo?  The updater is only looking at `nuget.org` for what appears to be a non-public package.

**Comment by PoteRii** [comment] 2024-01-03 17:38
there is no Nuget.Config. We are using GitHub Nuget Registry and we have specified credentials for it in the dependabot.yaml file.
In fact yes, it is looking for private packages on public nuget, but the error does not contain any private package:

updater | Dependabot encountered '5' error(s) during execution, please check the logs for more details.
updater | +------------------------------------------------------+
updater | |            Dependencies failed to update             |
updater | +--------------------------------------+---------------+
updater | | xunit.runner.visualstudio            | unknown_error |
updater | | prometheus-net.AspNetCore            | unknown_error |
updater | | Microsoft.EntityFrameworkCore.Design | unknown_error |
updater | | xunit                                | unknown_error |
updater | | WireMock.Net                         | unknown_error |
updater | +--------------------------------------+---------------+

**Comment by brettfo** [comment] 2024-01-05 20:22
Looking through the logs, the custom github nuget feed is never queried, which makes me think the updater is _only_ considering sources from a `NuGet.config` file, and since that file doesn't exist, it falls back to `api.nuget.org`, so the problem is _probably_ that the feeds specified in dependabot.yml aren't being considered.  I'll keep digging to see if I can figure it out.

**Comment by brettfo** [comment] 2024-01-05 21:46
I created issue #8721 to track this.

**Comment by abdulapopoola** [comment] 2024-01-24 02:26
@PoteRii this should be fixed in #8721 now; can you confirm resolution please?

**Comment by PoteRii** [comment] 2024-01-24 04:46
@abdulapopoola hello, private nuget works, but now we have a different error for which we`ve opened github tichket

**Comment by probitdavid** [comment] 2024-01-24 10:38
It still seems broken for msbuild based projects

**Comment by abdulapopoola** [comment] 2024-01-29 22:02
Sorry to hear that and glad to hear you've opened up a ticket. Closing this out based on the resolution of the primary issue.

@probitdavid ; I do apologize about the regression; we do have folks working round the clock to address the `nuget` issues. It's a top priority for us to ship fixes.

**Closed by abdulapopoola** 2024-01-29 22:02 UTC
Labels: T: bug 🐞, L: dotnet:nuget
