### ISSUE TITLE
add option to ignore requirements file 

### ISSUE THREAD

**Issue by Czaki** [dependabot/dependabot-core#1657] opened 2020-01-29 09:54 UTC
In my python project I would store two requirements files. One most actual and one with minimal version of packages on which project works. I use more recent also for bundling. 

It is possible to add option of ignoring given file to not be checked by dependabot?

**Comment by Czaki** [comment] 2020-03-29 14:21
Any chance?

**Comment by jurre** [comment] 2021-02-25 15:26
This is currently only possible if they are in different folders. We won't be adding support for this right now, but maybe in the future.

**Comment by jwhitlock** [comment] 2022-10-11 22:09
We also have this issue. We store `requirements.txt` and `pyproject.toml` in the root folder, and have a list of bad words (offensive words and trademarks disallowed in user-generated content) in `emails/badwords.txt`. Dependabot processes `badwords.txt` as a requirements file, and searches PyPI for projects with bad words. It's about 250 missing projects and 350 found and processed per dependabot scan. It would be nice to tell Dependabot to skip this file, or do not decend to subdirectories, or skip the `email` directory.

**Comment by deivid-rodriguez** [comment] 2022-10-12 11:59
I think, instead of an option to ignore certain files, it would be better to add a configuration to explicitly define which manifest files you want watched, and when that's defined, don't scan anything other than that.

**Comment by jeffwidman** [comment] 2023-02-05 22:11
Duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2883

**Closed by jeffwidman** 2023-02-05 22:11 UTC
Labels: T: feature-request, L: python:pip, F: language-support, F: noise
