### ISSUE TITLE
Python poetry undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by HariSekhon** [dependabot/dependabot-core#7864] opened 2023-08-22 01:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python poetry

### Manifest location and content before the Dependabot update

`/pyproject.toml`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "11:30"
    groups:
      python-packages:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

Expected to see a useful error message.

Got this raw unhandled code error instead:

```
updater | 2023/08/21 23:48:50 ERROR <job_712118307> undefined method `strip' for nil:NilClass
updater | 
updater |           url = url.strip.gsub(%r{/*$}, "") + "/"
updater |                    ^^^^^^
```

**Comment by HariSekhon** [comment] 2023-08-22 01:28
Reading the code is appears to be caused by this line:

https://github.com/dependabot/dependabot-core/blob/fe7e6aa337d98282afcb6993e01672e8f6fc0faf/python/lib/dependabot/python/update_checker/index_finder.rb#L152C1-L153C50

        def clean_check_and_remove_environment_variables(url)
          url = url.strip.gsub(%r{/*$}, "") + "/"
called here:

https://github.com/dependabot/dependabot-core/blob/fe7e6aa337d98282afcb6993e01672e8f6fc0faf/python/lib/dependabot/python/update_checker/index_finder.rb#L54C60-L54C60

and here:

[dependabot-core/python/lib/dependabot/python/update_checker/index_finder.rb](https://github.com/dependabot/dependabot-core/blob/fe7e6aa337d98282afcb6993e01672e8f6fc0faf/python/lib/dependabot/python/update_checker/index_finder.rb#L28)

Line 28 in [fe7e6aa](https://github.com/dependabot/dependabot-core/commit/fe7e6aa337d98282afcb6993e01672e8f6fc0faf)

 clean_check_and_remove_environment_variables(url) 
which seems to imply that this is a problem of URL being passed in, ie. a possible configuration problem.

Most likely this is caused by a private JFrog Artifactory Cloud url in the pyproject.toml and requires private registry configuration:

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#configuring-private-registries

I think this code needs to be written more defensively to surface better root cause analysis error messages.

**Comment by deivid-rodriguez** [comment] 2023-08-22 03:29
Duplicate of #7431 and #7724. We will be fixing this shortly.

**Closed by deivid-rodriguez** 2023-08-22 03:29 UTC
Labels: T: bug 🐞

**Comment by HariSekhon** [comment] 2023-08-22 15:37
Ah, thanks for the reply, I didn't realize this was possibly also due to the official default PyPI url not being supplied in the config explicitly.
