### ISSUE TITLE
Add support for Gradle Version Catalogs (Gradle 7.0)

### ISSUE THREAD

**Issue by ReginFell** [dependabot/dependabot-core#3121] opened 2021-02-11 09:02 UTC
Gradle 7.0 was released recently and it introduces a new Central Declaration System as well as a new supported format .toml. https://github.com/gradle/gradle/issues/15352

Would be nice if Dependabot supported this.

**Comment by JavierSegoviaCordoba** [comment] 2021-03-10 12:39
I would like that dependabot search for ALL toml files in the project (regardless of the directory or subdirectory the file is in).

**Comment by madhead** [comment] 2021-03-31 22:51
As an expansion for this… 

I was using a trick with a `Versions.kt` file in `buildSrc` hosting all the versions for my project and using it in the build. Take a look at the [example](https://github.com/madhead/ImgMacroBot/blob/master/buildSrc/src/main/kotlin/Versions.kt) in [madhead/ImgMacroBot](https://github.com/madhead/ImgMacroBot):

_buildSrc/src/main/kotlin/Versions.kt_
```kotlin
object Versions {
    const val JVM = "11"

    object Plugins {
        const val KOTLIN = "1.4.21"
        const val DETEKT = "1.15.0"
        const val LIQUIBASE = "2.0.4"
    }

    object Dependencies {
        const val KTOR = "1.5.1"
        const val KOIN = "2.2.2"
        const val KOTLINX_SERIALIZATION = "1.0.1"
        const val TGBOTAPI = "0.30.0"
        const val SKIJA = "0.89.18"
        const val MICROMETER = "1.6.4"
        const val LOG4J = "2.14.0"
        const val JACKSON = "2.12.1"
        const val JUNIT = "5.7.1"
        const val MOCKK = "1.10.6"
        const val LIQUIBASE = "4.3.1"
        const val SNAKEYAML = "1.28"
        const val OJDBC11 = "21.1.0.0"
    }
}
```
And then in any _build.gradle.kts_:

```kotlin
dependencies {
    implementation(platform("org.apache.logging.log4j:log4j-bom:${Versions.Dependencies.LOG4J}"))
    implementation(platform("io.micrometer:micrometer-bom:${Versions.Dependencies.MICROMETER}"))
 
    api("io.micrometer:micrometer-core")
    api("dev.inmo:tgbotapi:${Versions.Dependencies.TGBOTAPI}")
    api("org.jetbrains.skija:skija-linux:${Versions.Dependencies.SKIJA}")
    …
}
```

Dependabot seems not to handle that correctly, check the [repo's insights](https://github.com/madhead/ImgMacroBot/network/dependencies). I don't know if Dependabot actually executes Gradle to parse the dependencies, but seems like it's abilities in parsing them are limited.

Probably, if it executed full-featured Gradle it could handle any scenarios like mine or like the new central declaration system.

**Comment by huehnerlady** [comment] 2021-04-27 14:50
@madhead that sounds like a completely different issue. Here we ask for the support of the new gradle feature with toml files and not for the buildSrc workaround. Maybe it makes sense to open a separate issu for that?

**Comment by JavierSegoviaCordoba** [comment] 2021-04-27 15:47
Another thin, a Version Catalog can be published, and you can add them to whatever project you want via settings.gradle files:

```
dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }

    versionCatalogs {
        create("libs") { from("com.example.catalogs:some-catalog:1.0.0") }
    }
}
```

So should be great dependabot can search for updates for them.

**Comment by madhead** [comment] 2021-04-27 15:49
Take it easier!

My point is not about that particular `buildSrc` example, it's just an example. I'm trying to add a comment that if only Dependabot actually **evaluate the build script** and extract the versions from the model, it could support all the scenarios, including this new TOML feature and aforementioned `versionCatalogs`.

* I don't know how does Dependabot work currently, but it seems like it [uses](https://github.com/dependabot/dependabot-core/blob/main/gradle/lib/dependabot/gradle/file_parser.rb) a bunch of regexps to parse the scripts. I understand it could be the only option - evaluating a build scripts needs a Java, which might be unacceptable, but it's just an idea.

**Comment by tbroyer** [comment] 2021-04-27 16:15
@madhead There's #1164 already. It wouldn't tell Dependabot which file to _update_ though, for automatic pull requests.

**Comment by madhead** [comment] 2021-04-27 16:18
@tbroyer, yep, looks exactly what I was talking about! And, yeah, updates are almost impossible with this approach.

**Comment by JavierSegoviaCordoba** [comment] 2021-04-27 16:44
Anyway, having dependencies in buildSrc is not only a bad practice, there are unlimited ways to organize them there, so it is really difficult to cover all use cases.

Knowing version catalogs will be the standard way for dependency management, I think there is no sense in searching a way to get it working in buildSrc.

**Comment by DanySK** [comment] 2021-05-12 11:15
There's a bit of confusion. There are two different issues at hand:
1. supporting the central declaration system;
2. supporting Gradle fully.

Although 2. (see #1164 as @tbroyer suggests) would likely cover both, adding 1. first would be useful in many cases and easier.

**Comment by ReginFell** [comment] 2021-05-12 12:27
Yeah, parsing toml should be relatively simple task since dependabot already has this for Python

**Comment by huehnerlady** [comment] 2021-05-12 12:47
I would say the ultimate goal is to support gradle fully. if this could be done in the near future, then no need for the central dependencies. BUT as it does not seem to be near I would say it might be a very good way to migrate towards more support of gradle-kotlin-dsl :)

**Comment by huehnerlady** [comment] 2021-06-11 14:37
Is there any update on this? Would be great to have this feature and I thought someone mentioned it should not be tooo much work?

**Comment by jurre** [comment] 2021-06-11 14:40
It's not currently on our roadmap, I'm not sure who said that, but it seems like a significant amount of work from a quick glance

**Comment by DanySK** [comment] 2021-06-11 14:45
@jurre, the comparison was being made with the proposal for going through the Gradle Tooling API #1164; my feeling is that the amount of work required to support the central declaration in a TOML file would be way smaller...

**Comment by jurre** [comment] 2021-06-11 14:47
> @jurre, the comparison was being made with the proposal for going through the Gradle Tooling API #1164; my feeling is that the amount of work required to support the central declaration in a TOML file would be way smaller...

Yes, I agree that it seems smaller, but still a significant amount of work that we currently don't have planned, so I can't give a timeline

**Comment by DanySK** [comment] 2021-06-11 14:53
I see; thanks for the clarification.

**Comment by be1ski** [comment] 2021-06-11 14:58
@jurre we are very sad to hear that 🥲 maybe you have at least an approximate date for the appearance of this feature?

**Comment by StefanOltmann** [comment] 2021-06-11 14:59
Sad. Dependabot does not work with Gradle in most use cases.

**Comment by jurre** [comment] 2021-06-11 15:01
@asciimike would be the best person to help answer that, but I don't think there is much we can commit to at this point

**Comment by DanySK** [comment] 2021-06-11 15:02
@StefanOltmann @be1ski one way around that is to manage dependencies via [refreshVersions](https://github.com/jmfayard/refreshVersions/) and automatic upgrades via [UpGradle](https://github.com/DanySK/upgradle). I'm currently achieving dependabot-like functionality this way, while I wait for support to Gradle to be complete.

**Comment by JavierSegoviaCordoba** [comment] 2021-06-11 16:59
I am being forced to generate the TOML files from code inside `build.gradle.kts` files to get dependabot working.

**Comment by Nambers** [comment] 2021-07-10 03:11
Is there any update on this? Would be great to have this kind of feature like supporting the toml or buildSrc in gradle.
But my dependabot look like dont get my toml file.

**Comment by asciimike** [comment] 2021-07-13 00:36
No updates on timeline, as we don't have the gradle expertise or time at present to properly prioritize this (or #1164, which would be even better). If folks are interested in working on this, let us know.

**Comment by dmedinag** [comment] 2021-07-16 09:03
I have to add myself to the interested parties in seeing this happen. TOML catalogs introduce a massive leap forward in dependency management for frameworks developed with gradle and since we're using my team and I have had to say goodbye to Dependabot :( We'd love to have it back in our project.

**Comment by DanySK** [comment] 2021-07-16 09:30
@dmedinag as soon as the refreshVersions plugin will support TOML catalogs, UpGradle will provide Dependabot-like functions for Gradle projects through refreshVersions.

**Comment by tbroyer** [comment] 2021-07-16 09:50
@DanySK Dependabot powers GitHub's security alerts, it's not only about having automatic updates through pull requests.

**Comment by DanySK** [comment] 2021-07-16 10:19
@tbroyer sure, but if @dmedinag is dropping all of Dependabot functionality, in that way at least he can get updates back.
Having dependabot supporting Gradle better would be great for me too (that's why I'm following the discussion here...).

**Comment by jurre** [comment] 2021-07-16 11:38
> @DanySK Dependabot powers GitHub's security alerts, it's not only about having automatic updates through pull requests.

These are currently actually separate systems, Alerts power security updates, but dependabot is not used to scan for alerts at this time. (We hope to bring those systems implementations together at some point, but we've not been able to prioritize it)

**Comment by tbroyer** [comment] 2021-07-16 11:53
@jurre As someone who would like alerts, and doesn't really care about automatic updates, is the code open source and could I contribute to it to add support for those TOML files?

**Comment by jurre** [comment] 2021-07-16 12:36
> @jurre As someone who would like alerts, and doesn't really care about automatic updates, is the code open source and could I contribute to it to add support for those TOML files?

Nope, unfortunately all of that is private :(

**Comment by tbroyer** [comment] 2021-07-16 13:27
And for Alerts, lockfiles would be great (and even better, when used): https://docs.gradle.org/current/userguide/dependency_locking.html

**Comment by plastiv** [comment] 2021-11-16 12:06
For people who stumbled across this issue I would like to let you know that Renovate Bot supports Gradle Versions Catalogs as of Sep 2021 https://github.com/renovatebot/renovate/issues/8692#issuecomment-911897526

I hope I don't violate TOC by advertising competitors 😄 .

**Comment by rr-nick-tan** [comment] 2022-01-08 17:16
hi dependabot team, do you have any plan to have it support this year 2022? otherwise, i will have to switch to renovatebot.

**Comment by kimble** [comment] 2022-01-17 21:57
Version catalogs are becoming stable in Gradle 7.4 https://docs.gradle.org/7.4-rc-1/release-notes.html

**Comment by TWiStErRob** [comment] 2022-03-24 17:50
@jurre can you please comment on whether this is going to be supported?

- [ ] I think at the bare minimum the conventional default `libs.versions.toml` could be supported  
       as mentioned by @ReginFell toml support is there in python,
- [ ] and then multiple/different file names and locations as \#2 put it
- [ ] then maybe `settings.gradle(.kts)` definition (hardcoded),
- [ ] then maybe `settings.gradle(.kts)` definition (imported) as separate future improvements?

It doesn't have to be full-on immediate support, but Gradle is so widely used that even the slightest support would help a lot of projects, right?

**Comment by GrahamBorland** [comment] 2022-03-24 19:34
FWIW I recommend [Renovate](https://github.com/renovatebot/renovate) which works beautifully with version catalogs. (I have no affiliation, just a happy user.)

**Comment by gesellix** [comment] 2022-07-16 14:24
What about GitHub/Dependabot working together with Renovate, combining code bases (or create a shared lib for both tools) and ultimately making Dependabot recognize Gradle's Version Catalogs?

We all probably don't want or even need _the perfect solution_, which might be impossible given Gradle's rich dependency model and feature set.

**Comment by JavierSegoviaCordoba** [comment] 2022-07-16 16:35
That implies GitHub or Microsoft buying Renovate company (supposing Renovate company wants to allow that)

**Comment by TWiStErRob** [comment] 2022-07-16 19:23
Yeah Mend is a competitor to GitHub on many fields. On the competitor side, acquisition seems unlikely, because Renovate was just acquired a few years ago, and have been rebranded and integrated recently.

But in an ideal world the two companies would work together to create something better for the users, or at least compete 🤔. As it currently stands, GitHub's solution discourages/blocks progress in the Java/Kotlin ecosystem. 🥺

**Comment by boohba** [comment] 2022-07-16 20:00
> Yeah Mend is a competitor to GitHub on many fields. On the competitor side, acquisition seems unlikely, because Renovate was just acquired a few years ago, and have been rebranded and integrated recently.
> 
> But in an ideal world the two companies would work together to create something better for the users, or at least compete 🤔. As it currently stands, GitHub's solution discourages/blocks progress in the Java/Kotlin ecosystem. 🥺

Microsoft just hates Java because they know that it's better than C#

**Comment by jurre** [comment] 2022-07-25 18:34
> @jurre can you please comment on whether this is going to be supported? Gradle 7.4 is out, the feature is stable.

Hey, apologies for the late response, I've been out on parental leave for the last few months.

Yes, it's something that we want to support, but I can't speak to the timeline unfortunately. Is there anything you can point to to gauge adoption within the community? It would help a lot with prioritization.

**Comment by colintheshots-meetup** [comment] 2022-07-25 20:49
I can't speak for the entire community or every production project, but here at Meetup we've had a new app in production for more than a year now using Gradle version catalogs exclusively. We're never going back to the old ways.

**Comment by PaulWoitaschek** [comment] 2022-07-25 22:21
The same at Yazio. I don't think there is a way to pull statistical data here. 

However: Version catalogs is the standard way to go. Afaik this is the one single recommendation that Gracle gives on how to manage dependency Versions. 

So now that it's no longer incubating I expect the adoption to only increase. And every project that migrates to Version catalogs will probably also migrate from dependabot to renovate.

**Comment by TWiStErRob** [comment] 2022-07-25 22:22
Every Gradle project I touch I migrate to Version Catalogs as they solve the many issues of the old workarounds and provide a much better support foundation for tooling.

Re community usage:
Opted in: [filename:libs.versions.toml](https://github.com/search?q=filename%3Alibs.versions.toml&type=Code) out of potential adopters: https://github.com/search?q=%22gradle-7.4-bin.zip%22&type=code (this query needs work, not sure why it's not working).

Once the above query works, you should get a full list of support from `"gradle-7.4-bin.zip" OR "gradle-7.4-all.zip" OR "gradle-7.4.1-bin.zip" OR "gradle-7.4.1-all.zip" OR "gradle-7.4.2-bin.zip" OR "gradle-7.4.2-all.zip" OR "gradle-7.5-bin.zip" OR "gradle-7.5-all.zip"`

**Comment by Thunderforge** [comment] 2022-07-25 22:25
For what it's worth, the Fortune 500 company I work for wants to use Version Catalogs, but doesn't want to give up Dependabot.

So it may be a Catch-22: if Dependabot won't support it until it's more popular, it won't be more popular until Dependabot supports it.

**Comment by JakeWharton** [comment] 2022-07-25 22:57
There's a way to pull statistical data but it's GitHub's responsibility to do so, not the community. They're literally sitting on the largest corpus of software projects both public and private. They have the ability to ask things like "How many projects updated in the last 6 months with a `gradlew` file also have a `gradle/libs.versions.toml`" with ease. Or better yet, plot a trend line of adoption. I don't think a bunch of "I use it, too" comments offer anything statistically significant or relevant.

Btw: I use it, too.

**Comment by eygraber** [comment] 2022-07-25 23:21
I don't know if Gradle has any telemetry data on it; I'm assuming that would be useful if they did. 

I've been using version catalogs since they were in preview, and I've been pushing for their adoption to anyone who will listen.

I know @ben-manes has been suggesting that someone (Gradle) assume responsibility for [his plugin](https://github.com/ben-manes/gradle-versions-plugin). Maybe something can be done with that?

**Comment by alwaysbemark** [comment] 2022-07-25 23:26
Gradle version catalogues have been truly life-changing for us, at this stage I would never use anything but for new JVM projects. We use them within settings.gradle files under `dependencyResolutionManagement` rather thanin .toml files but if one is easier to deliver than the other - we're happy to switch.

**Comment by ben-manes** [comment] 2022-07-25 23:34
Since the GitHub Dependency Graph api came out in [beta](https://github.blog/changelog/2022-06-17-dependency-graph-has-a-rest-api-for-submitting-dependencies-detected-at-build-time/), I think the next step is for @JLLeitschuh to deploy a prototype of Gradle's [github-dependency-extractor](https://github.com/gradle/github-dependency-extractor) plugin. That would avoid many of the headaches, but unfortunately there has not been much recent communication around this topic.

**Comment by rciovati** [comment] 2022-07-26 08:07
While I agree with @JakeWharton that it's GitHub's responsibility to obtain and track this data, I ran a couple low-effort and low-confidence queries with Sourcegraph and these are the results:

- 5k+ open source projects reference Gradle 7.4 or 7.5, not including forks ([source](https://sourcegraph.com/search?q=context:global+file:gradle/wrapper/gradle-wrapper.properties+count:all+%227.4%22+OR+%227.5%22+select:repo&patternType=regexp
))
- ~700 repos have a `libs.versions.toml` file ([source](https://sourcegraph.com/search?q=context:global+file:libs.versions.toml+count:all+select:repo&patternType=literal))

These are indeed lower limits as Sourcegraph includes only open source projects

**Comment by jurre** [comment] 2022-07-26 10:00
Thanks @rciovati, of course I am happy to perform a query on our end that includes private repo counts, but I am not entirely sure what the right query would be to get a good idea of what adoption looks like. I see `libs.versions.toml` mentioned, but I also see dependencyResolutionManagement in `settings.gradle` mentioned, should these both be included?

As for the 7.4 or 7.5 version, this does not automatically mean that these projects are using version catalogs right?

I'm not super familiar with gradle so I'm just trying to make sure that I paint a fair picture when I try to get this prioritized 🤷

**Comment by JLLeitschuh** [comment] 2022-07-26 10:18
> Since the GitHub Dependency Graph api came out in beta, I think the next step is for @JLLeitschuh to deploy a prototype of Gradle's github-dependency-extractor plugin. That would avoid many of the headaches, but unfortunately there has not been much recent communication around this topic.

The reason there's not been much communications around this is that I was the one at Gradle spearheading this effort and I left Gradle last January for the Dan Kaminsky Fellowship. I'd personally love to finish this story (or find a company willing to fincance finishing this story) but I'm not personally available until the end of the year.

At this point, the best next step would be for us to get some beta testers for the Gradle Plugin I wrote that pulls the dependency information out of an executing Gradle Build and sends that information to GitHub.

Anyone who is willing to invest time into this and genuinely is willing to contribute and wants to setup a meeting with me to discuss finishing this project, find the link below to my calendly. NOTE: I'm in a bit of crunch time attempting to finish my work that I'm presenting at Black Hat, and DEFCON, so I won't be available until after the second week of August. But if anyone wants to chat after then, feel free to put something on my calendar.

https://calendly.com/jonathan-leitschuh-at-dan-kaminsky-fellowship/30min

**Comment by mikepenz** [comment] 2022-07-26 10:30
As an alternative approach to the above, I've been experimenting with a GitHub action, which would parse the output returned from the Gradle `dependencies` task, making it theoretically work for any gradle project (and it would not require other adoptions to the project). 

You can look at the code here: https://github.com/mikepenz/gradle-dependency-submission (https://github.com/mikepenz/gradle-dependency-submission/blob/main/src/process.ts#L104-L110)
While it works, and would be project independent, there are surely better alternatives, as highlighted above. 

And the dependencies highlighted within the [Dependency Graph](https://github.com/mikepenz/gradle-dependency-submission/network/dependencies)

The problem is that right now most maven packages are not linked to the repositories (even with the `pom.xml` defining the right url), and even worse some dependencies linking to wrong repositories. 
Reported here: https://github.com/community/community/discussions/19492

A second problem seems to be that the dependency graph for maven packages ignores the hierarchy of dependencies and will only render a flat list. Reported here: https://github.com/community/community/discussions/19495

**Comment by rciovati** [comment] 2022-07-26 10:33
>  I see `libs.versions.toml` mentioned, but I also see `dependencyResolutionManagement` in `settings.gradle` mentioned, should these both be included?

@jurre Yes, if you want more precise result you should also include any generic `*.versions.toml` file and the other ways of using the feature that are [mentioned in the doc](https://docs.gradle.org/current/userguide/platforms.html). Declaring dependencies in `libs.versions.toml` is just the simplest way of using Gradle's version catalogs. Arguably that would already be very useful for many people.

> As for the 7.4 or 7.5 version, this does not automatically mean that these projects are using version catalogs right?

Correct, that only means that they have a Gradle version that support version catalogs.

**Comment by bric3** [comment] 2022-07-26 12:19
@jurre Version catalog and `dependencyResolutionManagement` are not mutually exclusive, I think you can count any project that has at least a `gradle/*.versions.toml`, maybe `gradle/*.toml`.

And yes you can count me as well, for public repositories, as well as private ones in my orgs (project created/maintained by other teams).

**Comment by jmfayard** [comment] 2022-07-28 10:43
I think the issue can be marked as resolved, judging by https://github.com/square/okhttp/pull/7386

**Comment by martinbonnin** [comment] 2022-07-28 10:53
@jmfayard that okhttp issue is made by Renovate. This is the dependabot repo.

**Comment by LachlanMcKee** [comment] 2022-07-28 11:30
@jmfayard I believe the main reason that having dependabot work with Gradle versions catalogue is because it has deeper integration with Github

**Comment by huehnerlady** [comment] 2022-11-24 10:26
Is there any update on this? Unfortunately this limits our use of dependabot massively as we are using toml files in most of our repositories :(

**Comment by ben-manes** [comment] 2022-11-24 10:44
@huehnerlady I use [gradle-dependency-submission](https://github.com/mikepenz/gradle-dependency-submission) which works pretty well. While github is confused about where the dependency is defined (so no PRs), it does know the coordinates to provide update and security alerts. I still use [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin) primarily (which is toml compatible) and wanted to leverage github’s security features for a public repository.

**Comment by TWiStErRob** [comment] 2022-11-24 22:27
Wow, workaround^2 :) Man, you need to experience fully-automatic PR-based CI-protected version bumps. Once you go there, there's no way back to accepting anything less. Thanks for highlighting the dependency submission API though, that's a nice feature for security alerts.

I'd like to call out to members, to reiterate that we're not expecting a full-on runtime-friendly fully-full Gradle support, any minimal support (even regex parsing) would be a huge step forward (https://github.com/dependabot/dependabot-core/issues/3121#issuecomment-1077886075).

**Comment by alsutton** [comment] 2023-01-04 15:56
@jurre Any chance you could take a look at https://github.com/dependabot/dependabot-core/pull/6249 which would provide a solution to this issue?

**Comment by warting** [comment] 2023-03-13 07:09
Today is the day my dreams came true! I noticed a few new PR from dependabot in my projects today bumping various kind of libraries in my toml files! :heart:

**Comment by planetf1** [comment] 2023-03-13 14:28
@warting so dependabot now appears to support toml files now? if so yay indeed!

**Closed** 2023-03-13 22:06 UTC
Labels: T: feature-request, L: java:gradle

**Comment by deivid-rodriguez** [comment] 2023-03-13 22:10
As you observed, we added [Gradle Version Catalog support](https://github.blog/changelog/2023-03-13-dependabot-version-updates-keeps-gradle-version-catalogs-up-to-date/) 🎉.

Thanks for your patience! Please report any issues or feature requests over the initial MVP as separate issues :)

**Comment by svenjacobs** [comment] 2023-03-14 08:55
The [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) doesn't seem to be updated yet. Do I need to specify `directory: "/gradle"` in `dependabot.yml` or how does Dependabot distinguish between `build.gradle`, `build.gradle.kts` and `gradle/libs.version.toml`?

**Comment by huehnerlady** [comment] 2023-03-14 09:17
I am also looking for a documentation what the MVP is actually supporting in regards to toml files.
As @svenjacobs says are there special requirements that needs to be met in order to get it to work? 

And are only versions supported, or also plugins and libraries for example, documented [here](https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format)?

**Comment by alsutton** [comment] 2023-03-14 11:12
For those who want some docs, we've just deployed dependabot on our version catalogue for Gradle and we're getting update PRs. The only thing we needed to do was create `/.github/dependabot.yml` in our repo with the following contents;

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
```

**Comment by deivid-rodriguez** [comment] 2023-03-14 11:27
Hei, sorry for the lack of documentation, we have some updates there but we haven't been able to deploy them yet.

This initial version supports updating the "standard" version catalog file `gradle/libs.versions.toml`, and it supports updating versions, plugins and libraries. Other setups configuring custom catalogs at `settings.gradle` are not yet supported.

**Comment by deivid-rodriguez** [comment] 2023-03-14 12:40
No problem!

No, I don't think that's supported either, sorry. We support referencing `versions` as `version.ref` references in plugins or libraries inside the `lib.versions.toml` file. But I don't think accessing versions like that is supported.

The underlying issue is that we don't run Gradle/Java under the hood, so anything that requires evaluating Java code is not really supported at the moment.

**Comment by danielstravito** [comment] 2023-03-14 14:11
> We all probably don't want or even need _the perfect solution_, which might be impossible given Gradle's rich dependency model and feature set.

As noted in the PR, the full dependency version used for different configurations can be found in Gradle lockfiles that are easily parsable, so this is far from _impossible_.

Using `libs.versions.toml` for dependency tracking is kind of like using `package.json` instead of `package-lock.json` in JS, or `Cargo.toml` instead of `Cargo.lock` in Rust. Haven't used DependaBot with those languages, if they don't use the lock-files in those cases, then this comment can be disregarded.

Documentation on Gradle lockfiles can be found [here](https://docs.gradle.org/current/userguide/dependency_locking.html).

**Comment by deivid-rodriguez** [comment] 2023-03-14 19:03
Docs have also been updated now to mention the scope of the current support: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file (footnote number 3 in package-ecosystem table).

**Comment by tjuszczyk** [comment] 2023-03-23 15:00
> This initial version supports updating the "standard" version catalog file `gradle/libs.versions.toml`, and it supports updating versions, plugins and libraries. Other setups configuring custom catalogs at `settings.gradle` are not yet supported.

@deivid-rodriguez  Is there any. scheduled plan to support additional `gradle/*.toml` files as well as a default one?

**Comment by tjuszczyk** [comment] 2023-03-23 15:51
With `gradle/libs.versions.toml` supported, wouldn't supporting list of `gradle/*.toml` be simple addition?

**Comment by deivid-rodriguez** [comment] 2023-03-23 16:06
It shouldn't be too hard, but we still need to parse the configuration in `settings.gradle`, which is written if Groovy. Given the dynamic nature of it, there's probably a few different ways to configure it, so it might get tricky, but we'd gladly review a PR implementing it. We already parse `settings.gradle` from Ruby for other things.

**Comment by Kernald** [comment] 2023-08-11 03:31
> It shouldn't be too hard, but we still need to parse the configuration in `settings.gradle`, which is written if Groovy. Given the dynamic nature of it, there's probably a few different ways to configure it, so it might get tricky, but we'd gladly review a PR implementing it. We already parse `settings.gradle` from Ruby for other things.

Note that this file might be written in Kotlin as well - our repo has a `settings.gradle.kts` containing a version catalog. I guess the next step for us is to migrate that one to a toml until #1164.

**Comment by Kernald** [comment] 2023-08-11 05:01
> Hei, sorry for the lack of documentation, we have some updates there but we haven't been able to deploy them yet.
> 
> This initial version supports updating the "standard" version catalog file `gradle/libs.versions.toml`, and it supports updating versions, plugins and libraries. Other setups configuring custom catalogs at `settings.gradle` are not yet supported.

@deivid-rodriguez while I understand that there's not a lot of focus on this with priority on #1164, is there any chance this could be slightly expanded to cover `gradle/*.versions.toml` instead? Gradle's documentation shows how projects might use different version catalogs, e.g. [here](https://docs.gradle.org/current/userguide/platforms.html#sec:sharing-catalogs) example 15. This specific example is in Groovy, but applies just the same to toml - by having different files. The goal being to have different sets of dependencies (e.g. a test-only catalog).

**Comment by koppor** [comment] 2025-04-20 17:28
> Docs have also been updated now to mention the scope of the current support: [docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) (footnote number 3 in package-ecosystem table).

Can you guide us where to find this footnote?

I don't see a footnote as of 2025-04-20:

![Image](https://github.com/user-attachments/assets/fa7d1817-b3f5-49f0-bceb-89aa3c3c9f68)
