### ISSUE TITLE
Dependabot not updating for all github actions

### ISSUE THREAD

**Issue by uayevan** [dependabot/dependabot-core#6235] opened 2022-11-30 11:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

```
version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

Does Dependabot expect all Github actions to be of consistent version throughout? In my codebase, I have `actions/checkout@v3` everywhere, but in one file, there's `actions/checkout@v2` instead. I was expecting to have a pull request made to update that to v3, however, Dependabot gives this as output:
```
updater | INFO <job_528016779> Checking if actions/checkout 3 needs updating
  proxy | 2022/11/30 11:18:10 [108] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/30 11:18:10 [108] * authenticating git server request (host: github.com)
  proxy | 2022/11/30 11:18:10 [108] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
updater | INFO <job_528016779> Latest version is 3
updater | INFO <job_528016779> No update needed for actions/checkout 3
```
And nothing is done for the one that is at v2. Does Dependabot naively find the first tag of `actions/checkout` it finds and then go from there? Is there an option that could be set to check each and every single instance of `actions/checkout` and update any if needed?

**Comment by deivid-rodriguez** [comment] 2022-12-01 13:38
Hi @uayevan, this is a duplicate of #3750, make sure to subscribe to that ticket, hopefully it will be resolved soon. Thanks for your report!

**Closed by deivid-rodriguez** 2022-12-01 13:38 UTC
Labels: T: bug 🐞, L: github:actions
