### ISSUE TITLE
Support realtime updates on submodules

### ISSUE THREAD

**Issue by dlip-immutable** [dependabot/dependabot-core#1921] opened 2020-06-19 05:41 UTC
Is there a possibility to support realtime updates for git submodules also?

**Comment by jeffwidman** [comment] 2022-08-31 00:18
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.
 
Closing as a dupe of https://github.com/dependabot/dependabot-core/issues/2207

**Closed by jeffwidman** 2022-08-31 00:18 UTC
Labels: T: feature-request, 💁 service
