### ISSUE TITLE
Better support for multi language, multi module projects

### ISSUE THREAD

**Issue by planetf1** [dependabot/dependabot-core#2102] opened 2019-10-07 12:19 UTC
I have a project at https://github.com/odpi/egeria (well I'm actually experimenting on my fork first) which is primarily a maven project, but contains Java, JavaScript, docker - more no doubt in future.

Currently whilst I can easily configure maven/java support against the repo, for javascript I have to go hunting for each packages.json and add manually by specifying the path

Ditto for docker - we build 7 or so images (driven by maven) during the build, but enabling docker image support means I have to specify the path of every individual docker file

I would like dependabot configuration to be easier - by default run against all docker files in my project, or all package.json. This makes it more resiliant to future change too - such as new docker images being created,

**Comment by infin8x** [comment] 2020-07-20 15:29
Duplicate of #1278 (specifically, supporting wildcards for selecting package manifests)

**Closed by infin8x** 2020-07-20 15:29 UTC
Labels: F: version-updates ⬆️, T: feature-request
