### ISSUE TITLE
dependabot doesn't update quay images

### ISSUE THREAD

**Issue by georgettica** [dependabot/dependabot-core#4500] opened 2021-12-08 09:46 UTC
**Package ecosystem**
docker

**Package manager version**
brew (but is irrelevant)

**Language version**
Irrelevant

**Manifest location and content prior to update**
Irrelevant

**dependabot.yml content**
```
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
//- directory: "/"
//  labels:
//  - "dependency"
//  package-ecosystem: "github-actions"
//  schedule:
//    interval: "daily"
- directory: "/"
  labels:
  - "dependency"
  package-ecosystem: "docker"
  schedule:
    interval: "daily"
```

**Updated dependency**
Irrelevant

**What you expected to see, versus what you actually saw**
I expect that quay.io version updates will create a PR that will bump the version

**Native package manager behavior**
Irrelevant

**Images of the diff or a link to the PR, issue or logs**
no link to PR because none were made

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```
# Dockerfile
FROM: quay.io/app-sre/ubi8-ubi-minimal:8.3-201
# it should update to 8.5-204 at the least
```

```
# dependabot file
version: 2
updates:
- directory: "/"
  labels:
  - "dependency"
  package-ecosystem: "docker"
  schedule:
    interval: "daily"
```

**Comment by jurre** [comment] 2021-12-08 10:38
I think this is caused by quay not correctly implementing pagination according to the docker spec, which causes the library we use for interacting with the registry to not paginate quay responses correctly, it's covered in https://github.com/dependabot/dependabot-core/issues/3989. Will likely need to be fixed upstream, preferably by Quay themselves (but seems unlikely), and otherwise in https://github.com/deitch/docker_registry2/issues/56#issuecomment-869496320.

I'm going to close this issue as I've reopened https://github.com/dependabot/dependabot-core/issues/3989, and that has more context.

**Closed by jurre** 2021-12-08 10:38 UTC
Labels: T: bug 🐞
