### ISSUE TITLE
Incorrect .github.io submodule linking

### ISSUE THREAD

**Issue by Glazelf** [dependabot/dependabot-core#5634] opened 2022-09-05 21:39 UTC
When updating a submodule from a repository including .github.io (or periods in general, I have not done proper testing) the link Dependabot includes doesn't correctly refer to the submodule repository.
## Example
URL refers to https://github.com/Leanny/leanny when it should refer to https://github.com/Leanny/leanny.github.io. This behaviour is consistent between all links to the submodule repository in [the PR](https://github.com/Glazelf/NinigiBot/pull/360).
![image](https://user-images.githubusercontent.com/35176230/188514196-c2af590b-d217-4a09-8214-8ed262b6515a.png)

Made a blank issue instead of a bug report since this doesn't fit in with a specific language or package managing system etc.

**Comment by jeffwidman** [comment] 2022-09-07 00:44
I wonder if this is somehow related to https://github.com/dependabot/dependabot-core/issues/4959? The codepath isn't the same, but the rationale for how the code that cause #4959 may have been trying to protect against something like this? Not sure...

**Comment by jeffwidman** [comment] 2023-02-06 10:29
Closing as a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/1965

**Closed by jeffwidman** 2023-02-06 10:29 UTC
Labels: L: git:submodules, F: pull-requests
