### ISSUE TITLE
pip: manifest files exclusion

### ISSUE THREAD

**Issue by oleks-popovych** [dependabot/dependabot-core#4169] opened 2021-08-25 10:55 UTC
Currently my projects has both `Pipfile` files and `setup.py`. 
`Pipfile`s are used to quickly setup environments and setup.py is for distribution.

But I'd like to update and check only `setup.py` and ignore `Pipfile`. 
Are there is any way to achieve this?

P.S. You product is awesome :)

**Comment by jeffwidman** [comment] 2022-11-24 09:37
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/1657.

Also, my understanding is `setup.py` is deprecated in favor of `pyproject.toml` these days.

**Closed by jeffwidman** 2022-11-24 09:37 UTC
Labels: T: feature-request
