### ISSUE TITLE
Poetry dependency groups not recognized

### ISSUE THREAD

**Issue by stinodego** [dependabot/dependabot-core#5811] opened 2022-09-29 07:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

There is a related issue: #5296

### Package ecosystem

pip

### Package manager version

Poetry 1.2.1

### Manifest location and content before the Dependabot update

/pyproject.toml

### dependabot.yml content

```
version: 2

updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    reviewers: [stinodego]
    assignees: [stinodego]
```

### Updated dependency

pytest-mock `3.7.0` -> `3.9.0`

### What you expected to see, versus what you actually saw

I expect Dependabot to send a PR updating `pytest-mock`, as there is a newer version available and it is directly defined as a dependency in `pyproject.toml`.

When adding `allow` -> `dependency-type: all` to `dependabot.yml`, Dependabot opens a PR as expected.

### Smallest manifest that reproduces the issue

`.github/dependabot.yml`:
```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
```

`pyproject.toml`:
```toml
[tool.poetry]
name = "mypackage"
version = "0.1.0"
description = ""
authors = ["Stijn de Gooijer <stijn@degooijer.io>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.test.dependencies]
pytest-mock = "^3.7.0"
```

**Comment by stinodego** [comment] 2022-09-29 10:20
Thank you! If this is intentional, I would be curious how I could configure Dependabot to update only direct dependencies for both production and development dependencies.

**Comment by deivid-rodriguez** [comment] 2022-09-29 10:52
Haha, that's indeed a very good question 😅, I'll make sure to check on that too.

**Comment by bryanforbes** [comment] 2022-10-03 22:17
I'm also interested in the answer to this question. My dev dependencies haven't had PRs created for them since switching over to the new dev group syntax about a month ago.

**Comment by deivid-rodriguez** [comment] 2022-10-04 09:07
From looking at our Poetry dependency parsing code:

https://github.com/dependabot/dependabot-core/blob/86b4fdf9054552c0ffc4b8ff145f0e65cf4a7473/python/lib/dependabot/python/file_parser/poetry_files_parser.rb#L38-L60

I have no idea how Poetry groups are actually working in some cases, I would say they are completely unsupported as of now 🤔.

**Comment by xaviml** [comment] 2022-10-04 09:51
Hi @deivid-rodriguez ,

I see that dependabot has the concept of "production" and "development", but now that poetry added groups, the "production" dependencies are placed in "tool.poetry.dependencies" (this did not changed), and the "development" dependencies are split among groups that user define "tool.poetry.group.<name_of_the_group>.dependencies".

It seems that the convention for development dependencies is "tool.poetry.group.dev.dependencies", but the poetry user can define any group as mentioned above.

A solution could be to check all dependencies that go into "tool.poetry.dependencies" for "production", and "tool.poetry.group.*.dependencies" for "development".

Hopefully this clarifies how groups work with poetry. In summary, poetry does not have the concept of development dependencies anymore since some dependencies can be specified for test or build for example.

Regards,
Xavi M.

**Comment by deivid-rodriguez** [comment] 2022-10-04 10:16
Yep, that's how I understand it too. And it seems that groups are precisely intended for this, so your suggestion seems the right way to go about this.

<img width="801" alt="Captura de Pantalla 2022-10-04 a las 12 14 56" src="https://user-images.githubusercontent.com/2887858/193794683-3ca0c6ce-b149-4c64-baab-8913758e8b4e.png">

However, I don't see us actually parsing the new ".groups." table, so I would expect groups being ignored for now. Yet people is reporting this to be working, at least in some cases, so I must be missing something.

**Comment by LeeeeT** [comment] 2022-10-09 13:38
I'm having the same issue even with `dependency-type` set to `all`.

Here's my `dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
```

And dependabot updates log:

 ```

  proxy | time="2022-10-09T12:40:23Z" level=info msg="proxy starting" commit=6f55f3cf0a9eb1e73a8e6168f1b0cdfbacc9462b
  proxy | 2022/10/09 12:40:23 Listening (:1080)
updater | 2022-10-09T12:40:23.642199175 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-10-09T12:40:23.660040794 [479636522:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-10-09T12:40:25Z" level=info msg="guest starting" commit=29feba232daab3724961df8a7964dcf315b4c7a1
updater | time="2022-10-09T12:40:25Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=479636522 updater_timeout=45m0s updater_version=0cec954a097e9923346bc4e715f710404937b2cb
updater | I, [2022-10-09T12:40:26.957346 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_479636522> Starting job processing
  proxy | 2022/10/09 12:40:29 [002] GET https://api.github.com:443/repos/LeeeeT/valtypes
  proxy | 2022/10/09 12:40:29 [002] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [002] 200 https://api.github.com:443/repos/LeeeeT/valtypes
  proxy | 2022/10/09 12:40:29 [004] GET https://api.github.com:443/repos/LeeeeT/valtypes/git/refs/heads/main
  proxy | 2022/10/09 12:40:29 [004] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [004] 200 https://api.github.com:443/repos/LeeeeT/valtypes/git/refs/heads/main
  proxy | 2022/10/09 12:40:29 [006] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [006] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [006] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [008] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/pyproject.toml?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [008] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [008] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/pyproject.toml?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [010] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/.github?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [010] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [010] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/.github?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [012] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/docs?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [012] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [012] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/docs?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [014] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/testing?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [014] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [014] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/testing?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [016] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/tests?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [016] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [016] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/tests?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [018] GET https://api.github.com:443/repos/LeeeeT/valtypes/contents/valtypes?ref=856643b93c98dd96f2bf4994aedb798658cecf73
  proxy | 2022/10/09 12:40:29 [018] * authenticating github api request
  proxy | 2022/10/09 12:40:29 [018] 200 https://api.github.com:443/repos/LeeeeT/valtypes/contents/valtypes?ref=856643b93c98dd96f2bf4994aedb798658cecf73
updater | INFO <job_479636522> Finished job processing
updater | time="2022-10-09T12:40:30Z" level=info msg="task complete" container_id=job-479636522-file-fetcher exit_code=0 job_id=479636522 step=fetcher
updater | I, [2022-10-09T12:40:31.339868 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_479636522> Starting job processing
updater | INFO <job_479636522> Starting update job for LeeeeT/valtypes
updater | INFO <job_479636522> Finished job processing
updater | time="2022-10-09T12:40:33Z" level=info msg="task complete" container_id=job-479636522-updater exit_code=0 job_id=479636522 step=updater
```

**Comment by deivid-rodriguez** [comment] 2022-10-22 09:20
Just checked again against the repo reported by @LeeeeT and poetry groups are simply ignored, `dependency-type` does not seem to play any role here. So I'll update the issue title to reflect this.

**Comment by deivid-rodriguez** [comment] 2022-10-22 09:23
Actually, if this is simply that groups are not supported, which seems the case, this is a duplicate of #5296. So I'll close this ticket in favor of #5296. Please subscribe to that other issue for updates!

**Closed by deivid-rodriguez** 2022-10-22 09:23 UTC
Labels: T: bug 🐞, L: python:poetry, F: version-updates ⬆️
