### ISSUE TITLE
Support wildcard/glob patterns in directory config

### ISSUE THREAD

**Issue by clxmstaab** [dependabot/dependabot-core#1958] opened 2020-06-19 14:02 UTC
when working with the very popular [Composer bin plugin](https://github.com/bamarni/composer-bin-plugin) to isolate your dependencies in a php and composer depenency manager context, the resulting file structure in your repo looks like

```
vendor-bin/
├── churn-php
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
├── clx-active-record-fixer
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
├── php-cs-fixer
│   ├── composer.json
│   ├── composer.lock
│   └── vendor
└── phpstan
    ├── composer.json
    ├── composer.lock
    └── vendor
```

this means for every dependency/tool I managed via the "Composer bin plugin" today, I need to configure a separate pattern in my `dependabot.conf`.

in our usual projects this looks like

```
version: 2
updates:
  -   package-ecosystem: composer
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: npm
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/churn-php/
      versioning-strategy: increase
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/clx-active-record-fixer/
      versioning-strategy: increase
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/php-cs-fixer/
      versioning-strategy: increase
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/phpstan/
      versioning-strategy: increase
      schedule:
        interval: daily
```

the number of entries grows with the number of dependencies managed via "Composer bin plugin".

things would get a lot easier if we could glob/wildcard patterns in the `directory` config. when glob/wildcard patterns would be supported our `dependabot.conf` could get simplified to 

```
version: 2
updates:
  -   package-ecosystem: composer
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: npm
      directory: /
      schedule:
        interval: daily

  -   package-ecosystem: composer
      directory: /vendor-bin/*/
      versioning-strategy: increase
      schedule:
        interval: daily
```

see the `directory: /vendor-bin/*/` line which would contain "all the magic".

**Comment by IEvangelist** [comment] 2020-12-03 18:18
I too would like this feature, I was exploring the source code - looking to understand how this works. I noticed that allowing the `directory` to config option to support globbing would really make this much more powerful. Right now we have many repos that have to define an entry per directory, it would be much easier to specify a glob instead.

See #1952

**Comment by feelepxyz** [comment] 2020-12-10 10:13
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/2178

This isn't specific to the package manager and requires some deeper changes in the way dependabot fetches the repo contents to work. We've got some ideas around how this will also play into grouped updates.

**Closed by feelepxyz** 2020-12-10 10:13 UTC
