### ISSUE TITLE
[GOLANG] Better handle major version in branch name for go dependencies

### ISSUE THREAD

**Issue by acabarbaye** [dependabot/dependabot-core#4331] opened 2021-10-20 09:57 UTC
In go, the major version of a dependency can be part of the namespace 
e.g. github.com/shirou/gopsutil/V3
meaning the resulting branch name created by dependabot is `dependabot/go_modules/.../github.com/shirou/gopsutil/v3-3.21.9`
But this is not the case for all packages
e.g. github.com/spf13/viper-1.9.0 -> `dependabot/go_modules/.../github.com/spf13/viper-1.9.0`

The problem is that it is then quite difficult to distinguish the major version from the package name in the first case. I was hence wondering whether it was possible to express the package name with separators different from the ones used by dependabot i.e. `-`, `_` and `/`, or concatenate differently the major version with the package name or remove the major version altogether since the whole version is added later on.

**Comment by brrygrdn** [comment] 2021-11-26 16:21
Hi @acabarbaye, my read of the issue is that you would like to be able to programmatically extract the package name from the Dependabot-created branches, is this correct?

If so, it might be useful to look at this action we have for extracting metadata about branches in GitHub Actions:
https://github.com/dependabot/fetch-metadata

I understand you may not analysing the branch names in GitHub Actions, but it makes use of YAML metadata that Dependabot puts in its commits, e.g https://github.com/dependabot/fetch-metadata/pull/114/commits/93245a5336d2429e548897c55a16276c70ece27e

Does this help with what you are trying to achieve?

**Comment by acabarbaye** [comment] 2021-12-15 11:49
This works well in the context of github actions. However, I am using a different CI system and the only information I have access to is the branch name

**Comment by jeffwidman** [comment] 2022-08-25 04:45
👋 Sorry for the slow response. I understand why you're asking for this, but I'm going to close this as unplanned. 

I'm actually curious what CI system you're using? Because I'm really surprised you're not able to analyse the YAML metadata in the commit as described by @brrygrdn above... that feels like the most straightforward solution here.

**Closed by jeffwidman** 2022-08-25 04:45 UTC
Labels: T: bug 🐞, L: go:modules, needs-info
