### ISSUE TITLE
Too many PRs: Rebase new PR before open a new outdated PR

### ISSUE THREAD

**Issue by hfhbd** [dependabot/dependabot-core#4031] opened 2021-07-08 18:10 UTC
If your code contains more updatable dependencies as configured in the settings (default 5), dependabot won't create more PRs. After merging one PR, dependabot will open a new PR. 
Unfortunately, this new PR is every time out of date. Although dependabot automatically rebases the PR after a few minutes, it still creates a (email) notification and uses your CI minutes for a useless commit. I would expect a rebased PR when dependabot creates a new PR. 

As the issue happens when merging one of 5 PRs, it would be easy to reproduce by using an out of date repo with more than 5 updatable dependencies, start dependabot, and merge 1 PR.

Sample: checkout this out of date [commit](https://github.com/hfhbd/ComposeTodo/commit/cdda7e509a0131b0064a12ddf3037da94ebe791a) and upload to to a new GitHub repository

**Package ecosystem**
Gradle
**Package manager version**
Gradle 7.1
**Language version**
Kotlin
**Manifest location and content prior to update**
build.gradle.kts

**dependabot.yml content**
Nothing special, https://github.com/hfhbd/ComposeTodo/blob/main/.github/dependabot.yml
**Images of the diff or a link to the PR, issue or logs**
https://github.com/hfhbd/ComposeTodo/pull/303

I hope, this issue does affect the _updating logic_, otherwise I will ask GitHub support.

**Comment by saiichihashimoto** [comment] 2021-08-10 17:23
I agree. I reduced dependabot down to one PR at a time, but the second PR it creates is always instantly out of date and requires a rebase.

**Comment by dave-v** [comment] 2022-03-02 12:07
I am having the same problem, except that it doesn't rebase automatically, so every PR that gets raised this way requires a manual rebase command before dependabot rebases it.

**Comment by orien** [comment] 2022-03-28 04:54
We're experiencing the same. It's causing confusion amongst our engineering team and reducing trust in Dependabot.

1. Dependabot raises 5 PRs (`open-pull-requests-limit` default value).
2. One or more of these are merged.
3. Dependabot creates more PRs, each:
   -  include changes from merged Dependabot PRs (looks like multiple libraries are being upgraded).
   -  the base commit is outdated

@asciimike You mention something similar in https://github.com/dependabot/dependabot-core/issues/4163#issuecomment-908415614. Is this issue being tracked? Is it considered  defect?

**Comment by melink14** [comment] 2022-04-19 10:06
Ran into this as well (after changing open PR limit to 1 to avoid extra rebases upon merging) which breaks my auto merging loop since it looks like Dependabot will not update the branch without some action right after creation.

I wonder if the bug here is that when dependabot checks for new updates it prepares to create PRs for all n possible updates even when it can only open <n number of PRs. 

See #4603 where the commit that the new PR was based off of was more than 30 minutes old. This probably means that if the theory in #4163 is correct then there's probably room for optimization since there was a lot of time between update and PR creation.

I wonder if the instrumentation for this has shown any patterns.

**Comment by melink14** [comment] 2022-04-19 11:08
Few more details after observing this a couple more times:

In my case, it seems like the dep was always 1 CL behind (even though I'm sure they were all available from the beginning). Since the pull request being closed and the new commit being merged happen at around the same time. In the majority of cases, it might be enough to wait a short period of time after PR closing before filling the open quota.

In my case, I was able to use another app to issue `@dependabot rebase` command for PRs behind main so at least I won't need manual intervention!

**Comment by jeffwidman** [comment] 2022-08-25 06:38
Related:
* https://github.com/dependabot/dependabot-core/issues/4057

**Comment by jeffwidman** [comment] 2022-10-06 16:50
From https://github.com/dependabot/dependabot-core/issues/5234 which is a duplicate of this:

> The fact that `open-pull-request-limit` is enabled by default is simply one mechanism by which the race condition is systematically produced, exacerbating the severity of the bug.

via @Kurt-von-Laven in https://github.com/dependabot/dependabot-core/issues/5234#issuecomment-1266010274

**Comment by deivid-rodriguez** [comment] 2022-11-16 18:19
Yeah, we believe root cause was fixed but could never reliably reproduce the issue, so we were not fully sure. But nobody has reported this issue again, so I guess we can go ahead and close this. I'll take my chances and do that but feel free to reopen if I'm wrong!

**Closed by deivid-rodriguez** 2022-11-16 18:19 UTC
Labels: T: bug 🐞, L: java:gradle, 💁 service

**Comment by melink14** [comment] 2022-11-16 23:12
It does fix the issue but also makes the 1 PR at a time usecase not useful. Posted full comment at the other issue: https://github.com/dependabot/dependabot-core/issues/5234#issuecomment-1317799375
