### ISSUE TITLE
Support custom folder names for github-actions

### ISSUE THREAD

**Issue by sverhagen** [dependabot/dependabot-core#4024] opened 2021-07-05 08:01 UTC
**Current situation**:

The `github-actions: "package-ecosystem"` does always assume (as implemented [here](https://github.com/dependabot/dependabot-core/blob/2f0db3e851ba2cc43d0b6dcd70da5e69d5b63eb6/github_actions/lib/dependabot/github_actions/file_fetcher.rb)) that the files to be checked by Dependabot are in a folder called `.github/workflows`, even if you override the folder using the `directory` property.

I.e. for `directory: "foo/bar"`, the GitHub Actions are assumed to be in `foo/bar/.github/workflow`.

**Desired situation**:

In our use case we have a repository that provisions other repositories. While this repository has its _own_ `.github/workflow` (which is fine), it also has the GitHub Actions for the repositories to be provisioned, in: `foo/bar/github/workflows`. Since this is inside our source tree, we would like to avoid dotfiles (hence `github` over `.github`), but this is not supported by Dependabot.

**Notes**:

1. I don't think there is much of a real use case for having `foo/bar/.github/workflow` follow the `.github/workflow` pattern. I am not aware of `.github/workflow` having any special meaning to GitHub unless appearing in the root of a repository.
2. I appreciate that a naive solution to the above would be a breaking change, but a less-naive solution could be to check `foo/bar/.github/workflow` for a given `directory: "foo/bar"`, and then to fall back to check "just" `foo/bar`. This would allow me to configure `directory: foo/bar/github/workflows`, which would then first check `foo/bar/github/workflows/.github/workflows`, but then fall back to `foo/bar/github/workflows` as desired.

Thank you for your time and consideration.

**Comment by 0dminnimda** [comment] 2022-08-07 18:27
Is this behavior documented?

**Comment by jeffwidman** [comment] 2022-08-25 09:30
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

I'm going to close this as a dupe of the following:
* https://github.com/dependabot/dependabot-core/issues/5137
* https://github.com/dependabot/dependabot-core/issues/5047

I realize this ticket was filed first, but those have more details/comments, so let's continue the conversation there.

**Closed by jeffwidman** 2022-08-25 09:30 UTC
Labels: T: feature-request
