### ISSUE TITLE
Sorting of authors in composer.lock

### ISSUE THREAD

**Issue by rihardssceredins** [dependabot/dependabot-core#1401] opened 2019-09-23 06:41 UTC
Hey,

First off - really loving Dependabot. It saves us so much time! 👏🏼

I'm wondering why Dependabot is changing the order of authors in composer.lock file? Is there any way to disable that or what do we have to change on our side to be in sync with Dependabot's configuration?

<img width="1348" alt="Screenshot 2019-09-23 at 09 08 01" src="https://user-images.githubusercontent.com/23099574/65404898-26378c00-dde3-11e9-968a-b71144cab82b.png">

**Comment by feelepxyz** [comment] 2019-09-23 08:54
@rihardssceredins 👋 which version of composer are you running locally? We're on 1.9.0 so maybe this is the cause. We're pretty much just doing a composer update.

**Comment by rihardssceredins** [comment] 2019-09-23 10:47
@feelepxyz just validated that everyone on our team is using composer 1.9.0. 🤷🏼‍♂️

**Comment by feelepxyz** [comment] 2019-09-23 13:13
@rihardssceredins ah it's probably because we use this https://github.com/localheinz/composer-normalize - we also set `sort-packages` to `true`: https://getcomposer.org/doc/06-config.md#sort-packages

**Comment by rihardssceredins** [comment] 2019-09-23 13:55
@feelepxyz nice!
We also have `sort-packages` set to `true` in `composer.json`. We don't however use the composer-normalize package you mentioned. I'll look into it but I would say this creates unnecessary changes in composer.json for those not using normalizer. Maybe you can check if composer.json contains normalizer package and only then apply normalizer? Or make normalizing configurable?

**Comment by feelepxyz** [comment] 2019-09-23 15:04
@greysteil it looks like we require [comooser-normalize](https://github.com/localheinz/composer-normalize) in dev, do you know if it always gets run on composer updates?

**Comment by greysteil** [comment] 2019-09-23 15:06
That's just run on our own `composer.json` file.

The changes to our users' lockfiles are likely due to a change by packagist (they re-indexed their packages). If users clear their caches locally then they will see the same changes when running `composer update`. As a result I don't think this is a Dependabot bug, just a slightly annoying transition period for Composer users.

**Comment by feelepxyz** [comment] 2019-09-23 15:09
@greysteil nice one! Looks like that will do it. @rihardssceredins could you confirm clearing your composer cache fixes the issue?

**Comment by rihardssceredins** [comment] 2019-09-24 07:51
@feelepxyz just tried it but the only change in `composer.lock` after following the instructions was a minor package update. No changes to authors for existing packages were made.

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.9
PHP binary path: /usr/local/Cellar/php/7.3.9_1/bin/php 
```

Maybe you have to do the same thing on your end?

**Comment by infin8x** [comment] 2020-07-20 15:21
Closing this as it's unlikely we'll get to it in the foreseeable future. Please feel free to reopen if this work is critical to your scenario.

**Closed by infin8x** 2020-07-20 15:21 UTC
Labels: T: feature-request
