### ISSUE TITLE
non semver docker tags like python:3.9.0-alpine3.12

### ISSUE THREAD

**Issue by vchrisb** [dependabot/dependabot-core#2692] opened 2020-10-28 12:52 UTC
There are many docker image tags that are in the form of `python:3.9.0-alpine3.12` or `golang:1.15-alpine3.12`
In this case `3.9.0` is the python version and `alpine3.12` the actual image version.
I currently don't see a way to use this or similar formats with dependabot.

Maybe having an option to specify a regex for the image tag could be a solution.

**Comment by missedone** [comment] 2021-01-29 08:08
I have similar maybe more complex request, we use openjdk images, Ex. `openjdk:11.0.2-jre-stretch`

* works from `openjdk:11.0.2-jre-stretch` to `openjdk:11.0.3-jre-stretch`
* works from `openjdk:11.0.9-jre-buster` to `openjdk:11.0.10-jre-buster`
* does NOT work `openjdk:11.0.3-jre-stretch` to `openjdk:11.0.10-jre-buster`, note that both the jre and os version gets updated

**Comment by jeffwidman** [comment] 2022-08-25 09:20
Closing as a dupe of https://github.com/dependabot/dependabot-core/issues/2692. I realize that one is newer, but it better describes the problem, so let's use that to track the conversation.

**Closed by jeffwidman** 2022-08-25 09:20 UTC
Labels: T: feature-request
