### ISSUE TITLE
Currently, the dependency is not updated in the multi-project configuration using Gradle's buildSrc.

### ISSUE THREAD

**Issue by kazuyatada** [dependabot/dependabot-core#3288] opened 2021-03-17 09:52 UTC
Dependabot cannot update dependencies on projects built by following the steps in `Creating Multi-project Builds` in Gradle's `Get Started Guides`.
https://docs.gradle.org/current/samples/sample_building_java_applications_multi_project.html

This is the project actually created by the above procedure. I've added the GitHub Dependabot settings to this.
https://github.com/kazuyatada/sample-gradle-multi

As a result, `build.gradle` cannot be detected and an error occurs.
In the configuration using `buildSrc`, the dependencies that are commonly used in multiple projects are described in the `*.gradle` files under `buildSrc/src`, but Dependabot does not refer to the `*.gradle` files under `buildSrc/src`. It is the cause.

I hope Dependabot will also update the `*.gradle` files under `buildSrc/src`.

**Comment by sczerwinski** [comment] 2021-04-10 20:37
Possible duplicate: #2180

**Comment by jeffwidman** [comment] 2022-08-23 18:32
Yep, this is a dupe of #2180

**Closed by jeffwidman** 2022-08-23 18:32 UTC
Labels: T: feature-request, L: java:gradle
