### ISSUE TITLE
Docker: Support ARG FROM

### ISSUE THREAD

**Issue by hfhbd** [dependabot/dependabot-core#4597] opened 2022-01-06 11:06 UTC
**Package ecosystem**
docker
**Package manager version**
"Dockerfile"
**Language version**
docker
**Manifest location and content prior to update**
```docker
ARG HUB=docker.io
FROM ${HUB}/docker:20.10.7-dind
```
**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
```
**Updated dependency**
```docker
ARG HUB=docker.io
FROM ${HUB}/docker:20.10.12-dind
```
**What you expected to see, versus what you actually saw**
Actually, this line does not support ARGs parsing including replacing: https://github.com/dependabot/dependabot-core/blob/b7ad648e8f97d273f6e74650644fa808d5731bb0/docker/lib/dependabot/docker/file_parser.rb#L42
Dependabot should put all `ARG`s in a map and replace the values before executing the regex.
This syntax is valid: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

**Native package manager behavior**
n/a
**Images of the diff or a link to the PR, issue or logs**
n/a, because Dependabot does not detect this line as valid `FROM` syntax, so no dependency was detected.
**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment] 2022-09-15 09:20
I'm temp re-opening due to the reversion (explained in https://github.com/dependabot/dependabot-core/pull/4837) and then closing as a dupe of https://github.com/dependabot/dependabot-core/issues/2057

**Closed by jeffwidman** 2022-09-15 09:20 UTC
Labels: T: feature-request, L: docker, 🍏 core
