### ISSUE TITLE
Errored with the message "Dependabot encountered an unknown error" in WinUi3 app

### ISSUE THREAD

**Issue by Vijorich** [dependabot/dependabot-core#8971] opened 2024-02-03 19:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

.NET 8 C#12 Winui3

### dependabot.yml content

https://github.com/Vijorich/TestWinuiRep/blob/master/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Expected updates from:
Microsoft.Windows.SDK.BuildTools 10.0.22621.756 > 10.0.22621.2428
Microsoft.WindowsAppSDK 1.4.231115000 > 1.4.231219000
WinUIEx 2.0.0 > 2.3.3
Saw:
An unknown error
```
updater | |          Dependencies failed to update           |
updater | +----------------------------------+---------------+
updater | | Microsoft.WindowsAppSDK          | unknown_error |
updater | | WinUIEx                          | unknown_error |
updater | | Microsoft.Windows.SDK.BuildTools | unknown_error |
updater | +----------------------------------+---------------+
```

### Images of the diff or a link to the PR, issue, or logs

```
  proxy | 2024/02/03 19:24:01 proxy starting, commit: e4e44a385413a544e0ec23b81ab7b65458b55b0f
  proxy | 2024/02/03 19:24:01 Listening (:1080)
updater | 2024-02-03T19:24:01.349215770 [782404320:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-02-03T19:24:03Z" level=info msg="guest starting" commit=931b0e2ddcc9b4086b8dc40b5972b92558a9866a
updater | time="2024-02-03T19:24:03Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=782404320 updater_timeout=45m0s updater_version=b656c539dcdc155e9feb19c351a79e0ce7d1befe-nuget
updater | 2024/02/03 19:24:06 INFO <job_782404320> Starting job processing
  proxy | 2024/02/03 19:24:06 [002] GET https://github.com:443/Vijorich/TestWinuiRep/info/refs?service=git-upload-pack
  proxy | 2024/02/03 19:24:06 [002] * authenticating git server request (host: github.com)
  proxy | 2024/02/03 19:24:06 [002] 200 https://github.com:443/Vijorich/TestWinuiRep/info/refs?service=git-upload-pack
  proxy | 2024/02/03 19:24:06 [004] POST https://github.com:443/Vijorich/TestWinuiRep/git-upload-pack
  proxy | 2024/02/03 19:24:06 [004] * authenticating git server request (host: github.com)
  proxy | 2024/02/03 19:24:06 [004] 200 https://github.com:443/Vijorich/TestWinuiRep/git-upload-pack
  proxy | 2024/02/03 19:24:06 [006] POST https://github.com:443/Vijorich/TestWinuiRep/git-upload-pack
  proxy | 2024/02/03 19:24:06 [006] * authenticating git server request (host: github.com)
  proxy | 2024/02/03 19:24:06 [006] 200 https://github.com:443/Vijorich/TestWinuiRep/git-upload-pack
updater | 2024/02/03 19:24:06 INFO <job_782404320> Finished job processing
updater | time="2024-02-03T19:24:06Z" level=info msg="task complete" container_id=job-782404320-file-fetcher exit_code=0 job_id=782404320 step=fetcher
updater | 2024/02/03 19:24:09 INFO <job_782404320> Starting job processing
  proxy | 2024/02/03 19:24:09 [008] GET https://api.nuget.org:443/v3/registration5-gz-semver2/microsoft.windowsappsdk/index.json
  proxy | 2024/02/03 19:24:09 [008] 200 https://api.nuget.org:443/v3/registration5-gz-semver2/microsoft.windowsappsdk/index.json
  proxy | 2024/02/03 19:24:09 [010] GET https://api.nuget.org:443/v3/registration5-gz-semver2/microsoft.windows.sdk.buildtools/index.json
  proxy | 2024/02/03 19:24:10 [010] 200 https://api.nuget.org:443/v3/registration5-gz-semver2/microsoft.windows.sdk.buildtools/index.json
  proxy | 2024/02/03 19:24:10 [012] GET https://api.nuget.org:443/v3/registration5-gz-semver2/winuiex/index.json
  proxy | 2024/02/03 19:24:10 [012] 200 https://api.nuget.org:443/v3/registration5-gz-semver2/winuiex/index.json
  proxy | 2024/02/03 19:24:10 [014] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231115000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:10 [014] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231115000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:10 [016] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.756/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:10 [016] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.756/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:10 [018] GET https://api.nuget.org:443/v3-flatcontainer/winuiex/2.0.0/winuiex.nuspec
  proxy | 2024/02/03 19:24:10 [018] 200 https://api.nuget.org:443/v3-flatcontainer/winuiex/2.0.0/winuiex.nuspec
  proxy | 2024/02/03 19:24:10 [020] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.2.221109.1/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:10 [020] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.2.221109.1/microsoft.windowsappsdk.nuspec
updater | 2024/02/03 19:24:10 INFO <job_782404320> Starting update job for Vijorich/TestWinuiRep
updater | 2024/02/03 19:24:10 INFO <job_782404320> Checking all dependencies for version updates...
updater | 2024/02/03 19:24:10 INFO <job_782404320> Checking if Microsoft.WindowsAppSDK 1.4.231115000 needs updating
  proxy | 2024/02/03 19:24:10 [026] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231115000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:10 [026] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231115000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:11 [030] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231115000/microsoft.windowsappsdk.1.4.231115000.nupkg
  proxy | 2024/02/03 19:24:11 [030] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231115000/microsoft.windowsappsdk.1.4.231115000.nupkg
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0-windows10.0.22621.0 --package-tfms native net6.0-windows10.0.17763.0 net6.0-windows10.0.18362.0 uap10.0 uap10.0.17763 uap10.0.18362 win10-arm64 win10-x64 win10-x86 --verbose
updater | The package is compatible.
  proxy | 2024/02/03 19:24:13 [032] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231219000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:13 [032] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231219000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:13 [034] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231219000/microsoft.windowsappsdk.1.4.231219000.nupkg
  proxy | 2024/02/03 19:24:13 [034] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231219000/microsoft.windowsappsdk.1.4.231219000.nupkg
updater | 2024/02/03 19:24:14 INFO <job_782404320> Latest version is 1.4.231219000
updater | 2024/02/03 19:24:14 INFO <job_782404320> Requirements to unlock all
updater | 2024/02/03 19:24:14 INFO <job_782404320> Requirements update strategy 
updater | Finding updated dependencies for Microsoft.WindowsAppSDK.
  proxy | 2024/02/03 19:24:14 [036] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231219000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:14 [036] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.231219000/microsoft.windowsappsdk.nuspec
updater | 2024/02/03 19:24:14 INFO <job_782404320> Updating Microsoft.WindowsAppSDK from 1.4.231115000 to 1.4.231219000
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj --dependency Microsoft.WindowsAppSDK --new-version 1.4.231219000 --previous-version 1.4.231115000 --verbose
  proxy | 2024/02/03 19:24:15 [040] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [041] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [042] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [042] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [041] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [040] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [046] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [047] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [048] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [046] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [047] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [051] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [052] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [048] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [051] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [052] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [055] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [057] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [058] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [055] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [057] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [060] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [062] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [058] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:15 [064] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [060] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [062] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [066] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [068] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [064] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [070] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [066] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [068] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [072] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [074] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [070] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [076] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [072] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [074] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:16 [076] 200 https://dc.services.visualstudio.com:443/v2/track
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj]
updater |   Running for SDK-style project
updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET
updater |   Determining projects to restore...
updater | /usr/local/dotnet/current/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/tmp/package-dependency-resolution_KoNBcM/Project.csproj]
updater | 
updater | Build FAILED.
updater | 
updater | /usr/local/dotnet/current/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/tmp/package-dependency-resolution_KoNBcM/Project.csproj]
updater |     0 Warning(s)
updater |     1 Error(s)
updater | 
updater | Time Elapsed 00:00:00.59
updater | 
updater |  STDERR: 
updater | 
updater |     Package [Microsoft.WindowsAppSDK] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj].
updater | Update complete.
updater | 2024/02/03 19:24:16 INFO <job_782404320> [Transport] Sending envelope with items [event] 12fe7048a03440009b48d189dc14991a to Sentry
  proxy | 2024/02/03 19:24:16 [082] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/02/03 19:24:16 [082] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/02/03 19:24:16 ERROR <job_782404320> Error processing Microsoft.WindowsAppSDK (Dependabot::DependabotError)
updater | 2024/02/03 19:24:16 ERROR <job_782404320> FileUpdater failed
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:43:in `run'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/03 19:24:16 ERROR <job_782404320> bin/update_files.rb:24:in `<main>'
updater | 2024/02/03 19:24:16 INFO <job_782404320> Checking if WinUIEx 2.0.0 needs updating
  proxy | 2024/02/03 19:24:16 [086] GET https://api.nuget.org:443/v3-flatcontainer/winuiex/2.0.0/winuiex.nuspec
  proxy | 2024/02/03 19:24:16 [086] 200 https://api.nuget.org:443/v3-flatcontainer/winuiex/2.0.0/winuiex.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0-windows10.0.22621.0 --package-tfms net6.0-windows10.0.18362 --verbose
updater | The package is compatible.
  proxy | 2024/02/03 19:24:17 [091] GET https://api.nuget.org:443/v3-flatcontainer/winuiex/2.3.3/winuiex.nuspec
  proxy | 2024/02/03 19:24:17 [091] 200 https://api.nuget.org:443/v3-flatcontainer/winuiex/2.3.3/winuiex.nuspec
updater | 2024/02/03 19:24:17 INFO <job_782404320> Latest version is 2.3.3
updater | 2024/02/03 19:24:17 INFO <job_782404320> Requirements to unlock all
updater | 2024/02/03 19:24:17 INFO <job_782404320> Requirements update strategy 
updater | Finding updated dependencies for WinUIEx.
  proxy | 2024/02/03 19:24:17 [093] GET https://api.nuget.org:443/v3-flatcontainer/winuiex/2.3.3/winuiex.nuspec
  proxy | 2024/02/03 19:24:17 [093] 200 https://api.nuget.org:443/v3-flatcontainer/winuiex/2.3.3/winuiex.nuspec
  proxy | 2024/02/03 19:24:17 [095] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.230822000/microsoft.windowsappsdk.nuspec
  proxy | 2024/02/03 19:24:17 [095] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windowsappsdk/1.4.230822000/microsoft.windowsappsdk.nuspec
updater | 2024/02/03 19:24:17 INFO <job_782404320> Updating WinUIEx from 2.0.0 to 2.3.3
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj --dependency WinUIEx --new-version 2.3.3 --previous-version 2.0.0 --verbose
  proxy | 2024/02/03 19:24:18 [097] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [097] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [099] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [099] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [101] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [101] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [103] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:18 [103] 200 https://dc.services.visualstudio.com:443/v2/track
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj]
updater |   Running for SDK-style project
updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET
updater |   Determining projects to restore...
updater | /usr/local/dotnet/current/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/tmp/package-dependency-resolution_HHfh1J/Project.csproj]
updater | 
updater | Build FAILED.
updater | 
updater | /usr/local/dotnet/current/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/tmp/package-dependency-resolution_HHfh1J/Project.csproj]
updater |     0 Warning(s)
updater |     1 Error(s)
updater | 
updater | Time Elapsed 00:00:00.54
updater | 
updater |  STDERR: 
updater | 
updater |     Package [WinUIEx] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj].
updater | Update complete.
updater | 2024/02/03 19:24:18 INFO <job_782404320> [Transport] Sending envelope with items [event] 0186723e55c64495acd88647d332ddb0 to Sentry
  proxy | 2024/02/03 19:24:18 [106] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/02/03 19:24:18 [106] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/02/03 19:24:18 ERROR <job_782404320> Error processing WinUIEx (Dependabot::DependabotError)
updater | 2024/02/03 19:24:18 ERROR <job_782404320> FileUpdater failed
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:43:in `run'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/03 19:24:18 ERROR <job_782404320> bin/update_files.rb:24:in `<main>'
updater | 2024/02/03 19:24:19 INFO <job_782404320> Checking if Microsoft.Windows.SDK.BuildTools 10.0.22621.756 needs updating
  proxy | 2024/02/03 19:24:19 [113] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.756/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:19 [113] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.756/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:19 [118] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.756/microsoft.windows.sdk.buildtools.10.0.22621.756.nupkg
  proxy | 2024/02/03 19:24:19 [118] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.756/microsoft.windows.sdk.buildtools.10.0.22621.756.nupkg
  proxy | 2024/02/03 19:24:19 [120] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.2428/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:19 [120] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.2428/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:19 [122] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.2428/microsoft.windows.sdk.buildtools.10.0.22621.2428.nupkg
  proxy | 2024/02/03 19:24:19 [122] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.2428/microsoft.windows.sdk.buildtools.10.0.22621.2428.nupkg
updater | 2024/02/03 19:24:19 INFO <job_782404320> Latest version is 10.0.22621.2428
updater | 2024/02/03 19:24:19 INFO <job_782404320> Requirements to unlock all
updater | 2024/02/03 19:24:19 INFO <job_782404320> Requirements update strategy 
updater | Finding updated dependencies for Microsoft.Windows.SDK.BuildTools.
  proxy | 2024/02/03 19:24:19 [124] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.2428/microsoft.windows.sdk.buildtools.nuspec
  proxy | 2024/02/03 19:24:19 [124] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.windows.sdk.buildtools/10.0.22621.2428/microsoft.windows.sdk.buildtools.nuspec
updater | 2024/02/03 19:24:19 INFO <job_782404320> Updating Microsoft.Windows.SDK.BuildTools from 10.0.22621.756 to 10.0.22621.2428
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj --dependency Microsoft.Windows.SDK.BuildTools --new-version 10.0.22621.2428 --previous-version 10.0.22621.756 --verbose
  proxy | 2024/02/03 19:24:20 [126] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [126] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [128] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [128] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [130] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [130] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [132] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/02/03 19:24:20 [132] 200 https://dc.services.visualstudio.com:443/v2/track
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj]
updater |   Running for SDK-style project
updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET
updater |   Determining projects to restore...
updater | /usr/local/dotnet/current/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/tmp/package-dependency-resolution_0Qei1X/Project.csproj]
updater | 
updater | Build FAILED.
updater | 
updater | /usr/local/dotnet/current/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/tmp/package-dependency-resolution_0Qei1X/Project.csproj]
updater |     0 Warning(s)
updater |     1 Error(s)
updater | 
updater | Time Elapsed 00:00:00.58
updater | 
updater |  STDERR: 
updater | 
updater |     Package [Microsoft.Windows.SDK.BuildTools] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/TestWinuiRep/TestWinuiRep.csproj].
updater | Update complete.
updater | 2024/02/03 19:24:21 INFO <job_782404320> [Transport] Sending envelope with items [event] 80b735d0596b4655bcea7216206b18d5 to Sentry
  proxy | 2024/02/03 19:24:21 [135] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/02/03 19:24:21 [135] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/02/03 19:24:21 ERROR <job_782404320> Error processing Microsoft.Windows.SDK.BuildTools (Dependabot::DependabotError)
updater | 2024/02/03 19:24:21 ERROR <job_782404320> FileUpdater failed
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:43:in `run'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/03 19:24:21 ERROR <job_782404320> bin/update_files.rb:24:in `<main>'
updater | 2024/02/03 19:24:21 INFO <job_782404320> Finished job processing
updater | 2024/02/03 19:24:21 INFO Results:
updater | Dependabot encountered '3' error(s) during execution, please check the logs for more details.
updater | +--------------------------------------------------+
updater | |          Dependencies failed to update           |
updater | +----------------------------------+---------------+
updater | | Microsoft.WindowsAppSDK          | unknown_error |
updater | | WinUIEx                          | unknown_error |
updater | | Microsoft.Windows.SDK.BuildTools | unknown_error |
updater | +----------------------------------+---------------+
updater | time="2024-02-03T19:24:21Z" level=info msg="task complete" container_id=job-782404320-updater exit_code=0 job_id=782404320 step=updater
```

### Smallest manifest that reproduces the issue

You can repeat this by creating any WinUi3 application and if you add dependabot to the repository where it resides, it will get errors

**Comment by ChristianGalla** [comment] 2024-02-10 13:36
This looks like a duplicate of #8572

**Closed** 2024-02-21 23:33 UTC
Labels: T: bug 🐞
