### ISSUE TITLE
Bundler: Platform is wrongly removed

### ISSUE THREAD

**Issue by andyw8** [dependabot/dependabot-core#8444] opened 2023-11-21 18:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler 2.4.10

### Language version

Ruby 3.2

### Manifest location and content before the Dependabot update

https://github.com/Shopify/ruby-lsp/blob/main/Gemfile

### dependabot.yml content

https://github.com/Shopify/ruby-lsp/blob/main/.github/dependabot.yml

### Updated dependency

sorbet and releted gems

### What you expected to see, versus what you actually saw

Dependabot is removing the `x64-mingw-ucrt` platform for some reason. It should not.

### Native package manager behavior

Platforms are unchanged.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/Shopify/ruby-lsp/pull/1191/files

**Comment by deivid-rodriguez** [comment] 2023-11-21 19:12
Thanks for reporting!

This is an upstream regression. I just merged the fix at https://github.com/rubygems/rubygems/pull/7170. Will release it and pick up the fix in Dependabot as soon as possible.

**Comment by Bo98** [comment] 2023-11-21 19:16
https://github.com/rubygems/rubygems/pull/7170 will actually make it remove `x64-mingw32` as well - as that's what the original code was intended to do. It's supposed to remove both `x64-mingw-ucrt` and `x64-mingw32` as they are not valid platforms since sorbet-static doesn't support them, but a bug made it so only one was being removed. 

I suppose it depends what the mingw platforms are supposed to be targetting here. If the idea of that lockfile is to support `BUNDLE_WITHOUT=development`, then I've separately described and reported that at https://github.com/rubygems/rubygems/issues/7169.

**Comment by deivid-rodriguez** [comment] 2023-11-21 19:22
Oh, you're totally right, my bad!

For now this is indeed expected, so closing. if this behavior is biting you too @andyw8, feel free to chime in at https://github.com/rubygems/rubygems/issues/7169.

Once Dependabot picks up the fix I pointed to before, Dependabot will also remove `x64-mingw32` as @Bo98 pointed out.

**Closed by deivid-rodriguez** 2023-11-21 19:22 UTC
Labels: T: bug 🐞, L: ruby:bundler
