### ISSUE TITLE
Dependabot pull request linked wrong repository for firebase-admin-python

### ISSUE THREAD

**Issue by zeshuaro** [dependabot/dependabot-core#3171] opened 2021-02-20 01:00 UTC
**Package manager/ecosystem**
pip/Python

**Manifest contents prior to update**
[requirements.txt](https://github.com/nsw-covid19-tracker/functions/blob/5ccebff21f5c32c0bb9203ae698bb6f1815c8de5/requirements.txt) prior to update

**Updated dependency**
`firebase-admin` from `4.5.1` to `4.5.2`

**What you expected to see, versus what you actually saw**
The pull request that Dependabot created linked the wrong repository. It linked [firebase-admin-go](https://github.com/firebase/firebase-admin-go) where it should be linking [firebase-admin-python](https://github.com/firebase/firebase-admin-python). And so the diff tree was also incorrect as it showed the one from `firebase-admin-go`

**Images of the diff or a link to the PR, issue or logs**
[Here](https://github.com/nsw-covid19-tracker/functions/pull/25) is the link to the PR

**Comment by jeffwidman** [comment] 2022-11-23 23:05
👋 sorry for the slow reply.

Is this still an issue? I suspect it was caused by incorrect metadata published to PyPI... I checked https://github.com/firebase/firebase-admin-python/commits/master/setup.py but didn't see any obvious fixes of a typo pointing at the wrong repo, however https://github.com/firebase/firebase-admin-python/pull/613 added a metadata URL that Dependabot will use.

I'm going to close as I'm pretty confident it's fixed by ☝️ but if for some reason I'm wrong, please comment and we can re-open.

**Closed by jeffwidman** 2022-11-23 23:05 UTC
Labels: T: bug 🐞, L: python:pip, F: package-metadata
