### ISSUE TITLE
Update Docker image tags referenced in Java source files (helpful when using Localstack)

### ISSUE THREAD

**Issue by kesslerj** [dependabot/dependabot-core#8075] opened 2023-09-21 19:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We use Localstack when testing our Spring Boot applications to have AWS resources available in Docker containers. We are used to using Dependabot everywhere in the project to update dependencies. Now we've stumbled across that it doesn't seem to be supported to update Docker image tags referenced in Java code.

Here is a simple example snippet: If it helps, I'm also happy to provide an example repository.
```java
  private static final LocalStackContainer localStackContainer;

  static {
    localStackContainer = new LocalStackContainer(DockerImageName.parse("localstack/localstack:2.2.0"))
        .withServices(LocalStackContainer.Service.KMS)
        .withEnv("AWS_DEFAULT_REGION", "eu-central-1");
    localStackContainer.start();
  }
```

I found some other feature requests/issues that also suggest Docker image tag support in other places. The latest ticket seems to me to be this one, which also links the other tickets: #7189

**Comment by yeikel** [comment] 2023-10-15 01:13
This issue seems to be a duplicate of https://github.com/dependabot/dependabot-core/issues/6893

**Comment by deivid-rodriguez** [comment] 2023-10-16 08:10
Thanks @yeikel, closing as a duplicate!

@kesslerj Please what that other issue for updates.

**Closed by deivid-rodriguez** 2023-10-16 08:10 UTC
Labels: T: feature-request
