### ISSUE TITLE
Dependabot fails to open a PR

### ISSUE THREAD

**Issue by ylemkimon** [dependabot/dependabot-core#2411] opened 2020-08-04 13:28 UTC
**Package manager/ecosystem**
JavaScript / Yarn 2

**Manifest contents prior to update**
`package.json`
```json
{
  "devDependencies": {
    "terser-webpack-plugin": "^3.0.6",
    ...
  },
  ...
}
```
https://github.com/KaTeX/KaTeX/blob/master/package.json

`yarn.lock`
```yaml
"terser-webpack-plugin@npm:^3.0.6":
  version: 3.0.8
  resolution: "terser-webpack-plugin@npm:3.0.8"
...
```
https://github.com/KaTeX/KaTeX/blob/master/yarn.lock

**Updated dependency**
[`terser-webpack-plugin`](https://www.npmjs.com/package/terser-webpack-plugin) 3.0.8 -> 3.1.0

**What you expected to see, versus what you actually saw**
Dependabot to open a PR updating `terser-webpack-plugin`

Is this because Dependabot doesn't support Yarn 2 yet? (It did at least open a PR for other dependency.)

**Images of the diff or a link to the PR, issue or logs**
```log
updater | INFO <job_44365479> Checking if terser-webpack-plugin  needs updating
  proxy | 2020/08/04 05:03:10 GET https://registry.npmjs.org:443/terser-webpack-plugin
  proxy | 2020/08/04 05:03:10 200 https://registry.npmjs.org:443/terser-webpack-plugin
  proxy | 2020/08/04 05:03:10 GET https://registry.npmjs.org:443/terser-webpack-plugin/3.1.0
  proxy | 2020/08/04 05:03:10 200 https://registry.npmjs.org:443/terser-webpack-plugin/3.1.0
updater | INFO <job_44365479> Latest version is 3.1.0
  proxy | ...
updater | INFO <job_44365479> Requirements to unlock update_not_possible
updater | INFO <job_44365479> Requirements update strategy widen_ranges
updater | INFO <job_44365479> No update possible for terser-webpack-plugin 
```

**Comment by jonhuteau** [comment] 2020-12-02 10:01
I got similar issue but with Composer. In my `composer.json`

```json
{
  "require": {
    "symfony/string": "5.1.*"
  }
}
``` 

Here are my logs from Dependabot

```
updater | INFO <job_71886561> Checking if symfony/string 5.1.8 needs updating
  proxy | 2020/12/02 07:14:13 [215] GET https://packagist.org:443/p/symfony/string.json
  proxy | 2020/12/02 07:14:13 [215] 200 https://packagist.org:443/p/symfony/string.json
updater | INFO <job_71886561> Latest version is 5.2.0
  proxy | 2020/12/02 07:14:13 [217] GET https://repo.packagist.org/packages.json
  proxy | 2020/12/02 07:14:13 [217] 200 https://repo.packagist.org/packages.json
  proxy | 2020/12/02 07:14:14 [218] GET http://repo.packagist.org/p/provider-latest%247c6a406f1c628e62207a9b16e99a1ab7ad936e7d881360236c293b4bb11f7309.json
  proxy | 2020/12/02 07:14:14 [218] 200 http://repo.packagist.org/p/provider-latest%247c6a406f1c628e62207a9b16e99a1ab7ad936e7d881360236c293b4bb11f7309.json
  proxy | 2020/12/02 07:14:26 [220] GET https://repo.packagist.org/packages.json
  proxy | 2020/12/02 07:14:26 [220] 200 https://repo.packagist.org/packages.json
updater | INFO <job_71886561> Requirements to unlock update_not_possible
updater | INFO <job_71886561> Requirements update strategy bump_versions_if_necessary
updater | INFO <job_71886561> No update possible for symfony/string 5.1.8
```

If I run `composer update --dry-run` I can see 

```
  - Updating symfony/string (v5.1.8) to symfony/string (v5.1.9)
```

There is a PR about Yarn and NPM https://github.com/dependabot/dependabot-core/pull/2732, maybe this need to be implemented for Composer ?

**Comment by jeffwidman** [comment] 2022-08-11 07:28
The update not possible error has a _wide_ range of underlying causes. We actually had it as a focus point last quarter and fixed a number of root causes.

I'm going to close this as it's two years old at this point so decent chance the root cause is fixed, but if you see it happen again, please file another issue and we'll try to take a closer look.

**Closed by jeffwidman** 2022-08-11 07:28 UTC
Labels: T: bug 🐞
