### ISSUE TITLE
Update all poetry.lock dependencies

### ISSUE THREAD

**Issue by l0b0** [dependabot/dependabot-core#4032] opened 2021-07-09 02:50 UTC
Dependabot seems to only update the dependencies listed in pyproject.toml, and not the ones in poetry.lock.

For example, [this repo](https://github.com/linz/template-python-hello-world) is configured to check for Python package updates daily, and last checked 7 hours ago. But when I run `poetry update` a whole bunch of packages are updated:

```text
$ poetry update
Updating dependencies
Resolving dependencies... (11.7s)

Writing lock file

Package operations: 0 installs, 14 updates, 0 removals

  • Updating six (1.15.0 -> 1.16.0)
  • Updating distlib (0.3.1 -> 0.3.2)
  • Updating lazy-object-proxy (1.4.3 -> 1.6.0)
  • Updating attrs (20.2.0 -> 21.2.0)
  • Updating identify (1.5.9 -> 1.6.2)
  • Updating nodeenv (1.5.0 -> 1.6.0)
  • Updating packaging (20.4 -> 21.0)
  • Updating pathspec (0.8.0 -> 0.8.1)
  • Updating py (1.9.0 -> 1.10.0)
  • Updating pyyaml (5.3.1 -> 5.4.1)
  • Updating regex (2020.10.28 -> 2021.7.6)
  • Updating typed-ast (1.4.1 -> 1.4.3)
  • Updating typing-extensions (3.7.4.3 -> 3.10.0.0)
  • Updating virtualenv (20.1.0 -> 20.4.7)
```

I would instead expect all the locked dependencies to be kept up to date.

**Comment by jeffwidman** [comment] 2023-02-04 10:17
👋 Sorry for the slow response.

Dependabot does support bumping deps in the `poetry.lock` file as demonstrated by this test (and other tests in this file):
https://github.com/dependabot/dependabot-core/blob/c9df0dd1bfb671589560584c5b162861da0d5ac5/python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb#L227-L240

However, Dependabot isn't smart enough to unlock multiple deps if multiple packages have to bump simultaneously in order to get past version constraint issues. Ie, if bumping one direct dep would violate constraints in another direct dep, that update will fail. There's a number of tickets to tackle that, #1190 is probably the catch-all, but it's a very tricky problem when you dig into the edge-cases. We've made some progress on it in `npm`, but not for `python`.

If you're not seeing `pyproject.toml` bumps from Dependabot result in `poetry.lock` bumps, please file a new issue with specific examples and a reproducible public repo.

At this point, it's been nearly two years since the example in the original issue happened... does it still reproduce for single dependencies that aren't held back due to the known multi-constraint problem or should we close this?

**Comment by l0b0** [comment] 2023-02-07 04:47
> Dependabot does support bumping deps in the poetry.lock file as demonstrated by this test (and other tests in this file):

As far as I can tell that test at least is irrelevant for this case, because it checks that requests and pytest are updated when `pyproject.toml` references both of these. The original issue is that a package listed in `poetry.lock` *and **not** listed in `pyproject.toml`*, that is, a *dependency* of one of the packages listed in `pyproject.toml`, is not being updated. Is there a test where `pyproject.toml` contains *only* package X, `poetry.lock` contains package X and its dependency, package Y, and an update to package *Y* is updated?

**Comment by deivid-rodriguez** [comment] 2023-02-07 13:29
Hei @l0b0!

By default Dependabot only updates direct dependencies. To update indirect dependencies too, you need to explicitly configure it by using

```
allow:
  - dependency-type: all
```

See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow.

I'm closing this since I believe this is expected behavior, but let me know if you run into any issues or you disagree.

**Closed by deivid-rodriguez** 2023-02-07 13:29 UTC
Labels: T: feature-request, L: python:poetry
