### ISSUE TITLE
How to run the dependabot cli in local or in github action to Scan an image URL and provide suggestions

### ISSUE THREAD

**Issue by arununzer** [dependabot/dependabot-core#7574] opened 2023-07-17 13:14 UTC
Hello Team,

How to run the dependabot cli in local or in github actions Workflow to Scan an image URL and provide suggestions to update the image in the workflow itself without raising a PR.

**Comment by jakecoffman** [comment] 2023-07-24 20:34
Duplicate of https://github.com/dependabot/cli/issues/149

**Closed by jakecoffman** 2023-07-24 20:34 UTC
