### ISSUE TITLE
Allow disabling dependabot on forks

### ISSUE THREAD

**Issue by hauntsaninja** [dependabot/dependabot-core#5914] opened 2022-10-18 05:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

This is a duplicate of https://github.com/dependabot/dependabot-core/issues/2804

However, that issue has been linked to well over a thousand times, so it's impossible to see what the actual status of the issue is (without having to click to expand the fold several hundred times). The last visible comments are over a year ago. Is the team planning to add this? Is there anything I could do to help? Is there a timeline?

**Comment by jurre** [comment] 2022-10-18 19:00
We're actively working on this and a permanent fix should land in the next couple of weeks. We'll share more around the time we''re ready to roll this out

**Comment by jeffwidman** [comment] 2022-10-21 20:37
I'm going to close as a duplicate of https://github.com/dependabot/dependabot-core/issues/2804. I realize that one is a bit noisy/hard to track, but it's still better for everyone if we keep discussion in one place.

**Closed by jeffwidman** 2022-10-21 20:37 UTC
Labels: T: feature-request
