### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by mackoj** [dependabot/dependabot-core#2108] opened 2019-09-24 14:56 UTC
I love the idea of Dependabot but it doesn't work quite well me, it would be great if you could add support for updating iOS dependencies system that are the most used like Swift Package Manager / Carthage / Cocoapods.

Thanks

**Comment by infin8x** [comment] 2020-07-02 16:30
Duplicate of #1245

**Closed by infin8x** 2020-07-02 16:30 UTC
