### ISSUE TITLE
Dependabot does not respect version constraints for pip-compile

### ISSUE THREAD

**Issue by devchakraborty** [dependabot/dependabot-core#4579] opened 2022-01-05 00:35 UTC
I'm not sure how general this issue is – maybe it applies to all `requirements.txt` even without `pip-compile`, or maybe it's something specific to our exact use of `pip-compile`. Any feedback appreciated!

>

**Package ecosystem**
Python (pip-compile)
**Package manager version**
pip-compile 6.4.0
**Language version**
Python 3.8.12
**Manifest location and content prior to update**

We are using a private repository and I can't disclose the full content of these files. We essentially have a `requirements.txt`, `requirements-dev.txt`, and `constraints.txt` that we generate via `pip-compile`.

**dependabot.yml content**

(Truncated & redacted from private repo):

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "[redacted]"
    schedule:
      interval: "weekly"
```

**Updated dependency**

`pyparsing` was updated from `2.4.7` to `3.0.6`.

The relevant path in the dependency tree is:

- `pytest==6.2.5` (via `pytest >= 6.2` required by `pyproject.toml`)
- `packaging` (via `packaging` required by `pytest`)
- `pyparsing==2.4.7` (via `pyparsing>=2.0.2,<3` required by `packaging`)

**What you expected to see, versus what you actually saw**

Expected: We were hoping Dependabot would be aware of version restrictions in the whole dependency tree, preventing it from performing a major upgrade of `pyparsing`.
Actual: Dependabot updates every package in the requirements files to the latest possible, seemingly ignoring dependency constraints.

**Native package manager behavior**

We generate our files using: 

```
pip-compile pyproject.toml --output-file requirements.txt
pip-compile pyproject.toml --extra tests --output-file requirements-dev.txt
pip-compile pyproject.toml --extra tests --strip-extras --output-file constraints.txt
```

This respects version numbers in dependencies.

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Running the above `pip-compile` commands with a `pyproject.toml` with a dependency on `pytest >= 6.2` should yield requirements files that trigger the issue. (I haven't tested this, though, don't have dependabot set up to run locally)

**Comment by deivid-rodriguez** [comment] 2023-10-26 12:17
I think this is a duplicate of https://github.com/dependabot/dependabot-core/issues/5140. That issue is newer, but it includes repro instructions, and a potential approach to fixing it.

So let me close this in favor of the newer issue. If interested, please subscribe to that other ticket!

**Closed by deivid-rodriguez** 2023-10-26 12:17 UTC
Labels: T: bug 🐞, L:python:pip-compile, versioning
