### ISSUE TITLE
Show the original dependency in case of a transient dependency for npm packages

### ISSUE THREAD

**Issue by sampsakuronen** [dependabot/dependabot-core#6405] opened 2023-01-10 06:25 UTC
Could you include the original dependency in the description of a PR in case it's a transient dependency? 

More specifically for the npm ecosystem (`yarn why json5`). Including this information would make it faster to triage the updates based on the description alone. This is especially interesting for automatic security updates and triaging their impact on the project.

**Comment by deivid-rodriguez** [comment] 2023-01-10 10:24
I think it's a nice idea, maybe something like

<img width="907" alt="Captura de pantalla 2023-01-10 a las 11 23 00" src="https://user-images.githubusercontent.com/2887858/211525954-3e5b5738-1728-4a5b-86da-b21f0763ae04.png">

**Comment by jeffwidman** [comment] 2023-02-11 08:26
Closing as a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2125

**Closed by jeffwidman** 2023-02-11 08:26 UTC
Labels: T: feature-request, F: pull-requests
