### ISSUE TITLE
badge issues after switch from dependabot-preview to GitHub's dependabot

### ISSUE THREAD

**Issue by piramiday** [dependabot/dependabot-core#1960] opened 2020-06-18 22:01 UTC
I had set up a badge while using **[dependabot-preview](https://github.com/marketplace/dependabot-preview)**, like so:

> _Originally posted by @greysteil in https://github.com/dependabot/feedback/issues/6#issuecomment-503994253_
So [![Dependabot Status](https://api.dependabot.com/badges/status?host=github&repo=yss14/musicshare)](https://dependabot.com) would be https://api.dependabot.com/badges/status?host=github&repo=yss14/musicshare. For private repos you have to add `&identifer=<the github repo's ID>` onto that.

after I migrated my settings to GitHub, my badge is now showing a gray **inactive**, rather than a green enabled.

is this supposed to happen? should I have updated the code for the badge, post-inclusion in GitHub? if so, how?

**Comment by HonkingGoose** [comment] 2020-09-07 13:28
@feelepxyz @piramiday This issue (#1960) is a duplicate of #1912, I'll leave it to the maintainers to decide on how/if to resolve the duplication.

**Comment by jeffwidman** [comment] 2022-09-22 19:49
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/1912

**Closed by jeffwidman** 2022-09-22 19:49 UTC
Labels: T: bug 🐞, 💁 service, F: Compatibility score
