### ISSUE TITLE
Add private NuGet feeds for GitHub-native dependabot in a global setting

### ISSUE THREAD

**Issue by jasonycw** [dependabot/dependabot-core#3312] opened 2021-03-22 02:53 UTC
We've been using dependabot for quite some time through https://app.dependabot.com/

Recently, I'm testing on GitHub native dependabot but I found 1 key feature is missing

On dependabot dashboard, under `Config variables`, there are options for us to add our own NuGet feed. 
We have some NuGet package put under our GitHub Team private feed and by adding the feeds' URL in dependabot dashboard, `dependabot-preview` can create PR for our private package properly
![image](https://user-images.githubusercontent.com/4518597/111933922-6ae8d400-8afb-11eb-92b0-35ffc3d43bc8.png)

It seems that there is no such option to add `Config variables` for the GitHub-native version, is this feature missing or is it hidden somewhere else?
![image](https://user-images.githubusercontent.com/4518597/111933394-57893900-8afa-11eb-955f-f3bd6c7a8859.png)

I know we can add `./.github/dependabot.yml` to [setup the repositories one by one](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates), but we would prefer one global setting like the one in https://app.dependabot.com/accounts/{github}/config-variables

If there is no such option in GitHub-native version, we may need to go back to https://app.dependabot.com/ for now since we don't have time to setup `.yml` for all of our repos again.

**Comment by jasonrudolph** [comment] 2021-03-22 14:29
I _think_ @jurre's reply will resolve this issue, so I'm going to close this out. If this doesn't resolve the issue, please let us know, and we'll follow up. :bow:

**Comment by jasonycw** [comment] 2021-03-23 03:42
Hi @jurre and @jasonrudolph thanks for the reference, but it's still not quite the same as what I want.

Instead of just setting a secret and then adding `dependabot.yml` into each repository one by one, I am looking for a global setting place for managing the GitHub-native dependabot.

There are many global settings under https://app.dependabot.com/accounts/{github}/config-variables and https://app.dependabot.com/accounts/{github}/config-variables which apply to all repositories without the need to manually set it for every single one of them.
![image](https://user-images.githubusercontent.com/4518597/112088368-aa322600-8bca-11eb-8038-cc39dcc5d4ca.png)
![image](https://user-images.githubusercontent.com/4518597/112088410-bc13c900-8bca-11eb-9d5f-1820c66a3fd5.png)
![image](https://user-images.githubusercontent.com/4518597/112088498-e4032c80-8bca-11eb-9f46-03ada94c8072.png)

With the above settings, all repository managed by `dependabot-preview` will automatically now the NuGet feeds without me going into each repo and update any `dependabot.yml`.

If there are some more global config for dependabot under https://github.com/organizations/{github}/settings/security_analysis then that will be much better than the current repository by repository approach.

**Comment by jasonrudolph** [comment] 2021-03-23 15:05
> Hi @jurre and @jasonrudolph thanks for the reference, but it's still not quite the same as what I want.

Thanks for the clarification, @jasonycw. That _does_ sound useful. ✨  I'm re-opening this issue so that we can track it as a feature request.

**Comment by asciimike** [comment] 2021-04-12 18:34
I'm going to close this as a dupe of the more generally requested https://github.com/dependabot/dependabot-core/issues/3312, since it's the same feature (one registry config per org).

**Closed by asciimike** 2021-04-12 18:34 UTC
Labels: T: feature-request

**Comment by AraHaan** [comment] 2021-04-12 18:37
Closed it out as a dupe of itself man 😂.

**Comment by asciimike** [comment] 2021-04-12 18:38
Ugh, my copy/paste is all wonky today. #3360 is what I meant.

**Comment by AraHaan** [comment] 2021-04-12 19:21
Thanks, also for me I use a repository level nuget.config and dependabot seems to respect it as well.

Perhaps the issue creator could use that too? Plus if they use any CI's the CI's would use it as well too so it could be considered a bonus for that option too.
