### ISSUE TITLE
Dependabot not respecting private registry config

### ISSUE THREAD

**Issue by dermyhughes** [dependabot/dependabot-core#4275] opened 2021-10-01 10:15 UTC
**Package ecosystem**
npm

**dependabot.yml content**
```
version: 2
registries:
  my-nexus-registry:
    type: npm-registry
    url: https://[url-to-nexus-registry]
    username: ${{secrets.PRIVATE_REPOSITORY_USERNAME}}
    password: ${{secrets.PRIVATE_REPOSITORY_PASSWORD}}
updates:
  - package-ecosystem: npm
    directory: '/'
    registries:
      - my-nexus-registry
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 10
    target-branch: develop
```

**What you expected to see, versus what you actually saw**
I expect Dependabot to update dependancies using the private registry as set in the dependabot.yml file, but Dependabot continues to use the public npm registry (https://registry.npmjs.org) for public packages.
Dependabot _will_ use the private registry for private packages which are only available on the private Nexus registry but I want Dependabot to use that registry for _all_ packages.

**Comment by jurre** [comment] 2021-10-01 11:04
To enforce this you could check in an `.npmrc` with:

```
registry=https://[url-to-nexus-registry]
```

I think that should work, lmk if it doesn't!

I'm wondering, is dependabot "downgrading" your dependencies from the private registry to the public one?

**Comment by dermyhughes** [comment] 2021-10-01 13:00
Thanks @jurre. I thought Dependabot created a temporary `.npmrc` file for this purpose. I was trying to avoid using a repo level `.npmrc` to avoid issues with env variables my local use and our CI pipeline.

**Comment by Jonny-Cornwell-i2** [comment] 2022-04-21 17:31
We are also seeing the same behaviour, we already have a `.npmrc` file with the registry set and the `dependabot.yml` file is practically identical to the original report. Was wondering if anything has progressed and there is a way to get dependabot to always use the configured registry?

**Comment by jeffwidman** [comment] 2022-09-17 10:44
I suspect this is a duplicate of https://github.com/dependabot/dependabot-core/issues/4669 but not sure... @dermyhughes / @Jonny-Cornwell-i2 do they sound like the same issue to you? If so I'll close this one as it has less info than that one.

**Comment by dermyhughes** [comment] 2022-09-20 07:16
@jeffwidman Yes, that seems to be the same issue that I originally reported.

**Comment by jeffwidman** [comment] 2022-09-22 06:32
Closing as dupe per ☝️

**Closed by jeffwidman** 2022-09-22 06:32 UTC
Labels: T: bug 🐞, L: javascript:npm, ❓ needs-triage
