### ISSUE TITLE
Dependabot failing to ignore deps having a property that cannot be parsed properly

### ISSUE THREAD

**Issue by vmassol** [dependabot/dependabot-core#5111] opened 2022-05-09 14:28 UTC
This is [our `dependabot.yml` file](https://github.com/xwiki/xwiki-rendering/blob/master/.github/dependabot.yml):

```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore XWiki dependencies since we always keep them up to date and Dependabot has problems with maven properties
      # defined in parent poms.
      - dependency-name: "org.xwiki.*"
    open-pull-requests-limit: 15
```

Notice the `ignore` used. 

When it's executed, it [fails with `Property not found: commons.version`](https://github.com/xwiki/xwiki-rendering/network/updates/362482346).

All our deps using `commons.version` have a groupid starting with `org.xwiki.`. For example:

```
          <dependency>
            <groupId>org.xwiki.commons</groupId>
            <artifactId>xwiki-commons-tool-test-simple</artifactId>
            <version>${commons.version}</version>
          </dependency>
```

It's as if the parsing was done before the ignore was used., could that be?

Thanks

**Comment by vmassol** [comment] 2022-05-09 14:30
Note that according to https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/troubleshooting-the-dependency-graph#does-the-dependency-graph-detect-dependencies-specified-using-variables these deps should just be ignored but not fail dependabot.

**Comment by jakecoffman** [comment] 2022-10-20 20:56
Thanks for the report.

This is sort of a duplicate of https://github.com/dependabot/dependabot-core/issues/5543 

The underlying issue was due to Dependabot not being able to lookup parent POMs that are snapshots. Dependabot found the variable `commons.version` in the child POM and failed the job since it couldn't find the value it held. 

It's true that Dependabot could have realized that `commons.versions` only applies to `org.wiki.commons` in this case and be ignored. However I think even Maven would fail if it came across an undefined variable. 

We can leave this issue open to track this as an enhancement.

**Comment by jeffwidman** [comment] 2023-02-11 06:41
So within Dependabot, we _currently_ do all our `ignore` filtering post-resolving. The obvious alternative of applying ignores beforehand doesn't really work because those ignored deps may have constraints that affect the allowed versions of non-ignored constraints. 

Ideally, what we'd really like to do is pass those ignores somehow into the native package manager so that it can handle ignoring those dep versions at resolution time. But even in that case, it'd likely still need to fetch the manifests of the ignored package for the same reasons... it's just that it can better filter halfway through resolving than we can in Ruby at the very end.

So I'm going to close, as i don't see a straightforward way for us to change this behavior of applying ignores after they're at least partially resolved.

**Closed by jeffwidman** 2023-02-11 06:41 UTC
Labels: T: bug 🐞, L: java:maven, F: dependency-ignores

**Comment by jeffwidman** [comment] 2023-02-11 06:43
Additionally, our underlying Maven parsing is all regex/ruby, and we want to long term move to using Maven itself as that's much less brittle. So while technically we could workaround this via Ruby, we'd rather invest that energy into figuring out how to switch to Maven long term than invest more time into re-implementing Maven in ruby (but poorly) and then rip it all out.

**Comment by vmassol** [comment] 2023-02-13 10:11
Thanks for taking the time to explain why you're not going to invest time to fix it. Indeed, it would be much better to use the Maven/Aether API (we do that in XWiki too, to resolve dependencies from java).
