### ISSUE TITLE
Handle withdrawn versions

### ISSUE THREAD

**Issue by nick-traeger** [dependabot/dependabot-core#4253] opened 2021-09-22 10:55 UTC
Dependabot has (legitimately) created a merge request for a new version. But now the developer has noticed an error and deleted the version. Dependabot does not notice this and writes "is up to date" in the logs, because there is no newer version. It would be nice if Dependabot recognizes that the current version was removed and creates a new merge request on the older version.

We use pip for package management, but possibly this would be suitable for other services as well.

**Comment by brrygrdn** [comment] 2021-11-26 18:01
Thanks @nick-traeger, I'm going to close this out as a duplicate of https://github.com/dependabot/dependabot-core/issues/4379 - I realise you posted first, but we've started tracking that issue.

I don't have anything to share in terms of roadmap, but this a feature we are interested in.

**Closed by brrygrdn** 2021-11-26 18:01 UTC
Labels: T: feature-request
