### ISSUE TITLE
no implicit conversion of nil into String in file_fetcher.rb

### ISSUE THREAD

**Issue by danmoseley** [dependabot/dependabot-core#8508] opened 2023-12-01 18:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

No idea -- if the problem relates to a particular file in the repo, it isn't clear from the error message.

### dependabot.yml content

https://github.com/danmoseley/eShop/blob/dependabot/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Dependabot to work or fail with a helpful error. I got the error message below and I've simplified the yml as far as possible without effect. 

### Images of the diff or a link to the PR, issue, or logs

https://github.com/danmoseley/eShop -- branch "dependabot"

```
updater | time="2023-12-01T18:26:23Z" level=info msg="guest starting" commit=17df297b9449ef5936111b658329653bcfc0c9bc
updater | time="2023-12-01T18:26:23Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=757278263 updater_timeout=45m0s updater_version=e83cd566eb627cd83ed43645e38ef9caff47ed79-nuget
updater | 2023/12/01 18:26:26 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/01 18:26:28 INFO <job_757278263> Starting job processing
  proxy | 2023/12/01 18:26:29 [002] GET https://github.com:443/danmoseley/eShop/info/refs?service=git-upload-pack
  proxy | 2023/12/01 18:26:29 [002] * authenticating git server request (host: github.com)
  proxy | 2023/12/01 18:26:29 [002] 200 https://github.com:443/danmoseley/eShop/info/refs?service=git-upload-pack
  proxy | 2023/12/01 18:26:29 [003] POST https://github.com:443/danmoseley/eShop/git-upload-pack
  proxy | 2023/12/01 18:26:29 [003] * authenticating git server request (host: github.com)
  proxy | 2023/12/01 18:26:29 [003] 200 https://github.com:443/danmoseley/eShop/git-upload-pack
  proxy | 2023/12/01 18:26:29 [004] POST https://github.com:443/danmoseley/eShop/git-upload-pack
  proxy | 2023/12/01 18:26:29 [004] * authenticating git server request (host: github.com)
  proxy | 2023/12/01 18:26:29 [004] 200 https://github.com:443/danmoseley/eShop/git-upload-pack
updater | 2023/12/01 18:26:30 ERROR <job_757278263> Error during file fetching; aborting: no implicit conversion of nil into String
updater | 2023/12/01 18:26:30 ERROR <job_757278263> no implicit conversion of nil into String
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:48:in `join'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:48:in `block in fetch_files'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:47:in `uniq'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:47:in `fetch_files'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:108:in `files'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:107:in `block in dependency_files'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:125:in `with_retries'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:107:in `dependency_files'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:30:in `perform_job'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/01 18:26:30 ERROR <job_757278263> bin/fetch_files.rb:24:in `<main>'
```

**Comment by austindrenski** [comment] 2023-12-02 00:48
@danmoseley I've been seeing the same errors you've been reporting for several days across a variety of projects all with varied packages, versioning schemes, MSBuild constructs, etc.

All of which to say that I don't think this is project specific, nor does it seem like something with a clear repo eng cause (i.e. even when there's no MSBuild evaluation required, it fails).

Since all of the projects where I'm seeing these errors are from a private org, I've put together a minimal repro showing this happen with even a very basic repo skeleton:

- https://github.com/austindrenski/dependabot-nuget-failure

```console
$ tree
.
├── Directory.Build.props
├── Directory.Packages.props
├── dependabot-nuget-failure.sln
├── global.json
└── src
    ├── Directory.Build.props
    └── SomeProject
        └── SomeProject.csproj

2 directories, 7 files
```

```csproj
<!-- Directory.Build.props -->
<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

</Project>
```

```csproj
<!-- Directory.Packages.props -->
<Project>

  <ItemGroup>
    <PackageVersion Include="System.Text.Json" Version="7.0.0" />
  </ItemGroup>

</Project>
```

```csproj
<!-- src/Directory.Build.props -->
<Project>

  <Import Project="../Directory.Build.props" />

</Project>
```

```csproj
<!-- src/SomeProject/SomeProject.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
```

```
  proxy | 2023/12/02 00:17:24 proxy starting, commit: 6cffd6fae1b2f713f2d837bc45fe916f855c821d
  proxy | 2023/12/02 00:17:24 Listening (:1080)
updater | 2023-12-02T00:17:25.267021840 [757428563:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-12-02T00:17:27Z" level=info msg="guest starting" commit=17df297b9449ef5936111b658329653bcfc0c9bc
updater | time="2023-12-02T00:17:27Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=757428563 updater_timeout=45m0s updater_version=ad73cc6aa16e85e1a2f46ede0b3cf7eb5dac4e3c-nuget
updater | 2023/12/02 00:17:29 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/02 00:17:32 INFO <job_757428563> Starting job processing
  proxy | 2023/12/02 00:17:32 [002] GET https://github.com:443/austindrenski/dependabot-nuget-failure/info/refs?service=git-upload-pack
  proxy | 2023/12/02 00:17:32 [002] * authenticating git server request (host: github.com)
  proxy | 2023/12/02 00:17:32 [002] 200 https://github.com:443/austindrenski/dependabot-nuget-failure/info/refs?service=git-upload-pack
  proxy | 2023/12/02 00:17:32 [003] POST https://github.com:443/austindrenski/dependabot-nuget-failure/git-upload-pack
  proxy | 2023/12/02 00:17:32 [003] * authenticating git server request (host: github.com)
  proxy | 2023/12/02 00:17:32 [003] 200 https://github.com:443/austindrenski/dependabot-nuget-failure/git-upload-pack
  proxy | 2023/12/02 00:17:32 [004] POST https://github.com:443/austindrenski/dependabot-nuget-failure/git-upload-pack
  proxy | 2023/12/02 00:17:32 [004] * authenticating git server request (host: github.com)
  proxy | 2023/12/02 00:17:32 [004] 200 https://github.com:443/austindrenski/dependabot-nuget-failure/git-upload-pack
updater | 2023/12/02 00:17:32 ERROR <job_757428563> Error during file fetching; aborting: no implicit conversion of nil into String
updater | 2023/12/02 00:17:32 ERROR <job_757428563> no implicit conversion of nil into String
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:48:in `join'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:48:in `block in fetch_files'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:47:in `uniq'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/nuget/lib/dependabot/nuget/file_fetcher.rb:47:in `fetch_files'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:108:in `files'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:107:in `block in dependency_files'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:125:in `with_retries'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:107:in `dependency_files'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:30:in `perform_job'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/02 00:17:32 ERROR <job_757428563> bin/fetch_files.rb:24:in `<main>'
updater | 2023/12/02 00:17:32 INFO <job_757428563> Sending event 16e6ff5f1320461c8b451e099971695a to Sentry
  proxy | 2023/12/02 00:17:33 [006] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/02 00:17:33 [006] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/02 00:17:33 INFO <job_757428563> Finished job processing
updater | 2023/12/02 00:17:33 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | file_fetcher_error |
updater | +--------------------+
updater | time="2023-12-02T00:17:33Z" level=info msg="task complete" container_id=job-757428563-file-fetcher exit_code=0 job_id=757428563 step=fetcher
updater | time="2023-12-02T00:17:34Z" level=warning msg="failed during fetch, skipping updater" job_id=757428563
```

**Comment by danmoseley** [comment] 2023-12-02 17:54
And also perhaps improve logging to include information like the file being processed and the version of dependabot being used.

**Comment by deivid-rodriguez** [comment] 2023-12-04 16:51
> @brettfo @deivid-rodriguez if this, https://github.com/dependabot/dependabot-core/issues/8490 and https://github.com/dependabot/dependabot-core/issues/8470 and maybe others were introduced by the changes to the Nuget code paths that were deployed a few days ago (https://github.com/dependabot/dependabot-core/commits/main/nuget/lib/dependabot/nuget) , would it make sense to revert that so it can be stabilized in isolation while our repos remain unblocked? Rather than fixing issues individually as they are reported, which may take some time.

@danmoseley Yeah, several regressions have been introduced by the updater changes that you point out. We apologize for that and will work on smoother rollout of non trivial changes like that in the future. Fixing regressions here is currently a priority and we have just shipped a few of them. We understand the current frustration, but we want to avoid a full revert because that PR also fixed several bugs and provided new features for other users, so reverting it would make those regress and cause similar frustration. If you notice problems that are not currently represented in issues, please submit and we will prioritize accordingly.

**Comment by danmoseley** [comment] 2023-12-04 23:50
@deivid-rodriguez thanks for the reply, I understand difficult rollouts myself 🙂

I'll open any other issues I see, but right now it's broken for my repos so I expect any issues would be after that is working again.

BTW, if in future there is some means to "opt in" to a "pre-release" dependabot on Github, I expect many of us would be glad to occasionally help try out bits before they are widely deployed, if that would help.

**Comment by deivid-rodriguez** [comment] 2023-12-05 08:22
Yeah, we have ways to introduce feature flags for complicated features and gradually roll them out, and also to temporarily enable particular repositories to run against certain branches, we just rushed a bit too much in this particular case. Noting you as future potential beta testers for features that need testing before being rolled out, thank so much for your kind feedback and patience by the way.

**Comment by jakecoffman** [comment] 2023-12-05 12:39
Fixed by https://github.com/dependabot/dependabot-core/pull/8511

**Closed by jakecoffman** 2023-12-05 12:39 UTC
Labels: T: bug 🐞, L: dotnet:nuget

**Comment by martincostello** [comment] 2023-12-05 16:14
That error looks like #8530.

**Comment by austindrenski** [comment] 2023-12-05 16:29
> That error looks like #8530.

ope, hadn't seen that one yet, thanks!
