### ISSUE TITLE
Support Java built using Bazel

### ISSUE THREAD

**Issue by JensRantil** [dependabot/dependabot-core#1215] opened 2019-06-13 15:06 UTC
Bazel: https://bazel.build

**Comment by nathanhleung** [comment] 2020-02-21 00:39
See also: https://github.com/dependabot/feedback/issues/341

**Comment by asciimike** [comment] 2021-06-25 16:07
Closing this as a dupe of https://github.com/dependabot/dependabot-core/issues/2196

**Closed by asciimike** 2021-06-25 16:07 UTC
Labels: T: new-ecosystem
