### ISSUE TITLE
recreate doesn't follow newest config (commit prefix)

### ISSUE THREAD

**Issue by anatawa12** [dependabot/dependabot-core#5818] opened 2022-09-30 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

7.2 with kotlin

### Language version

kotlin gradle script

### Manifest location and content before the Dependabot update

/build.gradle.kts

### dependabot.yml content

https://github.com/fixrtm/fixRTM/blob/6e9e00837f37b82592750af99555110c2f4bb7d4/.github/dependabot.yml

### Updated dependency

see fixrtm/fixRTM#519

### What you expected to see, versus what you actually saw

EXPECTED: on @dependabot recreate、dependabot should follow the newest config
ACTUAL: dependabot follow the old (the time PR is created) format.

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

see fixrtm/fixRTM#519

### Smallest manifest that reproduces the issue

Updating commit prefix of `.github/dependabot.yml` should reproduce this problem

Maybe relates #3419

**Comment by jeffwidman** [comment] 2022-10-01 00:24
👋 pretty sure this is a duplicate of https://github.com/dependabot/dependabot-core/issues/4652... the commit message isn't re-built, so it keeps whatever was on the original PR.

**Closed by jeffwidman** 2022-10-01 00:24 UTC
Labels: T: bug 🐞, L: java:gradle, F: pull-requests
