### ISSUE TITLE
Standard Python support

### ISSUE THREAD

**Issue by flying-sheep** [dependabot/dependabot-core#3290] opened 2021-03-17 12:15 UTC
There’s exactly two standard ways of specifying dependencies, none of which dependabot supports.

1. [PEP 517’s `prepare_metadata_for_build_wheel()`](https://www.python.org/dev/peps/pep-0517/#prepare-metadata-for-build-wheel).

   The legacy way to specify Python dependencies is `requirements.txt`. The standard way is having a PEP 517 build system configured. That build system can optionally define a function called `prepare_metadata_for_build_wheel`. If that function exists, the dependencies can be obtained (from the metadata) without building a wheel, otherwise `build_wheel()` needs to be called.

   Code to just do the above would look like:

   ```py
   import build
   deps = build.ProjectBuilder("path/to/project").get_dependencies("sdist")
   # or
   deps = build.ProjectBuilder("path/to/project").get_dependencies("wheel") - {"wheel"}
   ```

2. [PEP 631](https://www.python.org/dev/peps/pep-0631/) a new standardized way to specify dependencies in a Python project (now merged into [PEP 621](https://www.python.org/dev/peps/pep-0621/)).

   It’s supported by [`flit`](https://flit.readthedocs.io/en/latest/) and a bunch of other new build backends. So if you want to continue your (incomplete) way of just parsing files and not calling into Python, this needs to be supported.

**Comment by flying-sheep** [comment] 2021-12-17 12:44
This should be pretty straightforward (if one knows ruby, which I don’t). You already have

1. a format preserving TOML parser (for poetry support)
2. a parser and serializer for the [PEP 508](https://www.python.org/dev/peps/pep-0508/) dependency specifier language (for requirements.txt support)

So you just have to read the TOML tables `project.dependencies` and `project.optional-dependencies.*` instead of `tool.poetry.dependencies` and `tool.poetry.extras`, and then use the PEP 508 handling logic instead of the poetry version specifier logic

**Comment by dreinon** [comment] 2022-03-01 22:37
I just got a dependabot PR of my project using pdm! Hope this has been finally accepted :slightly_smiling_face:

**Comment by drewcassidy** [comment] 2022-04-19 03:49
now that setuptools supports PEP621, It would be nice to see this

**Comment by drewcassidy** [comment] 2022-04-20 04:36
> So you just have to read the TOML lists `project.dependencies` and `project.optional-dependencies.*` instead of the toml tables `tool.poetry.dependencies` and `tool.poetry.extras.*`, and then use the PEP 508 handling logic instead of the poetry version specifier logic

I would say to read `build-system.requirements` too. some of those things may be pinned too (like a project using pybind11).

**Comment by ofek** [comment] 2022-04-29 02:08
> I would say to read `build-system.requirements` too

Minor correction: `build-system.requires`

**Comment by jorgepiloto** [comment] 2022-07-20 14:55
I am surprised after finding that dependabot was able to parse a `pyproject.toml` using Poetry as the build-system, see https://github.com/pyansys-testing/dependabot-pyproject/pull/3/files

**Comment by jorgepiloto** [comment] 2022-07-20 14:57
However, when using Flit as the build-system, dependabot did not opened any PR.

**Comment by vnmabus** [comment] 2022-07-25 18:34
It seems that this issue also causes projects moving towards pyproject.toml adoption to lose their list of dependents, unless the name of the project is also repeated in setup.py.

See https://github.community/t/bug-project-not-showing-network-dependents/3161 for examples.

**Comment by jenstroeger** [comment] 2022-07-28 07:27
@jorgepiloto @vnmabus exactly my problem after moving to `pyproject.toml` and Flit.

To be honest, I am surprised that @dependabot doesn’t support such a fundamental and standardized process, and quite concerned that this issue isn’t being addressed.

**Comment by jurre** [comment] 2022-07-28 07:59
Hey, thanks for the pings on this! It's definitely on our radar and we want to support this, but I can't share a timeline as to when we'll be able to ship support for this across both Dependabot and the Dependency Graph.

**Comment by ofek** [comment] 2022-08-26 19:25
This will fix https://github.com/community/community/discussions/6456 too. It's really affecting many now that everyone is trying to use static metadata standards e.g.:

- https://twitter.com/hynek/status/1562291846423859200
- https://github.com/encode/httpx/pull/2351

**Comment by jorgepiloto** [comment] 2022-08-29 06:43
All the logic for parsing Python version specification is implemented in [dependabot/python/file_parser/](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/file_parser/).

It looks like most of the logic is already implemented. It is just a matter of combining the "pyproject.toml" file finder and the "setup.py" requirements parser.

I wish I could be more familiar with Ruby to address this. Maybe I could try to open a PR to start pushing on this issue.

**Comment by tiangolo** [comment] 2022-08-31 13:40
Just to add my two cents, I've been holding some project packaging migrations and updates waiting for this.

It would greatly benefit my projects at least: FastAPI, Typer, SQLModel, Asyncer and others. 🤓🚀

Some bugs in the past in some of these libraries would have been prevented/detected by this.

And just in case, some of these packages are used internally by GitHub, so, maybe it could help prevent internal problems too. 😅

**Comment by deivid-rodriguez** [comment] 2022-09-05 07:36
Hello @flying-sheep! Thanks for this ticket, it's very informative.

I've been having a look at this. While it's clear to me what would be needed to support Pep621 (basically what you describe at https://github.com/dependabot/dependabot-core/issues/3290#issuecomment-996694772), I'm not sure what the expectations would be for Dependabot in order to support the other standard way of specifying dependencies that you mention in this issue. Can you point at an opensource project that follows that standard, and what kind of PRs would be expected for Dependabot to create?

Thanks!

**Comment by flying-sheep** [comment] 2022-09-05 08:03
Every single Python project that uses the `[build-system]` table uses PEP 517.

I think so far, Poetry is the only build tool that doesn’t also implement PEP 621, and you already support Poetry.

**Comment by deivid-rodriguez** [comment] 2022-09-05 08:24
> Every single Python project that uses the [build-system] table to specify a build backend uses PEP 517.

Can you give me an example project that uses PEP 517 but does not use poetry? Unfortunately I know nothing about Python, so seeing some examples would be useful for me.

**Comment by deivid-rodriguez** [comment] 2022-09-05 08:32
I know these are probably basic questions for you, but.. Do projects following PEP 517 always specify their dependencies through a `pyproject.toml` file, or are there any other files used to declare dependencies? Also, is there any concept of lock file in the standard, or is poetry the only tool that has this concept?

**Comment by flying-sheep** [comment] 2022-09-05 08:57
> Can you give me an example project that uses PEP 517 but does not use poetry?

Probably not. I think all build backends that have been created since PEP 621 exists support PEP 621, and all earlier build backends except for Poetry have added PEP 621 support in the meantime. A new build backend would need a really good reason for not supporting PEP 621.

> Do projects following PEP 517 always specify their dependencies through a pyproject.toml file, or are there any other files used to declare dependencies?

Setuptools can either use `setup.py`, `setup.cfg`, or `pyproject.toml`, Flit, Hatch, … all support PEP 621 (and therefore `pyproject.toml`) but also support their own config files `flit.toml`, `hatch.toml`, …

I think most people use PEP 621 for consistency and simplicity, but if you want a catch-all solution you need to go the PEP 517 route.

**Comment by deivid-rodriguez** [comment] 2022-09-05 09:06
> Probably not. I think all build backends that have been created since PEP 621 exists support PEP 621, and all earlier build backends except for Poetry have added PEP 621 support in the meantime. A new build backend would need a really good reason for not supporting PEP 621.

Alright! So that sounds like supporting PEP 621 + Poetry should be enough for this, nice!

> Setuptools can either use `setup.py`, `setup.cfg`, or PEP 621 (`pyproject.toml`). Flit, Hatch, … all support PEP 621 (`pyproject.toml`) but also support their own config files `flit.ini`, `hatch.toml`, … and as said Poetry uses `pyproject.toml` but not the PEP 621 table structure.

That's helpful, thanks!

**Comment by flying-sheep** [comment] 2022-09-05 09:18
If you want to go the 99%* route using static files instead of the 100% route using PEP 517, the correct sequence to determine which build backend is used is this:

1. If `pyproject.toml` does not exist or has no `build-system` table or `build-system.build-backend` is `'setuptools.build_meta'`, the build backend is setuptools and depdendencies are specified in `setup.py`, `setup.cfg`, or `pyproject.toml` (PEP 621)
2. If `build-system.build-backend` is `'poetry.core.masonry.api'`, dependencies are specified in `pyproject.toml` (poetry’s custom table)
3. Else dependencies are *probably* in `pyproject.toml` (PEP 621)

The sequence for PEP 517 would be much simpler:

1. If `pyproject.toml` exists and has a `build-system` table:

   1. create a Python virtual environment with the packages in `build-system.requires` installed
   2. run this: `deps = build.ProjectBuilder("path/to/project").get_dependencies("wheel") - {"wheel"}` to get the deps

3. Else we’re dealing with legacy setuptools which you already support.

*Maybe that 99% will decline rapidly in the future. The PEP 517 route would be robustly 100%

**Comment by deivid-rodriguez** [comment] 2022-09-05 16:28
Thanks!

I did conduct some experiments with the "100% route" you suggested, although I have no idea how to plug it into our current architecture. I feel more confident with the 99% route although I understand is not as bullet proof, but it works better with our current architecture.

For what it's worth, this is a small log of my experiments:

```
>>> deps = build.ProjectBuilder(".").get_dependencies("wheel") - {"wheel"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ProjectBuilder' object has no attribute 'get_dependencies'. Did you mean: 'check_dependencies'?
```

Turns out `get_dependencies` was renamed a bit over a year ago: https://github.com/pypa/build/blob/main/CHANGELOG.rst#040-2021-05-23.

Then I tried the updated code with https://github.com/encode/httpx, and I get the following:

```
>>> import build
>>> deps = build.ProjectBuilder("/tmp/httpx").get_requires_for_build("wheel")
>>> deps
set()
```

I'm not sure what to do with that, any ideas?

**Comment by ofek** [comment] 2022-09-05 16:56
- Build deps == [`build-system.requires`](https://peps.python.org/pep-0518/#build-system-table) + [`get_requires_for_build_wheel`](https://peps.python.org/pep-0517/#get-requires-for-build-wheel)
- Runtime deps == [`project.(dependencies|optional-dependencies)`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dependencies-optional-dependencies)

I think just supporting runtime deps for now would be best since it's what most of us care about and implementing it would take a day for someone competent in Ruby

**Comment by deivid-rodriguez** [comment] 2022-09-05 17:00
Thanks @ofek!

Yes, for now I'm just parsing `project.dependencies` from `pyproject.toml` similarly to what we do for Poetry (I will add support for `optional-dependencies` later), but I was curious about the other approach @flying-sheep was mentioning. I get now that that's for build dependencies, and I agree that most users care about runtime deps, so that should get the most priority!

**Comment by flying-sheep** [comment] 2022-09-06 07:19
Ah, I should have added that. The hook `prepare_metadata_for_build_wheel` will write a static file with *runtime* dependencies in it, so you can use the approach for runtime dependencies as well.

**Comment by pradyunsg** [comment] 2022-09-06 08:11
I'd be fine if dependabot starts by respecting only the static dependency declarations in project.dependencies. We can extend that to support the other stuff (build, from build-system.requires and dynamic ones from the build backend, via metadata generation as well as the other hook).

I'll note that https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#pyproject-toml is a thing, and the metadata generation step is how you'd get the "entire" set of runtime dependencies. That matches the project.dependencies for nearly every project though, so it'd be preferable to start with just statically reading things and we can extend this later. :)

**Comment by deivid-rodriguez** [comment] 2022-09-06 09:34
Thanks, this is starting to make sense! @pradyunsg those docs are nice!

Which static file the hook `prepare_metadata_for_build_wheel` writes to?

**Comment by flying-sheep** [comment] 2022-09-06 11:04
`prepare_metadata_for_build_wheel('<dir>')` creates `<dir>/<package>-<version>.dist-info/METADATA`, which contains [`Requires-Dist: ...`](https://peps.python.org/pep-0345/#requires-dist-multiple-use) lines (see [here](https://peps.python.org/pep-0345/#version-specifiers) for format).

**Comment by ofek** [comment] 2022-09-06 14:16
Just FYI, while `prepare_metadata_for_build_wheel` would produce results that account for dynamic metadata and therefore would be more accurate, it is an optional API method.

**Comment by ofek** [comment] 2022-09-06 16:59
Hatchling might be the only backend that doesn't, for [reasons](https://github.com/pypa/hatch/issues/128), but if this is what you'll use (I hope it is) then I'll implement it as this use case is far more compelling than the others I've encountered 🙂

**Comment by ofek** [comment] 2022-09-12 14:07
Hatchling [now supports](https://github.com/pypa/hatch/releases/tag/hatchling-v1.9.0) `prepare_metadata_for_build_wheel`

@deivid-rodriguez Has there been any progress on any implementation?

**Comment by deivid-rodriguez** [comment] 2022-09-12 14:11
We started working on it, so yeah, there's been some progress, but I can't tell yet when it will be ready.

**Comment by ofek** [comment] 2022-09-21 03:58
Awesome! Is there anything we can do to help

**Comment by pradyunsg** [comment] 2022-09-21 18:59
Thanks for the clarification and I'll say that I certainly appreciate the regular updates and responses here.

Do you know if it would be possible for 2 to get a public issue and potentially get tracked in GitHub's public roadmap, like https://github.com/github/roadmap/issues/467?

**Comment by ofek** [comment] 2022-09-27 18:47
That shipped today fyi https://github.com/github/roadmap/issues/467#issuecomment-1259801516

**Comment by davidism** [comment] 2022-09-27 19:01
If GitHub only considers `[project] dependencies = []`, it will miss out on development dependencies.

Currently Flask pins all its development dependencies in different `requirements/*.txt` files, like `tests.txt` and `docs.txt`. I'm switching over to PDM, which allows specifying development dependency groups (which are distinct from optional dependency groups, dev groups aren't exposed in the build) in `pyproject.toml`. PDM also produces a `pdm.lock` file with every transitive dependency name and version.

`pyproject.toml`:

```toml
[tool.pdm.dev-dependencies]
pytest = [
    "pytest",
    "blinker",
]
coverage = [
    "pytest-cov",
    "coverage[toml]",
]
mypy = [
    "mypy",
    "pytest",
    "sqlalchemy[mypy]",
]
sphinx = [
    "sphinx",
    "pallets-sphinx-themes",
    "sphinx-issues",
    "sphinxcontrib-log-cabinet",
]
pre-commit = [
    "pre-commit",
]
tox = [
    "tox",
    "tox-pdm",
]
```

`pdm.lock`:

```toml
[[package]]
name = "alabaster"
version = "0.7.12"
summary = "A configurable sidebar-enabled Sphinx theme"

[[package]]
name = "attrs"
version = "22.1.0"
requires_python = ">=3.5"
summary = "Classes Without Boilerplate"

[[package]]
name = "babel"
version = "2.10.3"
requires_python = ">=3.6"
summary = "Internationalization utilities"
dependencies = [
    "pytz>=2015.7",
]

# continues for every library installed in the env
```

At least detecting the projects listed in the `tool.pdm.dev-dependencies` section of `pyproject.toml` would be nice. It's the same format, lists of project names, as the standard `optional-dependencies`. Reading `pdm.lock` would allow building an even more accurate dependency graph.

**Comment by ofek** [comment] 2022-09-27 19:06
The solution would be a PR for every tool (that is in widespread). I plan to open one for Hatch.

**Comment by davidism** [comment] 2022-09-27 19:07
@frostming not sure if you're already following this, but this will be relevant for PDM.

**Comment by davidism** [comment] 2022-09-27 19:08
@jeffwidman is there a public repo for the dependency graph like this one for dependabot?

**Comment by ofek** [comment] 2022-09-27 19:11
@davidism The PRs would go here, dep graph would now have multiple Actions https://github.com/github/dependency-submission-toolkit#writing-your-own-dependency-submission-action

**Comment by courtneycl** [comment] 2022-09-28 21:40
👋 Hi from the dependency graph team. We don't have a public repo, but we do have this work prioritised and I can update here once it's fixed.

**Comment by pradyunsg** [comment] 2022-09-28 23:58
Thanks @courtneycl for chipping in! Looking forward to the improvements in the area of GitHub + modern Python Packaging stuff.

**Comment by davidism** [comment] 2022-10-03 14:46
I've left some comments on the PR that's about to get merged. https://github.com/dependabot/dependabot-core/pull/5661 I'm worried that only supporting pins in `pyproject.toml` will encourage users to put pins there, which will be fine for applications but really bad if libraries pin like that. Would really like to see support for lock files, even though they're not standard yet, since there's already non-standard Poetry support.

**Comment by deivid-rodriguez** [comment] 2022-10-24 21:09
We've shipped preliminary support for updating dependencies following PEP621 in pyproject.toml files with #5661.

Of course there may be bugs and missing features, but I'm closing this main issue now and will track any future enhancements as separate issues.

Thanks!

**Closed by deivid-rodriguez** 2022-10-24 21:09 UTC
Labels: T: feature-request, python

**Comment by zhan9san** [comment] 2022-10-25 00:20
> I've left some comments on the PR that's about to get merged. https://github.com/dependabot/dependabot-core/pull/5661 I'm worried that only supporting pins in `pyproject.toml` will encourage users to put pins there, which will be fine for applications but really bad if libraries pin like that. Would really like to see support for lock files, even though they're not standard yet, since there's already non-standard Poetry support.

@davidism 
Thanks for your time
Please allow me to ask a stupid question.

Why it is bad if libraries pin like that?
Why it's better to support for lock files?

**Comment by ofek** [comment] 2022-10-25 00:28
@zhan9san https://iscinumpy.dev/post/bound-version-constraints/

But there's no cause for concern:

> [...] we not only support full pins, but also other perfectly valid ways of restricting dependencies. Just in case there's some misunderstanding there.

**Comment by tiangolo** [comment] 2022-11-04 11:13
I just came back here to say THANK YOU @deivid-rodriguez and everyone involved! :hugs:

I'm now getting Dependabot upgrades in my projects with `pyproject.toml` including FastAPI and others :tada:

**Comment by deivid-rodriguez** [comment] 2022-11-04 11:23
Thank you for the kind words @tiangolo, we're glad this is turning out useful for your projects 🎉.

**Comment by ofek** [comment] 2022-12-07 18:29
@annarosenthal Awesome! Are there docs?

**Comment by annarosenthal** [comment] 2022-12-08 15:52
> @annarosenthal, that’s great to hear. But it still says “[pyproject.toml](https://github.com/iterative/dvc/blob/main/pyproject.toml) has no dependencies or is too large to display” for us. See [iterative/dvc](https://github.com/iterative/dvc/network/dependencies) for example.
> 
> Also, does this mean that we can now use `dependency-review-action` with pyproject.toml files?

Thanks for flagging. We looked into it and this is caused by a discrepancy in assumptions we made for different/older PEP standards. Apologies about it. However, I filed a bug issue internally asking to update this issue once the fix ships.

**Comment by flying-sheep** [comment] 2022-12-09 11:52
I think the idea behind the docs is simply: “we recommend using a lockfile”. I’m not sure why that is – [It’s not a good idea to pin versions for Python libraries](https://iscinumpy.dev/post/bound-version-constraints/) and for libraries, I rather run tests with the newest version of everything instead of some older lockfile version, because that’s what people get when they install my library.

`requirements.txt` is a convention, not a standard. Some people use it for abstract dependencies (reading it in `setup.py` and writing its contents to the package’s metadata), others use it as a lockfile, e.g. via

```bash
pip-compile --generate-hashes pyproject.toml --output-file=requirements.txt
```

But as long as dependabot recommends lockfiles, it makes sense to say “we recommend using `poetry.lock` or `requirements.txt` AS LOCKFILES”, while of course the recommended format for Python package metadata is PEP 621.

----

Maybe the whole segment should be reworded to be more clear

**Comment by ofek** [comment] 2022-12-12 06:55
> We have [this general doc](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph)

That helps, thanks!

**Comment by courtneycl** [comment] 2023-02-13 20:10
👋  Hi folks -- [with the latest changelog](https://github.blog/changelog/2023-02-13-dependency-graph-supports-the-python-pep-621-standard/) you should be seeing the expected dependencies from your `pyproject.toml` files in your dependency graph insights. Do let me know if you experience any issues.

Thank you for your feedback on the docs! I'll share it with the docs team.

**Comment by cpswan** [comment] 2023-02-14 11:29
I may be in a small minority doing this, but we only use `pyproject.toml` and `poetry.lock` to generate a `requirements.txt` that has pinned SHAs (to satisfy dependency pinning for [OpenSSF Scorecards](https://securityscorecards.dev/)).

When a dependency gets bumped I'm seeing Dependabot PRs that update the `poetry.lock` but to get the `requirements.txt` (which is actually used for pulling in dependencies) into sync I then have to manually run:

```
poetry export --format requirements.txt --output requirements.txt
```

Yes, I guess I could change my workflow to use poetry for the install (though I think there's potentially a bootstrapping problem there). But it would also be nice if Dependabot could just keep `poetry.lock` and `requirements.txt` in sync for me.

Examples:

[A Dependabot PR that modifies `poetry.lock` but leaves `requirements.txt` untouched](https://github.com/atsign-foundation/at_server/pull/1095)
[The PR for the manually generated changes to `requirements.txt`](https://github.com/atsign-foundation/at_server/pull/1129) (feels like this could easily be done by Dependabot too)
[The workflow that runs `python3 -m pip install --require-hashes -r tools/requirements.txt`](https://github.com/atsign-foundation/at_server/blob/trunk/.github/workflows/at_server.yaml)

**Comment by patrick91** [comment] 2023-02-14 11:36
> 👋 Hi folks -- [with the latest changelog](https://github.blog/changelog/2023-02-13-dependency-graph-supports-the-python-pep-621-standard/) you should be seeing the expected dependencies from your `pyproject.toml` files in your dependency graph insights. Do let me know if you experience any issues.
> 
> Thank you for your feedback on the docs! I'll share it with the docs team.

Does this mean we can remove [the stub setup.py](https://patrick.wtf/posts/til-how-to-show-dependents-packages-on-github-when-using-poetry) from project using poetry?

Will this also for PDM? 😊

**Comment by fapulito** [comment] 2025-05-01 08:08
> 👋 Hi folks -- [with the latest changelog](https://github.blog/changelog/2023-02-13-dependency-graph-supports-the-python-pep-621-standard/) you should be seeing the expected dependencies from your `pyproject.toml` files in your dependency graph insights. Do let me know if you experience any issues.
> 
> Thank you for your feedback on the docs! I'll share it with the docs team.

Hello @courtneycl - I have a pyproject.toml file and it doesn't seem to be getting read by Dependabot. 

<img width="678" alt="Image" src="https://github.com/user-attachments/assets/692fcf2f-5123-4d42-b08d-ef1fa17a059c" />

<img width="570" alt="Image" src="https://github.com/user-attachments/assets/c1f0ce34-5c1a-4b16-a7d2-88f5893552a4" />

**Comment by courtneycl** [comment] 2025-05-01 16:48
Hi @fapulito -- do you see the dependencies in the `pyproject.toml` file in the `Dependencies` tab there? 

You need to configure Dependabot with the configuration file to get any version updates for the dependencies.

**Comment by fapulito** [comment] 2025-05-01 17:12
> Hi @fapulito -- do you see the dependencies in the `pyproject.toml` file in the `Dependencies` tab there? 
> 
> You need to configure Dependabot with the configuration file to get any version updates for the dependencies. 

Thank you for replying I thought that would happen automatically and also have a requirements.txt file. I will review tonight and post tomorrow on results. 🤞🏻

**Comment by ElDavoo** [comment] 2026-01-04 17:06
> post tomorrow on results.

💤
