### ISSUE TITLE
Gradle plugin version bumping

### ISSUE THREAD

**Issue by TobiasRoland** [dependabot/dependabot-core#1104] opened 2019-04-09 17:07 UTC
Yesterday when running the [gradle versions plugin](https://github.com/ben-manes/gradle-versions-plugin) I noticed that dependabot does not bump my spring plugin version which was defined in the `build.gradle` plugin block 

```
plugins {
    // would expect the below to be bumped to 2.1.4.RELEASE
    id "org.springframework.boot" version "2.1.3.RELEASE"
}
```

Would be great if it dependabot could update this, too

**Comment by joshuatcasey** [comment] 2019-09-30 17:36
This would be great for us too! We're using an `ext` block to set the Spring boot version for both the plugin and the BOM.

https://github.com/cloudfoundry/uaa/blob/develop/dependencies.gradle

**Comment by ColtonIdle** [comment] 2020-09-24 01:05
@TobiasRoland how do you get the gradle versions plugin and dependabot working together?

**Comment by busches** [comment] 2021-01-09 04:26
This is working for me today, appears to be added quite a while back https://github.com/dependabot/dependabot-core/commit/e571c5c6f3a812c0c51973ca063438d3cad71238

**Comment by zbynek** [comment] 2021-09-26 08:37
@TobiasRoland is this still reproducable? If yes, could you share a link to the repo you're trying to update?

**Comment by koppor** [comment] 2023-06-22 19:30
Does not work here.

Expected diff:

```diff
- id("org.openrewrite.rewrite") version("6.0.0")
+ id("org.openrewrite.rewrite") version("6.1.4")
```

Nothing happens.

All releases of the plugin are given there: https://github.com/openrewrite/rewrite-gradle-plugin/releases

Repository: https://github.com/jabref/jabref

**Comment by zbynek** [comment] 2023-06-24 08:06
@koppor it seems the[ regex used to find plugin version declaration](https://github.com/dependabot/dependabot-core/blob/main/gradle/lib/dependabot/gradle/file_parser.rb#L227) is not generic enough. To allow dependabot to update that plugin you can just remove parentheses around plugin ID and version.

**Comment by koppor** [comment] 2023-09-05 10:34
Interestingly, the plugin was not updated from 6.1.25 to 6.2.4 - even though that version is available: https://docs.openrewrite.org/reference/gradle-plugin-configuration

```groovy
id 'org.openrewrite.rewrite' version '6.1.25'
```

```yaml
version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    ignore:
      - dependency-name: com.microsoft.azure:applicationinsights-core
        versions:
          - ">= 2.5.a" # Blocked by https://github.com/microsoft/ApplicationInsights-Java/issues/1155
      - dependency-name: com.microsoft.azure:applicationinsights-logging-log4j2
        versions:
          - ">= 2.5.a" # Blocked by https://github.com/microsoft/ApplicationInsights-Java/issues/1155
```

**Comment by zbynek** [comment] 2023-09-05 17:57
@koppor which repository are you talking about? Seems OK in https://github.com/JabRef/jabref/commit/2a5a23b09725c5e1ec06bb7c41c6a69f6e3e8322

**Comment by koppor** [comment] 2023-09-05 22:32
@zbynek Thank you for checking. Must have been a bad timing on my side (working on branch and in parallel to dependabot updates being merged automatically). They also release at fast pace (see https://github.com/openrewrite/rewrite-gradle-plugin/releases), thus my assumption that 6.1.25 was older than two weeks was wrong.

**Comment by zbynek** [comment] 2023-09-06 04:53
@jurre maybe this issue can be closed now?

**Comment by koppor** [comment] 2023-09-06 06:08
Maybe someone could do some RegEx magic to support `"` too 😅

**Comment by zbynek** [comment] 2023-09-13 22:01
@koppor I don't want to discourage you from poposing a PR, but personally I won't make one because the regexp based solution will never be perfect and might get completely replaced by https://github.com/dependabot/dependabot-core/issues/1164 anyway.

**Comment by koppor** [comment] 2023-09-14 05:54
Thank you for the link. Then, this one can surely be closed!

**Closed** 2023-11-29 14:57 UTC
Labels: T: feature-request, L: java:gradle, F: language-support, F: version-updates ⬆️
