### ISSUE TITLE
Replace our git shim with native `git`'s `insteadOf` functionality 

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5616] opened 2022-09-02 03:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

We recently encountered an issue with `git` 's `.insteadOf` feature not handling some edge cases... it forced us to write a custom shim layer: https://github.com/dependabot/dependabot-core/pull/5332

I'd like to get `insteadOf` improved so that we could rely on it and remove the shim... So this issue tracks the following steps:
- [ ] Write tests in core `git` against `insteadOf` that replicate our failures
- [ ] Work with `git` team to write whatever code is needed to fix those failures
- [ ] Pull in the new version of `git`
- [ ] Use that instead of our shim
- [ ] Deploy/monitor to confirm issue fixed
- [ ] Archive our [shim repo](https://github.com/dependabot/git-shim)

**Comment by jeffwidman** [comment] 2022-09-02 03:34
I connected with one of the core `git` contributors on IM and he said:
> I'm surprised that this doesn't work already, Git's tests include a case that sounds like the one that #5332 claims is broken: https://github.com/git/git/blob/be1a02a17ede4082a86dfbfee0f54f345e8b43ac/t/t5505-remote.sh#L55
>
> Though that test appears to have the `insteadof` match with the URL for `myremote`, so I could believe that our coverage is poor in this area for one reason or another.
>
> The function that sets up the rewrite rules is here: https://github.com/git/git/blob/be1a02a17ede4082a86dfbfee0f54f345e8b43ac/remote.c#L237-L255
>
> This is the function that applies the rewrites: https://github.com/git/git/blob/be1a02a17ede4082a86dfbfee0f54f345e8b43ac/remote.c#L31-L55
>
> Looking through them briefly, ISTM they should work just fine even with URL rewrites that have `:` characters in them, but I could be missing something that's obvious to everybody else ;-).


So the best first step is ensuring there's some test cases that match what was breaking for us... that'll help isolate if it's core `git` or something on our end

**Comment by jakecoffman** [comment] 2022-09-09 15:05
Sorry for the confusion, let me try to explain it better. 

The issue is that there's no way to replace all uses of the SCP style URLs ahead of time since we don't know all of the hosts that will be involved in the update. For instance, we invoke `cargo` which starts pulling manifests of dependencies and it encounters a SCP style URL that we don't know existed since we let `cargo` handle things.

In the case of a git protocol URL we can write `git config --global url."https://".insteadOf git://` and that would take care of any host.

But for SCP style URLS doing `git config --global url."https://".insteadOf "git@"` would result in a URL that is like `https://example.com:path.git` which isn't a valid URL due to the colon hanging out at the end. Had we known the host was going to be example.com, we could have written `git config --global url."https://example.com/".insteadOf "git@example.com:"`.

The `insteadOf` functionality is working as designed, it's just not sufficient for our use-case. We would have to do pre-work of grabbing every manifest involved to process all of the hostnames. The shim approach seemed much simpler, and fixes the issue for every ecosystem.

**Comment by jeffwidman** [comment] 2022-09-12 09:20
Thanks @jakecoffman for clarifying, that makes a _lot_ more sense. I may reach out to you for a quick call at some point to noodle on this one further, but for now it's not high priority.

**Closed** 2022-11-22 16:26 UTC
Labels: T: tech-debt ⚙️
