### ISSUE TITLE
[Python] Dependabot changes `~=1.1.0` to `>=1.1.0,<1.3.0`

### ISSUE THREAD

**Issue by daviddavis** [dependabot/dependabot-core#1440] opened 2019-10-09 12:21 UTC
We have our requirements specified in Python using `~=` and instead of just bumping the version, dependabot insists on changing the format using >=,<.

**Comment by rebelagentm** [comment] 2019-10-09 16:10
Hi! 👋 Thanks for reporting this.  The team is pretty swamped at the moment scaling Dependabot for all of GitHub :octocat:, but we'll take a look at this as soon as we can.

**Comment by PerchunPak** [comment] 2022-06-10 10:58
Can't reproduce in last time (https://github.com/fire-square/fire-square-style/pull/49, https://github.com/PerchunPak/pinger-bot/pull/49, https://github.com/fire-square/fire-square-style/pull/45).
Last PR with this problem was https://github.com/PerchunPak/mc-plugin-helper/pull/43.

Is this was accidentally fixed?

**Comment by PerchunPak** [comment] 2022-07-27 11:36
Reproduced this again in https://github.com/PerchunPak/mc-plugin-helper/pull/47, maybe it's now happening when dependency's version bumps on 2 version in one time?

**Comment by deivid-rodriguez** [comment] 2022-10-03 19:09
Hello @PerchunPak! Sorry for not getting back earlier, too many things you know 😅.

I actually think this is intentional. Dependabot default for libraries (as opposed to applications, which would get the behavior you want by default) is to widen requirements instead of bumping them, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy.

You should get what you want by changing your configuration once we support the `increase` and `increase-if-necessary` strategies in Python. This is not yet supported, but will be very soon.

**Comment by deivid-rodriguez** [comment] 2022-10-03 19:16
We added the required changes in this repo at https://github.com/dependabot/dependabot-core/pull/5605, but then I noticed that we still need some internal changes for this to work. I will update and close this issue once we roll those out.

**Comment by deivid-rodriguez** [comment] 2022-10-06 12:22
@PerchunPak This is now live, can you verify the `increase-if-necessary` strategy works for you?

**Closed** 2022-10-06 13:01 UTC
Labels: T: feature-request, L: python:pip, F: language-support
