### ISSUE TITLE
Support alternative Cargo registries

### ISSUE THREAD

**Issue by lilymara-onesignal** [dependabot/dependabot-core#1767] opened 2020-03-27 21:14 UTC
Cargo has supported alternative registries for several versions now. There are various reasons for using one, most notably to support private, internal dependencies. I have set up two very simple crates (one library and one binary that uses the library) to illustrate the issue:

- https://github.com/nate-onesignal/test-bin
- https://github.com/nate-onesignal/test-pkg

I tried to set up dependabot on the test-bin crate, which consumes test-pkg from an alternative crate registry. The registry is configured in the `.cargo/config` file, as required by cargo, but dependabot does not pick up on it. Here are the error logs after dependabot runs on that repo:

```
  proxy | time="2020-03-27T21:06:18Z" level=info msg="proxy starting" commit=c112a5a5cd86983046156e55becbc0d14ef9cb3e
  proxy | 2020/03/27 21:06:18 Listening (:1080)
fetcher | yarn config v1.22.4
fetcher | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
fetcher | Done in 0.03s.
fetcher | INFO <job_27787409> Starting job processing
  proxy | 2020/03/27 21:06:22 GET https://api.github.com:443/repos/nate-onesignal/test-bin
  proxy | 2020/03/27 21:06:22 * authenticating github api request
  proxy | 2020/03/27 21:06:22 200 https://api.github.com:443/repos/nate-onesignal/test-bin
  proxy | 2020/03/27 21:06:22 GET https://api.github.com:443/repos/nate-onesignal/test-bin/git/refs/heads/master
  proxy | 2020/03/27 21:06:22 * authenticating github api request
  proxy | 2020/03/27 21:06:22 200 https://api.github.com:443/repos/nate-onesignal/test-bin/git/refs/heads/master
  proxy | 2020/03/27 21:06:22 GET https://api.github.com:443/repos/nate-onesignal/test-bin/contents/Cargo.toml?ref=b28678e0ab7862d6aca02fdf0c615b4b6781e9c5
  proxy | 2020/03/27 21:06:22 * authenticating github api request
  proxy | 2020/03/27 21:06:22 200 https://api.github.com:443/repos/nate-onesignal/test-bin/contents/Cargo.toml?ref=b28678e0ab7862d6aca02fdf0c615b4b6781e9c5
  proxy | 2020/03/27 21:06:22 GET https://api.github.com:443/repos/nate-onesignal/test-bin/contents/?ref=b28678e0ab7862d6aca02fdf0c615b4b6781e9c5
  proxy | 2020/03/27 21:06:22 * authenticating github api request
  proxy | 2020/03/27 21:06:22 200 https://api.github.com:443/repos/nate-onesignal/test-bin/contents/?ref=b28678e0ab7862d6aca02fdf0c615b4b6781e9c5
  proxy | 2020/03/27 21:06:22 GET https://api.github.com:443/repos/nate-onesignal/test-bin/contents/Cargo.lock?ref=b28678e0ab7862d6aca02fdf0c615b4b6781e9c5
  proxy | 2020/03/27 21:06:22 * authenticating github api request
  proxy | 2020/03/27 21:06:22 200 https://api.github.com:443/repos/nate-onesignal/test-bin/contents/Cargo.lock?ref=b28678e0ab7862d6aca02fdf0c615b4b6781e9c5
fetcher | INFO <job_27787409> Finished job processing
  proxy | time="2020-03-27T21:06:24Z" level=info msg="proxy starting" commit=c112a5a5cd86983046156e55becbc0d14ef9cb3e
  proxy | 2020/03/27 21:06:24 Listening (:1080)
updater | yarn config v1.22.4
updater | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
updater | Done in 0.02s.
updater | INFO <job_27787409> Starting job processing
updater | INFO <job_27787409> Starting update job for nate-onesignal/test-bin
updater | INFO <job_27787409> Checking if test-pkg 0.2.0 needs updating
  proxy | 2020/03/27 21:06:48 GET https://crates.io:443/api/v1/crates/test-pkg
  proxy | 2020/03/27 21:06:48 404 https://crates.io:443/api/v1/crates/test-pkg
updater | INFO <job_27787409> Latest version is
updater | INFO <job_27787409> Handled error whilst updating test-pkg: dependency_file_not_resolvable {:message=>"error: failed to parse manifest at `/home/dependabot/dependabot-updater/dependabot_tmp_dir/Cargo.toml`\n\nCaused by:\n  No index found for registry: `nate-mara-alt-crates`\n"}
updater | INFO <job_27787409> Finished job processing
```

The critical log line is 

```
error: failed to parse manifest at `/home/dependabot/dependabot-updater/dependabot_tmp_dir/Cargo.toml`

Caused by:
 No index found for registry: `nate-mara-alt-crates`
```

But the index for this registry is defined here: https://github.com/nate-onesignal/test-bin/blob/master/.cargo/config

**Comment by jurre** [comment] 2020-03-29 10:43
Thanks for reporting this, it definitely seems like something we’d want to support but the team is currently pretty swamped with integrating and scaling dependabot for GitHub so it might be some time before we get to this.

**Comment by johnbatty** [comment] 2020-04-01 12:39
@nate-onesignal Fyi, I have implemented cargo alternative registry support for `dependabot-core`.  I haven't submitted an upstream PR yet because it currently does not have tests, and needs a little documentation and cleanup.  However, it is working and we are actively using it.

See here for my fork, if you want to try it out:
https://github.com/Metaswitch/dependabot-core/tree/cargo-alternative-registries

**Comment by asciimike** [comment] 2021-03-15 21:01
We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta, though we don't specifically have cargo. If it can use git (which it looks like it may?) you can use private git registries. Would you mind giving that a try and seeing if it works?

**Comment by nate-onesignal** [comment] 2021-03-15 22:41
Thanks @asciimike, Cargo can use git as a source-of-truth, but it does have its own HTTP-based API for proper semver-enabled private registries. We use this, so I don't think we'll be able to take advantage of the git-only support unfortunately.

**Comment by jeffwidman** [comment] 2022-09-16 07:38
Closing as a duplicate of #3478. I realize this issue came first, but that one appears to have more information so I'd prefer to close this one.

**Closed by jeffwidman** 2022-09-16 07:38 UTC
Labels: T: feature-request, L: rust:cargo, F: private-registries 💂‍♂️
