### ISSUE TITLE
API to trigger dependabot

### ISSUE THREAD

**Issue by big-andy-coates** [dependabot/dependabot-core#6098] opened 2022-11-09 23:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

As part of the release process for an organisation, it is useful to run dependabot across all repos prior to releasing, to ensure all 3rd party dependencies are as up to date as possible.

However, I've been unable to find an easy way to trigger a dependabot scan via a cli, api, or http request. This means the release process requires some one to manually go through a list of repositories and manually kick off dependabot.... which is error prone.

I can see from inspecting the site that clicking the 'Check for updates' button it has an action looking something like `action="/creek-service/creek-service/network/updates?update_config_id=12152846"` and clicking the button results a http request to `https://github.com/creek-service/creek-service/network/updates?update_config_id=12152846`. However, the `update_config_id` varies from repo to repo.

It would be great it there was either a `gh` command or consistent URL that could be used to trigger dependabot to work its awesome magic.

Thanks for the great work :)

**Comment by deivid-rodriguez** [comment] 2022-11-14 13:43
Hei! Thanks for the kind words!

I didn't read all in details, but this request _may be_ a duplicate of either https://github.com/dependabot/dependabot-core/issues/2980 or https://github.com/dependabot/dependabot-core/issues/2201?

**Comment by big-andy-coates** [comment] 2022-11-15 21:32
Thanks @deivid-rodriguez. That second issue looks close.

**Closed** 2022-11-15 21:32 UTC
Labels: T: feature-request, 💁 service

**Comment by deivid-rodriguez** [comment] 2022-11-15 22:03
We do care about old issues and we'll make sure to post any updates in there 👍.
