### ISSUE TITLE
Dependabot does not update package.json sometimes

### ISSUE THREAD

**Issue by almeidx** [dependabot/dependabot-core#6450] opened 2023-01-16 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

3.3.0

### Language version

18.13.0

### Manifest location and content before the Dependabot update

[/package.json](https://github.com/almeidx/translate/blob/main/package.json)

### dependabot.yml content

[dependabot.yml](https://github.com/almeidx/translate/blob/main/.github/dependabot.yml)

### Updated dependency

`eslint` from 8.31.0 to 8.32.0 
`prettier` from 2.8.2 to 2.8.3 
`node-fetch` from 2.6.7 to 2.6.8 
`vitest` from 0.27.0 to 0.27.1 

### What you expected to see, versus what you actually saw

Expected: both the manifest (package.json) and lock file (yarn.lock) to be updated

Actual: the manifest file (package.json) was not updated, except for https://github.com/almeidx/translate/pull/63

PS: This has been happening for a while now, but I've been updating the manifest manually in each PR / updated dependencies manually myself

### Native package manager behavior

Both the manifest (package.json) and lock file (yarn.lock) are updated

### Images of the diff or a link to the PR, issue, or logs

https://github.com/almeidx/translate/pull/59
https://github.com/almeidx/translate/pull/61
https://github.com/almeidx/translate/pull/62
https://github.com/almeidx/translate/pull/64

**Comment by deivid-rodriguez** [comment] 2023-01-17 11:11
Hi @almeidx!

By default, in the case of libraries, Dependabot keeps the existing requirement in the manifest file (`package.json` here) if the version Dependabot wants to update to satisfies it. For example, in the case of `vitest`, the latest version (`0.27.1`) satisfies the requirement in the `package.json` file (`^0.27.0`). So, Dependabot keeps the existing requirement in place and only updates the lockfile.

This behavior is fully configurable though, I think the versioning strategy that fits your expectation would be the `increase` strategy. Have a look at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file for more information!

I'll close this since I believe this is expected behavior but let me know if something does not square.

**Closed by deivid-rodriguez** 2023-01-17 11:11 UTC
Labels: T: bug 🐞
