### ISSUE TITLE
Update actions of composite GitHub actions

### ISSUE THREAD

**Issue by ad-m-ss** [dependabot/dependabot-core#6936] opened 2023-03-29 17:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi,

We use dependabot for our GitHub repository. It works great and [as documented](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) for workflows. It successfully updates actions referenced in workflows. However, we have just notice that we have still some actions out-dated. 

We determined that our workflows use local composite actions to re-use some common logic within steps. See detail: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action  

What do you think about updating actions references from composite actions too? Probably this can be considered as a "slightly different format" for workflows and apply the same constraint and mutations as for workflows.

We use composite actions like:

```yaml
name: Test
permissions:
  id-token: write # required for aws-actions/configure-aws-credentials@v2
  contents: read # required for actions/checkout@v3
  actions: read
jobs:
  build:
    name: Push
    needs: test
    runs-on: ubuntu-20.04
    steps:
     ...
      - name: Build Docker image for sidecar
        uses: ./.github/actions/build-image
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/image
          context: sidecar
``` 

We have local file `.github/actions/build-image/action.yml`:
```yaml
name: 'Build & push container image'
description: 'Uses image tag depends on Git information'
inputs:
  image:
    description: 'OCI image name'
    required: true
  context:
    description: "Build context"
    required: false
    default: "."
  file:
    description: "Dockerfile path"
    required: false
    default: "./Dockerfile"
runs:
  using: "composite"
  steps:
  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@v3 # that is never updated by dependabot, not detected too
    with:
      images: ${{ inputs.image }}
      tags: |
        type=schedule
        type=sha,format=long,prefix=
        type=ref,event=branch
        type=ref,event=tag
        type=ref,event=pr
  - name: Build and push Docker image
    uses: docker/build-push-action@v3
    id: build
    with:
      context: ${{ inputs.context }}
      push: true
      file: ${{ inputs.file }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha,scope=buildx-${{ inputs.context }}
      cache-to: type=gha,mode=max,scope=buildx-${{ inputs.context }}
```

**Comment by deivid-rodriguez** [comment] 2023-03-30 08:10
Hei!

I think this is a duplicate of https://github.com/dependabot/dependabot-core/issues/6704?

I see two different (not necessarily mutually exclusive) to go about this:

* Automatically fetch composite actions residing at `.github/actions` by default, so that actions in them can be updated. This is requested/reported at https://github.com/dependabot/dependabot-core/issues/6345.
* Automatically find references to local composite actions in workflows and fetch those files, so that actions in them can be updated.

Happy to guide anyone trying to implement any of this!

**Closed** 2023-03-30 08:12 UTC
Labels: T: feature-request, L: github:actions

**Comment by deivid-rodriguez** [comment] 2023-03-30 14:43
No problem!
