### ISSUE TITLE
Emit a log message when applying ignored versions in the current job

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5740] opened 2022-09-17 18:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When the current job is affected by `ignored_versions`, let's emit a log:

* What ignored_versions are configured?
* How many candidate versions were there before/after applying ignored versions? (maybe??)

Alternative: only output if the candidate set is reduced to zero? (like `Dependabot::AllVersionsIgnored`)

Related:
https://github.com/dependabot/dependabot-core/pull/1849

**Comment by jeffwidman** [comment] 2023-02-11 01:20
This is a great first issue if anyone is interested. There's an example of how to do this here:
* https://github.com/dependabot/dependabot-core/pull/6601

**Comment by abdulapopoola** [comment] 2024-03-11 19:29
This is a duplicate of an internal issue that is being worked on.

**Closed by abdulapopoola** 2024-03-11 19:29 UTC
Labels: T: feature-request, F: pull-requests, F: error-messages
