### ISSUE TITLE
Python updated to an alpha version. 3.10.1-slim -> 3.11.0a4-slim

### ISSUE THREAD

**Issue by oittaa** [dependabot/dependabot-core#4643] opened 2022-01-19 00:19 UTC
**Package ecosystem**

docker

**Package manager version**

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**

```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
```
**Updated dependency**

-FROM python:3.10.1-slim
+FROM python:3.11.0a4-slim
**What you expected to see, versus what you actually saw**

Dependabot should use stable versions and not update to alpha versions.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

https://github.com/oittaa/gcp-storage-emulator/pull/124

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment] 2022-09-17 09:06
I suspect this has the same root cause as https://github.com/dependabot/dependabot-core/issues/4798 but I'll leave it open in case they're different... that one doesn't appear to have a suffix in the dockerfile name so probably makes sense to use both scenarios in our tests.

**Comment by deivid-rodriguez** [comment] 2022-09-18 13:22
@jeffwidman I'm pretty sure they are the same, it should be fine to close this one as a duplicate.

**Closed** 2022-11-19 11:34 UTC
Labels: T: bug 🐞, L: docker
