### ISSUE TITLE
PRs created by dependabot cannot read secret in Github Actions

### ISSUE THREAD

**Issue by yskkin** [dependabot/dependabot-core#3703] opened 2021-05-12 02:43 UTC
**Package ecosystem**
N/A

**Package manager version**
N/A

**Language version**
N/A

**Manifest location and content prior to update**

**dependabot.yml content**
N/A

**Updated dependency**
N/A

**What you expected to see, versus what you actually saw**
A step which reqire secret fails
![image](https://user-images.githubusercontent.com/5965113/117910474-f3733c00-b316-11eb-8920-2905c7e2ab94.png)

Manually created PR cannot reproduce this.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by asciimike** [comment] 2021-05-12 04:20
Closing as a dupe of #3253, which has all the context you'll need to get this working.

**Closed by asciimike** 2021-05-12 04:20 UTC
Labels: T: bug 🐞
