### ISSUE TITLE
custom schedule interval?

### ISSUE THREAD

**Issue by trusktr** [dependabot/dependabot-core#8249] opened 2023-10-21 21:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd like to make Dependabot run every 3 months, for example, so I don't get my email spammed. But the schedule option seems to include only daily, weekly, and monthly.

**Comment by deivid-rodriguez** [comment] 2023-10-23 17:25
Thanks! This is a duplicate of https://github.com/dependabot/dependabot-core/issues/6339, make sure to watch that other issue 👍

**Closed by deivid-rodriguez** 2023-10-23 17:25 UTC
Labels: T: feature-request
