### ISSUE TITLE
Add support for Terraform 0.12 / HCL2

### ISSUE THREAD

**Issue by marocchino** [dependabot/dependabot-core#2110] opened 2019-09-13 01:07 UTC
Add support for Terraform 0.12 and HCL2 syntax. Dependabot currently fails with a cryptic error message when HCL2 syntax is parsed: 

```
Dependabot couldn't parse the main.tf found at `/terraform/manifests/xxx/main.tf`.

You can mention @dependabot in the comments below to contact the Dependabot team.
```

**Comment by infin8x** [comment] 2020-07-20 15:16
Duplicate of #1176

**Closed by infin8x** 2020-07-20 15:16 UTC
