### ISSUE TITLE
Multi-stage Dockerfile creates two PR's, second Supersedes the first

### ISSUE THREAD

**Issue by AllexVeldman** [dependabot/dependabot-core#3681] opened 2021-05-10 06:57 UTC
**Package ecosystem**
docker

**Updated dependency**
`python:3.9.4` -> `python:3.9.5`
`python:3.9.4-slim` -> `python:3.9.5-slim`
**What you expected to see, versus what you actually saw**
Expected:
Two Pull Requests to open, 1 for each version change

Actual:
1. PR with `python:3.9.4` -> `python:3.9.5` is opened.
2. PR with `python:3.9.4-slim` -> `python:3.9.5-slim` is opened.
3. PR from step 1 is closed with a "Superseded by <PR from step 2>" comment

**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/59562474/117617882-735da280-b16d-11eb-9bd4-bab987cd3e20.png)

From the Dependabot log file:
```
...
updater | INFO <job_130287806> Latest version is 3.9.5
updater | INFO <job_130287806> Requirements to unlock own
updater | INFO <job_130287806> Requirements update strategy 
updater | INFO <job_130287806> Updating python from 3.9.4 to 3.9.5
  proxy | 2021/05/10 05:04:45 [078] * authenticating github api request
updater | INFO <job_130287806> Submitting python pull request for creation
updater | INFO <job_130287806> Checking if python 3.9.4-slim needs updating
...
updater | INFO <job_130287806> Latest version is 3.9.5-slim
updater | INFO <job_130287806> Requirements to unlock own
updater | INFO <job_130287806> Requirements update strategy 
updater | INFO <job_130287806> Updating python from 3.9.4-slim to 3.9.5-slim
  proxy | 2021/05/10 05:04:48 [148] * authenticating github api request
updater | INFO <job_130287806> Submitting python pull request for creation
updater | INFO <job_130287806> Finished job processing
```

**Comment by thepwagner** [comment] 2021-05-11 11:21
Sorry for this noise!

This is the first scenario described in https://github.com/dependabot/dependabot-core/pull/3686 , which reverts changes introduced to make Dependabot behave as you expected. The bug with multistage build producing PRs that supersede each other will be reverted in the next release of Dependabot (~days).

I agree with your expected behaviour, but I think that's a duplicate of https://github.com/dependabot/dependabot-core/issues/3261 . There's a potential workaround and an implementation idea in https://github.com/dependabot/dependabot-core/issues/3261#issuecomment-837166835

As the immediate bug will be fixed, and the request for expected behaviour is tracked elsewhere, I'm going to close this issue.

**Closed by thepwagner** 2021-05-11 11:21 UTC
Labels: T: bug 🐞
