### ISSUE TITLE
pyproject.toml dependencies not reported or updated

### ISSUE THREAD

**Issue by Twistedsnail** [dependabot/dependabot-core#5933] opened 2022-10-20 01:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

https://github.com/Twistedsnail/pip-dependabot/blob/master/pyproject.toml

### dependabot.yml content

https://github.com/Twistedsnail/pip-dependabot/blob/master/.github/dependabot.yml

### Updated dependency

[from]
setuptools==64
pyyaml==5.4.1

[to]
setuptools==65.x.x
pyyaml==6.0

### What you expected to see, versus what you actually saw

I expected to see the project's dependencies listed [on the dependency graph](https://github.com/Twistedsnail/pip-dependabot/network/dependencies).
I also expected to see a PR updating the [from] to [to] sections as listed above.

I saw that the `pyproject.toml` was recognized as a manifest file but as `has no dependencies or is too large to display`.
No PR was made.

### Smallest manifest that reproduces the issue

https://github.com/Twistedsnail/pip-dependabot

**Comment by deivid-rodriguez** [comment] 2022-10-20 01:19
This is a duplicate of #3290 and will be fixed by #5661!

**Closed** 2022-10-20 01:22 UTC
Labels: T: bug 🐞
