### ISSUE TITLE
pip with increase-if-necessary strategy fails with TypeError

### ISSUE THREAD

**Issue by waltervos** [dependabot/dependabot-core#9440] opened 2024-04-05 11:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

/requirements.txt:
```
azure-core~=1.30.0
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: increase-if-necessary
```

### What you expected to see, versus what you actually saw

I expect dependabot to run without issues (as it has done until March 19. Instead, it fails with:

Parameter 'requirements_update_strategy': Expected type T.nilable(Dependabot::RequirementsUpdateStrategy), got type Symbol with value :bump_versions_if_necessary (TypeError)

Specifically:

Using 'bump_versions_if_necessary' requirements update strategy
Found 1 dependency file(s) at commit (...)
 - /requirements.txt
(...)

Checking if azure-core  needs updating
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'requirements_update_strategy': Expected type T.nilable(Dependabot::RequirementsUpdateStrategy), got type Symbol with value :bump_versions_if_necessary (TypeError)
Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:215
Definition: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.247.0/lib/dependabot/update_checkers/base.rb:62
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:300:in `report_error'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/signature.rb:234:in `block in each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/signature.rb:228:in `each'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/signature.rb:228:in `each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:215:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:339:in `new'
	from bin/update_script.rb:339:in `update_checker_for'
	from bin/update_script.rb:559:in `block in <main>'
	from bin/update_script.rb:545:in `each'
	from bin/update_script.rb:545:in `<main>'

### Smallest manifest that reproduces the issue

Already included the smallest manifest and smallest dependabot config :)

**Comment by sachin-sandhu** [comment] 2024-05-19 23:07
Hi @waltervos ,  

Can you please confirm if you are still facing the same issue as we are unable to re-produce it. If yes, can you please provide following information:

1. Kindly share full dependabot.yml content. I see the file content is missing _schedule interval_ information. for example the Dependabot config should be as following to run in GitHub.

```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
      schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
```

2. Are you trying to run Dependabot in GitHub repo. If yes, can you please share the full job log that failed to run.
3. If possible, please provide information how can we reproduce the error (i.e reference project structure).

**Comment by waltervos** [comment] 2024-05-21 14:11
@sachin-sandhu I work on Azure DevOps, with Azure Pipelines, so unfortunately there's no github repo/pipeline I can share. I've tested the attached setup out and it reproduces the issue (on Azure Pipelines). I've included the schedule/interval property, but we don't normally use it.

Does this help?

[dependabot-core-issue_9440-repro.zip](https://github.com/dependabot/dependabot-core/files/15390992/dependabot-core-issue_9440-repro.zip)

**Comment by sachin-sandhu** [comment] 2024-05-21 15:58
Thanks @waltervos , I'm going through the information. Will get back in case i need additional information.

**Comment by JamieMagee** [comment] 2024-05-24 16:11
@waltervos it looks like this is an issue with the Azure DevOps task that you're using. It requires a change to be made in the task. I've outlined what needs to be done in this comment: https://github.com/tinglesoftware/dependabot-azure-devops/issues/1046#issuecomment-2129910091

**Comment by abdulapopoola** [comment] 2024-05-25 01:24
Closing this out as the tracking issue in tinglesoftware has been filed. Please feel free to reopen.

**Closed by abdulapopoola** 2024-05-25 01:24 UTC
Labels: T: bug 🐞, L: ruby:bundler, good first issue, L: python
