### ISSUE TITLE
Support Singular Pull Request for Scheduled Updates

### ISSUE THREAD

**Issue by aaronmallen** [dependabot/dependabot-core#6185] opened 2022-11-21 21:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I have dependabot scheduled for every monday and it would be awesome if instead of receiving a bunch of PRs for each dependency update if I could configure dependabot to do all of the updates in a single Pull request.

**Comment by jurre** [comment] 2022-11-22 19:23
Going to close this out as a duplicate of https://github.com/dependabot/dependabot-core/issues/1190, it's something that's definitely on a radar 👍

**Closed by jurre** 2022-11-22 19:23 UTC
Labels: T: feature-request
