### ISSUE TITLE
Setting autocomplete/automerge on dependabot created PRs

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#3411] opened 2021-03-30 14:37 UTC
Over past couple of months, we had gotten feature requests from multiple teams in our organization to autocomplete scheduled PRs created by our service for AzureDevops repos. @feelepxyz @jurre Is this an ask that you might have observed for other clients as well?

**Comment by asciimike** [comment] 2021-04-05 22:22
Closing as a dupe of #2268 (which has context on why there is no automerge on Dependabot PRs, and some workarounds using Actions).

**Closed** 2021-04-05 22:22 UTC
Labels: T: feature-request
