### ISSUE TITLE
patch updates not grouped correctly

### ISSUE THREAD

**Issue by OmarTawfik** [dependabot/dependabot-core#8973] opened 2024-02-03 20:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Cargo

### Manifest location and content before the Dependabot update

https://github.com/NomicFoundation/slang/blob/main/Cargo.toml

### dependabot.yml content

https://github.com/NomicFoundation/slang/blob/main/.github/dependabot.yml

### Updated dependency

`syn` from `2.0.29` to `2.0.32`

## Expected

In my `dependabot.yml`, I chose to group `patch` and `minor` updates together, and keep `major` updates separate:
https://github.com/NomicFoundation/slang/blob/e097231c3c220dd6177dc704cbf0f4e95b644507/.github/dependabot.yml#L17-L21

## Actual

The following PR was created separately for a `patch` update: https://github.com/NomicFoundation/slang/pull/777
Instead of getting grouped with others in: https://github.com/NomicFoundation/slang/pull/778

**Comment by Nishnha** [comment] 2024-03-21 21:08
I tried to recreate PR #777 but I wasn't able to. I got this message in the job log instead:

```
updater | 2024/03/21 20:50:58 INFO Starting grouped update job for NomicFoundation/slang
updater | 2024/03/21 20:50:58 INFO Found 1 group(s).
updater | 2024/03/21 20:50:58 INFO Detected existing pull request for 'non-major-dependencies'.
updater | 2024/03/21 20:50:58 INFO Deferring creation of a new pull request. The existing pull request will update in a separate job.
```

When I tried to recreate PR #778 I got this PR created message that suggests syn would be included in the group update as it has 22 updates instead of just 21:

```
 +---------------------------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                           Changes to Dependabot Pull Requests                                                           |
updater | +------------------------------+--------------------------------------------------------------------------------------------------------------------------+
updater | | closed: dependencies_changed | anyhow,clap,clap_complete,ignore,indicatif,napi,napi-derive,proc-macro2,quote,rayon,regex,reqwest,semver,similar-asse... |
updater | | created                      | anyhow ( from 1.0.75 to 1.0.81 ), clap_complete ( from 4.4.6 to 4.5.1 ), ignore ( from 0.4.20 to 0.4.22 ), indexmap (... |
updater | +------------------------------+--------------------------------------------------------------------------------------------------------------------------+
updater | Dependabot encountered '2' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | clap          | unknown_error |
updater | | url           | unknown_error |
updater | +---------------+---------------+
```

I'm going to close this issue out as resolved since it's not reproducible and the job logs suggest it was fixed.

**Closed by Nishnha** 2024-03-21 21:08 UTC
Labels: T: bug 🐞, F: grouped-updates 🎳
