### ISSUE TITLE
NPE in FileParser for composer

### ISSUE THREAD

**Issue by leoamigood** [dependabot/dependabot-core#5919] opened 2022-10-18 13:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

composer

### What you expected to see, versus what you actually saw

Looks like there is NPE in FileParser for composer code:
https://github.com/dependabot/dependabot-core/blob/6535db13c37f05f268c7251216fe689ecbb9e346/composer/lib/dependabot/composer/file_parser.rb#L168

```
undefined method `find' for nil:NilClass\n\n        
parsed_lockfile.fetch(key, []).find { |d| d[\"name\"] == name }\n
```

I get this error in this repo: https://github.com/JoshuaEstes/ServerTools

**Comment by jeffwidman** [comment] 2023-02-06 09:49
We should try to repro this using the dry-run script against that repo... if it doesn't reproduce, then close for the reasons outlined here:
* https://github.com/dependabot/dependabot-core/issues/5824#issuecomment-1302396988

**Comment by deivid-rodriguez** [comment] 2023-02-06 21:52
It seems to be indeed crashing, so let's keep open!

**Comment by abdulapopoola** [comment] 2024-04-16 14:36
This will be picked up by @garryhurleyjr

**Comment by GarryHurleyJr** [comment] 2024-04-29 16:03
added some defensive coding around nil for key file and lockfile.  still have debugging code to remove.

**Comment by GarryHurleyJr** [comment] 2024-05-03 22:35
Code merged

**Closed by GarryHurleyJr** 2024-05-03 22:35 UTC
Labels: T: bug 🐞, L: php:composer, good first issue, Batch
