### ISSUE TITLE
Dependabot doesn't handle mixed versions

### ISSUE THREAD

**Issue by sblask** [dependabot/dependabot-core#6011] opened 2022-11-01 08:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

version: 2

updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - consciousconsumers/platform-security

### What you expected to see, versus what you actually saw

I've got several workflows and in one of them I've got an outdated (v2 instead of v3) github action:

```
~/Code/work/aws-configs/.github $ rg checko
workflows/enforce-rebase.yml
13:      - name: Git checkout
14:        uses: actions/checkout@v3

workflows/pre-commit.yml
15:      - name: Git checkout
16:        uses: actions/checkout@v3

workflows/terraform.yml
18:      - name: Git Checkout
19:        uses: actions/checkout@v2
72:      - name: Git checkout
73:        uses: actions/checkout@v2
```

I expected a PR to update the terraform workflow, but I didn't get any. The only entries in the log mentioning checkout are these:
```
updater | INFO <job_496722497> Checking if actions/checkout 3 needs updating
  proxy | 2022/11/01 07:52:03 [042] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 07:52:03 [042] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 07:52:03 [042] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
updater | INFO <job_496722497> Latest version is 3
updater | INFO <job_496722497> No update needed for actions/checkout 3
```

**Comment by deivid-rodriguez** [comment] 2022-11-15 17:49
Hei!

This is a duplicate of https://github.com/dependabot/dependabot-core/issues/3750, and there's a WIP PR that I expect will fix this: #6082.

Please upgrade to the referenced issue and PR for updates, thanks :)

**Closed by deivid-rodriguez** 2022-11-15 17:49 UTC
Labels: T: bug 🐞, L: github:actions
