### ISSUE TITLE
Terraform 0.15 support

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#1176] opened 2019-05-29 05:40 UTC
Dependabot's terraform support doesn't work with HCL 2.0.

In particular, our logic for parsing HCL files is [here](https://github.com/dependabot/dependabot-core/blob/master/terraform/lib/dependabot/terraform/file_parser.rb#L219-L246) and shells out to [this tool](https://github.com/kvz/json2hcl) which only support HCL 1.0 and, unfortunately, [looks unmaintained](https://github.com/kvz/json2hcl/issues/12).

To fix this we need a HCL -> soemthing-readable-by-ruby parser to replace the one we're currently using.

**Comment by greysteil** [comment] 2019-05-29 05:41
@hmarr would love your eyes on this if there's an easy fix. There seems to be almost no support for HCL in Ruby which is how we ended up using a Go project that converts HCL to JSON. 😢

**Comment by hmarr** [comment] 2019-05-29 10:29
Yep, I'll sort something out 👍

**Comment by hmarr** [comment] 2019-06-03 20:16
Upgrading to HCL 2 turns out to be surprisingly difficult. I've tried several different approaches, but none of them have worked so far. The closest I've got is using `github.com/hashicorp/terraform/config` as a library, but that breaks Terragrunt support. Parsing HCL 2 seems to require a full specification of the HCL's structure, and I can't find one for Terraform's HCL that includes Terragrunt. We could start maintaining one, but that would be a fair amount of work.

I'm going to park this for now as we have several other high priority issues to address, and come back to it in a bit.

**Comment by domcleal** [comment] 2019-06-10 10:58
> Parsing HCL 2 seems to require a full specification of the HCL's structure, and I can't find one for Terraform's HCL that includes Terragrunt. We could start maintaining one, but that would be a fair amount of work.

Terragrunt itself doesn't support 0.12 yet either and they're making some changes over at https://github.com/gruntwork-io/terragrunt/pull/731 which may be relevant. The syntax in the current Terragrunt config file is known not to be HCL2 compatible, so they're moving it into a `terragrunt.hcl` file which will be HCL2 compatible.

**Comment by wata727** [comment] 2019-06-14 12:45
[terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect) might be a good replacement in the case.

**Comment by lorengordon** [comment] 2019-07-08 10:49
@hmarr terragrunt now works with terraform 0.12. But, I think I'd suggest keeping the current parser as a fallback, if possible. That way the HCL1 syntax still works, either terraform or terragrunt.

**Comment by evenh** [comment] 2019-08-21 09:13
Some alternatives to look into:

- https://github.com/tmccombs/hcl2json
- https://github.com/PetrusHahol/pyhcl2

**Comment by scottybrisbane** [comment] 2019-10-23 01:30
Bump, this is an important issue to resolve.

**Comment by johncblandii** [comment] 2019-12-11 20:20
Can we get this worked out soon? It makes our repos noisy and renders Dependabot, a tool we really like, useless for those specific TF 0.12 repos.

**Comment by tbugfinder** [comment] 2019-12-30 20:31
This tool is very close compare to terraform-config-inspect: https://github.com/amplify-education/python-hcl2

**Comment by jakauppila** [comment] 2020-01-25 22:15
Until an HCL2.0 -> JSON library is available, would it be feasible to add support for Terraform 0.12 configurations that are expressed as JSON?

**Comment by sheldonhull** [comment] 2020-04-06 18:29
Idea on possible fix: specifying an exact file to match. 

* Scenario: I place all my provider versions into `versions.tf`
* Dependabot directory filters to only `*versions.tf`
* Versions submitted for bump now is only against this `versions.tf` without problem of parsing the remaining files.

This actual requirement to me seems like it might be the fix needed to support HCL2 without more complicated parsing requirements for an entire new HCL2 format in the remaining content in a folder.

**Comment by patrickjahns** [comment] 2020-04-07 11:05
@sheldonhull 
There is already a pull request from the community at https://github.com/dependabot/dependabot-core/pull/1388

I've taken the liberty to convert it into a github action for the time-being - hopefully this is useful for anyone else as well https://github.com/marketplace/actions/terraform-dependabot

**Comment by sheldonhull** [comment] 2020-04-07 16:50
I tried the scenario above and it doesn't work as expects a directory, not file path. 
@patrickjahns EPIC! thanks for this. I am totally checking this out for sure!

**Comment by osterman** [comment] 2020-08-27 05:48
Perhaps rename title now to Terraform 0.13 =)

**Comment by evenh** [comment] 2020-09-08 09:03
There has been over a year since the last official response and it seems important to many users of Dependabot. Could we please get a rough time estimate on this issue @greysteil & @hmarr? Is there anything the community could help out with to speed up the process?

**Comment by greysteil** [comment] 2020-09-08 09:16
I don't work on Dependabot anymore (I'm working on GitHub's code scanning features) but @infin8x is the product manager responsible here.

**Comment by bcomnes** [comment] 2020-09-08 19:49
Even improving the error message would be an improvement (e.g. dependabot doesn't support terraform 0.12 or newer!).  But also just adding support for the newer versions.

**Comment by estraph** [comment] 2020-10-02 07:14
Hi @infin8x is a fix for this on the roadmap? I checked the [public roadmap](https://github.com/github/roadmap/projects/1?card_filter_query=terraform) but couldn't find one.

**Comment by infin8x** [comment] 2020-10-08 18:23
Hi @estraph - it is not, at present. We understand and are tracking the ask but don't have a timeline.

**Comment by tbugfinder** [comment] 2020-10-08 19:49
My workaround is using https://github.com/renovatebot/renovate

**Comment by masutaka** [comment] 2020-10-09 04:40
My workaround is using [tfupdate](https://github.com/minamijoyo/tfupdate) ([CircleCI orb](https://circleci.com/developer/orbs/orb/masutaka/tfupdate))

**Comment by lorengordon** [comment] 2020-10-09 13:37
We're using the github action based on the dependabot pr, https://github.com/dependabot/dependabot-core/pull/1388#issuecomment-610322918

**Comment by bogaertg** [comment] 2021-01-25 10:48
Some news about this feature ?
Terraform with dependabot is useless without HCL 2 support.

**Comment by davidski** [comment] 2021-01-25 14:34
This seems to be on the roadmap now for this quarter (Q1 2021)! 💥

https://github.com/github/roadmap/issues/150

**Comment by mattthaber** [comment] 2021-04-07 14:41
> This seems to be on the roadmap now for this quarter (Q1 2021)! 💥
> 
> [github/roadmap#150](https://github.com/github/roadmap/issues/150)

was terraform 0.14 removed from the roadmap? i no longer see it there

**Comment by lorengordon** [comment] 2021-04-07 14:47
Yeah, if you look at the edited issue body, you can see @github-product-roadmap removed `terraform 0.14` and `pipenv 2020.11.15` before closing the issue. And no new issue was created, that I can see, yet. I guess that's one way to handle a roadmap. :/

**Comment by davidski** [comment] 2021-04-07 14:47
Yup. Looks like it was edited today to remove both pipenv 2020.11.15 and terraform 0.14. 😞 Nothing on the future roadmap to indicate modern Terraform will _ever_ be supported. Might be time to switch over to renovate or an alternative. 😢

**Comment by jurre** [comment] 2021-04-07 15:02
It's still on our planning, but we unfortunately didn't get to it last quarter. It's planned for this quarter. I expect the roadmap to be updated with this as our planning for this quarter gets finalized.

**Comment by asciimike** [comment] 2021-04-07 15:02
Hey folks, I split the issue into per-quarter ecosystem updates so we were accurately tracking when , and apparently the automation didn't pick up the Q2 updates issue :(

Don't worry, both these ecosystems are on the schedule for this quarter, and I'll post the new issue when it's updated on the roadmap.

**Comment by asciimike** [comment] 2021-04-07 20:17
Roadmap issue has been updated: https://github.com/github/roadmap/issues/191

Apologies on the delay and confusion, we promise we still care about getting these ecosystems shipped!

**Comment by wagnst** [comment] 2021-04-15 18:33
Some days ago terraform `0.15.0` was released. Will this roadmap cover `0.15` as well?

**Comment by asciimike** [comment] 2021-04-15 18:37
Looks like yesterday: https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-15-general-availability

I think we'll have to look at it and assess how much extra effort it will be to support it, though my guess is that from where we're at (0.11 IIRC?) to 0.14 or 0.15 will be the same amount of effort (the changes in 0.12 were the thing we never implemented).

**Comment by lorengordon** [comment] 2021-04-20 16:42
I feel like the problem is really the syntax of HCL1 vs HCL2, rather than any specific terraform versions. TF 0.11 and earlier used HCL1. TF 0.12 and later use HCL2.

**Comment by asciimike** [comment] 2021-04-20 16:53
@lorengordon, correct. In https://github.com/dependabot/dependabot-core/issues/1176#issuecomment-498409498 _hmarr took a look at HCL2, and we've seen https://github.com/dependabot/dependabot-core/pull/1388 and https://github.com/dependabot/dependabot-core/pull/3063 (a few months ago) as attempts to get it working.

**Comment by jurre** [comment] 2021-05-06 09:34
Just wanted to let y'all know that we've started working on this. If you have any (public) projects we could test against please let me know.

**Comment by lorengordon** [comment] 2021-05-06 13:42
@jurre Here are a couple of ours you can use, where the test configs should have external modules with stale refs, and the dependabot config is already setup...

* https://github.com/plus3it/terraform-aws-tardigrade-security-group
* https://github.com/plus3it/terraform-aws-tardigrade-vpc-flow-log

**Comment by jurre** [comment] 2021-05-14 13:20
Support for HCL2 should be available now, we're still working on support for lockfiles, so if you have those checked into version control you'll have to hold on for a bit longer.

We're also planning to add support for provider updates, something that we did not do until now.

A *big* thank you to @userhas404d and @jmahowald who's PR's formed the core of our implementation.

I'm going to leave this issue open until we land support for lockfiles and providers, but please open issues for other things you run into.

**Comment by lorengordon** [comment] 2021-05-14 13:28
@jurre Confirmed it's working on those projects I linked before, thanks!

**Comment by mwarkentin** [comment] 2021-05-14 21:10
Are there some docs on how this works / how to set it up? :)

**Comment by wagnst** [comment] 2021-05-14 22:41
Great! now testing shows unfortunately that private registries are not supported (for modules hosted there), they don't reveal their version until authenticated. Created https://github.com/dependabot/dependabot-core/issues/3723

**Comment by asciimike** [comment] 2021-05-15 00:54
> Are there some docs on how this works / how to set it up? :)

You can just use terraform as you've always used it, we just support the new versions!

**Comment by asciimike** [comment] 2021-05-15 00:55
> Great! now testing shows unfortunately that private registries are not supported (for modules hosted there), they don't reveal their version until authenticated. Created https://github.com/dependabot/dependabot-core/issues/3723

It's on our radar (along with lockfiles and some other goodies), so stay tuned!

**Comment by mwarkentin** [comment] 2021-05-15 02:04
@asciimike yeah I haven't used dependabot for terraform yet. Wondering if there are docs or examples over https://dependabot.com/terraform/

**Comment by asciimike** [comment] 2021-05-15 05:34
Ah apologies, https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates#enabling-dependabot-version-updates is going to be the best place to start.

**Comment by ohookins** [comment] 2021-05-21 10:24
Any intention/interest of supporting [terraform-bundle](https://github.com/hashicorp/terraform/tree/main/tools/terraform-bundle) files?

**Comment by jurre** [comment] 2021-05-21 10:45
> Any intention/interest of supporting [terraform-bundle](https://github.com/hashicorp/terraform/tree/main/tools/terraform-bundle) files?

Currently no plans to support them, and we likely won't be able to work on it the near future. We can explore it a bit, and if someone wants to contribute support for it, I'd definitely be open to discussing that.

Would you expect Dependabot to only update the bundle file, or also generate the actual bundles?

I have some questions around how we should even handle cases like this:

```
  google = {
    versions = ["~> 1.0", "~> 2.0"]
  }
```

**Comment by ohookins** [comment] 2021-05-21 10:50
Can't comment on the multiple versions as we only use one. But my hope was that Dependabot would just update the bundle file, and then we re-run our build pipeline to regenerate the bundle.

**Comment by ohookins** [comment] 2021-05-23 11:59
I'm looking into alternative approaches, like putting our bundle dependencies in a traditional `required_providers` block and then using an HCL2 parser to reform it into what terraform-bundle would read - allowing me to use Dependabot to update the versions and then trigger a build and bundle it with a little extra work. Sadly the first phase of checking for updates is failing.

```
updater | INFO <job_137261663> Checking if hashicorp/archive  needs updating
  proxy | 2021/05/23 11:43:07 [022] GET https://registry.terraform.io:443/v1/providers/hashicorp/archive/versions
  proxy | 2021/05/23 11:43:07 [022] 200 https://registry.terraform.io:443/v1/providers/hashicorp/archive/versions
updater | INFO <job_137261663> Latest version is 2.2.0
updater | INFO <job_137261663> Requirements to unlock update_not_possible
updater | INFO <job_137261663> Requirements update strategy 
updater | INFO <job_137261663> No update possible for hashicorp/archive 
```
Initially I was defining constraints using the twiddle operator but changed them all to `>=` which should allow it to work. Currently I have this dependency defined as:
```
    archive = {      
      source = "hashicorp/archive"
      version = ">= 2.1"
    }
```
Not sure what's going on here that is preventing the update, although I haven't dug into the logic in depth yet.

**Comment by masutaka** [comment] 2021-05-26 04:09
Do you plan to support the terraform version?

```
terraform {
  required_version = "0.15.4" # <- this
  # ...
}
```

**Comment by masutaka** [comment] 2021-05-27 01:27
I strongly hope dependabot will support the actual terraform version. :smile:

**Comment by jurre** [comment] 2021-06-10 10:03
Lockfile support and private registries are now available, with that, I'm going to consider this done.

Feel free to open separate feature requests for things not currently supported and we can discuss those separately.

**Closed by jurre** 2021-06-10 10:03 UTC
Labels: F: language-support, L: terraform, T: feature-request
