### ISSUE TITLE
Update dependency in same PR instead of superseding it

### ISSUE THREAD

**Issue by Andre601** [dependabot/dependabot-core#3993] opened 2021-06-25 14:46 UTC
The way Dependabot currently manages open PRs of dependencies, which received an update is bad in some way.

Whenever a dependency has been updated and a PR for the previous version is open will Dependabot create a new PR, close the existing one and comment on it with `Superseded by #:id`

This is in many ways bad and only causes the amount of open PRs to be bloated.
There are many different OS-Projects that may not be able to update a dependency in time due to reasons such as priority or simply because it needs validation or testing to guarantee stuff not breaking by it. And in such a time, which can be days or even weeks, can the dependency update, causing Dependabot to repeat the cycle anew.

With this issue would I now suggest implementing a config option (which would be disabled by default to not break existing setups) to tell Dependabot to not create a new PR every time a dependency updates and an open PR being there. Instead, should it just update the PR in question, similar to a rebase, and post a comment there informing about the dependency being updated alongside any changelog and/or release notes if available.

That way could people like me keep track of dependencies while not being annoyed by 3+ separate notifications that PR A was closed, PR B was opened and Comment A was made informing us about it.

**Comment by mwaddell** [comment] 2022-01-29 18:57
Duplicate of #2882

**Comment by Andre601** [comment] 2022-01-29 19:30
Can't really see where this is a duplicate of the mentioned issue.
The issue in question is more about Dependabot force-pushing changes whenever conflicts are detected in a file, while mine is more about updating an existing update PR instead of making a new one just because the dependency's version got bumped again...

**Comment by mwaddell** [comment] 2022-01-29 20:10
Sorry - my mistake.

**Comment by jeffwidman** [comment] 2022-08-31 00:23
👋 Hey there! Sorry for the slow response... we've been a bit buried.

Closing as a dupe of https://github.com/dependabot/dependabot-core/issues/2264. That one wasn't named very clearly for folks searching, so I tweaked the title to make it more clear.

**Closed by jeffwidman** 2022-08-31 00:23 UTC
Labels: T: feature-request
