### ISSUE TITLE
Dependabot endlessly creates PRs, closing the old one, to create the same thing a second later.

### ISSUE THREAD

**Issue by KyleSanderson** [dependabot/dependabot-core#7894] opened 2023-08-24 05:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

go, npm, github

### dependabot.yml content

https://github.com/autobrr/autobrr/blob/82ffd3645b8139b2fda924ea70afeaa2bc277dd2/.github/dependabot.yml

### What you expected to see, versus what you actually saw

https://github.com/autobrr/autobrr/pull/1045#issuecomment-1675787855 this is the exact wrong behaviour.

The group should be updated, not closed and a new issue created - this is actively harmful. This runs a bunch of webhooks saying an issue was closed without merging, and a new one has been opened. This not only damages projects using the schedule feature, but spams watchers (actual end-users of a project) endlessly with noise if you take a single weekend off from coding. If I don't touch a project for a month, I don't need 5 closed issues, with the exact same issue opened time and time again.

See: https://github.com/autobrr/autobrr/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+

**Comment by jakecoffman** [comment] 2023-08-24 18:43
That sounds frustrating! 

It looks like https://github.com/autobrr/autobrr/pull/1045 was superseded by https://github.com/autobrr/autobrr/pull/1046 because `@types/node` and `eslint` had newer versions.

The team has talked about removing the superseding functionality [in the past](https://github.com/dependabot/dependabot-core/issues/2264), but right now this is working as designed. 

Perhaps setting the schedule to monthly might be better? 

For now I'm going to close as a duplicate of https://github.com/dependabot/dependabot-core/issues/2264 because I think the root cause of this frustration is the superseding functionality. I appreciate you taking the time to let us know!

**Closed by jakecoffman** 2023-08-24 18:43 UTC
Labels: T: bug 🐞, F: grouped-updates 🎳

**Comment by KyleSanderson** [comment] 2023-08-24 19:11
> That sounds frustrating!
> 
> It looks like [autobrr/autobrr#1045](https://github.com/autobrr/autobrr/pull/1045) was superseded by [autobrr/autobrr#1046](https://github.com/autobrr/autobrr/pull/1046) because `@types/node` and `eslint` had newer versions.
> 
> The team has talked about removing the superseding functionality [in the past](https://github.com/dependabot/dependabot-core/issues/2264), but right now this is working as designed.
> 
> Perhaps setting the schedule to monthly might be better?
> 
> For now I'm going to close as a duplicate of #2264 because I think the root cause of this frustration is the superseding functionality. I appreciate you taking the time to let us know!

Ultimately what I'm looking for from this is for a way to have a pending PR to update deps in preparation for a release. When the release is close I'm going to rebase the PR through the command, test the artifact, then merge into the tree. This is simply impossible if on any polling interval it generates new PRs on a whim if a dependency is updated.

I'm happy to chat with PM if desired during ET hours.
