### ISSUE TITLE
nokogiri stack level is too deep error

### ISSUE THREAD

**Issue by leoamigood** [dependabot/dependabot-core#5856] opened 2022-10-08 09:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### What you expected to see, versus what you actually saw

```
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786591059978&selected=1515294786591059978) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786591059978&selected=1515294786591059978)  2022-10-08T06:47:31.167Z pid=1 tid=kggt WARN: {"context":"Job raised exception","job":{"retry":3,"queue":"high","args":["MasterEx/bean-mapping-benchmark"],"class":"ContentSurferJob","jid":"209ce2ff2a6ae34ebcd9d99e","created_at":1665211262.457624,"enqueued_at":1665211646.8645055,"error_message":"stack level too deep","error_class":"SystemStackError","failed_at":1665211395.2709484,"retry_count":2,"retried_at":1665211589.6356738}}
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786591059982&selected=1515294786591059982) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786591059982&selected=1515294786591059982) 2022-10-08T06:47:31.167Z pid=1 tid=kggt WARN: SystemStackError: stack level too deep
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786591059987&selected=1515294786591059987) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786591059987&selected=1515294786591059987) 2022-10-08T06:47:31.190Z pid=1 tid=kggt WARN: /usr/local/bundle/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/xml/searchable.rb:252:in `each'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786591059988&selected=1515294786591059988) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786591059988&selected=1515294786591059988) /usr/local/bundle/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/xml/searchable.rb:252:in `find'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786591059993&selected=1515294786591059993) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786591059993&selected=1515294786591059993) /usr/local/bundle/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/xml/searchable.rb:252:in `extract_params'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786591059994&selected=1515294786591059994) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786591059994&selected=1515294786591059994) /usr/local/bundle/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/xml/searchable.rb:175:in `xpath'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786595254274&selected=1515294786595254274) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786595254274&selected=1515294786595254274) /usr/local/bundle/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/xml/searchable.rb:189:in `at_xpath'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294786595254284&selected=1515294786595254284) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294786595254284&selected=1515294786595254284) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser/property_value_finder.rb:35:in `block in property_details'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787106959375&selected=1515294787106959375) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787106959375&selected=1515294787106959375) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser/property_value_finder.rb:33:in `loop'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787106959376&selected=1515294787106959376) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787106959376&selected=1515294787106959376) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser/property_value_finder.rb:33:in `property_details'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787106959377&selected=1515294787106959377) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787106959377&selected=1515294787106959377) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:257:in `value_for_property'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787106959378&selected=1515294787106959378) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787106959378&selected=1515294787106959378) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:233:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153664&selected=1515294787111153664) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153664&selected=1515294787111153664) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153666&selected=1515294787111153666) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153666&selected=1515294787111153666) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153667&selected=1515294787111153667) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153667&selected=1515294787111153667) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153668&selected=1515294787111153668) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153668&selected=1515294787111153668) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153669&selected=1515294787111153669) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153669&selected=1515294787111153669) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153670&selected=1515294787111153670) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153670&selected=1515294787111153670) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153672&selected=1515294787111153672) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153672&selected=1515294787111153672) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153673&selected=1515294787111153673) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153673&selected=1515294787111153673) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
Oct 08 07:47:32 [finder](https://my.papertrailapp.com/systems/finder/events?focus=1515294787111153674&selected=1515294787111153674) [sidekiq](https://my.papertrailapp.com/groups/36296331/events?q=program%3Asidekiq&focus=1515294787111153674&selected=1515294787111153674) /usr/local/bundle/bundler/gems/dependabot-core-6a1c0b75262e/maven/lib/dependabot/maven/file_parser.rb:236:in `evaluated_value'
```

**Comment by jurre** [comment] 2022-10-17 11:41
@leoamigood could you add a bit more context on what is required to reproduce this issue? There's not much we can do with the current information you've provided. It also looks like you're not using GitHub's hosted version of Dependabot, as those logs look look like ours, could you share a bit more about that as well?

**Comment by leoamigood** [comment] 2022-10-17 12:11
@jurre Sure, i am using Dependabot separate from Github hosted version, by just using gems in my app. 
I run dependency evaluations against many github repos, and collect logs if any fails happen.
In this case it looks like dependency evaluation failed for [this repo](https://github.com/MasterEx/bean-mapping-benchmark)
causing `SystemStackError: stack level too deep`

Let me know if i can help further.

**Comment by thavaahariharangit** [comment] 2024-04-10 15:37
In Progress : https://github.com/dependabot/dependabot-core/pull/9472

**Comment by thavaahariharangit** [comment] 2024-04-16 12:28
PR Merged and this issue is resolved. https://github.com/dependabot/dependabot-core/pull/9472

**Closed by thavaahariharangit** 2024-04-16 12:28 UTC
Labels: T: bug 🐞, L: java:maven, good first issue, Batch
