### ISSUE TITLE
[Golang]: Dependabot creates conflicts in Go Modules

### ISSUE THREAD

**Issue by kushthedude** [dependabot/dependabot-core#1846] opened 2020-05-07 07:18 UTC
**Package manage/ecosystem**

Golang 1.13

**Manifest contents prior to update**

https://github.com/layer5io/meshery/blob/master/go.mod

**What you expected to see, versus what you actually saw**

Whenever dependabot bumps a Go-Modules, it updates the package version in `go.mod` by overwriting on the current version but rather than overwriting in `go.sum`, dependabot adds the `.sum` manifest for the updated version, which creates conflicts when we merge and starts development on local.
As dependabot updates the `yarn.lock` or `package-lock.json` by overwriting the updated version dependencies on current, it should also do the same for `go.sum`.

**Images of the diff or a link to the PR, issue or logs**

See here https://github.com/layer5io/meshery/pull/964/files , Dependabot overwrites the version in `go.mod` but in `go.sum` it doesn't remove manifests of the old version which we need to do manually to avoid conflicts on local environment.

**Comment by hmarr** [comment] 2020-05-13 11:20
Looks like this is a duplicate of https://github.com/dependabot/feedback/issues/909, so let's track this there.

**Closed by hmarr** 2020-05-13 11:20 UTC
Labels: bug
