### ISSUE TITLE
How can we change the Maven repository URL to an internal Nexus proxy?

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#3806] opened 2021-05-28 00:51 UTC
Hi team, 

This line : https://github.com/dependabot/dependabot-core/blob/2f0db3e851ba2cc43d0b6dcd70da5e69d5b63eb6/maven/lib/dependabot/maven/file_parser/repositories_finder.rb#L26 

Suggests that this value is hardcoded and cannot be set. 

I am running in a corporate environment where there is no connectivity with `repo.maven.apache.org` and where we need to use our internal Nexus proxy to pull the dependencies. 

This results in the following error : 

`23:54:26  /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/excon-0.81.0/lib/excon/socket.rb:156:in connect: no address for repo.maven.apache.org (Resolv::ResolvError) (Excon::Error::Socket)
`

I tried setting a explicit `distributionManagement` section but that did not help

I also set explicit repositories in the configuration :  

```
 credentials << {
      "type" => "maven_repository",
       "url" => "https://mymaven-repo"
    }
```

But it is still trying to connect to repo.maven.apache.org/maven2

**Comment by yeikel** [comment] 2021-05-28 03:46
I tried updating the `CENTRAL_REPO_URL` and pushing an internal version (using https://github.com/dependabot/dependabot-core/blob/main/Dockerfile.ci) but somehow the logs still show that is trying to connect to to https://repo.maven.apache.org/maven2

I am lost

**Comment by yeikel** [comment] 2021-05-29 08:20
It seems that releasing the gems with a different `CENTRAL_REPO_URL` works. Is there any other way to accomplish this?

**Comment by lseppala** [comment] 2021-11-30 23:41
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since. Is this still happening, or has this problem been resolved and can we close this issue?

As it seems you're familiar, Dependabot now supports configuring private registries ([documentation link](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-private-registries)). If this is still an issue even with private registry (your internal Nexus proxy) configured, I think I understand that the issue is that it Dependabot will still check the default `CENTRO_REPO_URL` regardless of whether it succeeded in connecting to the internal Nexus first. This would be a bug, and we will prioritize it appropriately if confirmed the issue is still happening.

**Comment by yeikel** [comment] 2021-12-28 14:16
Yes. The issue is still happening as the line mentioned above is not something we can overwrite

**Comment by lseppala** [comment] 2022-01-04 18:07
Thanks for the confirmation. We will prioritize and address as soon as we can.

**Comment by marwin1991** [comment] 2022-03-04 14:23
Is there any progress to use override `CENTRAL_REPO_URL` ?

**Comment by marwin1991** [comment] 2022-03-04 15:06
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-private-registries

For python there is a ability to define:
<html>
<body>


replaces-base | For registries with type: python-index, if the boolean value is true, pip resolves dependencies by using the specified URL rather than the base URL of the Python Package Index (by default https://pypi.org/simple).
-- | --



</body>
</html>


I think it would be pretty simple to change default (`CENTRAL_REPO_URL = "https://repo.maven.apache.org/maven2" `
to value from `maven-repository.url` when `replaces-base` set to `true`

**Comment by yeikel** [comment] 2022-03-04 16:07
I am using dependabot script and this is how I defined the proxy : 


ENV['http_proxy'] = 'http://xxx:port/'
ENV['no_proxy'] = '127.0.0.1,.localdomain'

I am not sure if there is any way for the dependabot app

**Comment by peter-c-larsson** [comment] 2022-04-07 06:59
Similar issue where we have a corporate proxy that is configured when running with all combinations of:
```
"https_proxy=http://198.18.0.33:8080", "http_proxy=http://198.18.0.33:8080", "HTTPS_PROXY=http://198.18.0.33:8080", "HTTP_PROXY=http://198.18.0.33:8080"
```

Can see in the firewall in that the proxy settings is not honored.



In our logs all we see is:
```
[2022-04-07 06:37:06 +0000 tid=1bb6] ERROR -- [.../tutorial/java-tutorial=>maven] EOFError (EOFError)
[2022-04-07 06:37:06 +0000 tid=1bb6] INFO  -- [.../tutorial/java-tutorial=>maven] Fetching info for org.apache.maven.plugins:maven-compiler-plugin
```

**Comment by jakecoffman** [comment] 2022-10-19 21:06
`replaces-base` for Maven was implemented in core in https://github.com/dependabot/dependabot-core/pull/5908

Let me know if you have any issues with it.

**Closed by jakecoffman** 2022-10-19 21:06 UTC
Labels: T: bug 🐞, L: java:maven, 🍏 core
