### ISSUE TITLE
[Gitlab] Creating a new MR results in a "assignee_ids is invalid" error

### ISSUE THREAD

**Issue by RodrigoPetter** [dependabot/dependabot-core#1732] opened 2020-03-12 17:54 UTC
Since this https://github.com/dependabot/dependabot-core/pull/1576 PR, creating a new MR at Gitlab results in the error "Server responded with code 400, message: assignee_ids is invalid".

If I print the post boby of the request I can see the following:

```
:remove_source_branch=>true, :assignee_ids=>[nil], :labels=>"dependencies,ruby", :milestone_id=>nil}, :verify=>false}
```

The log of the Gitlab response:

```
Traceback (most recent call last):
	17: from automatic-update-script.rb:6:in `<main>'
	16: from automatic-update-script.rb:6:in `glob'
	15: from automatic-update-script.rb:14:in `block in <main>'
	14: from automatic-update-script.rb:14:in `each'
	13: from automatic-update-script.rb:17:in `block (2 levels) in <main>'
	12: from /dpe-dependabot/dependabot-script.rb:66:in `execute'
	11: from /dpe-dependabot/dependabot-script.rb:66:in `each'
	10: from /dpe-dependabot/dependabot-script.rb:119:in `block in execute'
	 9: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/pull_request_creator.rb:74:in `create'
	 8: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/pull_request_creator/gitlab.rb:45:in `create'
	 7: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/pull_request_creator/gitlab.rb:136:in `create_merge_request'
	 6: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/clients/gitlab_with_retries.rb:64:in `method_missing'
	 5: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/clients/gitlab_with_retries.rb:82:in `retry_connection_failures'
	 4: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/clients/gitlab_with_retries.rb:67:in `block in method_missing'
	 3: from /dpe-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.117.2/lib/dependabot/clients/gitlab_with_retries.rb:67:in `public_send'
	 2: from /dpe-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.13.1/lib/gitlab/client/merge_requests.rb:89:in `create_merge_request'
	 1: from /dpe-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.13.1/lib/gitlab/request.rb:53:in `block (2 levels) in <class:Request>'
/dpe-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.13.1/lib/gitlab/request.rb:61:in `validate': Server responded with code 400, message: assignee_ids is invalid. Request URI: https://gitlab.defpub.local/api/v4/projects/portal%2Dda%2Ddefensoria%2Foperations%2Fdpe%2Ddependabot/merge_requests (Gitlab::Error::BadRequest)
```

If I revert the #1576 code, then the post starts to work again.

The diference betwen the two are:
- Error: `:assignee_ids=>[nil]`
- Success: `:assignee_ids=>nil`

My assignees probably is `nil` because i followed the example at dependabot-script: 
https://github.com/dependabot/dependabot-script/blob/d35ea8d9b632eb512bfd05306686d3b0b5fd02ba/generic-update-script.rb#L179

As I do not wish to send an assignees ID, removing the line 179 from the `generic-update-script.rb` solved my problem. 

I don't know what should be the correct solution. Maybe update the example or adding a validation to not try sending an invalid list at the assignee_ids.

**Comment by m-aciek** [comment] 2020-06-04 15:23
Got hit by it today. +1

**Comment by andrcuns** [comment] 2020-06-27 08:56
I would argue the issue is in the dependabot-script repository and that's where it should be fixed. The change in core just alligned with changes in gitlab api.

**Comment by jurre** [comment] 2021-11-26 13:34
I don't believe this is an issue we can fix in dependabot-core, but rather the calling code needs to be updated. I'm going to close out this issue.

**Closed by jurre** 2021-11-26 13:34 UTC
Labels: 🍏 core
