### ISSUE TITLE
PNPM Dependabot dependencies failing to update

### ISSUE THREAD

**Issue by mkallies** [dependabot/dependabot-core#8025] opened 2023-09-13 14:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

8.16.2

### Manifest location and content before the Dependabot update

pnpm-lock.yaml https://gist.github.com/mkallies/a4e1c7cbecf2824fb0a9713d66ca5028

### dependabot.yml content

# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 25
    commit-message:
      prefix: '[Dependabot]'
      include: 'scope'
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: 'next'
      - dependency-name: 'react-number-format'

### What you expected to see, versus what you actually saw

Updates should happen correctly without errors.

In particular, we see errors like the following:

updater | 2023/09/13 14:13:24 INFO <job_721502440> Sending event 862ec9e73b4f45738f47397dba972f5a to Sentry
  proxy | 2023/09/13 14:13:24 [960] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/09/13 14:13:24 [960] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/09/13 14:13:24 ERROR <job_721502440> Error processing storybook (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/09/13 14:13:24 ERROR <job_721502440> Progress: resolved 1, reused 0, downloaded 0, added 0
updater |  ERROR  Command failed with exit code 128: git fetch --depth 1 origin 2311c30aee8855386143334874755e5101224288
updater | error: cannot run ssh: No such file or directory
updater | fatal: unable to fork
updater | 
updater | pnpm: Command failed with exit code 128: git fetch --depth 1 origin 2311c30aee8855386143334874755e5101224288
updater | error: cannot run ssh: No such file or directory
updater | fatal: unable to fork
updater |     at makeError (/home/dependabot/.cache/node/corepack/pnpm/8.6.12/dist/pnpm.cjs:24890:17)
updater |     at handlePromise (/home/dependabot/.cache/node/corepack/pnpm/8.6.12/dist/pnpm.cjs:25461:33)
updater |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
updater |     at async gitFetcher (/home/dependabot/.cache/node/corepack/pnpm/8.6.12/dist/pnpm.cjs:113576:11)
updater |     at async fetcher (/home/dependabot/.cache/node/corepack/pnpm/8.6.12/dist/pnpm.cjs:126087:16)
updater |     at async run (/home/dependabot/.cache/node/corepack/pnpm/8.6.12/dist/pnpm.cjs:125494:23)
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/common/lib/dependabot/shared_helpers.rb:343:in `run_shell_command'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:57:in `run_pnpm_updater'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:41:in `block (2 levels) in run_pnpm_update'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/common/lib/dependabot/shared_helpers.rb:194:in `with_git_configured'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:40:in `block in run_pnpm_update'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `block in in_a_temporary_repo_directory'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `chdir'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `in_a_temporary_repo_directory'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:39:in `run_pnpm_update'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:24:in `updated_pnpm_lock_content'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:246:in `updated_pnpm_lock_content'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:175:in `pnpm_lock_changed?'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:208:in `block in updated_lockfiles'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:207:in `each'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:207:in `updated_lockfiles'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:43:in `updated_dependency_files'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:86:in `generate_dependency_files'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:36:in `run'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:25:in `create_from'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:122:in `check_and_create_pull_request'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `check_and_create_pr_with_error_handling'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:63:in `run'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/09/13 14:13:24 ERROR <job_721502440> bin/update_files.rb:23:in `<main>'
updater | 2023/09/13 14:13:24 INFO <job_721502440> Finished job processing
updater | 2023/09/13 14:13:24 INFO Results:
updater | Dependabot encountered '24' error(s) during execution, please check the logs for more details.
updater | +--------------------------------------------------+
updater | |          Dependencies failed to update           |
updater | +----------------------------------+---------------+
updater | | @storybook/addon-links           | unknown_error |
updater | | @babel/parser                    | unknown_error |
updater | | @babel/core                      | unknown_error |
updater | | array.prototype.at               | unknown_error |
updater | | @storybook/nextjs                | unknown_error |
updater | | dd-trace                         | unknown_error |
updater | | @apollo/client                   | unknown_error |
updater | | @typescript-eslint/parser        | unknown_error |
updater | | launchdarkly-react-client-sdk    | unknown_error |
updater | | @actions/core                    | unknown_error |
updater | | @datadog/browser-rum             | unknown_error |
updater | | ua-parser-js                     | unknown_error |
updater | | @babel/types                     | unknown_error |
updater | | typescript                       | unknown_error |
updater | | vercel                           | unknown_error |
updater | | eslint                           | unknown_error |
updater | | @babel/generator                 | unknown_error |
updater | | @babel/traverse                  | unknown_error |
updater | | jest-environment-jsdom           | unknown_error |
updater | | jest                             | unknown_error |
updater | | eslint-plugin-testing-library    | unknown_error |
updater | | msw                              | unknown_error |
updater | | @typescript-eslint/eslint-plugin | unknown_error |
updater | | storybook                        | unknown_error |
updater | +----------------------------------+---------------+
updater | time="2023-09-13T14:13:24Z" level=info msg="task complete" container_id=job-721502440-updater exit_code=0 job_id=721502440 step=updater

We do not see any dependabot updates since we've migrated to pnpm

### Native package manager behavior

It worked before we switched to pnpm

**Comment by deivid-rodriguez** [comment] 2023-09-26 09:03
Hei, thanks for the report. This seems like a duplicate of #7258, which is an upstream issue which unfortunately remains unsolved.

I'm going to close this based on that, please watch that other issue where we are tracking resolution.

Of course, if I'm mistaken and this looks like something different, let me know!

**Closed by deivid-rodriguez** 2023-09-26 09:03 UTC
Labels: T: bug 🐞, L: javascript:pnpm
