### ISSUE TITLE
Automatic PR merging with branch protection rules

### ISSUE THREAD

**Issue by bennycode** [dependabot/dependabot-core#2034] opened 2020-02-10 11:27 UTC
In my GitHub repository I [protected](https://help.github.com/en/github/administering-a-repository/about-protected-branches) the "master" branch so that it requires pull request reviews before merging. This now stops Dependabot from [automatic PR merging](https://dependabot.com/blog/automatic-pull-request-merging/) because it needs a pull request review first. 

I cannot add Dependabot to the list of people who can dismiss pull request reviews because it's an integration and not a user. 

Can I add Dependabot to the list of [code owners](https://github.blog/2017-07-06-introducing-code-owners/) so that it can approve it's own PR? 

My goal is to achieve that Dependabot can auto merge dependency updates while other contributors still need an approval to merge PRs.

**Comment by ZebraFlesh** [comment] 2020-08-26 00:01
I've successfully added the `dependabot-preview` app to my code owners file. Combined with the auto-approve-action, dependabot can now auto merge PRs to my protected branch.

**Comment by mwaddell** [comment] 2022-01-29 19:21
> Dependabot currently can't approve its own PRs.

Nobody can approve their own PRs, even if they're code owners, or even admins.  It's dumb (because it doesn't actually prevent any "bad behavior" - it's a false sense of security), but it's a github-wide limitation.  Your only option is to use a custom github action like noted by @feelepxyz which runs as a different "user" than dependabot.

**Comment by josesimoes** [comment] 2022-09-01 11:35
I'm having this same problem.

Considering that there is an option in the protection rule to add people/apps that can dismiss PR reviews, I thought on adding `dependabot` there. Turns out that one can only add people that are on the repo (or organization) people list. 
I then sent an invite for dependabot to join the organization. Nothing happened after that. I guess that's because the invite requires accepting it and this account is automated.

Was thinking that maybe GitHub could "auto" add dependabot to the people's list of a repo that has dependabot updates enabled. Or maybe simpler to allow/accept adding dependabot in that exception list for the protection rules.

**Comment by jeffwidman** [comment] 2022-11-23 23:52
While this was originally opened against Dependabot pre-acquisition, today it's essentially a duplicate of https://github.com/dependabot/dependabot-core/issues/2480, so closing this one as a dupe.

Noe that for some usecases, there is a way to automerge: https://github.blog/changelog/2021-02-04-pull-request-auto-merge-is-now-generally-available/

**Closed by jeffwidman** 2022-11-23 23:52 UTC
Labels: F: pull-requests, 💁 service
