### ISSUE TITLE
Go module update broken

### ISSUE THREAD

**Issue by saschagrunert** [dependabot/dependabot-core#1248] opened 2019-07-10 09:44 UTC
The go module based updates seem broken to me since quite some time:

![screenshot](https://user-images.githubusercontent.com/695473/60959103-e4c93180-a307-11e9-8ba1-bd7f376bd244.png)

It's a bit hard to debug since I don't have any access to logs or such, but you may find something. The upstream repository is: https://github.com/cri-o/cri-o

**Comment by greysteil** [comment] 2019-07-10 12:16
Thanks for reporting. This is one for @hmarr.

**Comment by hmarr** [comment] 2019-07-13 19:30
I think the problem is that BitBucket switched off the previous version of their API, which was being used under the hood by one of the libraries we use for mapping packages to SCM repos. There was a patch to the library a couple of days ago to flip it to the new API version, which I'm hoping will fix this.

I was surprised Dependabot hadn't automatically kept the library up-to-date, then I realised (to my horror!) that we didn't have Dependabot enabled on that particular part of our codebase 😱. That's fixed in https://github.com/dependabot/dependabot-core/pull/1259.

**Closed** 2019-07-13 20:17 UTC

**Comment by saschagrunert** [comment] 2019-07-13 20:40
Thanks for all the work behind it.
