### ISSUE TITLE
Dependabot doesn't update actions with mixed tag use

### ISSUE THREAD

**Issue by dannysauer** [dependabot/dependabot-core#6695] opened 2023-02-18 14:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

Excerpt from dependencies page, with unnecessary links to workflows. Note that some workflows use checkout@v3, while others use checkout@v3.x.y

Dependencies defined in […/workflows/lint-secrets.yml](https://github.com/determined-ai/determined/blob/master/.github/workflows/lint-secrets.yml) 1
@actions
https://github.com/actions/checkoutactions/checkout
3
 Dependencies defined in […/workflows/pre-commit.yml](https://github.com/determined-ai/determined/blob/master/.github/workflows/pre-commit.yml) 3
@actions
https://github.com/actions/checkoutactions/checkout
3.0.0
@actions
https://github.com/actions/setup-pythonactions/setup-python
3
@pre-commit
https://github.com/pre-commit/actionpre-commit/action
3.0.0
 Dependencies defined in […/workflows/publish-helm.yml](https://github.com/determined-ai/determined/blob/master/.github/workflows/publish-helm.yml) 1
@actions
https://github.com/actions/checkoutactions/checkout
3.0.2

### dependabot.yml content

https://github.com/determined-ai/determined/blob/986681bb1dbb3889fd3a63e7e5099405eafc8e4f/.github/dependabot.yml

### Updated dependency

3.3.0

### What you expected to see, versus what you actually saw

I expect workflow files with fully qualified versions to be updated and workflow files with "v3" to stay unchanged.

What I saw is the scanner finding one workflow with v3, and deciding that all workflows with 3.x are thus OK because there is no v4. As a result, some actions fail due to a depreciation warning in 3.0.x which would've been fixed if dependabot was updating dependencies. :D 

Note: links above may not be accurate in the future, since I'm going to fix these manually today.

**Comment by deivid-rodriguez** [comment] 2023-02-22 14:19
This seems like a duplicate of #3750, although it does introduce that each version bumped should get their precision respected. I think #6082 should fix this, but I will check this detail too, since I'm not clear it will work the way you expect. Please subscribe to the other ticket and we can keep the discussion there.

**Closed by deivid-rodriguez** 2023-02-22 14:19 UTC
Labels: T: bug 🐞

**Comment by dannysauer** [comment] 2023-02-22 14:48
Cool, thanks for the links. My search skills failed met. :)
