### ISSUE TITLE
Notify Dependabot of a private dependency release

### ISSUE THREAD

**Issue by moltenice** [dependabot/dependabot-core#4008] opened 2021-06-30 09:46 UTC
Is this API call available on GitHub native Dependabot: https://github.com/dependabot/api-docs#notify-dependabot-of-a-private-dependency-release

When a private dependency updates, we want to tell Dependabot this via an API call from CI/CD so it can instantly create PRs in the repositories that have this dependency.

**Comment by asciimike** [comment] 2021-07-02 18:22
No, this API doesn't currently exist on GitHub-native Dependabot, nor do we support live updates (as called out in [our migration docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot)).

For now, setting Dependabot to update daily is going to be the fastest way to get an update out. In the future, live updates (or an API to trigger an update) may come out and make this easier. I'll leave this issue open as a FR to track that.

**Comment by jeffwidman** [comment] 2023-02-06 05:10
Closing as a duplicate of a combination of the following:
* https://github.com/dependabot/dependabot-core/issues/2980
* https://github.com/dependabot/dependabot-core/issues/2201
* https://github.com/dependabot/dependabot-core/issues/3488

**Closed by jeffwidman** 2023-02-06 05:10 UTC
Labels: T: feature-request, E: api-support
