### ISSUE TITLE
Open PR for specific release type (patch|minor|major)

### ISSUE THREAD

**Issue by mittalyashu** [dependabot/dependabot-core#2845] opened 2020-12-11 03:59 UTC
Dependabot opens a new PR for any package when there is a bump in version number regardless its a patch, minor or major release.

It will be helpful to limit the number of PRs, by specifying the release type. Using `schedule.interval` or `open-pull-requests-limit` doesn't give that much control over the type of PR dependabot creates.

This idea might no against security patch fix, maybe by-default it can ignores the configuration in case for security PR.

**Comment by mairaw** [comment] 2021-03-17 01:32
I'd love to see this implemented.

**Comment by feelepxyz** [comment] 2021-04-09 09:52
Closing as a duplicate of #2219

**Closed by feelepxyz** 2021-04-09 09:52 UTC
Labels: F: noise, F: pull-requests, F: version-updates ⬆️, T: feature-request
