### ISSUE TITLE
Only some dependency lock files updated (pip/pipenv)

### ISSUE THREAD

**Issue by stumpylog** [dependabot/dependabot-core#5066] opened 2022-04-28 21:58 UTC
**Package ecosystem:** pip / pipenv

**Package manager version:** 

**Language version** Python 3.8+

**Manifest location and content before the Dependabot update:** 
[`requirements.txt`](https://github.com/paperless-ngx/paperless-ngx/blob/128594584e00794f7d76cdbb23a5fc0ba101712d/requirements.txt) 
[`Pipfile.lock`](https://github.com/paperless-ngx/paperless-ngx/blob/128594584e00794f7d76cdbb23a5fc0ba101712d/Pipfile.lock) 

**dependabot.yml content**  
[dependabot.yml](https://github.com/paperless-ngx/paperless-ngx/blob/128594584e00794f7d76cdbb23a5fc0ba101712d/.github/dependabot.yml)

**Updated dependency**
pikepdf 5.1.1 -> 5.1.2  (but this has also been seen with other dependencies recently)

**What you expected to see, versus what you actually saw**
Both the requirements.txt and the Pipfile.lock updated to the new revision.  Instead, only the requirements.txt was updated.  Sometimes forcing a recreation of the pull will update both, for example [this pull request](https://github.com/paperless-ngx/paperless-ngx/pull/758) after a few attempts updated both the files.

**Native package manager behavior**
Doing a `pipenv lock` then `pipenv lock -r > requirements.txt` would yield the expected behavior.

**Images of the diff or a link to the PR, issue, or logs**
- Not working: https://github.com/paperless-ngx/paperless-ngx/pull/759
- Also not working: https://github.com/paperless-ngx/paperless-ngx/pull/835

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment] 2022-11-24 09:43
Related:
* https://github.com/dependabot/dependabot-core/issues/1946

**Comment by deivid-rodriguez** [comment] 2022-11-24 10:11
Pretty sure this is a duplicate of #6200. This one is older, but the new one has a bit more discussion and I already investigated a bit that particular case, so let me close this one in favor of #6200.

Please subscribe and/or comment there if still interested!

**Closed by deivid-rodriguez** 2022-11-24 10:11 UTC
Labels: T: bug 🐞, L: python:pip
