### ISSUE TITLE
Support wildcard for actions packages

### ISSUE THREAD

**Issue by fmeriaux** [dependabot/dependabot-core#5137] opened 2022-05-13 09:31 UTC
Actually to update composite actions in a mono-repo, we have to declare something like:

```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/<my-custom-action-A>"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/<my-custom-action-B>"
    schedule:
      interval: "daily"
```

After some discussions (cf: https://github.com/dependabot/dependabot-core/issues/4178#issuecomment-1118527672), I think it could be interesting to manage wildcards for this kind of use.

```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/**"
    schedule:
      interval: "daily"
```

**Comment by jeffwidman** [comment] 2022-08-25 07:55
Whoever takes a look at this, please also read through the alternative solution proposed here:
* https://github.com/dependabot/dependabot-core/issues/5047

**Comment by jeffwidman** [comment] 2023-02-09 23:53
This appears to be a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2178

That one is more generic, and so when we actually implement we may need to re-open this more specific ticket to track the specific changes necessary to enable actions... but I think the user-facing changes are all at the config file layer and generic across ecosystems so for now let's centralize the conversation over there.

If I'm wrong, please comment and we can reopen.

**Closed by jeffwidman** 2023-02-09 23:53 UTC
Labels: T: feature-request, L: github:actions, F: configuration-file

**Comment by nikaro** [comment] 2023-02-23 10:52
Hello, it is not clear to me if `directory: "/actions/**"` will look into `.github/actions/` or into `actions/` at the root of the repo. Can someone enlight me? 🙏

**Comment by deivid-rodriguez** [comment] 2023-02-23 13:30
Good question. We currently special case `/` to also look at `.github/workflows` but other than that, any directory configuration set looks exactly where instructed. So it should be `actions/` at the root of the repo I believe.

**Comment by Mahoney** [comment] 2026-09-01 09:22
So this is just a permanent maintenance burden? When adding or removing a composite action you have to remember to update dependabot.yaml?

I find this extremely surprising and unintuitive.
