### ISSUE TITLE
Ignore JS dependency until another dependency has been updated

### ISSUE THREAD

**Issue by stephanvierkant** [dependabot/dependabot-core#1804] opened 2020-04-17 12:37 UTC
I've got a library A v1 which uses library B v1. Library B has a new release (v2) that isn't compatible with library A v1. I'd like to ask dependabot to ignore updates until library A has been updated.

An example: I'm using Webpack Encore and Dependabot asks to upgrade multiple loaders (css-loader, file-loader) which aren't compatible with the latest version of Webpack Encore.

**Comment by jeffwidman** [comment] 2023-02-05 22:13
This looks like a duplicate of:
* #1296 

So closing as a duplicate. If for some reason I misunderstood, please clarify and we can re-open.

**Closed by jeffwidman** 2023-02-05 22:13 UTC
Labels: T: feature-request, L: javascript:npm
