### ISSUE TITLE
GET error for https://api.dependabot.com/repos

### ISSUE THREAD

**Issue by kiewietm** [dependabot/dependabot-core#3306] opened 2021-03-19 09:32 UTC
GET:  https://api.dependabot.com/repos?account-id=6178065&account-type=org&page=1&installation-state=active
Status: 500 Internal Server Error

![image](https://user-images.githubusercontent.com/36361934/111759788-4643f080-889e-11eb-934a-a6ceb314f378.png)

**Comment by asciimike** [comment] 2021-04-12 18:36
Closing as a dupe of https://github.com/dependabot/dependabot-core/issues/3450, which seems to also be fixed.

**Closed by asciimike** 2021-04-12 18:36 UTC
