### ISSUE TITLE
Dependabot flip-flop with python_full_version/python_version

### ISSUE THREAD

**Issue by glensc** [dependabot/dependabot-core#6091] opened 2022-11-09 12:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, pipenv

### What you expected to see, versus what you actually saw

It's becoming ridiculous already how dependabot fight with itself changing `python_version` to `python_full_version` and vice versa:

- https://github.com/Taxel/PlexTraktSync/commits/69dc149838db5c4f3cc36d886ad827ce9988a725/requirements.txt
  - `python_full_version` to `python_version`: https://github.com/Taxel/PlexTraktSync/commit/69dc149838db5c4f3cc36d886ad827ce9988a725
  - `python_version` to `python_full_version` https://github.com/Taxel/PlexTraktSync/commit/dc86ef1a3c277804393d92440f4e1354c61ca0e7 
  - `python_version < '4'` to `python_version < '4.0'`, drops `python_version >= '3.6'` https://github.com/Taxel/PlexTraktSync/commit/31516d211b291331a6b4786bddc95e5e1242f6ba
  - drops `python_full_version < '4.0.0'`, `python_version >= '3.6'` https://github.com/Taxel/PlexTraktSync/commit/bd3501dae2f631710ad9e29ccc3cbba66d1d6eb8

....and so on!

and typically the changes are not even for packages that are being bumped.

the same changes are visible in `Pipfile.lock` in same commits as well.

**Comment by glensc** [comment] 2022-11-09 12:59
my guess is that dependabot is running different versions of pipenv which is causing this.

but pipenv lock hasn't been updated for a while:
- https://github.com/dependabot/dependabot-core/commits/cf448a99d35d7956f4c64b8249029324c9627a91/python/helpers/requirements.txt

I don't know that's the place for the pin that is used to run pip/pipenv updates, but it might be.

**Comment by jeffwidman** [comment] 2022-11-09 23:38
Thanks for the report. This needs fixing, and your description made me 😄 :
> ridiculous already how dependabot fight with itself

Not sure of root cause, but your hunch sounds reasonable as a starting place.

**Comment by glensc** [comment] 2022-11-23 18:52
I think you should update `pipenv`:
- https://github.com/pypa/pipenv/issues/5499#issuecomment-1325522681

at least the problem i reported there did not repeat with `2022.9.24`

**Comment by deivid-rodriguez** [comment] 2022-11-23 18:58
Yeah, I already start that at #6104, but it's a tricky upgrade so it may take us some time.

**Comment by glensc** [comment] 2022-12-21 12:53
Unbelievable. it also removes version markers now:
- [Taxel/PlexTraktSync@`bc6d084` (#1301)](https://github.com/Taxel/PlexTraktSync/pull/1301/commits/bc6d084bd787f38684f282ddf6f96c1b2c7c8c57)

because it decided to write:

```diff
-            "markers": "python_version <= '3.7'",
+            "index": "pypi",
```

This is also fixed in newer pipenv or not yet reported?

**Comment by glensc** [comment] 2023-01-14 21:22
Is this the same problem? 

Removing attributes may damage distribution, if it drops the version range. see commit where I restored it manually:
- https://github.com/Taxel/PlexTraktSync/commit/9ecd9d71532b2eafec551b16f6e652a795a91e43

**Comment by jeffwidman** [comment] 2023-08-03 17:53
This will hopefully be fixed by:
* https://github.com/dependabot/dependabot-core/pull/7715

**Comment by deivid-rodriguez** [comment] 2023-09-22 10:22
Can you verify if the recent update of pipenv has fixed thanks? Thanks for all the pipenv reports and patience :pray:.

**Comment by deivid-rodriguez** [comment] 2023-11-01 16:18
Assuming this got fixed since we got no further feedback.

**Closed by deivid-rodriguez** 2023-11-01 16:18 UTC
Labels: T: bug 🐞, L: python:pip, python
