### ISSUE TITLE
Can specify poetry version to use

### ISSUE THREAD

**Issue by shooit** [dependabot/dependabot-core#7435] opened 2023-06-14 19:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The python package manager poetry, makes breaking changes to the expected format of its `pyproject.toml` and `poetry.lock` files across minor versions. Most recently, breaking changes were introduced in 1.5.1.

Dependabot should not change the `poetry.lock` file format when it runs. Instead it should either determine the appropriate poetry version to use based on the file or based on configuration provided by the user

PR that changed the version of poetry that dependabot uses: https://github.com/dependabot/dependabot-core/pull/7350
Related PR: https://github.com/dependabot/dependabot-core/pull/7418

**Comment by phillipuniverse** [comment] 2023-06-21 14:25
I think this is a duplicate of a conversation that has been going on for years at https://github.com/dependabot/dependabot-core/issues/1556. Lots of additional information about the hesitancy and difficulty in supporting multiple versions.

**Comment by jeffwidman** [comment] 2023-08-19 07:29
Yeah, this is a duplicate.

**Closed by jeffwidman** 2023-08-19 07:29 UTC
Labels: T: feature-request
