### ISSUE TITLE
Multiple Docker version declarations updated to a single one

### ISSUE THREAD

**Issue by tscolari** [dependabot/dependabot-core#1362] opened 2019-08-29 15:34 UTC
It seems that dependabot ignores prefixes (maybe also suffixes) when bumping images.
Our repo has 3 files:

*  Dockerfile.bionic
*  Dockerfile.trusty
*  Dockerfile.disco

We just enabled dependabot on it, and at its first PR this is what it did:

```diff
# Dockerfile.bionic
- FROM ubuntu:bionic-20190718 AS bionic
+ FROM ubuntu:bionic-20190807 AS bionic
```

```diff
# Dockerfile.disco
- FROM ubuntu:disco-20190718 AS disco
+ FROM ubuntu:bionic-20190807 AS disco
```

```diff
# Dockerfile.trusty
- FROM ubuntu:trusty-20180929
+ FROM ubuntu:bionic-20190807
```

I would definitely expect it to not update ubuntu releases given the complexity of it!

**Comment by greysteil** [comment] 2019-08-31 13:48
I think I know what's going on here.

- Dependabot is picking up all three of your files
- It's scanned for dependencies and finding only one - `ubuntu` - but with three different versions (`bionic-20190718`, `disco-20190718` and `trusty-20180929`)
- It's then looking for a relevant update, taking into account the prefix from the first requirement to find that `bionic-20190807` will do
- Finally it's updating all three "versions"  to the new one

The fundamental problem here is that Dependabot is grouping all three "requirements" together, rather than treating them as separate dependencies. I think the right fix would be for Dependabot to treat all three separately, but that would be quite a big refactor.

**Comment by infin8x** [comment] 2020-07-20 16:22
Duplicate of #2179

**Closed by infin8x** 2020-07-20 16:22 UTC
Labels: F: language-support, L: docker, T: feature-request
