### ISSUE TITLE
Capability to run commands post-update

### ISSUE THREAD

**Issue by CodingAnarchy** [dependabot/dependabot-core#6305] opened 2022-12-12 18:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have a pretty common workflow with Bundler and Sorbet, where to ensure that type hinting and runtime type enforcement in Ruby are maintained, after updating Ruby dependencies, we need to run some Sorbet commands to ensure compatibility.

Currently, dependabot's `auto-merge` functionality doesn't work for us, as CI will automatically fail until these commands are executed on the branch. Each dependabot PR thus requires that we manually go in, run these commands, and then manually merge after CI completes.

It would be ideal if we could configure dependabot to run these commands automatically on Ruby PRs, so the `auto-merge` functionality can be leveraged to increase our efficiency.

**Comment by jeffwidman** [comment] 2022-12-13 01:07
👋 Thanks for using Dependabot.

This is effectively a duplicate of:
* https://github.com/dependabot/dependabot-core/issues/5962

We aren't going to provide this via Dependabot, but instead you can setup a custom GitHub action to do this:
* https://github.com/dependabot/dependabot-core/issues/5962#issuecomment-1298026716
* https://github.com/dependabot/dependabot-core/issues/5962#issuecomment-1303781931

**Closed by jeffwidman** 2022-12-13 01:07 UTC
Labels: T: feature-request
