### ISSUE TITLE
Dependabot does not send pr

### ISSUE THREAD

**Issue by karinarastsinskagia** [dependabot/dependabot-core#6958] opened 2023-03-31 12:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Composer

### Package manager version

composer/semver  3.3.2  

### Language version

Php 8.1

### Manifest location and content before the Dependabot update

composer.json
```

{
    "name": "test/repo",
    "description": "",
    "require": {
        "illuminate/support": "^10.1",
        "jenssegers/agent": "^2.6",
        "phpunit/phpunit": "^10",
        "psr/simple-cache": "^2.0|^3.0",
        "react/promise": "^2.8",
        "spatie/laravel-package-tools": "^1.14",
    },
    "autoload": {
        "psr-4": {
            "Test\\Repo\\": "src/",
            "Test\\Repo\\Database\\Factories\\": "database/factories/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Test\\Repo\\Tests\\": "tests"
        }
    },
    "config": {
        "sort-packages": true,
    }
    }
}
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
```

### What you expected to see, versus what you actually saw

We have noticed that Dependabot is unable to create prs for packages which are identified as out of date. Particularly, despite the fact of detecting the packages newest versions, it fails to send a pull request  by displaying the message "Requirements to unlock update_not_possible".  

An example of this situation is shared below.

Does anyone know why this is happening and how to resolve it ?

Thank you

### Images of the diff or a link to the PR, issue, or logs

![Screenshot from 2023-03-31 14-54-36](https://user-images.githubusercontent.com/32904307/229113608-dc55f69b-2813-4577-9ecb-e223a4251510.png)

![Screenshot from 2023-03-31 14-49-23](https://user-images.githubusercontent.com/32904307/229113614-53bfa628-e82d-479d-a571-b81130c340db.png)

![Screenshot from 2023-03-31 14-48-57](https://user-images.githubusercontent.com/32904307/229113619-1b7e7eb1-eb4a-458d-9338-24a47ee54221.png)

![Screenshot from 2023-03-31 14-47-41](https://user-images.githubusercontent.com/32904307/229113627-a12b8941-6758-4993-b1e9-fdc27983d84b.png)

![Screenshot from 2023-03-31 14-48-25](https://user-images.githubusercontent.com/32904307/229113622-956007d7-ece2-481b-9df4-515910a47d09.png)

**Comment by jeffwidman** [comment] 2023-04-03 20:42
I suspect this is breaking because we don't yet support PHP 8:
* https://github.com/dependabot/dependabot-core/issues/6527
* https://github.com/dependabot/dependabot-core/pull/6506

This is something we hope to get to soon, so I suggest subscribing to ☝️ for updates... or just wait for it to magically start working for you when we ship it.

**Comment by KarinaRashchynskaya** [comment] 2023-04-04 09:40
> I suspect this is breaking because we don't yet support PHP 8:
> 
> * [Switch Dependabot from running `composer` using `php` `7.4` to `php` `8.2` #6527](https://github.com/dependabot/dependabot-core/issues/6527)
> * [Bump `php` to `8.2` #6506](https://github.com/dependabot/dependabot-core/pull/6506)
> 
> This is something we hope to get to soon, so I suggest subscribing to point_up for updates... or just wait for it to magically start working for you when we ship it.

Thank you very much for your response!
However, it makes me wonder since I have other repositories with the same features (dependabot.yml, PHP 8.1) where dependabot works as expected.  I mean that it creates prs for packages which are identified as out of date. Maybe you have other thoughts or explanations for the mentioned error message?

**Comment by karinarastsinskagia** [comment] 2023-04-04 09:42
> I suspect this is breaking because we don't yet support PHP 8:
> 
> * [Switch Dependabot from running `composer` using `php` `7.4` to `php` `8.2` #6527](https://github.com/dependabot/dependabot-core/issues/6527)
> * [Bump `php` to `8.2` #6506](https://github.com/dependabot/dependabot-core/pull/6506)
> 
> This is something we hope to get to soon, so I suggest subscribing to point_up for updates... or just wait for it to magically start working for you when we ship it.

Thank you very much for your response!
However, it makes me wonder since I have other repositories with the same features (dependabot.yml, PHP 8.1) where dependabot works as expected. I mean that it creates prs for packages which are identified as out of date. Maybe you have other thoughts or explanations for the mentioned error message?

**Comment by jeffwidman** [comment] 2023-04-05 01:55
It varies depending on the PHP packages pinned requirements for PHP/composer... eg, some of them may have minimum pins that require PHP 8, others may still allow both PHP 7/8.

Try running dry-run as explained in this PR to update our Readme (hope to land that soon) with the `DEBUG_HELPERS=true` set and you'll see the actual error message that `composer` is spitting out...

**Comment by karinarastsinskagia** [comment] 2023-04-05 10:06
> It varies depending on the PHP packages pinned requirements for PHP/composer... eg, some of them may have minimum pins that require PHP 8, others may still allow both PHP 7/8.
> 
> Try running dry-run as explained in this PR to update our Readme (hope to land that soon) with the `DEBUG_HELPERS=true` set and you'll see the actual error message that `composer` is spitting out...

I tried your suggestion and you're right. The issue is caused due to PHP versions which are required from the different packages.

Thanks a lot for your help

**Comment by jeffwidman** [comment] 2023-04-05 18:40
Thanks for circling back to let us know! 

I'm going to close as a duplicate of https://github.com/dependabot/dependabot-core/issues/6527

**Closed by jeffwidman** 2023-04-05 18:40 UTC
Labels: T: bug 🐞, L: php:composer
