### ISSUE TITLE
Docker image tag suffix changes with multi stage Dockerfile

### ISSUE THREAD

**Issue by pehbehbeh** [dependabot/dependabot-core#3261] opened 2021-03-11 13:03 UTC
We have a docker image `sourceboat/docker-phoenix` with two variants identified with a suffix in the tag name:

- `sourceboat/docker-phoenix:<version>-builder`
- `sourceboat/docker-phoenix:<version>-runtime`

In our project we use a multi stage docker setup where each stage uses a different variant. On updates dependabot changes the image variant (suffix). I would expect dependabot to only modify the version.

### Screenshot

<img width="977" alt="Bildschirmfoto 2021-03-11 um 13 52 11" src="https://user-images.githubusercontent.com/133831/110791235-4296e500-8272-11eb-9db8-131552f31517.png">

**Comment by feelepxyz** [comment] 2021-03-24 17:51
@pehbehbeh thanks for reporting, we're aware of this bug but have struggled to prioritise it. Will see if we can find the time.

**Comment by pehbehbeh** [comment] 2021-04-12 13:53
Could dependabot handle it if we flip the order?

`runtime-X.X.X` instead of `X.X.X-runtime`

**Comment by lucacome** [comment] 2021-04-19 18:38
Any update on this? We had this happen too.

**Comment by thepwagner** [comment] 2021-05-04 17:04
@lucacome @pehbehbeh Do you expect Dependabot will open multiple PRs for this case? (e.g. `nginx:1.19.10` and `nginx:1.19.10-alpine`).

If you expect a single `nginx` PR, what should happen when both images aren't available? (e.g. `nginx:1.19.10` exists but `nginx:1.19.10-alpine` does not).

**Comment by lucacome** [comment] 2021-05-04 17:25
@thepwagner I think it would make sense to have multiple PRs since they're technically different Docker images.

**Comment by lucacome** [comment] 2021-05-07 17:48
@thepwagner looks like there are still some issues. 

First I rebased the PR linked here and dependabot closed saying that it was no longer needed (not sure if related to this), I tried to reopen it and it keeps closing it.

I ran the check again and it opened the one for `nginx:1.19.10-alpine`, but won't open one for `nginx:1.19.10` because one already exists (?).

**Comment by thepwagner** [comment] 2021-05-07 18:11
@lucacome thanks for the report, I think I understand the problem:

1. When you trigger an update check, Dependabot sees the existing https://github.com/nginxinc/kubernetes-ingress/pull/1542 PR, and so doesn't want to create a new one. It considers that to be the definitive `nginx:1.19.10` pull request.
2. Within the closed source wrapper around `dependabot-core`, there's some logic that assumes if the number of dependencies parsed `!=` the number of dependencies when the PR was created, then it _must_ be because the dependency has since been removed.

(2) is the bug: because `nginx:1.19.10` and `nginx:1.19.10-alpine` are unique dependencies now: `2 != 1` so Dependabot invokes the "dependency was removed" logic.

**Comment by lucacome** [comment] 2021-05-07 19:44
@thepwagner thanks for the quick reply.

Let me know if there's anything I can do to help you test/debug this.

**Comment by lucacome** [comment] 2021-05-10 16:37
Just as you said https://github.com/nginxinc/kubernetes-ingress/pull/1581 was closed after a rebase.

**Comment by feelepxyz** [comment] 2021-05-24 16:16
Is someone working on this atm?

**Comment by lucacome** [comment] 2021-08-10 18:58
Any updates on this?

**Comment by lucacome** [comment] 2021-11-16 00:55
Just a friendly ping to check if this is going to be fixed anytime soon.

**Comment by gnarea** [comment] 2021-12-07 00:02
Folks, please add a thumbs-up to the OP to make it easier for the Dependabot team to prioritise issues. Asking for an update just adds noise -- if anyone where working on this issue they would've already posted an update.

---

Re: @thepwagner's workaround, if you're using it, keep in mind that you may end up compiling things with a different version of the platform using at runtime. Consider using `update-types: ["version-update:semver-major"]`.

**Comment by jeffwidman** [comment] 2022-08-29 22:50
Uh, oh. 

This issue was re-reported as #5538 and nobody realized it was a dupe of this ticket, nor the problems with simply slicing off the suffix, so #5560 was merged which (to me) appears to be a very similar fix to https://github.com/dependabot/dependabot-core/pull/3627 which was reverted for reasons explained upthread in this issue.

We'll circle up internally and figure out next steps... including whether #5560 needs to be reverted or not.

**Comment by deivid-rodriguez** [comment] 2022-08-31 18:15
We discussed this internally and we believe the approach we took in https://github.com/dependabot/dependabot-core/pull/5560 is different to the previous approach that got reverted. At least it seems that the issue with previous approaches is that they would consider different variants (for example, `nginx:1.19.9-alpine` and `nginx:1.19.9`) as different dependencies, and that had the issue of opening multiple PRs superseding and closing each other. I don't think https://github.com/dependabot/dependabot-core/pull/5560 has that issue.

So since this has already been shipped, I'll close this issue as fixed :tada:.

If any other issues related to this come up, let's deal with them separately.

**Closed by deivid-rodriguez** 2022-08-31 18:15 UTC
Labels: T: bug 🐞, L: docker

**Comment by gnarea** [comment] 2022-09-01 10:09
Sorry, but as someone unfamiliar with the Dependabot codebase (and therefore unable to understand those PRs), I'm not sure I understand what you're saying.

So, can I now trust Dependabot to just update the version number in the tag leaving everything else as is? So `nginx:1.19.9-alpine` always gets upgraded to `nginx:1.19.10-alpine`, not `nginx:1.19.10-whatever`? Are there any known edge cases that I should be aware of?

**Comment by deivid-rodriguez** [comment] 2022-09-01 10:20
Yes.

The only known case where I'm not sure what the behavior will be is the one mentioned at https://github.com/dependabot/dependabot-core/issues/3261#issuecomment-832098649

> If you expect a single nginx PR, what should happen when both images aren't available? (e.g. nginx:1.19.10 exists but nginx:1.19.10-alpine does not).

In that case, I'm not sure what the new behavior is, but I think it's quite rare to not release image variants in lockstep? Anyways, feel free to try this and let us know if it works!

**Comment by gnarea** [comment] 2022-09-01 10:22
Awesome! ¡Gracias, @deivid-rodriguez!

I'm taking a note to get Dependabot to upgrade our base Docker images and will let you know if we run into any issues.
