### ISSUE TITLE
Config Presets

### ISSUE THREAD

**Issue by dannyphillips** [dependabot/dependabot-core#1979] opened 2020-05-15 17:35 UTC
Often times, there are several projects which you want to have similar/same dependabot configs. It would be great to be able to define a preset so those configurations can easily be shared across repos. [Renovate already offers this feature](https://docs.renovatebot.com/config-presets/)

**Comment by jeffwidman** [comment] 2022-11-24 11:37
Closing as a duplicate of https://github.com/dependabot/dependabot-core/issues/2130.

**Closed by jeffwidman** 2022-11-24 11:37 UTC
Labels: T: feature-request, F: configuration-file
