### ISSUE TITLE
Dependabot tries to update docker to preview versions

### ISSUE THREAD

**Issue by leotsarev** [dependabot/dependabot-core#4228] opened 2021-09-15 09:16 UTC
**Package ecosystem**
docker
**Package manager version**
n/a
**Language version**
n/a
**Manifest location and content prior to update**
https://github.com/joinrpg/joinrpg-net/blob/91e7b4a5cca25296a5a59794ef80245ef2aeb3cd/src/Joinrpg.Dal.Migrate/Dockerfile
**dependabot.yml content**
https://github.com/joinrpg/joinrpg-net/blob/12f8e3b1724cda22a89d53cd545df9d8db29fe41/.github/dependabot.yml
**Updated dependency**
https://github.com/dotnet/dotnet-docker/blob/9cb9105b21af0691337a8d66764f3103763b3351/src/aspnet/6.0/bullseye-slim/amd64/Dockerfile
**What you expected to see, versus what you actually saw**
I expected dependabot NOT to update to 6.0-rc **preview** version and until **final** 6.0 will be released
**Native package manager behavior**
n/a
**Images of the diff or a link to the PR, issue or logs**
https://github.com/joinrpg/joinrpg-net/pull/1511
**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by leotsarev** [comment] 2021-09-16 07:59
Wow, now it superseded by 5.0.10 update.

**Comment by jeffwidman** [comment] 2022-08-25 05:33
From looking at your links, particularly https://github.com/joinrpg/joinrpg-net/pull/1511, I think this was a bug in the underlying package... it looks like they incorrectly pushed the docker tag `6.0` instead of a `6.0-rc` or preview equivalent... so Dependabot tried to bump it. However, my guess is they then pulled back that `6.0` tag, so when Dependabot re-ran, it found the new `5.0.10` tag, and there was no `6.0` tag... so that's why it mysteriously bumped to a lower version.

I'm going to close as I don't think there's an easy way to repro this, since I assume the _real_ `6.0` tag has been released as GA by now. And if working as intended now, then not worth investigating further given some of our other priorities. But if for some reason I misunderstood please comment and we can reopen.

**Closed by jeffwidman** 2022-08-25 05:33 UTC
Labels: T: bug 🐞, L: docker
