### ISSUE TITLE
[Yarn] Packages resolved from public registry rather than .npmrc registry in subdependency update 

### ISSUE THREAD

**Issue by milind009** [dependabot/dependabot-core#1937] opened 2020-06-23 10:44 UTC
We have been using the dry-run script for updating dependencies for many azure based repos. Recently, we had come across an issue while updating subdependencies.
In case of subdependency update for yarn(>= 1.15.2) on an ubuntu container using dependabot-core, packages in yarn.lock are getting resolved by public registry(registry.yarnpkg) instead of the private registry mentioned in the .npmrc file. Currently we have the repo level .npmrc in this sample format:
registry=https://private_registry_url/npm/registry/
always-auth=true
package-lock=false 

The user level .npmrc with auth token is in this format:

//private_registry_url/npm/registry/:username=office
//private_registry_url/npm/registry/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]
//private_registry_url/npm/registry/:email=xyz@gmail.com

The repo does not have a .yarnrc file checked in. Could this issue be because of missing .yarnrc or is the authentication details in .npmrc not in correct format?

**Comment by crtdaniele** [comment] 2020-09-29 14:43
Any idea?

**Comment by Nishnha** [comment] 2022-03-07 21:12
Hi @milind009,

I think this issue is a duplicate of https://github.com/dependabot/dependabot-core/issues/4669 and I left a response to some comments there https://github.com/dependabot/dependabot-core/issues/4669#issuecomment-1061139714

**Comment by jeffwidman** [comment] 2022-09-17 10:32
Closing as a dupe of #4669

**Closed by jeffwidman** 2022-09-17 10:32 UTC
Labels: T: feature-request, L: javascript:yarn, 🍏 core
