### ISSUE TITLE
Manual trigger for dependabot

### ISSUE THREAD

**Issue by wkr-spyrosoft** [dependabot/dependabot-core#6827] opened 2023-03-13 11:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I am unsuccessfully trying to configure dependabot as a GitHub workflow where I can set up specific triggers, such as "manual", or on a specific branch but only for specific `package-ecosystem` eg. "github-actions"

**Comment by jeffwidman** [comment] 2023-03-14 19:27
Partial duplicate of:
* https://github.com/dependabot/dependabot-core/issues/2980

The branches config is, uh, complicated... lots of folks want to do a variety of things.

You can also always run Dependabot yourself as a standalone script within a GitHub Action... eg using something like https://github.com/dependabot/dependabot-script or https://github.com/dependabot/cli and that'd allow you to do whatever pre-processing yourself within the GitHub action, including switching to specific branches, whatever trigger you want, etc.

I'm going to close as duplicate/a question, but feel free to ask additional questions if something doesn't make sense to you.

**Closed by jeffwidman** 2023-03-14 19:27 UTC
Labels: T: feature-request

**Comment by MPV** [comment] 2023-11-14 19:16
Today’s blog said:
>… and you'll have the option to manually trigger jobs whenever necessary.

https://github.blog/changelog/2023-11-14-dependabot-will-no-longer-automatically-re-run-failed-jobs-when-package-manifest-changes/

Any thoughts on whether this would solve it?

I haven’t yet found any info anywhere on what it means, or how to use it.

**Comment by seclerp** [comment] 2025-06-17 12:16
Just encountered this question while searching for the answer nowadays, and seems like it's possible to trigger Dependabot manually using **Insights | Dependency graph | Dependabot | Recent update jobs | Check for updates**.

Seems like it only supports triggering the default branch. Hope it helps someone.

![Image](https://github.com/user-attachments/assets/7e9119b8-709e-4f67-9bca-a71caf81f522)

![Image](https://github.com/user-attachments/assets/2b2d581d-0f93-48e7-9813-18292f4e27e4)
