### ISSUE TITLE
PyPi package deprecations

### ISSUE THREAD

**Issue by Avamander** [dependabot/dependabot-core#3221] opened 2021-03-03 09:28 UTC
It would be nice if there was a way to mark a Pip package as deprecated, or simply warn about dependencies not updated for a long time.

For example [Flask-BabelEx](https://github.com/mrjoes/flask-babelex) is deprecated and should be replaced with [Flask-Babel](https://github.com/python-babel/flask-babel).

**Comment by jeffwidman** [comment] 2022-08-11 06:36
Dupe of https://github.com/dependabot/dependabot-core/issues/3242, and unfortunately probably not something we can do for reasons outlined in https://github.com/dependabot/dependabot-core/issues/3242#issuecomment-1211592452.

**Closed by jeffwidman** 2022-08-11 06:36 UTC
Labels: T: feature-request
