### ISSUE TITLE
Multistage Dockerfiles using different tag@sha is updating all tags to latest

### ISSUE THREAD

**Issue by lorengordon** [dependabot/dependabot-core#4480] opened 2021-12-02 21:01 UTC
Here is an example: https://github.com/plus3it/spel-repo-builder/pull/2/files

It seems like Dependabot is not handling the scenario where the same image is present with different tags, e.g. `centos:7` vs `centos:8`, as it is trying to update the `centos:7` image to `centos:8`!

**Package ecosystem**
docker

**Manifest location and content prior to update**

* https://github.com/plus3it/spel-repo-builder/blob/main/Dockerfile.tools

**dependabot.yml content**

* https://github.com/plus3it/spel-repo-builder/blob/main/.github/dependabot.yml

**Updated dependency**

* `centos:7@sha256:dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f` => `centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177`

**What you expected to see, versus what you actually saw**

Didn't expect an update at all.

**Images of the diff or a link to the PR, issue or logs**

* https://github.com/plus3it/spel-repo-builder/pull/2/files

**🕹 Bonus points: Smallest manifest that reproduces the issue**

```
FROM centos:7@sha256:dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f

FROM centos:8@sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc
```

**Comment by deivid-rodriguez** [comment] 2022-11-13 21:55
Hi @lorengordon!

Could you clarify why you did not expect an update? Were you expecting only update to the sha256 if that changes, but nothing else?

I guess we could somehow support that, but in principle this seems to me like the expected behavior for most?

**Comment by deivid-rodriguez** [comment] 2022-11-13 22:45
Yeah, pretty sure what you are requesting is a duplicate of #1971, so let me close this in favor of that issue.

Also, the good news is that we have the `version-update:semver-major` that should do what you want. The bad news is that it's not yet working but I'm hoping that #6115 will fix it.

Please subscribe to the mentioned issue and PR :)

**Closed by deivid-rodriguez** 2022-11-13 22:45 UTC
Labels: T: bug 🐞, L: docker, 🍏 core
