### ISSUE TITLE
AzDO: Configuration too restrictive for on-premise?

### ISSUE THREAD

**Issue by hangy** [dependabot/dependabot-core#3620] opened 2021-05-02 17:59 UTC
It appears that dependabot might currently only run really well on Azure DevOps Service, but not on Azure DevOps Server.

- Source is created only with the hostname: https://github.com/dependabot/dependabot-script/blob/198a177090c111ffab27932ab0c02213c7d8b1fc/generic-update-script.rb#L79-L96
- Regex is pretty restrictive: https://github.com/dependabot/dependabot-core/blob/c3c87bb90042cf5b3d3af50d42b0e83fe3267041/common/lib/dependabot/source.rb#L26-L30

When hosting Azure DevOps Server on-premise, a typical URL to a repository might be something like `https://tfs.example.org/tfs/ProjectCollection/Tests/_git/SomeRepo` or `http://tfs.example.org:8080/tfs/ProjectCollection/Tests/_git/SomeRepo`. Also see the discussion in https://github.com/tinglesoftware/dependabot-azure-devops/issues/27#issuecomment-768054722

It might be interesting to allow callers to provide the API base URL for the project collection as an alternative to constructing it with `AZURE_HOSTNAME`, ie. by using `$SYSTEM_COLLECTIONURI`. The actual URL to the project collection cannot be determined automatically only by using the hostname and the name of the project collection.

**Comment by jurre** [comment] 2021-05-03 09:24
@hangy ADO support currently relies mostly community-contributions, I'd be happy to review and accept a PR that improves support for on-premise ADO! 👍

**Comment by hangy** [comment] 2021-05-04 07:55
@jurre Thanks for your response! I haven't used Ruby before, and I'm certainly no expert on different hosting options for AzDO on-prem and in the cloud, but I'll see what I can do. (Your colleagues at @microsoft are obviously way better informed when it comes to the details of this.)

As far as I can tell, the best option to integrate the Azure DevOps REST API for Azure DevOps Service as well as Azure DevOps Server, would be to specify the URL directly, when creating a new `Source`. After some digging, I found out, that the base URL for project related APIs reliably seems to be `$SYSTEM_COLLECTION/$PROJECT/_apis`. Basically, https://github.com/dependabot/dependabot-core/blob/5c2eb8b59d97372342513c6a3582727e898dae77/common/lib/dependabot/clients/azure.rb may actually work to some extent, if the a more complete `api_endpoint` URL was given in https://github.com/tinglesoftware/dependabot-azure-devops/blob/4c7c89fb7580924e3e5b2525fb03ee4acbb1c0ea/src/script/update-script.rb#L155. I'll have to test that separately.

However, as documented [here](https://specsolutions.gitbook.io/specsync/important-concepts/what-is-my-tfs-project-url), the URLs of AzDO on-prem can be pretty varied, so that detecting it in https://github.com/dependabot/dependabot-core/blob/08c679d9742ec87a74021fb737fa177c700e5dc4/common/lib/dependabot/source.rb#L42 might be pretty difficult, unless we were to catch all URLs with `/_git/`. Would that be acceptable from your point of view, or is the chance of false-positives too high?

Also, if we were to detect the API URL from the repo URL based on `/_git/`, we would probably have to remove the concept of `organization` and `project` from the `azure` source. With the amount of URL variations in the wild, detecting these properties would sometimes be impossible. In that case, the whole URL up to the "project" level would need to be specified as the `source.api_endpoint`. This may be a breaking change to the current behaviour - would it be OK with you?

**Comment by jurre** [comment] 2021-05-04 08:49
> Your colleagues at @microsoft are obviously way better informed when it comes to the details of this.

You're right, @JamieMagee or @milind009 , would you be able to offer any guidance? 🙇 

> catch all URLs with `/_git/`

That seems a bit of a wide net to cast 🤔, maybe if it's the last step in the check it'd be OK, so if it's not any of the other providers but it does match `/_git/`, assume it's ADO.

> Also, if we were to detect the API URL from the repo URL based on /_git/, we would probably have to remove the concept of organization and project from the azure source.

As long as the change only affects the Azure implementation I _think_ it'd be OK, although it does sound fairly hairy.

I wonder if there is a better option here, if you're running against azure devops we should have code-level access to Dependabot. I wonder if we should inject some details into dependabot to help it parse these URLs.

An API could look something like:

```ruby
Dependabot::Clients::Azure.configure do |config|
  config.source_api_url = "https://tfs.example.org/tfs/ProjectCollection/Tests"
  config.whatever_other_data_we_need = "some_other_option"
  # or even:
  config.source_regex = /^some|regex/
end
```

And then in `Dependabot::Source` we check if that config is set, and if it is we use it to parse the azure sources?

I'm just thinking out loud here

**Comment by hangy** [comment] 2021-05-05 07:20
> > catch all URLs with `/_git/`
> 
> That seems a bit of a wide net to cast 🤔, maybe if it's the last step in the check it'd be OK, so if it's not any of the other providers but it does match `/_git/`, assume it's ADO.

I don't like it either, as it is a very unspecific pattern to match. On the other hand, none of the other Sources do use an underscore prefix for "internal" URLs, so maybe it could work.

> > Also, if we were to detect the API URL from the repo URL based on /_git/, we would probably have to remove the concept of organization and project from the azure source.
> 
> As long as the change only affects the Azure implementation I _think_ it'd be OK, although it does sound fairly hairy.

As far as I can se, they're only used in then Azure client to build up the URLs for the actual API calls. 

> I wonder if there is a better option here, if you're running against azure devops we should have code-level access to Dependabot. I wonder if we should inject some details into dependabot to help it parse these URLs.

I just skimmed the code a bit, and it looks like the `from_source` method might still be interesting to support on-prem hosting, but apparently hostnames for GitHub, GitLab, and Bitbucket are hard-coded, too. So it might not be much of an issue after all. The AzDO extension uses some code to detect the [organization](https://github.com/tinglesoftware/dependabot-azure-devops/blob/573ae65d9358ad77de3bab3890ded66b93bb4c1a/src/extension/task/index.ts#L37-L63), so maybe it's something else that's acting up in https://github.com/tinglesoftware/dependabot-azure-devops/issues/44 and https://github.com/tinglesoftware/dependabot-azure-devops/issues/27#issuecomment-768054722. I'll check that again and get back to you.

**Comment by vmcbaptista** [comment] 2021-05-05 19:47
I faced this issue today. In my company, we recently updated to Az DevOps Server 2020 and I was trying to integrate dependabot.
Currently, we don't use HTTPS, so our URLs are like this:
http://ados-20:8080/tfs/ProjectCollection/TeamProject

I tried to set AZURE_HOSTNAME=ados-20:8080/tfs like suggested by https://github.com/tinglesoftware/dependabot-azure-devops/issues/112 but then I realized that dependabot was "forcing" HTTPS URL.

I'm also not into ruby, but I'm available to try to help if there's something I can do.

**Comment by hangy** [comment] 2021-05-05 20:41
@vmcbaptista I think that's not dependabot-core, but the 3rd party AzDO extension. I took the liberty of copying your text to a new issue there: https://github.com/tinglesoftware/dependabot-azure-devops/issues/114

**Comment by vmcbaptista** [comment] 2021-05-05 20:51
@hangy Thanks for checking this. but I faced the same problem when using dependabot-core directly

**Comment by hangy** [comment] 2021-05-05 21:02
> @hangy Thanks for checking this. but I faced the same problem when using dependabot-core directly

Using depedabot-core directly or could it be this script, which suffers from the same problem as the script from the extension? https://github.com/dependabot/dependabot-script/blob/9955ecfde6514d412aad052e7d5809af2039fb80/generic-update-script.rb#L82-L99

**Comment by vmcbaptista** [comment] 2021-05-05 21:06
> > @hangy Thanks for checking this. but I faced the same problem when using dependabot-core directly
> 
> Using depedabot-core directly or could it be this script, which suffers from the same problem as the script from the extension? https://github.com/dependabot/dependabot-script/blob/9955ecfde6514d412aad052e7d5809af2039fb80/generic-update-script.rb#L82-L99

nice catch! yes I tried both the extension and that dependabot-script

**Comment by jeffwidman** [comment] 2023-02-05 22:29
> we also have white spaces in both project collection, team projects, and repositories names, which I admit is quite unpleasant since this ends up being resolved to names with %20 in the middle, but this was done like this for a long time already and there are no plans to move to names without spaces.

Support for spaces in the URI was added via a community PR from @AlekhyaYalla:
* https://github.com/dependabot/dependabot-core/pull/5656

**Comment by jeffwidman** [comment] 2023-02-10 17:22
So to clarify @vmcbaptista / @hangy:
1. Is there still a valid bug here? I assume the hostname is still an issue even though the URI spaces issue has been fixed... but it'd be great to get confirmation?
2. It sounds like the issue is due to config that's hardcoded in `dependabot-script` and not a problem with `dependabot-core`... is that correct? If so, I'll transfer this issue to that repo so we can track it in the appropriate context.

**Comment by vmcbaptista** [comment] 2023-02-10 17:58
> So to clarify @vmcbaptista / @hangy:
> 1. Is there still a valid bug here? I assume the hostname is still an issue even though the URI spaces issue has been fixed... but it'd be great to get confirmation?
> 2. It sounds like the issue is due to config that's hardcoded in `dependabot-script` and not a problem with `dependabot-core`... is that correct? If so, I'll transfer this issue to that repo so we can track it in the appropriate context.

I would be more than happy to help, but to be fair this is already quite old, I don't really remember much about this and unfortunately I do not have access to any AzDo to test this again.

**Comment by jeffwidman** [comment] 2023-02-10 19:57
paging @mburumaxwell 🙇  since you know so much about ADO... any comments on ☝️ ?

**Comment by deivid-rodriguez** [comment] 2023-02-24 13:25
Thanks @mburumaxwell. Let's close this then!

**Closed by deivid-rodriguez** 2023-02-24 13:25 UTC
Labels: V: Azure Devops
