### ISSUE TITLE
Only Partial Maven Upgrade

### ISSUE THREAD

**Issue by lapplislazuli** [dependabot/dependabot-core#1400] opened 2019-09-22 07:47 UTC
Hey there, 
I'm enjoying dependabot since yesterday. 

However, it made some PRs on my Maven Project which broke the builds. 

The reason was that it promoted an upgrade from JUnit 5.4.2 to 5.5.2 but ONLY for the Engine, not for the API. I therefore had a missmatch and my builds failed. 
Same happened for Log4J2. 

Old Dependency (Fine):

```XML
 <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>2.11.2</version>
</dependency>
<dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>2.11.2</version>
</dependency>
```

Proposed PR (Breaking):

```XML
 <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>2.11.2</version>
</dependency>
<dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>2.12.1</version>
</dependency>
```

Should be Result (Fine):

```XML
 <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>2.12.1</version>
</dependency>
<dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>2.12.1</version>
</dependency>
```

Dependabot only promoted one change, not both. 

The Maven Issues here are also a little cryptic, as its throwing *ClassNotFound*-Exceptions but whatsoever thats a maven/java problem.

**Comment by jeffwidman** [comment] 2023-02-11 00:52
👋 Sorry for the slow reply.

Closing as a duplicate of:
* #1296

**Closed by jeffwidman** 2023-02-11 00:52 UTC
Labels: T: bug 🐞, L: java:maven, F: language-support
