### ISSUE TITLE
Release marked as `pre-release` trigger dependabot alerts

### ISSUE THREAD

**Issue by laurentsimon** [dependabot/dependabot-core#5284] opened 2022-06-17 22:03 UTC
Our repository received a version bump https://github.com/slsa-framework/slsa-github-generator/pull/346 for this pre-release https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.1.0

Is this a bug? If it's a feature, it should be turned off by default.

**Comment by jeffwidman** [comment] 2023-01-30 05:46
This is a `go` module, right?

This was tagged as `v1.1.0`, and then marked as a pre-release in GitHub releases UI. The problem is that in the `go` ecosystem, [a pre-release has a specific version format](https://go.dev/doc/modules/release-workflow#pre-release), and `v1.1.0` doesn't follow that... so the native `go` tooling sees it as a normal, non-pre-release version.

So in this case, I'd say this is actually an upstream bug in `slsa-github-generator` assigning a non-pre-release version number to a pre-release.

Technically we could check the GitHub API ourselves in Ruby to see that it's marked as a pre-release, we'll then be in a confusing situation because the version numbering scheme says normal, GitHub API says pre-release, which is it? But we aren't even going to go down that route because we want to focus Dependabot on being the glue code that handles running the native package managers and then creating PR's... in other words, we don't want to re-implement `go get` in ruby... instead, we'll defer to `go get` to do what it thinks. And `go get` is going to see this as a normal, non-pre-release.

**Closed by jeffwidman** 2023-01-30 05:46 UTC
Labels: T: bug 🐞

**Comment by jeffwidman** [comment] 2023-01-31 20:10
Oof, so a colleague pointed out that the root problem here actually referred to a GitHub action release, and not a go module release: https://github.com/slsa-framework/slsa-github-generator/pull/346

My apologies!

In that case, this is a duplicate of https://github.com/dependabot/dependabot-core/issues/2303, so will leave this closed.
