### ISSUE TITLE
pre/post dependabot scripting

### ISSUE THREAD

**Issue by MichaelScheetz-HPE** [dependabot/dependabot-core#1758] opened 2020-03-24 16:00 UTC
This would allow projects to script various things related to dependency updates. Especially for generated files that need to be checked in, e.g. protobuf.

**Comment by feelepxyz** [comment] 2020-03-25 15:00
@MichaelScheetz-HPE 👋 this is kind of possible with github actions, e.g. https://github.com/dependabot/dependabot-core/issues/935#issuecomment-603882655

Longer-term we might end up running entirely on Actions exposing these kinds of hooks directly.

**Comment by electrofelix** [comment] 2021-01-12 12:20
@feelepxyz confirmed, we now can commit additional modifications based on the dependency change automatically with github actions, however bumping into dependabot will subsequently refuse to update/replace the PR if it isn't merged because it's been modified.

Is there a particularly way for automation triggered via github actions to update a dependabot proposed PR without blocking dependabot from updating in the future?

If that exists, could consider this fully resolved.

**Comment by jurre** [comment] 2021-01-13 13:57
> @feelepxyz confirmed, we now can commit additional modifications based on the dependency change automatically with github actions, however bumping into dependabot will subsequently refuse to update/replace the PR if it isn't merged because it's been modified.
> 
> Is there a particularly way for automation triggered via github actions to update a dependabot proposed PR without blocking dependabot from updating in the future?
> 
> If that exists, could consider this fully resolved.

Yes, you can pre or postfix any commits made in the action with `[dependabot skip]` and Dependabot will force push any rebases over them (at which point the action should run again)

**Comment by electrofelix** [comment] 2021-02-19 10:16
@jurre Appears that didn't quite work as expected:
![image](https://user-images.githubusercontent.com/912324/108489161-23232280-7299-11eb-8475-4a2b8a12089d.png)

I think we need to drop our auto-merge workflow, that was handy for dealing with the situation in the past because we had local modifications. I was originally planning to retain because I thought the force push when dependabot rebases removed approvals, but maybe that's only if the resulting change is different?

I'm guessing that dependabot is probably looking at the history of commits and is seeing past the auto merge to see the commits merged in from master and not just looking at the commits being added to the target branch.

Unless of course this looks like a bug to you as maybe it should be ignoring both the commits and the merge commit updating the branch? (we like ensuring that all PRs pass with the latest state of the target branch not just the state they were branched from hence have enabled the requirement that the branch must be up to date to merge).

**Comment by electrofelix** [comment] 2021-03-22 14:49
@jurre looks like the suggestion to use `[dependabot skip]` isn't working at all.
![dependabot-skip-bug](https://user-images.githubusercontent.com/912324/112008725-a6949580-8b1d-11eb-8f5d-3e61659fd0bd.png)

I would have assumed that the above should have been handled the new release automatically, but it didn't. I thought this was working at least partially before, but it doesn't look like it's working

**Comment by jurre** [comment] 2021-03-22 15:10
> I would have assumed that the above should have been handled the new release automatically, but it didn't. I thought this was working at least partially before, but it doesn't look like it's working

This only works for the GitHub native version of dependabot, not for dependabot-preview I'm afraid

**Comment by electrofelix** [comment] 2021-03-22 16:12
@jurre ah, thanks, I see private registry support has appeared for Github native version, so will look at trying to pick that up. I'm guessing that this is mostly complete in any case based on github actions.

**Comment by electrofelix** [comment] 2021-04-30 09:10
Seems like there is something unusual going on, since switching to github native dependabot the `[dependabot skip]` prefixed commit messages don't appear to be getting treated as expected.

![image](https://user-images.githubusercontent.com/912324/116673014-c16aed00-a99a-11eb-8035-2df487d46ff3.png)

This isn't the only odd issue I've seen with github native dependabot running on private repos, so I'm wondering if there is some issue specific to switching from dependabot-preview or with private repos that makes the behaviour different? #3594 shows rebase-strategy isn't working for our private repositories either, but it does work as documented on a public test repo under my own user. So is this a case of something weird for private repos?

Essentially I think that the functionality is in place with Github native dependabot to close this, but for some reason we're still experiencing the old behaviour.

**Comment by jurre** [comment] 2021-04-30 11:33
@electrofelix it seems like the commit dependabot made has been edited directly, is that right? We check that the commit author of the last commit is Dependabot, excluding any follow-up commits that have the `[dependabot skip]` tag.

The thinking here is that people would push extra commits to that branch, but they would not override dependabot's commit. Maybe that assumption is false, and I can dive into why it was set up that way, but would you be able to try to change your workflow to not edit Dependabots commit and see if that solves the issue?

I don't think this should be different for private and public repo's, we don't differentiate based on that for this functionality.

I hope that helps 🤞

**Comment by electrofelix** [comment] 2021-04-30 13:10
@jurre It's not actually a commit by dependabot edited by someone else, however I think what you've said has given me a clue. When we generate the commit we use the following env settings for the action run step performing the git commit:
```
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
          GIT_COMMIT_MESSAGE: |
            [dependabot skip] Tidy-up dependencies
```

I'm guessing the bot is seeing the commit as having been made by dependabot due to the `GIT_AUTHOR_NAME: ${{ github.actor }}` part and modified by someone else `GIT_COMMITTER_NAME: GitHub Actions`. I'll look to update that part to use actions as the author and committer instead so that there isn't any confusion about the additional commit.

**Comment by feelepxyz** [comment] 2021-05-07 09:08
@electrofelix looks like we're not handling these commits when creating pull requests with an existing PR for a previous version. Working on a fix 👍

**Closed** 2021-05-07 12:27 UTC

**Comment by feelepxyz** [comment] 2021-05-07 12:30
Closed this from a fix to `[dependabot skip]` not always working. It should now be applied to existing PRs where there's a new version available.

We're not planning on adding any hooks directly into dependabot to run scripts as this opens the door to a lot of abuse. Using actions with `[dependabot skip]` prefixed to the commit is the recommended way or if you need more customization self-hosting dependabot-core: https://github.com/dependabot/dependabot-script

**Comment by jeffwidman** [comment] 2023-03-01 08:25
FWIW, here's an example repo we published demonstrating how to write your own GitHub Action workflow to achieve post-processing/scripting on Dependabot PR's: https://github.com/dependabot/dependabot-actions-workflow
