### ISSUE TITLE
Grouped dependencies: The title for updating a single dependency should be as before

### ISSUE THREAD

**Issue by huehnerlady** [dependabot/dependabot-core#7840] opened 2023-08-18 07:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

8.3

### Language version

Java/Groovy

### What you expected to see, versus what you actually saw

When there is only 1 dependency updated, I expect the Title to be the same as the PR titles without the grouping feature, so you see the dependency itself in the title.
eg: 	`Bump org.jetbrains:annotations from 23.0.0 to 24.0.1`

The title however shows
`Bump the dependencies group with 1 update`

**Comment by yeikel** [comment] 2023-08-19 04:43
Can you please share at least  : 

1. Smallest manifest that reproduces the issue
2. Images of the diff or a link to the PR, issue, or logs

With the little information you provided, it is a bit challenging to help you

**Comment by jakecoffman** [comment] 2023-08-21 17:43
I'm going to close this as a duplicate of #7662 since it was filed first, but thanks for reproducing the problem! We'll use it to test when we get around to it.

**Comment by jakecoffman** [comment] 2023-11-30 13:52
Reopening as this request is to change a grouped update title to look like a non-grouped update title if there is only 1 dependency updated. This is different than the bug identified in #7662.

**Comment by huehnerlady** [comment] 2023-12-15 11:00
@ghjm that is an interesting idea and I would argue would also resolve my issue as if I then say `minimum_updates=2` it should have the expected effect for the single dependabot PRs. maybe even a good default value for that parameter?

**Closed** 2024-04-04 17:10 UTC
Labels: T: bug 🐞, T: feature-request, F: package-metadata, F: grouped-updates 🎳
