### ISSUE TITLE
Add Configuration for Preferred Update Version

### ISSUE THREAD

**Issue by scheng-handy** [dependabot/dependabot-core#3252] opened 2021-03-09 23:35 UTC
Thank you for your hard work on Dependabot. 
I have a suggestion that could make it easier for some organizations to adopt the practice of auto dependency updates.

It would be helpful if we can specify the preferred version (major, minor, patch) to update to. My organization is trying to adopt auto dependency updates and we are cautious to avoid updating all of them to the latest version as it will surely break our code. Allowing users to specify the preferred version would help us build towards latest releases at our own pace. 

An example of this feature would be bundler's `bundle update --patch --minor --major` options. 

I know the `ignore` configuration option prevents some update versions but they are exceptions to the rule. My suggested feature would apply broadly to all of the dependencies.

**Comment by asciimike** [comment] 2021-04-12 18:47
I'm going to close this as a dupe of https://github.com/dependabot/dependabot-core/issues/2219, as I expect it will get caught up in that (e.g. "ignore all patch updates across a certain ecosystem" is something we're designing for").

https://github.com/dependabot/dependabot-core/issues/3479 is a related feature if you wanted to slowly opt-in to things and have the same control.

**Closed by asciimike** 2021-04-12 18:47 UTC
Labels: T: feature-request
