### ISSUE TITLE
Dependabot can't update Go modules that change path

### ISSUE THREAD

**Issue by mx-psi** [dependabot/dependabot-core#3623] opened 2021-05-03 10:51 UTC
**Package ecosystem** Go modules
**Package manager version** `go.mod` file has `go 1.15` directive.
**Language version** Go 1.15

**Manifest location and content prior to update** https://github.com/DataDog/datadog-agent/blob/071bf3c91129e10fe676681d7fb139fa2f519e12/go.mod

**dependabot.yml content** https://github.com/DataDog/datadog-agent/blob/071bf3c91129e10fe676681d7fb139fa2f519e12/.github/dependabot.yaml

**Updated dependency**

Dependabot tried and failed to update `github.com/soniah/gosnmp` from version `v1.26.0` to version `v1.31.0` (where it is named `github.com/gosnmp/gosnmp`).

**What you expected to see, versus what you actually saw**

I expected Dependabot to bump the version and update the dependency name to `github.com/gosnmp/gosnmp` on the go.mod file. It could also report some sort of message on the PR telling you to change your import paths.

It actually just failed to complete the `go.mod` check run.

**Native package manager behavior** n/a, we fixed this manually on DataDog/datadog-agent#8049

**Images of the diff or a link to the PR, issue or logs** 

Logs page shows the following message

```
Dependabot wasn't able to update github.com/soniah/gosnmp

The module path github.com/soniah/gosnmp found in your go.mod doesn't match the actual path github.com/gosnmp/gosnmp found in the dependency's go.mod.
```

The logs themselves don't show anything specially useful.

**🕹 Bonus points: Smallest manifest that reproduces the issue**

I think this should be enough

```
module github.com/something/something

go 1.15

require (
	github.com/soniah/gosnmp v1.26.0
)
```

A more complicated situation would be to have something like this

```
module github.com/something/something

go 1.15

require (
	github.com/soniah/gosnmp v1.26.0
	github.com/gosnmp/gosnmp v1.30.0
)
```

**Comment by thepwagner** [comment] 2021-05-03 15:58
Thanks for the clean reproduction steps!

There is currently [code in dependabot-core](https://github.com/dependabot/dependabot-core/blob/dc12c503d5f5e13d18d5af21414ae01fcd075fde/go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb#L113-L136) to raise an exception in this case, but nothing to recover / perform the rename.

The implementation/requirements may be similar to https://github.com/dependabot/dependabot-core/issues/2213 - both could potentially crawl and update paths imported in `**/*.go`.

**Comment by jeffwidman** [comment] 2021-05-06 19:04
I think the exception message is fairly clear that the rename happened. And not hard to change manually on the rare occasions that it happens.

The bigger meta-issue I think is that it's not easily discoverable when dependabot starts failing... it could be working fine and then silently start failing and you wouldn't realize it until you manually check the dependabot logs. Making that more visible would be great.

**Comment by thepwagner** [comment] 2021-05-07 14:18
>  it's not easily discoverable when dependabot starts failing...

Agreed! Xref https://github.com/dependabot/dependabot-core/issues/3626 for that separate concern.

**Comment by jeffwidman** [comment] 2022-08-09 04:40
I'm closing as I just don't see us investing the resources to support auto-updates on package renames anytime soon... manual renames are relatively rare, and we transparently return the error that we get from `go mod tidy`. 

Also, I'm a little concerned about security implications--if the rename happens, I _definitely_ want to alert a human that beyond just a version bump, there was also a path change. Doing that with some sort of extra banner / alert just isn't something we'll be building into Dependabot anytime soon. 

Surfacing that an error happened is certainly something we could improve on, so that it's more obvious that it needs fixing. But that's tracked under different tickets (both public and internal issue trackers for GitHub UI). So closing this.

**Closed by jeffwidman** 2022-08-09 04:40 UTC
Labels: T: feature-request, L: go:modules

**Comment by mx-psi** [comment] 2022-08-09 07:21
> Also, I'm a little concerned about security implications--if the rename happens, I definitely want to alert a human that beyond just a version bump, there was also a path change. Doing that with some sort of extra banner / alert just isn't something we'll be building into Dependabot anytime soon.

Thanks for the update! While I disagree, it's great to have a reply :)

> Surfacing that an error happened is certainly something we could improve on, so that it's more obvious that it needs fixing. But that's tracked under different tickets (both public and internal issue trackers for GitHub UI). So closing this.

Would you mind sharing the public Github issue # so I can subscribe?

**Comment by jeffwidman** [comment] 2022-08-24 21:02
> Would you mind sharing the public Github issue # so I can subscribe?

I'd probably start with https://github.com/dependabot/dependabot-core/issues/1955

**Comment by jeffwidman** [comment] 2022-08-24 21:07
Also, as a side note, I remembered that `go` module authors now have the ability to deprecate their module with a message: https://github.com/golang/go/commit/cde92846e227425df8258cafade02497a60e421e

It's not quite the same thing as a 301 redirect, but it's another case of something that a module author could push out. However, since it's plain text, it's not something we could really parse... and it only gets pushed out if a new version is released (at least according to those docs) so Dependabot will already do the right thing of raising a PR...
