### ISSUE TITLE
How to disable for a fork?

### ISSUE THREAD

**Issue by hugovk** [dependabot/dependabot-core#2804] opened 2020-11-30 07:24 UTC
I enabled Dependabot for a fork (https://github.com/hugovk/pytest), to make sure it was working smoothly before creating a PR to add it upstream (https://github.com/pytest-dev/pytest). Upstream is now using it, it's working well, thanks!

However, I now want to disable Dependabot for my fork but cannot find a way.

https://app.dependabot.com/accounts/hugovk says:

> You've successfully migrated pytest to GitHub 🎉

![image](https://user-images.githubusercontent.com/1324225/100579683-4a4b0300-32ed-11eb-957e-994a6f53e948.png)

At https://github.com/settings/installations/8631454, Dependabot Preview only has access to other repos:

![image](https://user-images.githubusercontent.com/1324225/100579731-63ec4a80-32ed-11eb-954c-e26ad5ff271d.png)

At https://github.com/hugovk/pytest/settings/security_analysis I have everything disabled:

![image](https://user-images.githubusercontent.com/1324225/100579832-939b5280-32ed-11eb-82c7-d35eb75f5635.png)

Deleting https://github.com/hugovk/pytest/blob/master/.github/dependabot.yml is not an option, because this is a fork, and it needs to be kept in sync with upstream.

How can I disable Dependabot for my fork?

**Package manager/ecosystem**

Python

**Manifest contents prior to update**

```yml
version: 2
updates:
- package-ecosystem: pip
  directory: "/testing/plugins_integration"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
```
https://github.com/hugovk/pytest/blob/master/.github/dependabot.yml
https://github.com/hugovk/pytest/blob/master/testing/plugins_integration/requirements.txt

**Comment by Mariatta** [comment] 2020-12-01 18:17
This is happening in CPython repo as well which has 17K forks. It would help us greatly if dependabot can be disabled in forks. Thanks.

**Comment by feelepxyz** [comment] 2020-12-03 09:33
We're aware of this issue and planning a fix. The workaround for now is to delete the fork and re-create it without enabling Dependabot security updates. Dependabot version updates (setup from config file) isn't enabled by default on new forks but will be if security updates has ever been turned on and since disabled.

**Comment by patcon** [comment] 2021-01-26 20:33
Thanks for clearly communicating! Any update on this?

(I have unrelated issues in the forks, so deleting and recreating isn't quite as easy as it could be.)

**Comment by feelepxyz** [comment] 2021-01-29 17:53
@patcon we'll get to it in the next couple of months :/ going to bump it up again with the team and see if we can get to it sooner.

**Comment by wesinator** [comment] 2021-02-15 15:28
Getting this issue on a fork of https://github.com/EFForg/https-everywhere 

Disabling actions did not prevent new PRs being generated

**Comment by ldez** [comment] 2021-02-26 01:55
Seems to be a duplicate of https://github.com/dependabot/dependabot-core/issues/2198

**Comment by trivikr** [comment] 2021-05-04 14:56
@feelepxyz bumping it again, as it has been three months since this comment.

![Screen Shot 2021-05-04 at 7 53 25 AM](https://user-images.githubusercontent.com/16024985/117023328-dd79d180-acad-11eb-8c86-bebeb8ef918b.png)

**Comment by featheredtoast** [comment] 2021-05-20 16:09
The workaround also doesn't work for forks I want private because I cannot change visibility of a (Github) fork, so I'm mirroring instead. Would the solution here also allow us to disable dependabot in mirrored repositories?

**Comment by return42** [comment] 2021-06-18 09:13
I think there is a need to act here because each fork has a master branch that cannot change after the fork is created. Those  dependabots from forks will run **infinite**! At least as long as the owner of the fork does not _fix_ his master branch what is expectable for 99% of the forks.  Thinking global, this is a totally unneeded wast of resources and energy ...

**Comment by domenkozar** [comment] 2021-07-27 09:04
@feelepxyz :pray: for another bump with the team. We can't use dependabot on nixpkgs with 6.5k forks.

**Comment by feelepxyz** [comment] 2021-07-28 12:24
> @feelepxyz 🙏 for another bump with the team. We can't use dependabot on nixpkgs with 6.5k forks.

Thanks for raising this. We've been pretty stretched so haven't managed to get to this yet. We still want  to get this fixed but can't promise a date yet.

**Comment by return42** [comment] 2021-07-28 12:47
> We've been pretty stretched

I have understanding for this 😄   .. If you see a chance to prioritize this it would be great / IMO it is a KO criteria for projects with a huge community (a lot forks). Anyway thanks a lot for having an eye on this.

**Comment by ziegenberg** [comment] 2021-08-02 13:37
This is a REAL annoyence. It's spamming forks with unnecessary messages. Can we get this fixed rather sooner than later?

**Comment by kellerza** [comment] 2021-08-25 06:28
At least if the flagged upgrade was fixed upstream and you merged upstream dependabot has the courtesy to close its upgrade PR

Now if someone can just teach it to stop spamming in the first place...

**Comment by wren** [comment] 2021-11-15 14:20
Hey, just a thought, but maybe spamming the thread that people are watching because they're tired of being spammed is not the best approach.

**Comment by return42** [comment] 2021-11-15 14:30
😆 .. I assume some user just want to spam back .. just to illustrate how bothersome it is that dependabot does spam in forks.

**Comment by Gustry** [comment] 2022-03-01 15:32
Any news on this very wanted feature request ?

It's a lot of PR which are closed every month because we don't care on forks.

**Comment by hugovk** [comment] 2022-03-06 14:06
I forgot one project uses dependabot and made the mistake of updating my fork from `upstream/main` and got 26 spam PRs:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1324225/156926470-49835e57-1aeb-4222-b995-cd5185b3f70f.png">

**Comment by RyanMulready** [comment] 2022-03-11 18:19
Ran into an interesting scenario with this issue today.

- `upstream` turned on github actions to run on `pull_request`
- I came along some time later and merged `upstream` and pushed to my fork
- `dependabot` came opened it's usually upgrades during its scheduled time for `upstream` and of course my fork as well
- the github `ci` action kicked off on `upstreams` and.... my fork as well; gha are turned on by default when you fork
- some weeks later I got a billing notice that i've exhausted all my action minutes for the month; `dependabot` used them all inadvertently

If I had a billing method on file the likely outcome would have been `dependabot` raking up charges that I wouldn't have been aware of until it was too late.

**Comment by ziegenberg** [comment] 2022-06-15 13:10
Hi @feelepxyz, any update on this? It's now years...

**Comment by feelepxyz** [comment] 2022-06-16 15:05
@ziegenberg Sorry I'm no longer working on Dependabot so not sure what they current state is 😞 would love to see this fixed.

cc 👋 @exvuma as pm for Dependabot

**Comment by shadycuz** [comment] 2022-08-19 14:49
I can't really recommend `dependabot` to my colleagues or clients anymore. Apparently M$, the owners of GitHub, use [renovatebot](https://github.com/renovatebot/renovate) over `dependabot`. Lots of these issues are already fixed in `renovatebot`. Like being able to [disable a fork](https://docs.renovatebot.com/configuration-options/#includeforks). Or being able to control the [PR labels](https://docs.renovatebot.com/configuration-options/#addlabels), something [dependabot cant do](https://github.com/dependabot/dependabot-core/issues/3465).

It will be a decent amount of work to switch my [opensource projects](https://github.com/DontShaveTheYak) to `renovatebot` but its now in the backlog.

**Comment by shadycuz** [comment] 2022-08-19 15:02
Edit: It was not a decent amount of work, it was like 5 mins for all my repos https://github.com/DontShaveTheYak/cloud-radar/pull/137

**Comment by hugovk** [comment] 2022-08-25 07:27
From https://github.com/dependabot/dependabot-core/issues/2198#issuecomment-1226506148:

> 👋 Hey there! This is super annoying, and very much on our radar. Unfortunately, I can't give any promises on timeline etc, but it is something we plan to fix.
> 
> However, it's also tracked over in https://github.com/dependabot/dependabot-core/issues/2804, so I'm going to close this as a duplicate. I realize this one is earlier, but the other one is the one we're tracking internally on some project boards, so just easier to keep that one as the canonical reference ticket.

Personally, I also recommend switching to Renovate as this is taking too long (3.5 years since https://github.com/dependabot/dependabot-core/issues/2198 was reported) and I currently have nearly 50 Dependabot PRs on my forks at https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3A%40me (and that's after closing 10 this week)!

**Comment by FabianKoestring** [comment] 2022-08-25 07:29
We also switched to Renovate. It worked like a charm. ✌

**Comment by jimklimov** [comment] 2022-08-25 10:14
In some cases (forking a project for active custom builds etc) I could
treat this as a sort of reminder that the fork is too far behind. Updating
master branch from upstream does automatically close irrelevant dependabit
PRs on a fork.

In other cases I have forks made for occasional PRs (not product builds),
and there it is just annoying noise in the mailbox.

**Comment by euphbriggs** [comment] 2022-09-07 11:27
One option that might be worth considering is to add an option to specify custom conditions that the repo owner can define. For example, [GitHub Actions has a way](https://github.com/orgs/community/discussions/26409#discussioncomment-3251822) to limit job runs to a specific `repository_owner`.

**Comment by charlesrocket** [comment] 2022-09-13 21:49
The internal ticket just got bumped; there might be some progress soon.

**Comment by jleedev** [comment] 2022-09-16 14:00
This might be a workaround:
 
Add a branch protection rule on `dependabot/*` to "Require a pull request before merging". If dependabot can't push branches, then it can't open pull requests.

**Comment by hugovk** [comment] 2022-09-16 14:13
Hmm, didn't seem to work. I created a rule like this but dependabot still created a PR: https://github.com/hugovk/warehouse/pull/108

![image](https://user-images.githubusercontent.com/1324225/190659255-c7b9472e-07d0-4f33-8cfd-b5ef4087b671.png)

Note it says "Applies to 0 branches".

**Comment by jakirkham** [comment] 2022-10-18 06:30
I just tried deleting a fork and recreating it, but the bot came back to open a PR anyways. It would be really helpful to have a fix for this issue (especially as the workaround doesn't seem to work any more)

**Comment by prplecake** [comment] 2022-10-19 20:46
It's impressive this has been an issue for going on two years now.

If this weren't associated with GitHub, I bet this app would've been disabled a long time ago for creating such a large amount of spam.

**Comment by hugovk** [comment] 2022-10-21 22:13
Some good news from a [duplicate](https://github.com/dependabot/dependabot-core/issues/5914#issuecomment-1282872261):

> We're actively working on this and a permanent fix should land in the next couple of weeks. We'll share more around the time we''re ready to roll this out

👍

**Comment by IEvangelist** [comment] 2022-10-31 14:56
We'd love this too in the `dotnet/docs` repo, ideally, we could easily configure the disabling of fork PRs. We automatically approve and merge @dependabot PRs, so we added a condition to prevent that but the PRs are still causing our forks to diverge. https://github.com/dotnet/docs/pull/32097

**Comment by Gustry** [comment] 2022-10-31 15:29
It's true that running in a GH Action makes way more sense to me... At least we can configure manual triggers, choose more CRON options (one every 3 months is enough for me, I don't need a monthly updates), control the name of repository with a "if" ... Thanks for the suggestion

**Comment by beatngu13** [comment] 2022-11-07 18:20
>Starting today, if you fork a repository with an existing `dependabot.yml`, Version updates will be disabled by default.

https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/

**Comment by hugovk** [comment] 2022-11-07 18:47
Great news! So for existing forks, I guess we can either delete/re-create the fork, or click Disable at the fork's `/settings/security_analysis`:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1324225/200390024-bf2b6f7a-a337-4ef9-a939-0614326c3b02.png">

**Comment by brrygrdn** [comment] 2022-11-07 20:22
👋🏻 Hi folks, as few people have noticed we've [shipped](https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/) a feature to ensure that forks aren't enabled by default of a `.dependabot.yml` file is present.

Any new forks you create should not become enabled unless change this new setting. For any existing forks that are sending you PRs, just disable it via repository settings as @hugovk mentions above.

**Closed by brrygrdn** 2022-11-07 20:22 UTC
Labels: T: bug 🐞, F: noise

**Comment by EwoutH** [comment] 2022-11-09 23:51
@brrygrdn Thanks a lot, this is fantastic news!

I'm curious what happens to existing forks when you add a `dependabot.yml` file for the first time. Initially the file won't be present on the forks, but when a fork is rebased/synced (and thus the `dependabot.yml` file is also added to the fork), what happens in that case?

**Comment by jduncanator** [comment] 2022-11-10 03:49
> 👋🏻 Hi folks, as few people have noticed we've [shipped](https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/) a feature to ensure that forks aren't enabled by default if a `dependabot.yml` file is present.
> 
> Any new forks you create should not become enabled unless change this new setting. For any existing forks that are sending you PRs, just disable it via repository settings as @hugovk mentions above.

This works great for actual forks, but doesn't resolve the issue where I'd like to keep a private mirror of a public repository for staging changes in. It would be great if that "disable" button could be extended to all repositories, not just forks.

**Comment by brrygrdn** [comment] 2022-11-11 10:30
> I'm curious what happens to existing forks when you add a dependabot.yml file for the first time. Initially the file won't be present on the forks, but when a fork is rebased/synced (and thus the dependabot.yml file is also added to the fork), what happens in that case?

@EwoutH By default, the Fork has Version Updates disabled so the file will not be applied when the fork is synced unless you enable Version Updates via the settings either before or after syncing.

This will be the case for any existing Fork that currently does not have a dependabot.yml file present.

This also applies if you manually add a dependabot.yml file to your Fork rather than sync it from the parent Repository, you will still need to enable it via settings for it to be recognised and used.

**Comment by brrygrdn** [comment] 2022-11-11 11:06
@jduncanator Thanks for the feedback, we are discussing extending this setting to all Repositories as we continue to improve our configuration

**Comment by EwoutH** [comment] 2022-11-11 11:15
Thanks for the extensive answer, this was exactly what I was looking for! This means large repositories with many forks can now safely add a Dependabot configuration without triggering a huge influx of PRs on forks.

As a added benefit, it should save GitHub from a lot of CI time :)

**Comment by jeffwidman** [comment] 2022-11-14 17:26
@EwoutH the docs are also open source, feel free to open a PR to improve them. Look on any docs page for the button that says "Make a contribution" to edit that particular page.

**Comment by jimklimov** [comment] 2022-11-24 06:58
Cheers, I must have missed something - although my fork's GitHub UI for
dependabot says it is disabled for forks and asks if I want to enable it, I
still get PR suggestions as the fork lags behind the main project that I
co-maintain.

Is there some further lever to truly disable it?

**Comment by jeffwidman** [comment] 2022-11-24 08:55
Hmm... from when we [shipped this on November 7th](https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/) going forward, no repos should be default opted-in.

One exception is any repo, fork-or-no-fork will be automatically opted in if you've selected the `Automatically enable for new repositories` option in your user or org settings. But that's essentially inheriting a manual opt-in.

Forks that were created before November 7th will require manual disabling... we considered disabling them, but couldn't easily distinguish between those who did/didn't manually enable it from the beginning, so it was safer/more predictable for users if we left them untouched.

To disable, as @hugovk mentions above you need to either delete/re-create the fork, or click Disable on the forked repo's `/settings/security_analysis` page:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1324225/200390024-bf2b6f7a-a337-4ef9-a939-0614326c3b02.png">

**Comment by jimklimov** [comment] 2022-11-24 14:51
Thanks! What confused me is that Depedabot's tab in Insights/Dependency Graph menu item said it is not enabled, so I did not look elsewhere:

![image](https://user-images.githubusercontent.com/1636756/203812376-08052059-6f0a-4b4b-890b-3eaaeecbaf84.png)

But indeed, it did offer to "Disable" under Security.
