### ISSUE TITLE
Grouped PR for packages that are released simultaneously

### ISSUE THREAD

**Issue by exequiel09** [dependabot/dependabot-core#317] opened 2018-03-20 00:03 UTC
Hi i have an interesting proposal, I have recently used dependabot for managing my dependencies and i have this some sort of problem in scoped packages like `@angular/*` packages having multiple PRs wherein they are all released at the same time. 

Hopefully you'll take time considering this since updating Angular with multiple PRs results in many queued CI tasks and too many PRs that needs to merged  Although there have been an auto-merge setting but i prefer not to use it. It would be better if it can be configured per repo basis.

**Comment by greysteil** [comment] 2018-03-20 11:37
Thanks for getting in touch. I'm keen to do something about this - it's next on my list.

In particular, when there are updates that need to be done together I'd like to bundle them into a single PR. We already do that for Ruby and Java, and I don't see any reason why we shouldn't for JS when all of your Angular / React packages are updated in lock-step.

**Comment by sakulstra** [comment] 2020-01-21 17:24
We're regularly spammed by `@material-ui`, `@babel`, `@storybook`, `@accounts`, ... would <3 to see any movement here.

**Comment by infin8x** [comment] 2020-07-02 14:08
Duplicate of #1296

**Comment by jeffwidman** [comment] 2022-09-17 21:53
Temp re-opening so I can close as "dupe" rather than "resolved" for clarity while skimming issue links.

**Closed by jeffwidman** 2022-09-17 21:53 UTC
Labels: T: feature-request
