### ISSUE TITLE
Can't authenticate to a private package registry

### ISSUE THREAD

**Issue by Ashkur** [dependabot/dependabot-core#4847] opened 2022-03-14 18:24 UTC
**Package ecosystem**
npm

**Language version**
node 14

**Manifest location and content prior to update**
/package.json

**dependabot.yml content**
```
version: 2
registries:
  bit-components:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_RC_TOKEN}}
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    registries:
      - bit-components # Allow version updates for dependencies in this registry
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
```
The `secrets.NPM_RC_TOKEN` stores the same token that I have on my local machine and in Vercel and it works great.

**Updated dependency**
from @evob/evob.ui.teste 0.0.2 to @evob/evob.ui.teste 0.0.3

**What you expected to see, versus what you actually saw**
I expected to see a PR to update my dependency but I always get error of authentication therefore unable to update it.

**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/23510117/158234934-04228781-6656-4c07-bcf1-b7ad162fb59f.png)

Dependabot update log error part:

```
updater | INFO <job_314401833> Checking if @evob/evob.ui.teste 0.0.3 needs updating
 proxy | 2022/03/14 17:48:47 [022] GET https://node.bit.dev:443/@evob%2Fevob.ui.teste
 proxy | 2022/03/14 17:48:47 [022] 404 https://node.bit.dev:443/@evob%2Fevob.ui.teste
updater | INFO <job_314401833> Handled error whilst updating @evob/evob.ui.teste: private_source_authentication_failure {:source=>"node.bit.dev"}
```

Dependabot update logs FULL:

 ```
proxy | time="2022-03-14T17:48:33Z" level=info msg="proxy starting" commit=0cfe6fc8a85a641097e4d9faf5c8349b892b1e40
  proxy | 2022/03/14 17:48:33 Listening (:1080)
updater | 2022-03-14T17:48:33.954483594 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-03-14T17:48:33.982120029 [314401833:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-03-14T17:48:35Z" level=info msg="guest starting" commit=4fb4616711b59a04fd2667246d0074f3ff728601
updater | time="2022-03-14T17:48:35Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=314401833 updater_timeout=45m0s updater_version=0.178.0-1392c95d8b130513f87d043c7a4d0e80bcb1f572
updater | I, [2022-03-14T17:48:37.144149 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_314401833> Starting job processing
  proxy | 2022/03/14 17:48:39 [002] GET https://api.github.com:443/repos/Ashkur/dependabit
  proxy | 2022/03/14 17:48:39 [002] * authenticating github api request
  proxy | 2022/03/14 17:48:39 [002] 200 https://api.github.com:443/repos/Ashkur/dependabit
  proxy | 2022/03/14 17:48:39 [004] GET https://api.github.com:443/repos/Ashkur/dependabit/git/refs/heads/master
  proxy | 2022/03/14 17:48:39 [004] * authenticating github api request
  proxy | 2022/03/14 17:48:39 [004] 200 https://api.github.com:443/repos/Ashkur/dependabit/git/refs/heads/master
  proxy | 2022/03/14 17:48:39 [006] GET https://api.github.com:443/repos/Ashkur/dependabit/contents/package.json?ref=d0e681b31b4f8e4fcf5334806bfdd0c015bbd27d
  proxy | 2022/03/14 17:48:39 [006] * authenticating github api request
  proxy | 2022/03/14 17:48:39 [006] 200 https://api.github.com:443/repos/Ashkur/dependabit/contents/package.json?ref=d0e681b31b4f8e4fcf5334806bfdd0c015bbd27d
  proxy | 2022/03/14 17:48:39 [008] GET https://api.github.com:443/repos/Ashkur/dependabit/contents/?ref=d0e681b31b4f8e4fcf5334806bfdd0c015bbd27d
  proxy | 2022/03/14 17:48:39 [008] * authenticating github api request
  proxy | 2022/03/14 17:48:39 [008] 200 https://api.github.com:443/repos/Ashkur/dependabit/contents/?ref=d0e681b31b4f8e4fcf5334806bfdd0c015bbd27d
  proxy | 2022/03/14 17:48:40 [010] GET https://api.github.com:443/repos/Ashkur/dependabit/contents/yarn.lock?ref=d0e681b31b4f8e4fcf5334806bfdd0c015bbd27d
  proxy | 2022/03/14 17:48:40 [010] * authenticating github api request
  proxy | 2022/03/14 17:48:40 [010] 200 https://api.github.com:443/repos/Ashkur/dependabit/contents/yarn.lock?ref=d0e681b31b4f8e4fcf5334806bfdd0c015bbd27d
updater | INFO <job_314401833> Finished job processing
updater | time="2022-03-14T17:48:40Z" level=info msg="task complete" container_id=job-314401833-file-fetcher exit_code=0 job_id=314401833 step=fetcher
updater | I, [2022-03-14T17:48:41.184331 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_314401833> Starting job processing
updater | INFO <job_314401833> Starting update job for Ashkur/dependabit
updater | INFO <job_314401833> Checking if next 12.1.0 needs updating
  proxy | 2022/03/14 17:48:44 [014] GET https://registry.yarnpkg.com:443/next
  proxy | 2022/03/14 17:48:44 [014] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:44 [014] 200 https://registry.yarnpkg.com:443/next
  proxy | 2022/03/14 17:48:46 [016] GET https://registry.yarnpkg.com:443/next/12.1.0
  proxy | 2022/03/14 17:48:46 [016] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:46 [016] 200 https://registry.yarnpkg.com:443/next/12.1.0
updater | INFO <job_314401833> Latest version is 12.1.0
updater | INFO <job_314401833> No update needed for next 12.1.0
updater | INFO <job_314401833> Checking if @types/react 17.0.40 needs updating
  proxy | 2022/03/14 17:48:46 [018] GET https://registry.yarnpkg.com:443/@types%2Freact
  proxy | 2022/03/14 17:48:46 [018] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:46 [018] 200 https://registry.yarnpkg.com:443/@types%2Freact
  proxy | 2022/03/14 17:48:47 [020] GET https://registry.yarnpkg.com:443/@types%2Freact/17.0.40
  proxy | 2022/03/14 17:48:47 [020] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:47 [020] 200 https://registry.yarnpkg.com:443/@types%2Freact/17.0.40
updater | INFO <job_314401833> Latest version is 17.0.40
updater | INFO <job_314401833> No update needed for @types/react 17.0.40
updater | INFO <job_314401833> Checking if @evob/evob.ui.teste 0.0.3 needs updating
  proxy | 2022/03/14 17:48:47 [022] GET https://node.bit.dev:443/@evob%2Fevob.ui.teste
  proxy | 2022/03/14 17:48:47 [022] 404 https://node.bit.dev:443/@evob%2Fevob.ui.teste
updater | INFO <job_314401833> Handled error whilst updating @evob/evob.ui.teste: private_source_authentication_failure {:source=>"node.bit.dev"}
updater | INFO <job_314401833> Checking if typescript 4.6.2 needs updating
  proxy | 2022/03/14 17:48:47 [026] GET https://registry.yarnpkg.com:443/typescript
  proxy | 2022/03/14 17:48:47 [026] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:47 [026] 200 https://registry.yarnpkg.com:443/typescript
  proxy | 2022/03/14 17:48:48 [028] GET https://registry.yarnpkg.com:443/typescript/4.6.2
  proxy | 2022/03/14 17:48:48 [028] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:49 [028] 200 https://registry.yarnpkg.com:443/typescript/4.6.2
updater | INFO <job_314401833> Latest version is 4.6.2
updater | INFO <job_314401833> No update needed for typescript 4.6.2
updater | INFO <job_314401833> Checking if react 17.0.2 needs updating
  proxy | 2022/03/14 17:48:49 [030] GET https://registry.yarnpkg.com:443/react
  proxy | 2022/03/14 17:48:49 [030] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:49 [030] 200 https://registry.yarnpkg.com:443/react
  proxy | 2022/03/14 17:48:49 [032] GET https://registry.yarnpkg.com:443/react/17.0.2
  proxy | 2022/03/14 17:48:49 [032] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:49 [032] 200 https://registry.yarnpkg.com:443/react/17.0.2
updater | INFO <job_314401833> Latest version is 17.0.2
updater | INFO <job_314401833> No update needed for react 17.0.2
updater | INFO <job_314401833> Checking if @types/node 17.0.21 needs updating
  proxy | 2022/03/14 17:48:49 [034] GET https://registry.yarnpkg.com:443/@types%2Fnode
  proxy | 2022/03/14 17:48:49 [034] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:49 [034] 200 https://registry.yarnpkg.com:443/@types%2Fnode
  proxy | 2022/03/14 17:48:49 [036] GET https://registry.yarnpkg.com:443/@types%2Fnode/17.0.21
  proxy | 2022/03/14 17:48:49 [036] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:50 [036] 200 https://registry.yarnpkg.com:443/@types%2Fnode/17.0.21
updater | INFO <job_314401833> Latest version is 17.0.21
updater | INFO <job_314401833> No update needed for @types/node 17.0.21
updater | INFO <job_314401833> Checking if react-dom 17.0.2 needs updating
  proxy | 2022/03/14 17:48:50 [038] GET https://registry.yarnpkg.com:443/react-dom
  proxy | 2022/03/14 17:48:50 [038] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:50 [038] 200 https://registry.yarnpkg.com:443/react-dom
  proxy | 2022/03/14 17:48:50 [040] GET https://registry.yarnpkg.com:443/react-dom/17.0.2
  proxy | 2022/03/14 17:48:50 [040] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:50 [040] 200 https://registry.yarnpkg.com:443/react-dom/17.0.2
updater | INFO <job_314401833> Latest version is 17.0.2
updater | INFO <job_314401833> No update needed for react-dom 17.0.2
updater | INFO <job_314401833> Checking if eslint-config-next 12.1.0 needs updating
  proxy | 2022/03/14 17:48:50 [042] GET https://registry.yarnpkg.com:443/eslint-config-next
  proxy | 2022/03/14 17:48:50 [042] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:50 [042] 200 https://registry.yarnpkg.com:443/eslint-config-next
  proxy | 2022/03/14 17:48:50 [044] GET https://registry.yarnpkg.com:443/eslint-config-next/12.1.0
  proxy | 2022/03/14 17:48:50 [044] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:51 [044] 200 https://registry.yarnpkg.com:443/eslint-config-next/12.1.0
updater | INFO <job_314401833> Latest version is 12.1.0
updater | INFO <job_314401833> No update needed for eslint-config-next 12.1.0
updater | INFO <job_314401833> Checking if eslint 8.11.0 needs updating
  proxy | 2022/03/14 17:48:51 [046] GET https://registry.yarnpkg.com:443/eslint
  proxy | 2022/03/14 17:48:51 [046] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:51 [046] 200 https://registry.yarnpkg.com:443/eslint
  proxy | 2022/03/14 17:48:51 [048] GET https://registry.yarnpkg.com:443/eslint/8.11.0
  proxy | 2022/03/14 17:48:51 [048] * authenticating npm registry request (host: registry.yarnpkg.com, basic auth)
  proxy | 2022/03/14 17:48:51 [048] 200 https://registry.yarnpkg.com:443/eslint/8.11.0
updater | INFO <job_314401833> Latest version is 8.11.0
updater | INFO <job_314401833> No update needed for eslint 8.11.0
updater | INFO <job_314401833> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-03-14T17:48:51Z" level=info msg="task complete" container_id=job-314401833-updater exit_code=0 job_id=314401833 step=updater
```

**Comment by Szymon-dziewonski** [comment] 2022-07-07 09:29
Thanks for ticket, I have exactly same issue, any solution available ?:)

**Comment by jeffwidman** [comment] 2022-09-17 10:40
Closing as I think this is a duplicate of https://github.com/dependabot/dependabot-core/issues/4502. If for some reason you think it's not, please comment and we can re-open.

**Closed by jeffwidman** 2022-09-17 10:40 UTC
Labels: T: bug 🐞, L: javascript:npm, F: private-registries 💂‍♂️
