### ISSUE TITLE
Dependabot should not suggest major-version updates for Elm packages

### ISSUE THREAD

**Issue by swithrow** [dependabot/dependabot-core#3375] opened 2021-03-26 20:09 UTC
**Package manager/ecosystem**
Elm

**Manifest contents prior to update**

```
"inkuzmin/elm-multiselect": "3.0.2",
```
**Updated dependency**

(inkuzmin/elm-multiselect from 3.0.2 to 4.0.0)
```
"inkuzmin/elm-multiselect": "4.0.0",
```
**What you expected to see, versus what you actually saw**

I expected dependabot to create PRs for minor and patch version updates. By definition, **major version updates introduce breaking changes to their API**. Minor and patch versions of an Elm package can be applied to an Elm codebase without needing to change any code.

This particular major-version update introduces a change that will break existing code. It's not a huge difference, and the codebase can be updated fairly quickly, but it will affect nearly every project that uses this particular package.

**Images of the diff or a link to the PR, issue or logs**
<img width="302" alt="image" src="https://user-images.githubusercontent.com/366507/112687055-479c8c80-8e4d-11eb-85a4-fd7b0e162d78.png">

**Comment by feelepxyz** [comment] 2021-03-29 09:29
@swithrow I don't think we want to change the default here as this is how dependabot works for all package ecosystems but we're thinking about making it easier to allow only certain semver updates.

We've received a lot of feedback for the reverse, where users only want to receive PRs for major versions and not for minor/patch versions but can see this could be useful too and should be pretty straight forward addition once we have the basics in place.

**Comment by asciimike** [comment] 2021-04-05 18:47
I'm going to close this as a dupe of: https://github.com/dependabot/dependabot-core/issues/2219. Even though the title of that is the opposite of what you want, it's the same mechanism and we're aiming to build it in a such a way that it will give devs the flexibility to handle this however they want.

**Closed by asciimike** 2021-04-05 18:47 UTC
Labels: T: feature-request
