### ISSUE TITLE
Creating .npmrc file with incorrect default registry while running npm update in npm_locfile_updater

### ISSUE THREAD

**Issue by AlekhyaYalla** [dependabot/dependabot-core#4111] opened 2021-08-03 05:28 UTC
The issue we are facing is while running the npm update in npm_lockfile_updater file, updated_lockfile_content method([here](https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb#L53)), 
while trying to run the npm update, it is moving the dependency files to a temporary location. 
In that method, it is trying to build a temporary .npmrc file content with the npmrc_builder([here](https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb#L781)).
Please find the repo .npmrc file and the copied .npmrc file below.
repo .npmrc content:
```
@org:always-auth=true
@org:registry=https://pkgs.sample.azure.com/org/_packaging/PrivateNpm/npm/registry/
```

Copied .npmrc content copied to temp directory:
```
@org:always-auth=true
@org:registry=https://pkgs.sample.azure.com/org/_packaging/PrivateNpm/npm/registry/
registry = https://pkgs.sample.azure.com/org/_packaging/PrivateNpm/npm/registry/
_auth = sample_auth_token
always-auth = true

always-auth = true
//pkgs.sample.azure.com/org/_packaging/PrivateNpm/npm/registry/:_auth=sample_auth_token

```
What we observed from the code flow of npmrc_builder([here](https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb#L40)) is, if the lock file contains unscoped dependencies being resolved from a private registry then it will consider the private registry as a "global registry"([here](https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb#L49)) and add this registry as the default registry in this newly created .npmrc file. 
The added one is a private registry and doesn't have the version/update for dependency, so dependabot is throwing the error `'No matching version found'` while running npm update.

While fetching the latest version for a dependency, it is using repo .npmrc file and getting the right version from the public registry. But while updating, it is using a newly created .npmrc file with an incorrect default registry, which is a private feed and
doesn't contain the updated version and hence raising `InconsistentRegistryResponse`([here](https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb#L341))
Having the registry fetching from 2 different .npmrc files are causing differentiation in identifying the latest version for dependency and trying to update the same version using a different newly created .npmrc file.

@greysteil @feelepxyz @jurre 
Could you help me in understanding, why dependabot is creating the duplicate .npmrc file, even though a file exists. 
This is causing ambiguity in fetching the version and updating the version from different files. Do you know any way to avoid this or fix this, like to not create another RC file, if there exists one?

**Comment by feelepxyz** [comment] 2021-08-04 10:05
> //pkgs.sample.azure.com/org/_packaging/PrivateNpm/npm/registry/:_auth

Looks like the above snippet includes auth token, you probably want to revoke this if it's a live token.

I can see that dependabot is doing the wrong thing when building the `.npmrc` file. There is some [code in the npmrc builder](https://github.com/dependabot/dependabot-core/blob/33198c89f93d6bfc6734e8538d53d460f59ae021/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb#L58) that should prevent this from happening. It looks like it's not working in this case. I'll see if I can reproduce this.

**Comment by AlekhyaYalla** [comment] 2021-08-06 07:56
@feelepxyz Thanks for the heads up. Will be testing my use case with the mentioned branch.

**Comment by lseppala** [comment] 2021-11-30 23:13
Hi @AlekhyaYalla. Is this still happening, or has this problem been resolved and can we close this issue?

In the timeline I see that you mentioned this issue as fixed in https://github.com/GiriB/dependabot-core/pull/439. Is this the case?

**Closed** 2022-09-14 06:53 UTC
Labels: L: javascript:npm, F: language-support, 🍏 core
