### ISSUE TITLE
Escape comments that have commit hashes

### ISSUE THREAD

**Issue by mikeblakeuk** [dependabot/dependabot-core#4980] opened 2022-04-08 08:53 UTC
**Given:** Microsoft DevOps is running a task (https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot)
**When:** Dependabot create a pull request and the log/comments has a hash Number e.g. `#123` from github
**Then:** The workitem isn't linked (as it don't match)

**Actual:** The _DevOps_ Work Item is wrongly linked to the PR. e.g. gitHub 123 isn't devOps 123

**Expected:** The commit comment should escape the # + number

**Workaround:** Disable the comment mentions in the DevOps Repositories
![image](https://user-images.githubusercontent.com/1986660/162401142-055e7560-aecc-4bdf-a096-15f61870afa8.png)

**Comment by jeffwidman** [comment] 2023-02-11 01:10
👋 Sorry for the slow reply. The root cause is:
* https://github.com/dependabot/dependabot-core/issues/5729

So I'm going to cross-link this from there and then close this as a duplicate.

**Closed by jeffwidman** 2023-02-11 01:10 UTC
Labels: T: feature-request, V: Azure Devops, Workaround :repeat:, F: package-metadata
