### ISSUE TITLE
Poetry dependency with URLs is treated as invalid

### ISSUE THREAD

**Issue by lucaskjaero** [dependabot/dependabot-core#4120] opened 2021-08-04 20:58 UTC
**Package ecosystem**
python - poetry
**Package manager version**
Poetry 1.1.4 - installed by CI
**Language version**
Python 3.9 - installed by CI
**Manifest location and content prior to update**
Full [pyproject.toml](https://github.com/fluent-labs/language-service/blob/main/pyproject.toml).
**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
```
**What you expected to see, versus what you actually saw**
I expected out-of-date packages to be identified, and PRs to be opened. Instead, I get this stacktrace (repeated) in the dependabot logs:
```
updater | ERROR <job_179691030> Error processing python-json-logger (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_179691030> RuntimeError
updater | <job_179691030> 
updater | <job_179691030>   The Poetry configuration is invalid:
updater | <job_179691030>     - [dependencies.da_core_news_sm] {'url': 'https://github.com/explosion/spacy-models/releases/download/da_core_news_sm-3.1.0/da_core_news_sm-3.1.0.tar.gz', 'version': '3.1.0'} is not valid under any of the given schemas
updater | <job_179691030>     - [dependencies.en_core_web_sm] {'url': 'https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0.tar.gz', 'version': '3.1.0'} is not valid under any of the given schemas
updater | <job_179691030>     - [dependencies.es_core_news_sm] {'url': 'https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.1.0/es_core_news_sm-3.1.0.tar.gz', 'version': '3.1.0'} is not valid under any of the given schemas
updater | <job_179691030>     - [dependencies.zh_core_web_sm] {'url': 'https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.1.0/zh_core_web_sm-3.1.0.tar.gz', 'version': '3.1.0'} is not valid under any of the given schemas
updater | <job_179691030>   
updater | <job_179691030> 
updater | <job_179691030>   at /usr/local/.pyenv/versions/3.9.6/lib/python3.9/site-packages/poetry/core/factory.py:43 in create_poetry
updater | <job_179691030>        39│             message = ""
updater | <job_179691030>        40│             for error in check_result["errors"]:
updater | <job_179691030>        41│                 message += "  - {}\n".format(error)
updater | <job_179691030>        42│ 
updater | <job_179691030>     →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
updater | <job_179691030>        44│ 
updater | <job_179691030>        45│         # Load package
updater | <job_179691030>        46│         name = local_config["name"]
updater | <job_179691030>        47│         version = local_config["version"]
updater | ERROR <job_179691030> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.158.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:323:in `run_poetry_command'
```
[Full logs with stacktrace here.](https://gist.github.com/lucaskjaero/07c4ac0cb60fe00d7aabdd8d0f33cedc#file-dependabot_logs-txt)
**Native package manager behavior**
Packages are installed, no error is thrown.
```
$ poetry update python-json-logger --lock --no-interaction
Updating dependencies
Resolving dependencies... (8.5s)
$
```

[Installation logs here.](https://gist.github.com/lucaskjaero/07c4ac0cb60fe00d7aabdd8d0f33cedc#file-dependabot_logs-txt)

**🕹 Bonus points: Smallest manifest that reproduces the issue**
Minimal example to reproduce:
```
[tool.poetry]
name = "language-service"
version = "0.1.0"
description = ""
authors = ["Lucas Kjaero-Zhang <lucas@lucaskjaerozhang.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"
da_core_news_sm = {url = "https://github.com/explosion/spacy-models/releases/download/da_core_news_sm-3.1.0/da_core_news_sm-3.1.0.tar.gz"}
en_core_web_sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0.tar.gz"}
es_core_news_sm = {url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.1.0/es_core_news_sm-3.1.0.tar.gz"}
zh_core_web_sm = {url = "https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.1.0/zh_core_web_sm-3.1.0.tar.gz"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Let me know if there's any other information that would help reproduce the issue.

**Comment by lucaskjaero** [comment] 2021-08-05 07:39
Interestingly, the poetry stacktrace shown in the error doesn't seem to exist. Maybe something has gone wrong when upgrading poetry? [Source](https://github.com/python-poetry/poetry/tree/master/poetry) I see similar issues happen when upgrading poetry vs going for a clean install. https://github.com/python-poetry/poetry/issues/2449

**Comment by njgrisafi** [comment] 2021-09-14 21:01
Also running into this issue when using `url` for poetry dependencies.

**Comment by jeffwidman** [comment] 2022-11-24 10:24
`poetry` shipped a lot of changes over the past year, does this still reproduce?

From the posted logs, it looks like this is a `poetry` bug, but it could be a problem with how we munge the manifest/lockfiles before we pass them to poetry...

**Comment by jeffwidman** [comment] 2023-02-02 05:59
Closing due to lack of user response. Also fairly sure this is/was a `poetry` bug.

**Closed** 2023-02-02 05:59 UTC
Labels: T: bug 🐞, L: python:poetry
